### ISSUE TITLE
Caja with double panel changes to last directory in the wrong panel when you clic in a folder of the other 

### ISSUE THREAD

**Issue by cpcbegin** [mate-desktop/caja#1006]
#### Expected behaviour
Each panel shows all the folder in the path, if you clic in any of them caja might show this folder in this panel. 

#### Actual behaviour
If you clic on a folder of the unfocus panel, change to the last folder showed in the focus panel.
Only runs ok if you previously change the focus to the other panel. 

#### Steps to reproduce the behaviour

1. Open Caja.
2. Clic F3
3. Select different path in each panel.
4. Clic in a folder of the path of panel without focus.

#### MATE general version
1.20.1

#### Package version
Included in distro.

#### Linux Distribution
Ubuntu Mate 18.04 64 bits

**Comment by onlygecko** [comment]
I can verify this issue.
* Caja 1.20.2
* Ubuntu Mate 18.04

**Comment by timovn** [comment]
Same here.
- Caja 1.20.2 (mate 1.20.1)
- Linux Mint 19

**Comment by gabdub** [comment]
Also reported as issue #988
