### ISSUE TITLE
caja does not show thumbnails for video files on samba shares

### ISSUE THREAD

**Issue by danboid** [mate-desktop/caja#1008]
#### Expected behaviour

If the user has ffmpegthumbnailer installer and the 'Show Thumbnails' option set to 'Always' and 'Only for files smaller than' set to a suitably large value under Caja's Preferences -> Preview tab

PLUS

ffmpeg has been compiled with smb support enabled (this really needs to be requested to become a new default for ffmpeg in ubuntu, once we have this working. The standard Arch ffmpeg package is also missing smb support) then caja should show thumbnails for video files when browsing samba file shares.

ffmpegthumbnailer already supports creating thumbnails from files stored on samba shares. I have tested this by installing ffmpeg-full from the AUR under Arch. ffmpeg-full builds ffmpeg with smb support enabled which in turn enables smb video thumbnail generation when you run ffmpegthumbnailer from the terminal on a suitable URI.

Note that in my testing, ffmpegthumbnailer would return the errors:

```Not a native file, thumbnailing will likely fail```

and

```Failed to stat file```

When run on a video stored on a samba share but it still successfully produces a thumbnail image so that seems to be a minor bug in ffmpegthumbnailer.

#### Actual behaviour

Even when all the above conditions are met, caja still fails to display thumbnails for any video files stored on samba shares.

#### Steps to reproduce the behaviour

Install ffmpeg with smb support enabled
Install ffmpegthumbnailer
Set the 'Show Thumbnails' option set to 'Always' and 'Only for files smaller than' to 4GB under Caja's Preferences -> Preview tab
Open caja in icon mode and browse to a samba directory that contains video files of less than 4GB in size

#### MATE general version

1.20.2

#### Package version

1.20.2-1

#### Linux Distribution

Tested under Arch amd64

**Comment by danboid** [comment]
Oops!

I was of course just presuming that caja used ffmpegthumbnailer to create video thumbnails but a quick look at the source code says otherwise.

Regardless, it might be helpful to someone to know that using ffmpegthumbailer for this is an option, when ffmpeg has been built appropriately.

**Comment by danboid** [comment]
@raveit65 

Why have you closed this bug? It is still valid, I just incorrectly assumed it was using ffmpegthumbnailer. Please re-open it , the title is still 100% correct.

**Comment by danboid** [comment]
I will close this bug when it is fixed. thank you.

**Comment by raveit65** [comment]
You wrote it is a problem of ffmpegthumbnailer-thumbnailer?

**Comment by danboid** [comment]
We can close this one now because I rewrote it so as not to mention ffmpegthumbnailer.

**Comment by danboid** [comment]
https://github.com/mate-desktop/caja/issues/1009

**Comment by danboid** [comment]
@raveit65 - yes. Many Linux file managers use ffmpegthumbnailer to create thumbs for videos. I presumed thats what caja did too until I looked at the source code. I never said this bug was fixed,hence me recreating it.
