### ISSUE TITLE
Errors with cajarename package when installing some python modules on ubuntu 18.04

### ISSUE THREAD

**Issue by mapellegrini** [mate-desktop/caja#1016]
I'm not sure who is packaging caja for Ubuntu, so apologies if this is not the correct place to report this. 

#### Expected behaviour
The modules should install without error

#### Actual behaviour
Installing certain python modules using pip2.7 results in the following errors: 

cajarename 17.3.28 requires caja, which is not installed.
cajarename 17.3.28 requires gir1.2-gtk-3.0, which is not installed.
cajarename 17.3.28 requires python-caja, which is not installed.
cajarename 17.3.28 requires python-gi, which is not installed.

#### Steps to reproduce the behaviour

wget https://bootstrap.pypa.io/get-pip.py  
sudo python2.7 get-pip.py
sudo pip2.7 install matplotlib 

I've also gotten the same errors installing mpi4py and openpyxl. 

#### MATE general version
$ caja --version
MATE caja 1.20.2

#### Package version
$ apt list --installed | grep caja

caja/bionic,now 1.20.2-4ubuntu1 amd64 [installed]
caja-admin/bionic,bionic,now 0.0.1-1 all [installed]
caja-common/bionic,bionic,now 1.20.2-4ubuntu1 all [installed]
caja-eiciel/bionic,now 1.18.1-1 amd64 [installed]
caja-extensions-common/bionic,bionic,now 1.20.0-1 all [installed]
caja-gtkhash/bionic,now 1.1.1-2 amd64 [installed]
caja-open-terminal/bionic,now 1.20.0-1 amd64 [installed]
caja-rename/bionic,bionic,now 17.3.28~bzr14+repack1-2 all [installed]
caja-seahorse/bionic,now 1.18.4-1 amd64 [installed]
caja-sendto/bionic,now 1.20.0-1 amd64 [installed]
caja-wallpaper/bionic,now 1.20.0-1 amd64 [installed]
deja-dup-caja/bionic,bionic,now 0.0.4-0ubuntu2 all [installed]
folder-color-caja/bionic,bionic,now 0.0.86-0ubuntu1 all [installed]
gir1.2-caja/bionic,now 1.20.2-4ubuntu1 amd64 [installed]
gir1.2-caja-2.0/bionic,now 1.20.2-4ubuntu1 amd64 [installed]
libcaja-extension1/bionic,now 1.20.2-4ubuntu1 amd64 [installed]
python-caja/bionic,now 1.20.0-1 amd64 [installed]
python-caja-common/bionic,bionic,now 1.20.0-1 all [installed]

#### Linux Distribution
Ubuntu 18.04 LTS Mate desktop AMD-64

**Comment by mapellegrini** [comment]
Here is the full output. 

[pip_error.txt](https://github.com/mate-desktop/caja/files/2088377/pip_error.txt)

**Comment by raveit65** [comment]
> I'm not sure who is packaging caja for Ubuntu, so apologies if this is not the correct place to report this.

Yes wrong place.File out a report at launchpad.
