### ISSUE TITLE
caja crashes with this svg file

### ISSUE THREAD

**Issue by scribe777** [mate-desktop/caja#1017]
#### Actual behaviour

Caja will not start up with this file in my home folder

#### Steps to reproduce the behaviour
place this file in your home folder and run caja from the MATE menu
name the file: svg
content:
```
<svg xmlns='http://www.w3.org/2000/svg'>
<path xmlns="http://www.w3.org/2000/svg"
	d="M341.4031,1694.70543h575.9031v0h575.9031v157.49225v157.49225h-575.9031h-575.9031v-157.49225z"
	data-paper-data="{&quot;strokeWidth&quot;:1,&quot;rotation&quot;:0,&quot;deleteIcon&quot;:null,&quot;rotationIcon&quot;:null,&quot;group&quot;:null,&quot;editable&quot;:true,&quot;annotation&quot;:null}" id="rectangle_6f467a3d-8947-4201-af41-d73b3b07bd5f"
	fill-opacity="0.00001"
	fill="#00bfff"
	fill-rule="nonzero"
	stroke="#00bfff"
	stroke-width="1"
	stroke-linecap="butt"
	stroke-linejoin="miter"
	stroke-miterlimit="10"
	stroke-dasharray=""
	stroke-dashoffset="0"
	font-family="none"
	font-weight="none"
	font-size="none"
	text-anchor="none"
	style="mix-blend-mode: normal"/>
</svg>
```

#### MATE general version
1.20.2

#### Linux Distribution
F28

**Comment by raveit65** [comment]
In inkscape this is a blank image, are you sure this .svg is valid?
And yes the caja window crashes when the thumbnailer tries to do his job. (in f28)
But for some reasons only the caja window and not the whole process.

**Comment by raveit65** [comment]
I get a abrt alarm and the culprit is gdk-pixbuf2.
Why not reporting it with fedora bug-reporting tool against gdk-pixbuf2 ?

**Comment by scribe777** [comment]
Hey @raveit65 , I have no idea if that SVG is valid.  I'm trying to build it right now by hand for use as an annotation box on an IIIF image viewer.  But I think we both agree that Caja shouldn't crash if it tries to generate a preview for a file which isn't valid... Maybe a (X) icon or something?  I didn't look deeper into the cause.  Thanks for figuring out that it is gdk-pixbuf2's fault.  I'll leave it to you to pass the ticket along to your 3rd party dependency.

**Comment by raveit65** [comment]
Fell free to file out a redhat bugzilla report via fedora bug reporting tool against gdk-pixbuf2'
You should have a alarm alarm in you own fedora.

**Comment by scribe777** [comment]
@raveit65 , look, that's not opensource friendly.  I spend the hour it took to figure out which file was causing your program to crash.  I am glad you figured out that it is "not my problem" by really, it is.  It is your problem because you depend on gdk-pixbuf2.  I am not taking another hour out of my day to report a problem you have with your dependency.  I have no idea how you call your library or if it really is the problem.  Maybe you should use a try catch block?  I have no idea.

**Comment by raveit65** [comment]
What is so so hard to file out a abrt report, you only have to press the button?
This take 2 min and not one hour.
How should i fix a issue with another package which isn't under our control?
And  i don't have any crashes with other .svg here.
Seriously i don't file out a report with a source which is possibly corrupt and of unclear origin.
This is your file so it's up to you to send it to **RedHat**.

**Comment by scribe777** [comment]
I don't have anything that pops up an abrt report dialog.  Apparently, you tested it and it crashes for you.  Press the button.  Caja still crashes when someone saves to their home folder a text file which might possibly contain an invalid SVG tag inside.  I would think this would be valuable information for you and you would take some personal responsibility for an app you write.  Use a different image library.  Send an intelligent report outlining exactly how you call your dependency.  Grow up man.

**Comment by lukefromdc** [comment]
The devs behind gdk-pixbuf2 may not even know this is happening, so they need that report. At the miniumum let them know a problem that crashes caja has been traced to that package. If you don't have any automatic tools installed for generating bug reports at least send a plain text report referring back to this issue

**Comment by raveit65** [comment]
Automatic bug-reporting is installed as default in fedora. You will find any abrt alarm here.
```
[root@satellite rave]# ls -la /var/spool/abrt
insgesamt 52
drwxr-x--x. 12 root abrt 4096 12. Jun 10:56 .
drwxr-xr-x. 11 root root 4096 25. Apr 08:36 ..
drwxr-x---   3 root abrt 4096 12. Jun 10:56 ccpp-2018-06-08-12:57:10.197150-29227
drwxr-x---   3 root abrt 4096 12. Jun 10:56 ccpp-2018-06-08-13:16:30.946939-3750
drwxr-x---   3 root abrt 4096 12. Jun 06:53 ccpp-2018-06-09-08:49:39.358882-16025
drwxr-x---   3 root abrt 4096 12. Jun 06:53 ccpp-2018-06-09-15:46:40.175740-30066
drwxr-x---   3 root abrt 4096 12. Jun 10:56 ccpp-2018-06-09-16:02:59.425547-9716
drwxr-x---   3 root abrt 4096 12. Jun 10:56 ccpp-2018-06-10-17:56:42.809846-2069
drwxr-x---   3 root abrt 4096 12. Jun 10:56 ccpp-2018-06-10-18:01:27.809772-8325
-rw-------   1 root root   22 10. Jun 16:33 last-via-server
drwxr-x---   3 root abrt 4096 12. Jun 10:56 oops-2018-06-09-08:20:29-731-0
drwxr-x---   3 root abrt 4096 12. Jun 06:53 oops-2018-06-10-19:05:59-753-0
drwxr-x---   3 root abrt 4096 12. Jun 06:52 Python3-2018-06-10-15:59:38-3900
```
Btw. Because you do not pay my salary, stop saying me what i have to do ;)
