### ISSUE TITLE
Mouse is stuck in rubberband mode after pressing Ctrl+. or Ctrl+;

### ISSUE THREAD

**Issue by elcste** [mate-desktop/caja#1024]
#### Steps to reproduce the behaviour
1. Give caja focus (the desktop or window)
2. Press <kbd>Ctrl</kbd>+<kbd>.</kbd> OR <kbd>Ctrl</kbd>+<kbd>;</kbd> 
3. Click in the caja window.
4. Now when you move the mouse you get a rubberband box, and each time you click you get a new one. There's no way to exit this (such as pressing <kbd>Esc</kbd>). The mouse can't be used for anything else. To get the mouse back, you need to run `caja -q` with the Run Application window or with a terminal brought up with <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>T</kbd> 

FWIW I've tried Marco and Compiz, mouse and touchpad, libinput and synaptics, and the original reporter tried different keyboard layouts.

#### MATE general version
1.20.1

#### Package version
1.20.2-4ubuntu1

#### Linux Distribution
Ubuntu MATE 18.04

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/caja/+bug/1778672

**Comment by selectiveduplicate** [comment]
I was able to reproduce the problem on an UM live VM. The thing is the problem doesn't happen after repeatedly following the steps, even though it has focus. I have to click again on the Caja window or desktop and then press Ctrl+.(or ,) to get the selection box.

The VM is with Marco(Adaptive compositing), 4.15.0-20 generic kernel. 

But I can't reproduce the problem on my main desktop PC, with an updated UM, 4.15.0-23 generic kernel and Marco(Compton GPU compositor). Whenever I press Ctrl+. or Ctrl+, I get the search box on the bottom-right! This doesn't happen on the live VM.

Pretty weird...

**Comment by elcste** [comment]
Weird indeed. I've tried it on five computers, both installed and live, and they all show the issue as I described without doing anything extra.

**Comment by lukefromdc** [comment]
Confirmed here. With ctrl. and ctrl: I get stuck in rubberband mode, assuming that to be the described selection box. On the other hand, ctrl+ and ctrl- worked fine in my test, bare metal, compiz-reloaded on Debian Unstable

**Comment by elcste** [comment]
Yes, rubberband mode — I couldn't think of that name.
