### ISSUE TITLE
Open caja with several tabs opened

### ISSUE THREAD

**Issue by colibris79** [mate-desktop/caja#1027]
It is not properly a bug but something I want to know if it is possible to do. I would like to be able to open Caja with several tabs opened. For example, when  I open Caja I want it to open with my "Home", "Downloads" and "Documents" folders opened in the same window but in different tabs. Is there any way to do this? Via terminal I just manage to open the three folders but in different windows.
Thanks

#### MATE general version
1.18

#### Linux Distribution
Mint 18.3 Mate

**Comment by monsta** [comment]
Implemented in 1.22 (https://github.com/mate-desktop/caja/pull/1053). Use `-t` switch.
