### ISSUE TITLE
On French translation, File and Bookmarks menu share the same shortcut since 1.20

### ISSUE THREAD

**Issue by alexarnaud** [mate-desktop/caja#1028]
French translations have been updated for 1.20, they have change Bookmarks translation from "Signet" to "Favoris"

#### Expected behaviour
File and Bookmarks menu should have different shorcuts

#### Actual behaviour
Alt + f jumps between File and Bookmarks (so in French, Fichier and Favoris)

#### Steps to reproduce the behaviour
1) Change the local to fr_FR.utf-8
2) Restart Caja
3) Press alt + f to go to Fichier menu
4) Press escape
5) Press alt + f

At step 5 you're on Favoris (Bookmarks)

#### MATE general version
1.20

#### Package version
1.20.2

#### Linux Distribution
Debian Sid

**Comment by sc0w** [comment]
Confirmed, it must be fixed into `transifex`:

`_Fichier` and `_Favoris` both have **_F**

**Comment by monsta** [comment]
Yes, it has to be fixed in [Transifex](https://www.transifex.com/mate/MATE/).
We have no control over localized shortcuts (which are made by prepending `_` to the chosen letter).
