### ISSUE TITLE
misbehavior when vsplit  caja window

### ISSUE THREAD

**Issue by zhangn1985** [mate-desktop/caja#1033]
### repeat steps:
1, unzip two version of linux kernel source to two different locations
2, open caja, and nav to first kernel source, and use `F3` to vsplit window, and nav left to another kernel source.
3, nav both kernel source to same deeper folder, eg `include/linux/amba`
4, you now focus on left side, and click `include` address button on the right side.

#### Expected behaviour
right side nav to include

#### Actual behaviour
left side nav to include

#### MATE general version
1.20.3

#### Package version
1.20.3

#### Linux Distribution
Debian

#### Link to downstream report of your Distribution
NA

**Comment by zhangn1985** [comment]
### step 1

![2018-07-26 21-50-33](https://user-images.githubusercontent.com/832666/43266463-0ee47b84-911e-11e8-9018-3bb1334b1e10.png)

### result

![2018-07-26 21-54-45](https://user-images.githubusercontent.com/832666/43266661-8910e564-911e-11e8-9c37-3d0392332b93.png)

**Comment by Riao** [comment]
Can confirm. This misbehaviour occurs while navigating any folders in dual pane. Clicking the navigation bar on the unfocused pane only affects the focused pane.

**Comment by SebastJava** [comment]
DUPLICATE? check:
https://github.com/mate-desktop/caja/issues/1006
https://github.com/mate-desktop/caja/issues/988

Personally, i could not confirm this, it's OK on my computer:
sebastien@sebastien-X101CH ~ $ inxi -Fxz
System:    Host: sebastien-X101CH Kernel: 4.15.0-29-generic i686 (32 bit gcc: 5.4.0)
           Desktop: MATE 1.18.0 (Gtk 3.18.9-1ubuntu3.3) Distro: Linux Mint 18.3 Sylvia
Machine:   System: ASUSTeK (portable) product: X101CH v: x.x
           Mobo: ASUSTeK model: X101CH v: x.xx
           Bios: American Megatrends v: X101CH.1203 date: 07/30/2012
CPU:       Dual core Intel Atom N2600 (-HT-MCP-) cache: 512 KB
           flags: (nx pae sse sse2 sse3 ssse3) bmips: 6385
           clock speeds: max: 1600 MHz 1: 1062 MHz 2: 1048 MHz 3: 864 MHz 4: 1274 MHz
Graphics:  Card: Intel Atom Processor D2xxx/N2xxx Integrated Graphics Controller bus-ID: 00:02.0
           Display Server: X.Org 1.18.4 drivers: (unloaded: fbdev,vesa)
           Resolution: 1024x600@60.02hz
           GLX Renderer: llvmpipe (LLVM 6.0, 128 bits)
           GLX Version: 3.0 Mesa 18.0.5 Direct Rendering: Yes
Audio:     Card Intel NM10/ICH7 Family High Definition Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.15.0-29-generic
Network:   Card-1: Qualcomm Atheros AR9485 Wireless Network Adapter driver: ath9k bus-ID: 02:00.0
           IF: wlp2s0 state: up mac: <filter>
           Card-2: Qualcomm Atheros AR8152 v2.0 Fast Ethernet
           driver: atl1c v: 1.0.1.1-NAPI port: e000 bus-ID: 04:00.0
           IF: enp4s0 state: up speed: 100 Mbps duplex: full mac: <filter>
Drives:    HDD Total Size: 352.1GB (24.9% used)
           ID-1: /dev/sda model: Hitachi_HTS54323 size: 320.1GB
           ID-2: USB /dev/sdb model: Card_Reader size: 32.1GB
Partition: ID-1: / size: 130G used: 57G (47%) fs: ext4 dev: /dev/sda5
           ID-2: swap-1 size: 4.29GB used: 0.02GB (1%) fs: swap dev: /dev/sda6
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 75.0C mobo: N/A
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 180 Uptime: 46 min Memory: 551.2/986.2MB
           Init: systemd runlevel: 5 Gcc sys: 5.4.0 Client: Shell (bash 4.3.481) inxi: 2.2.35

**Comment by zhangn1985** [comment]
@SebastJava yes, duplicate.
