### ISSUE TITLE
Caja can't resize file name column

### ISSUE THREAD

**Issue by geckolinux** [mate-desktop/caja#1040]
Hi there, I'm using Mate 1.20 with Caja 1.20.2 in openSUSE Leap 15.0.

I'm running into a major issue where I can't change the width of the file name column, and most of the longer filenames are cut off. I thought it was a known bug (that I had personally reported somewhere), but I have searched around on the openSUSE and Mate bug trackers and I can't seem to find anything. This is such a major bug that I'm wondering if I have a misconfiguration or if I'm doing something wrong? 

Thanks a lot!

**Comment by vkareh** [comment]
@geckolinux - have you filed a bug on the openSUSE bug tracker? I'm on Ubuntu MATE 18.10 running caja 1.20.2 and cannot reproduce this issue.

Are you using caja with the List View? Do you have a screenshot of what happens when trying to resize?

**Comment by geckolinux** [comment]
Hi there, thanks a lot for looking into this, and my apologies for the slow response.

Thanks for confirming that this is not a known bug, I had assumed that it was not working for a while. So I again tried to resize the column, and I discovered that it was indeed resizable, just that the mouse pointer was not changing to a <-> horizontal resize arrow. I played around with some theme settings (GeckoLinux STATIC Mate ships Numix as the default theme), and specifically after switching the mouse pointer from "default pointer" to "Adwaita" the horizontal resize arrow started appearing. Now even after putting it back to "default pointer" the horizontal resize arrow still works as expected.

So it looks like I had some bad dconf setting(s) in the defaults that GeckoLinux ships. It was originally created somewhere around Mate 1.16 IIRC, and it hasn't been updated since. So I'm not sure if this qualifies as a bug or not, I'll leave it to you to close this if you want.

Thanks again!

**Comment by geckolinux** [comment]
Another update: After another reboot cycle with the mouse pointer set to "default pointer" the horizontal resize pointer stopped appearing again. It appears that it must be set to a specific pointer style name, such as Adwaita.

**Comment by flexiondotorg** [comment]
Sounds like some cursor themes are incomplete. This is not a MATE bug, sorry.

**Comment by smithtim** [comment]
I am using the default theme that came with MATE.  If this is not a MATE bug, where should it be reported?
