### ISSUE TITLE
shift+delete does nothing in caja.

### ISSUE THREAD

**Issue by shirishag75** [mate-desktop/caja#1049]
#### Expected behaviour

Caja should delete number of files and directories chosen in caja. 

#### Actual behaviour

Does nothing. 

It perhaps partially may be due to but  AFAIK that  is default  behavior  - 

```
$ gsettings list-recursively org.mate.caja.preferences
org.mate.caja.preferences confirm-move-to-trash true
```

#### Steps to reproduce the behaviour

1. Go to any folder having bunch of files and folders, make sure caja is at  default (non-spatial mode) where you get the filename, size, type, modification time etc. 

2. Select bunch of files or/and directories using mouse. 

3. Try shift+delete to bypass the trash but doesn't  work. 

#### MATE general version 

1.20.3-1

#### Package version 

1.20.2-5
#### Linux Distribution 

Debian testing

#### Link to downstream report of your Distribution 

https://bugs.debian.org/907006

**Comment by sc0w** [comment]
It works fine here with caja 1.20.2 (debian testing):

<kbd>delete</kbd> <- ask to move to trash

<kbd>shift</kbd><kbd>delete</kbd> <- ask to permanently delete

**Comment by shirishag75** [comment]
strange, then probably something at my end.  Let me close it for the moment, if I get any more info, will open it again.
