### ISSUE TITLE
Caja caches folders from usb drives/disk

### ISSUE THREAD

**Issue by rcaridade145** [mate-desktop/caja#1066]
#### Expected behaviour
Two disks from Toshiba with the original name. Copy stuff from one to my pc. Safely remove it. Connect the other disk and i would get the folders from that disk.

#### Actual behaviour
Two disks from Toshiba with the original name. Copy stuff from one to my pc. Safely remove it. Connect the other disk and i get the folders from the first disk unless i close all the instances of Caja.

#### Linux Distribution
Ubuntu Mate 18.04.1

**Comment by rcaridade145** [comment]
I have been looking into some commits on nautilus, that may fix this issue.

https://gitlab.gnome.org/GNOME/nautilus/commit/3891241ba760c59d284b7579dbd340651c8d4d29
https://gitlab.gnome.org/GNOME/nautilus/commit/3bca716182916da5832cdf61b54adcbf95e3a87f

Which were the fixes to these bugs:

https://bugzilla.gnome.org/show_bug.cgi?id=684226
https://bugzilla.gnome.org/show_bug.cgi?id=757555

**Comment by lukefromdc** [comment]
I found only the first of the two Nautilus commits were directly applicable, as the "force-reload" function in Nautilus does not exist in Caja. None the less, I tested this with a pair of identically named camera cards formatted in the same camera, and no longer had the contents of the first card displayed after ejecting it, mounting the second card, and navigating to it again in Caja.

**Comment by rcaridade145** [comment]
Really nice

**Comment by lukefromdc** [comment]
Getting some issues with the PR, in that only a NEW window comes up with the correct contents. On the other hand, I just found that clicking the "reload" button in the toolbar will bring up the correct contents both in current master (and presumably thus releases) and with the PR when trying to show the new drive's contents in a window that was open when the old contents were showing
