### ISSUE TITLE
caja doesn't run under gdb. 

### ISSUE THREAD

**Issue by shirishag75** [mate-desktop/caja#1077]
#### Expected behaviour

Caja should run under gdb. 

#### Actual behaviour
```

$ gdb caja
GNU gdb (Debian 8.1-4+b1) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from caja...Reading symbols from /usr/lib/debug/.build-id/65/f5aa6c06e7aff2cfa91def753c89e355dccd01.debug...done.
done.
(gdb) set pagination 0
(gdb) set logging on
Copying output to gdb.txt.
(gdb) run
Starting program: /usr/bin/caja 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffef4eb700 (LWP 13793)]
[New Thread 0x7fffeecea700 (LWP 13794)]

(caja:13789): GLib-GObject-WARNING **: 01:56:48.100: invalid (NULL) pointer instance

(caja:13789): GLib-GObject-CRITICAL **: 01:56:48.101: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(caja:13789): GLib-GObject-WARNING **: 01:56:48.101: invalid (NULL) pointer instance

(caja:13789): GLib-GObject-CRITICAL **: 01:56:48.101: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(caja:13789): EggSMClient-CRITICAL **: 01:56:48.101: egg_sm_client_is_resumed: assertion 'client == global_client' failed
[New Thread 0x7fffee487700 (LWP 13795)]
[Thread 0x7fffee487700 (LWP 13795) exited]
[Thread 0x7fffef4eb700 (LWP 13793) exited]
[Thread 0x7ffff038ef40 (LWP 13789) exited]
[Inferior 1 (process 13789) exited normally]
(gdb) quit
```

#### Steps to reproduce the behaviour

Install Debian testing , install caja with -recommends and run caja under gdb. Caja doesn't run but aborts and you get the message above. 

#### MATE general version

1.20.3 

#### Package version

1.20.2-5

#### Linux Distribution

Debian testing 

#### Link to downstream report of your Distribution

bugs.debian.org/910084

**Comment by shirishag75** [comment]
It crashes when using removable drive too, especially when removing the drive via caja but until I have a proper stack trace I don't dare to say more.

**Comment by lukefromdc** [comment]
I just ran caja successfully under gdb (as root so as not to just invoke my session instance) on Debian Unstable with MATE 1.21 current from git master as of yesterday (11-3-2018) and locally build gtk 3.24.1 and glib 2.58.1

**Comment by shirishag75** [comment]
I am running under mate 1.20.3-2 not mate 1.21 so there may be differences. 

Although am running gtk 3.24.1 - 

$ pkg-config --modversion gtk+-3.0
3.24.1

My version of glib is also 2.58.1-2 though. 

gdb is - 
```

$ gdb --version
GNU gdb (Debian 8.1-4+b1) 8.1
```

**Comment by shirishag75** [comment]
caja by itself can't handle on its own on desktop if run from CLI. 

```
$ caja

(caja:16878): GLib-GObject-WARNING **: 18:38:04.945: invalid (NULL) pointer instance

(caja:16878): GLib-GObject-CRITICAL **: 18:38:04.945: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(caja:16878): GLib-GObject-WARNING **: 18:38:04.945: invalid (NULL) pointer instance

(caja:16878): GLib-GObject-CRITICAL **: 18:38:04.945: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(caja:16878): EggSMClient-CRITICAL **: 18:38:04.946: egg_sm_client_is_resumed: assertion 'client == global_client' failed
$ 

```

**Comment by shirishag75** [comment]
Interestingly, there is a 28 mb coredump of caja in systemd 

$ ls -lh /var/lib/systemd/coredump/core.caja.1000.e99792ba071c49888594c113ae67aa12.1329.1541276024000000.lz4
-rw-r-----+ 1 root root 28M Nov  4 01:43 /var/lib/systemd/coredump/core.caja.1000.e99792ba071c49888594c113ae67aa12.1329.1541276024000000.lz4    

I saw quite a few of such caja coredump files.

**Comment by shirishag75** [comment]
I was able to get a bit ahead - 

```
/var/lib/systemd/coredump$ sudo cp core.caja.1000.e99792ba071c49888594c113ae67aa12.1329.1541276024000000.lz4 /home/shirish

$ sudo chmod 777 core.caja.1000.e99792ba071c49888594c113ae67aa12.1329.1541276024000000.lz4

$ lz4 core.caja.1000.e99792ba071c49888594c113ae67aa12.1329.1541276024000000.lz4
Decoding file core.caja.1000.e99792ba071c49888594c113ae67aa12.1329.1541276024000000 
core.caja.1000.e9979 : decoded 184455168 bytes                                 

$ gdb caja core.caja.1000.e99792ba071c49888594c113ae67aa12.1329.1541276024000000
GNU gdb (Debian 8.1-4+b1) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from caja...Reading symbols from /usr/lib/debug/.build-id/65/f5aa6c06e7aff2cfa91def753c89e355dccd01.debug...done.
done.
[New LWP 1329]
[New LWP 1333]
[New LWP 1380]
[New LWP 11284]
[New LWP 1334]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `caja'.
---Type <return> to continue, or q <return> to quit---
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055aac7914c34 in drive_stop_cb (source_object=0x55aacbb1b280, res=0x7fa270083a80, user_data=<optimized out>)
    at caja-places-sidebar.c:2553
2553    caja-places-sidebar.c: No such file or directory.
[Current thread is 1 (Thread 0x7fa2a620cf40 (LWP 1329))]
(gdb)


```

**Comment by shirishag75** [comment]
also see https://paste.debian.net/1050465/

**Comment by shirishag75** [comment]
Even with the updated package, it doesn't run under gdb and exits normally :(

```
$ gdb caja
GNU gdb (Debian 8.3-1) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
--Type <RET> for more, q to quit, c to continue without paging--

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from caja...
Reading symbols from /usr/lib/debug/.build-id/da/44145ed422aa057d547550c3cad5e503549b17.debug...
(gdb) set pagination 0
(gdb) set logging on
Copying output to gdb.txt.
(gdb) run
Starting program: /usr/bin/caja 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff23e4700 (LWP 29912)]
[New Thread 0x7ffff1be3700 (LWP 29913)]
[New Thread 0x7ffff1380700 (LWP 29914)]
[Thread 0x7ffff1380700 (LWP 29914) exited]
[Thread 0x7ffff23e4700 (LWP 29912) exited]
[Thread 0x7ffff29dea80 (LWP 28652) exited]
[Inferior 1 (process 28652) exited normally]
```

**Comment by cwendling** [comment]
@shirishag75 usually your session will restart Caja automatically when it quits (at least if you use the it to show the desktop (?)), so in this case it's tricky to get Caja to really quit in a way where you can manually start it.
I'm not really sure how to disable that for testing, but others might know.  I used in the past to hack around it preventing the system to find the Caja executable so it would fail auto-restart and I could do it, but I'm sure there are better alternatives :)

**Comment by rbuj** [comment]
I recommend you [rebuilding the package you’re debugging](https://wiki.debian.org/HowToGetABacktrace#Rebuilding_the_package_you.2BIBk-re_debugging)
```shell
apt install build-essential fakeroot gdb
apt build-dep caja
DEB_BUILD_OPTIONS="nostrip noopt" apt source -b caja
apt build-dep libglib2.0-0
DEB_BUILD_OPTIONS="nostrip noopt nocheck nodocs" apt source -b libglib2.0-0
apt install ./*.deb
find . -name "*.deb" -exec apt install --reinstall {} \;
```
Backtrace:
```shell
LANG=C sudo gdb -p $(pgrep caja) -ex continue -ex bt
```
### Happy hacking!

**Comment by cwendling** [comment]
@rbuj Actually if you simply want debugging symbols: `apt install caja-dbg libglib2.0-0-dbg` and you can then indeed just connect to the running instance (given it doesn't crash at startup and you actually have time to do it).

**Comment by shirishag75** [comment]
@rbuj . I am using Debian and we already have the debugging symbols installed, even the other ones that @cwendling shared - 

$ aptitude search libglib2.0-0
i A libglib2.0-0                                         - GLib library of C routines                                    
i   libglib2.0-0-dbgsym                                  - debug symbols for libglib2.0-0

```
$ apt-cache policy libglib2.0-0
libglib2.0-0:
  Installed: 2.60.6-2
  Candidate: 2.60.6-2
  Version table:
     2.61.2-2 100
        100 http://cdn-fastly.deb.debian.org/debian experimental/main amd64 Packages
 *** 2.60.6-2 900
        900 http://cdn-fastly.deb.debian.org/debian testing/main amd64 Packages
        100 http://cdn-fastly.deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by rbuj** [comment]
### Install required packages to debug caja
```shell
$ LANG=C find-dbgsym-packages /usr/bin/caja
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libgio-2.0.so.0
W: Cannot find debug package for /lib/x86_64-linux-gnu/libgio-2.0.so.0 (e1a70697f280568355bd9f9df36f716625a65fb2)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libgmodule-2.0.so.0
W: Cannot find debug package for /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (7f2f93b87329e8cf85bec07d552847b05a2db8ac)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libgobject-2.0.so.0
W: Cannot find debug package for /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (da04b9745fb3b80f5c22f87ed4d5619e758250c3)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libXcomposite.so.1
W: Cannot find debug package for /lib/x86_64-linux-gnu/libXcomposite.so.1 (fd60c2c65acf6eaa3f92c2b9a12899e3ead42141)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libglib-2.0.so.0
W: Cannot find debug package for /lib/x86_64-linux-gnu/libglib-2.0.so.0 (ff53a231e7abbab5f672f43422c8636f0755bf38)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libXext.so.6
W: Cannot find debug package for /lib/x86_64-linux-gnu/libXext.so.6 (2fcae7c9cf1b5ba62085611c360601b428ba24b9)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libgthread-2.0.so.0
W: Cannot find debug package for /lib/x86_64-linux-gnu/libgthread-2.0.so.0 (7f988b36184fca357b62b15af08e273b8fd7dc6b)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libXau.so.6
W: Cannot find debug package for /lib/x86_64-linux-gnu/libXau.so.6 (f48f35ab49693e957bf0b776a3669a8fc7d226e2)
caja-dbgsym libatk-bridge2.0-0-dbgsym libatk1.0-0-dbgsym libatspi2.0-0-dbgsym libblkid1-dbgsym libbsd0-dbgsym libcairo-gobject2-dbgsym libcairo2-dbgsym libcaja-extension1-dbgsym libdatrie1-dbgsym libdbus-1-3-dbgsym libdconf1-dbgsym libepoxy0-dbgsym libexempi8-dbgsym libexif12-dbgsym libexpat1-dbgsym libffi6-dbg libfontconfig1-dbgsym libfreetype6-dbgsym libfribidi0-dbgsym libgail-3-0-dbgsym libgcc1-dbg libgcrypt20-dbgsym libgdk-pixbuf2.0-0-dbgsym libgpg-error0-dbgsym libgraphite2-3-dbgsym libgtk-3-0-dbgsym libharfbuzz0b-dbgsym libice6-dbg libicu63-dbgsym liblz4-1-dbgsym liblzma5-dbgsym libmate-desktop-2-17-dbgsym libmount1-dbgsym libnotify4-dbgsym libpango-1.0-0-dbgsym libpangocairo-1.0-0-dbgsym libpangoft2-1.0-0-dbgsym libpcre3-dbg libpixman-1-0-dbgsym libpng16-16-dbgsym libselinux1-dbgsym libsm6-dbgsym libstartup-notification0-dbgsym libstdc++6-8-dbg libsystemd0-dbgsym libthai0-dbgsym libuuid1-dbgsym libwayland-client0-dbgsym libwayland-cursor0-dbgsym libwayland-egl1-dbgsym libx11-6-dbgsym libx11-xcb1-dbgsym libxcb-render0-dbgsym libxcb-shm0-dbgsym libxcb-util0-dbgsym libxcb1-dbgsym libxcursor1-dbgsym libxdamage1-dbgsym libxdmcp6-dbg libxfixes3-dbgsym libxi6-dbgsym libxinerama1-dbgsym libxkbcommon0-dbgsym libxml2-dbg libxrandr2-dbgsym libxrender1-dbgsym zlib1g-dbg
```
**sudo apt install** caja-dbgsym libatk-bridge2.0-0-dbgsym libatk1.0-0-dbgsym libatspi2.0-0-dbgsym libblkid1-dbgsym libbsd0-dbgsym libcairo-gobject2-dbgsym libcairo2-dbgsym libcaja-extension1-dbgsym libdatrie1-dbgsym libdbus-1-3-dbgsym libdconf1-dbgsym libepoxy0-dbgsym libexempi8-dbgsym libexif12-dbgsym libexpat1-dbgsym libffi6-dbg libfontconfig1-dbgsym libfreetype6-dbgsym libfribidi0-dbgsym libgail-3-0-dbgsym libgcc1-dbg libgcrypt20-dbgsym libgdk-pixbuf2.0-0-dbgsym libgpg-error0-dbgsym libgraphite2-3-dbgsym libgtk-3-0-dbgsym libharfbuzz0b-dbgsym libice6-dbg libicu63-dbgsym liblz4-1-dbgsym liblzma5-dbgsym libmate-desktop-2-17-dbgsym libmount1-dbgsym libnotify4-dbgsym libpango-1.0-0-dbgsym libpangocairo-1.0-0-dbgsym libpangoft2-1.0-0-dbgsym libpcre3-dbg libpixman-1-0-dbgsym libpng16-16-dbgsym libselinux1-dbgsym libsm6-dbgsym libstartup-notification0-dbgsym libstdc++6-8-dbg libsystemd0-dbgsym libthai0-dbgsym libuuid1-dbgsym libwayland-client0-dbgsym libwayland-cursor0-dbgsym libwayland-egl1-dbgsym libx11-6-dbgsym libx11-xcb1-dbgsym libxcb-render0-dbgsym libxcb-shm0-dbgsym libxcb-util0-dbgsym libxcb1-dbgsym libxcursor1-dbgsym libxdamage1-dbgsym libxdmcp6-dbg libxfixes3-dbgsym libxi6-dbgsym libxinerama1-dbgsym libxkbcommon0-dbgsym libxml2-dbg libxrandr2-dbgsym libxrender1-dbgsym zlib1g-dbg

### Install those that are missing
```
$ for lib in libgio libgmodule libgobject libXcomposite libglib libXext libgthread libXau; do apt-cache search $lib dbg; done
libgio3.0-cil-dbgsym - debug symbols for libgio3.0-cil
libxcomposite1-dbg - X11 Composite extension library (debug package)
libglibd-2.0-0-dbgsym - debug symbols for libglibd-2.0-0
libglib2.0-0-dbgsym - debug symbols for libglib2.0-0
libglib2.0-bin-dbgsym - debug symbols for libglib2.0-bin
libglib2.0-dev-bin-dbgsym - debug symbols for libglib2.0-dev-bin
libglib2.0-tests-dbgsym - debug symbols for libglib2.0-tests
libglibmm-2.4-1v5-dbgsym - debug symbols for libglibmm-2.4-1v5
libglib2.0-cil-dbgsym - Debug symbols for libglib2.0-cil
libglib-object-introspection-perl-dbgsym - debug symbols for libglib-object-introspection-perl
libglib-perl-dbgsym - debug symbols for libglib-perl
libxext6-dbg - X11 miscellaneous extensions library (debug package)
libxmu6-dbg - X11 miscellaneous utility library (debug package)
libxmuu1-dbg - X11 miscellaneous micro-utility library (debug package)
libxau6-dbg - X11 authorisation library (debug package)
$ for lib in libgio libgmodule libgobject libXcomposite libglib libXext libgthread libXau; do apt-cache search $lib dbg; done | cut -d' ' -f 1 | tr '\n' ' '
libgio3.0-cil-dbgsym libxcomposite1-dbg libglibd-2.0-0-dbgsym libglib2.0-0-dbgsym libglib2.0-bin-dbgsym libglib2.0-dev-bin-dbgsym libglib2.0-tests-dbgsym libglibmm-2.4-1v5-dbgsym libglib2.0-cil-dbgsym libglib-object-introspection-perl-dbgsym libglib-perl-dbgsym libxext6-dbg libxmu6-dbg libxmuu1-dbg libxau6-dbg
```
**sudo apt install** libgio3.0-cil-dbgsym libxcomposite1-dbg libglibd-2.0-0-dbgsym libglib2.0-0-dbgsym libglib2.0-bin-dbgsym libglib2.0-dev-bin-dbgsym libglib2.0-tests-dbgsym libglibmm-2.4-1v5-dbgsym libglib2.0-cil-dbgsym libglib-object-introspection-perl-dbgsym libglib-perl-dbgsym libxext6-dbg libxmu6-dbg libxmuu1-dbg libxau6-dbg

**Comment by rbuj** [comment]
@shirishag75 Have you been able to debug caja using gdb by attaching caja running process to gdb, for instance `gdb -p $(pgrep caja)`?

**Comment by shirishag75** [comment]
@rbuj, thank you for sharing the above info. as well. I am installing debian-goodies and see if there are any -dbgsym packages which are not installed which are needed to debug 

@rbuj, do I need to do a sudo ?

Btw I'm running on testing - ```

$ lsb_release -i -r
Distributor ID:	Debian
Release:	testing
```

Could it be done without using sudo 

`LANG=C sudo gdb -p $(pgrep caja) -ex continue -ex bt`

Also if I use the above command, where would it put the backtrace, I am guessing in the root's home directory rather than in the user's home directory :(

**Comment by rbuj** [comment]
You don't need to do sudo.
[bt command](https://sourceware.org/gdb/onlinedocs/gdb/Backtrace.html) prints the backtrace on gdb console.
You can also debug caja in eclipse:
```shell
$ cdtdebug -a $(pgrep -f caja)
```
![Captura de pantalla a 2019-08-29 22-29-01](https://user-images.githubusercontent.com/10171411/63974145-908f3200-caac-11e9-9da7-025ac19b5abe.png)

**Comment by lukefromdc** [comment]
Running  `sudo gdb caja` is simply one way of running a new instance of caja instead of opening a new window in the existing caja instance. Other ways are to run `gdb caja` in a session other than  a MATE session, or to open dconf-editor and set org>mate>desktop>session>required-components>filemanager to "" and start a new session in which caja does not run by default, and in that session run `gdb caja` in terminal and after it loads remember to type `run`(as in all "gdb<something>" cases) . With that approach be sure to set that back to caja afterwards to get icons back on the desktop.

Running` caja --quit` or `killall caja `simply restarts caja, and simply running `caja` while caja is already running (as same user) just opens a new window in the existing process thanks to the use of GtkApplication to force a single instance,

**Comment by shirishag75** [comment]
@rbuj all the work was of no use.  What keeps on happening is that if I put in external usb disk and then try to eject it (interestingly, the unmount option isn't presented) . After a time I get a dialog box that the folder is not responding. Closing it, closes the whole thing and I get no stack :(

[```
Thread 0x7f7bbc202700 (LWP 13861) exited]
[Thread 0x7f7bbc7fca80 (LWP 13860) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
No stack.
(gdb) quit
```

**Comment by lukefromdc** [comment]
I have never had this happen, can't duplicate it and this am out of ideas myself.
