### ISSUE TITLE
Proposed modification to the layout when the second pane is open 

### ISSUE THREAD

**Issue by PacmanTetris** [mate-desktop/caja#1098]

**Comment by PacmanTetris** [comment]
This is a proposed modification of the behavior and the layout when two file panes are open.
Currently, when the second pane (on the right side of the screen) is focused, the tree pane is on the left side of the screen.
I propose that whenever the focus shifts to the second pane, the tree pane should shift to the right margin of the screen, adjacent to the second pane. When the focus shifts back to the first pane, the tree pane would shift back to the left margin of the screen.

The advantages of this modification would be that
1) the tree pane is always adjacent to the focused pane, which is more convenient for the user (the view will be less cluttered, as there is no spatial separation between a file pane and its tree)
2) this arrangement is visually more pleasant. I suggest that the background colors of the tree pane and of the focused file pane should be the same (or slightly different, such as two shades of the same color), whereas the background color of the unfocused file pane should be in more or less stark contrast with the other color. This color arrangement will make the layout not only more visually pleasant, but will also enhance the usability because it will be much more immediate for the user to identify which pane is focused

**Comment by PacmanTetris** [comment]
Hi

could you please re-open the ticket? I have added in the comments the information that was missing when you closed the issue.

Thanks

 

Sent: Tuesday, December 18, 2018 at 5:58 PM

**Comment by lukefromdc** [comment]
That might be a major change in the code, and would break the normal expectaction that the sidebar is on the left.I don't see this happening
