### ISSUE TITLE
Caja not starts on Antergos

### ISSUE THREAD

**Issue by Magmaruss** [mate-desktop/caja#1116]
#### Expected behaviour
Caja starts when executing command 'caja' from terminal

#### Actual behaviour
Caja doesn't start up and terminal shows error message:

> caja: error while loading shared libraries: libexempi.so.3: cannot open shared object file: No such file or directory

I have latest exempi lib installed - 2.5.0-1

#### Steps to reproduce the behaviour

- Open terminal
- Execute command 'caja'

#### MATE general version
mate-desktop 1.20.4-1

#### Package version
caja 1.20.3-1

#### Linux Distribution
Arch 4.20.3-arch1-1-ARCH Antergos

**Comment by yetist** [comment]
Yes, after the latest system upgrade of archlinux, the exempi has been upgraded, so caja, eom can not startup. These packages need to be recompiled to link with the new libraries.
I think you should report bug to archlinux, Thank you.

**Comment by raveit65** [comment]
For this reason we ask for a downstream report against your distro in our template, to inform your distro mantainer and to avoid unneeded reports here.
Thank you for ignoring the template.

**Comment by Magmaruss** [comment]
No problem, my pleasure :)
