### ISSUE TITLE
If EEL_OMIT_SELF_CHECK is defined, the build will fail

### ISSUE THREAD

**Issue by yetist** [mate-desktop/caja#1129]
Run command like this:
```
export CFLAGS='-Wall -DEEL_OMIT_SELF_CHECK'
./autogen.sh
make
```
Will get the output:
```
  CCLD     caja

/usr/bin/ld: caja-application.o: in function `do_perform_self_checks':

caja-application.c:(.text+0x3fdd): undefined reference to `eel_exit_if_self_checks_failed'

/usr/bin/ld: caja-application.c:(.text+0x3fec): undefined reference to `eel_exit_if_self_checks_failed'

/usr/bin/ld: ../libcaja-private/.libs/libcaja-private.a(caja-directory.o): in function `caja_self_check_directory':

caja-directory.c:(.text+0x3a9d): undefined reference to `eel_before_check'
```
More log here: https://api.travis-ci.org/v3/job/487260061/log.txt

The `src/caja-application.c` file use different define:
```
static void
do_perform_self_checks (gint *exit_status)
{
#ifndef CAJA_OMIT_SELF_CHECK
    /* Run the checks (each twice) for caja and libcaja-private. */

    caja_run_self_checks ();
    caja_run_lib_self_checks ();
    eel_exit_if_self_checks_failed ();

    caja_run_self_checks ();
    caja_run_lib_self_checks ();
    eel_exit_if_self_checks_failed ();
#endif

    *exit_status = EXIT_SUCCESS;
}
```

**Comment by yetist** [comment]
If use the follow comand, also failed.
```
CFLAGS="-Wall -DEEL_OMIT_SELF_CHECK -DCAJA_OMIT_SELF_CHECK" ./autogen.sh --prefix=/usr && make
```

**Comment by yetist** [comment]
I tried running `make distcheck` in the Docker container and I got the following failure message:

```
Unable to init server: Could not connect: Connection refused

(check-program:21884): Gtk-WARNING **: 08:47:22.427: cannot open display: 
Trace/breakpoint trap (core dumped)
FAIL check-eel (exit status: 133)
```

The `check-program` program failed to run because there is no X display in the Docker container.

Looking at the `eel/check-program.c` code, I found that after the `EEL_OMIT_SELF_CHECK` is defined, the check-program returns successfully, so that `make distcheck` can be successfully executed in the Docker container.

The problem is that there is no configure parameter to define the `EEL_OMIT_SELF_CHECK`, and if it is defined by the `CFLAGS` environment variable, the compilation will fail. If I try to resolve the compilation failure, I need to define another  variable `CAJA_OMIT_SELF_CHECK`, but the compilation will fail even if they are defined by CFLAGS at the same time.

```
CFLAGS="-Wall -DEEL_OMIT_SELF_CHECK -DCAJA_OMIT_SELF_CHECK" ./autogen.sh --prefix=/usr && make
```

So, we need to read the code to solve this problem, otherwise we can't let Travis CI run `make distcheck`.

**Comment by raveit65** [comment]
Do, we really need `-DEEL_OMIT_SELF_CHECK -DCAJA_OMIT_SELF_CHECK` ?
For my point of view it's more important to have a working `make distcheck` command in travis.
This will save a lot of work for me when i release new tarballs, to avoid that i have to fix a broken distcheck for myself.

**Comment by yetist** [comment]
The build logs on fedora 29:
- use `'CFLAGS=-Wall -DEEL_OMIT_SELF_CHECK'`:
https://travis-ci.org/yetist/caja/jobs/487442500
- use `CFLAGS='-Wall -DEEL_OMIT_SELF_CHECK -DCAJA_OMIT_SELF_CHECK'`
https://travis-ci.org/yetist/caja/jobs/487459398

BTW, there are too many warnings after use the `-Wall`, It's going to go beyond the 10,000 line limit on the travis website, if it happens,  can only see the end output line through the raw log file.

**Comment by raveit65** [comment]
Too much errors, who like to fix them......

**Comment by yetist** [comment]
Let me try it.

**Comment by yetist** [comment]
Fixed this issue by the commits:
91f1dc66b6f56e57734d3048501a6c4679331290
2d595142c4c3f15391d71bf25e48e5905804ba94
