### ISSUE TITLE
Can't start caja as native wayland application

### ISSUE THREAD

**Issue by p-hamann** [mate-desktop/caja#1145]
#### Expected behaviour
Open a window as native wayland application

#### Actual behaviour
Error message:
Could not parse arguments: Cannot open display

#### Steps to reproduce the behaviour
1) Start a wayland session with a wayland compositor (e.g. Sway, Weston,..)
2) $ GDK_BACKEND=wayland caja

#### MATE general version
no MATE, Sway 1.0-rc2 in my case

#### Package version
1.20.3-2

#### Linux Distribution
Arch Linux

**Comment by lukefromdc** [comment]
Note that caja's desktop cannot run as a native wayland window without major changes that have not been started. It works fine under xwayland for now, but we are a long way from MATE on wayland

**Comment by p-hamann** [comment]
Thank you for your answer. Should not it be possible to run caja without the desktop option as wayland window because it uses gtk3?

**Comment by lukefromdc** [comment]
Not all widgets are native GTK widgets,, there is a lot of custom drawn stuff, and I'm pretty sure
the icon-canvas as drawn on the desktop uses x11 specific code. GNOME cited the difficulty of 
porting the desktop canvas to Wayland as their excuse to remove desktop code entirely from
Nautilus, something MATE will never do.

**Comment by p-hamann** [comment]
Alright, i got it. Thank you

**Comment by roberti42** [comment]
Any news about this?

**Comment by mbkma** [comment]
no, caja ist still missing wayland support: https://wiki.mate-desktop.org/developers-corner/wayland-meson/

**Comment by lukefromdc** [comment]
Native wayland support will require rewriting the desktop canvas that displays the icons. Its the same canvas used in navigation windows so far as I know. The whole reason Nautilus no longer handles desktop icons is reportedly that wayland support for them would have required a full rewrite of the very old canvas code. Apparently they found a simpler way for navigation windows only.

**Comment by eternal-sorrow** [comment]
Once again: is it possible to make caja work in Wayland without desktop support?

**Comment by mbkma** [comment]
It is not right now. Porting Caja to work on Wayland, even without desktop support is a major task, as all x11 related functions need to be replaced by functions that work on Wayland (and Caja has lots of x11 related functions).

**Comment by circl-lastname** [comment]
https://wiki.mate-desktop.org/developers-corner/wayland-meson/ Says caja and mate-control-center are finished, but are not working for me. MATE 1.26.0 on Debian 

mate-control-center says it cannot cast a Wayland screen to X11 screen, even with GDK_BACKEND=wayland
caja says Failed to parse arguments: Cannot open display: even with GDK_BACKEND=wayland

**Comment by lukefromdc** [comment]
You need MATE 1.28 for real wayland support. Preliminary woirk made it into 1.26 but a lot of things have changed since rhen. You cannot show desktop icons in Caja on 1.26, or run any part of mate-control-center in wayland except under Xwayland. A caja desktop under xeayland cannot be kept on the bottom, thus can cover up all other windows when clicked on. No tray in the panel until 1.28 for wayland, SNI supported wirh 1.28 in wayland. Most panel applets gained the ability to build in-proceaa for wayland support in 1.28 as well

**Comment by circl-lastname** [comment]
I've realized my error and removed my comment soon after posting. Thanks however

**Comment by lukefromdc** [comment]
No problem, people need to be able to find this information somewhere
