### ISSUE TITLE
Always show the file/folder rename widget

### ISSUE THREAD

**Issue by yetist** [mate-desktop/caja#1214]
#### Expected behaviour
After rename a file/folder, the rename widget is no longer displayed again.

#### Actual behaviour
After rename a file/folder,  then into any folder, the rename widget is show again, and alway display.

![image](https://user-images.githubusercontent.com/665058/56269676-c5ff3880-6126-11e9-867b-08dc683755ac.png)

#### Steps to reproduce the behaviour
- Open caja
- Select a file or folder, press F2, modify some characters and press Enter, the rename widget hide, and the file name is changed, everything is OK now.
- Enter other folders, the previous file rename widget is show again and keep show all the time.

#### MATE general version
master, and I remembered that 1.22 also has this issue.

**Comment by lukefromdc** [comment]
I've never seen the rename entry do this, but I HAVE seen the typeahead search box do this, I think (but am not sure) in both Nemo and Caja.

**Comment by yetist** [comment]
Sorry, I confirm it's a caja-extension's bug for myself, so close this report.
