### ISSUE TITLE
Copying to/from SSH server connection should keep timestamps

### ISSUE THREAD

**Issue by jondo** [mate-desktop/caja#1226]
#### Steps to reproduce the behaviour
- Use Caja to connect to an SSH server.
- Copy files to/from the server.

#### Expected behaviour
The "Date Modified" timestamps of the files should stay unchanged.

#### Actual behaviour
The "Date Modified" timestamps are reset to the current time.

#### Versions:
MATE general version: 1.20.0
Package version: 1.20.2
Linux Distribution: Linux Mint 19.1 MATE 64bit

#### Link to downstream report of your Distribution
N/A

#### Remark
According to [gvfs](https://gitlab.gnome.org/GNOME/gvfs/issues/346#note_357921),
>  it is up to the client to use G_FILE_COPY_ALL_METADATA, or copy some attributes selectively over g_file_get_attribute() resp. g_file_set_attribute()  functions.

**Comment by dark-penguin** [comment]
So this is why editing a file over ssh keeps it in permanent "File updated on disk!" state! I'm on MATE 1.20.4, Debian Buster.
