### ISSUE TITLE
Copy queue and pausing

### ISSUE THREAD

**Issue by handycz** [mate-desktop/caja#124]
It would be handy if one could queue more copy operations so they would run serially. Also there should be an option to pause copying (whole queue or only one file)

**Comment by alejandro-perez** [comment]
For the interface of queuing, I have a suggestions:

In the copy progress dialog, since you have a "row" per copy operation, and each copy operation has a single destination, you can drop files on top of these "rows", and files are queued to be copied to that very destination.

**Comment by lukefromdc** [comment]
Fixed with the series of commits
https://github.com/mate-desktop/caja/commit/89058ed86d271f22cd9359c66e42ff9e8cfd4715
through
https://github.com/mate-desktop/caja/commit/9081b8d96936b625c3c83b88282ad7437f8ef462
