### ISSUE TITLE
pdf preview is not loading with high cpu usage

### ISSUE THREAD

**Issue by mbkma** [mate-desktop/caja#1261]
#### Expected behaviour
Thumbnail loads quick & normal cpu usage 

#### Actual behaviour
With some pdf files thumbnails are loading forever which results in high cpu usage (~10-20%)
topo.pdf (2,2 MB) has 190 pages, is created with LaTeX with hyperref package
(In Nautilus 3.26.4 everything works fine here)

![Screenshot at 2019-07-12 11-04-36](https://user-images.githubusercontent.com/39454100/61117251-651d9d00-a496-11e9-9473-ddb1807a2f40.png)
![Screenshot at 2019-07-12 11-09-02](https://user-images.githubusercontent.com/39454100/61117424-be85cc00-a496-11e9-867b-708af4e6d10b.png)

#### MATE general version
1.20.1

#### Package version
1.20.2

#### Linux Distribution
Ubuntu Mate 18.04

**Comment by lukefromdc** [comment]
This might vary with the types of PDF documents in question? I've never had this issue, even on books of a couple hundred pages.

**Comment by mbkma** [comment]
can not reproduce the issue anymore, maybe it was caused by something else
