### ISSUE TITLE
Inconsistent naming of "Trash" when using English (UK)

### ISSUE THREAD

**Issue by Lantizia** [mate-desktop/caja#1273]
#### Expected behaviour
A consistent name, preferably not "Trash" as no one says that word in the British isles :)  
Basically we just call them bins, or possibly rubbish bin if you really want two words.

#### Actual behaviour
![image](https://user-images.githubusercontent.com/10448369/61962537-9e3f2c80-afc1-11e9-9000-5f2b3e67f324.png)

#### Steps to reproduce the behaviour
Should be self evident, but basically I could see the issue on all my installs of Ubuntu MATE 18.04 - so I thought I'd perhaps load up the 19.04 ISO in a VM.  
At first I used the live CD mode and couldn't see the issue (if I were to have taken the same screenshot as above - every red arrow would point to the word 'Trash', so it was consistent).
But if you actually install it as a British person would (e.g. English UK keyboard layout, GMT/BST time zone, etc etc...) then you get the above screenshot once the system is installed.

**Comment by monsta** [comment]
Translations are done in Transifex:
https://www.transifex.com/mate/MATE

We just sync with it, push new strings and pull new translations.

You'll need to register there and ask to join the team for your language.

**Comment by Lantizia** [comment]
Well I made an account on that Transifex thing, joined the MATE project on there... and I can't say it is jumping out at me where or how I'd go about fixing this specific bug.

I'm happy to try and figure out how this is done (any advice?) but you really shouldn't be expecting all people who would file a bug... to be able/willing to supply the fix themselves.  

This report itself should stand on its own merit and not closed until fixed, that is... if it is even agreed that there is a problem here?

You stated "we just sync with it, push new strings and pull new translation" - are you saying the word 'Trash' is going in (i.e. English - United States of America) and then you're getting out the phrases (supposedly in English - United Kingdom) of... "Rubbish Bin", "The Rubbish Bin", "Wastebasket" and also finally "Trash" ???

That seems like some crazy translator that can't make it's mind up.

My personal opinion on this is that it should simply be called 'Bin' which yes it's short for 'Rubbish Bin' but then I'm sure 'Trash' is short for 'Trash Can' also :)  Either that or just call it Trash in all English languages.

**Comment by cwendling** [comment]
@Lantizia to improve the translations for this, go to https://www.transifex.com/mate/MATE/language/en_GB/ and select "master--caja", and there perform all fixes needed.  You need to be accepted as a member of the UK team.

I also agree this shouldn't be closed before either a fix is out there or this is deemed not an issue.  Can we reopen this @monsta, or is it a policy to close all i18n bugs because they are dealt with some place else?

**Comment by Lantizia** [comment]
Ah "master--caja", I guess all my efforts in "1-22--caja" have been in vain then... it's just the first one I could see in the list, I never twigged what the "1-22" was in reference to until just now :)

I don't suppose you know if there is a way of searching for trash/trashing/trashed (searching for trash ought to do) within *all* "master--" areas of Transifex?  It's just that it likely pops up in documentation and lots of other non-Caja areas.

**Comment by cwendling** [comment]
> I guess all my efforts in "1-22--caja" have been in vain then...

Not necessarily, that's the current stable version and it might be released again at some point.  But it's not very future-proof, no :)

> I don't suppose you know if there is a way of searching for trash/trashing/trashed (searching for trash ought to do) within all "master--" areas of Transifex? It's just that it likely pops up in documentation and lots of other non-Caja areas.

Unfortunately no, I don't know, and you're post probably right there's other area that needs touching.  One I'd think of is *eom* that has a dialog about that, but I don't know which term it uses in en_UK

>

**Comment by Lantizia** [comment]
Well I've found 64 "master--" areas and I'm just going through them now one at a time.  Shouldn't take me too much longer.

**Comment by Lantizia** [comment]
Right looking through those 64 "master--" areas and I have dealt with the below ones... as these are the ones that mention trash (case insensitive) when untranslated from "English - United States"...

master--caja
master--eom
master--eom-user-guide
master--mate-applets
master--mate-search-tool-user-guide
master--mate-settings-daemon
master--mate-user-guide-content
master--mate-utils
master--pluma
master--trashapplet-applet-user-guide

And yeah I've opted for Bin instead of Trash.  Kept the translation as close to the original "English - United States" as possible just swapping things like Trash->Bin, trash->bin, trashed->binned... you get the idea.

**Comment by andibing** [comment]
Hi....

I've been involved in many English(UK) translation (i.e. en_gb) projects for open source projects.
I've been using "Rubbish Bin" instead of Trash consistently. 
You may find this table handy... https://wiki.ubuntu.com/EnglishTranslation/WordSubstitution

Regards,
Andi

**Comment by Lantizia** [comment]
The work was already done, so now... bin, rubbish bin and rubbish is used appropriately.  You should already be able to see it in things like Ubuntu MATE 20.04 for example which I'm about to move to and I'm testing in a VM.
