### ISSUE TITLE
Feature Request (renaming files by two times clicking on them)

### ISSUE THREAD

**Issue by blueray453** [mate-desktop/caja#1275]
Hey folks
Long time ago when I was still using windows there was this very nice feature that i'm still missing in Mate world! It is not a big thing but can make your life a lot easier if you know what i'm saying!
so here it is I want when we click two times on a file or folder, with a little bit pause between them, it triggers rename of that file or folder!
For seeing this in action any windows version does work just click on a file, pause a moment and click on it again then you can see that you can rename the file.
Really appreciate if someone does implement it!

You can find a similar feature request (which is long ago implemented) in Nemo. https://github.com/linuxmint/nemo/issues/520

thank you very much!

**Comment by flexiondotorg** [comment]
This feature is available via a Caja extension:

  * https://tari.in/www/software/cajarename/

This extension is shipped by default in some distros, Ubuntu MATE for example. I don't think we need to add the feature to Caja when our community has provided an excellent extension :smiley:
