### ISSUE TITLE
Multiple selection areas

### ISSUE THREAD

**Issue by thiagofurlan** [mate-desktop/caja#1276]
#### Expected behaviour
None

#### Actual behaviour
Caja allows you to create multiple selection areas

#### Steps to reproduce the behaviour
Start Caja
Press on Ctrl + . (dot)
Press mouse left button and drag
Press mouse left button and drag, again, again...

#### MATE general version
All

#### Linux Distribution
I tested on Ubuntu and Mint with Mate Desktop

**Comment by sc0w** [comment]
<kbd>control</kbd><kbd>.</kbd> does nothing since the commit https://github.com/mate-desktop/caja/commit/e740a981b0be879321e5b3837332712d8231b400 because it makes the issue https://github.com/mate-desktop/caja/issues/1024

**Comment by lukefromdc** [comment]
As of now in caja 1.27 builds from git master, I can use ctrl plus the mouse to rubberband two separate areas in a caja window no problem. You can hold the ctrl key down the entire process or just while selecting each area, behavior is the same: left mouse button hold to rubberband, left mouse button release to stop for any one area
