### ISSUE TITLE
caja closes all instances on reboot in Mint 19.1

### ISSUE THREAD

**Issue by Meshuguna** [mate-desktop/caja#1277]

**Comment by lukefromdc** [comment]
First things first:  open dconf-editor and make sure you have org->mate->desktop->session->auto-save-session set to TRUE, as this could have been lost at the update.  You reported Krusader is using a different, unrelated system to save it's application state, presumably that would work even if session-saving is set to FALSE though I am not familiar enough with Krusader to be sure of that.

Try this first, if it doesn't work we have a bug

**Comment by Meshuguna** [comment]
Thanks for this tip!

org-> >mate->desktop->session->auto-save-session 
is already set to ON (TRUE).

So, it looks like we have a bug.
Still, I'm wondering why no one else has reported this. 

Another feature of Krusader it would be nice to see in
Caja is regular expression searches... it's always
something!

Thanks,
M

**Comment by lukefromdc** [comment]
I can't duplicate this, it works fine on my machine.

**Comment by lukefromdc** [comment]
Just tested reboots with session saving turned on, saved Caja windows came up fine both with shutting down from the "shut down" panel applet and with logging out, then shutting down from lightDM. I simply can't duplicate this, wonder what is different?

Be sure to fill out an  issue report against LinuxMint, as this could be distro-specific. Also, is this caja-only or all saved applications? Try a Pluma window and see if it comes back up.

**Comment by Meshuguna** [comment]
Thanks for trying!
It's not just caja but all saved applications.
I left a few caja windows open, a text document
and a .pdf in Okular.

They all closed and I got a window saying:

Error – Okular
Could not open
OK

When I clicked on OK it opened Okular with no
documents.

A simple 'Restart' shutdown did leave my instance
of Okular open and intact, but still closed 
everything else.

This worked fine in Mint 17.3 so apparently it's
specific to the Mint distro and specifically to
version Tessa 19.1.

Thanks,
M

**Comment by lukefromdc** [comment]
OK, than this is not a Caja bug but rather a distro-specific issue with mate-session-manager, which is in charge of saving sessions. Open an issue against mate-session-manager with LinuxMint, and then open one here including that reference (the issue template will tell you where to put it). Closing this one as wrong package.

**Comment by Meshuguna** [comment]
Thanks!
