### ISSUE TITLE
[Translation] How to translate some strings

### ISSUE THREAD

**Issue by sbadux** [mate-desktop/caja#1294]
Hello,
could you please tell me if we have to translate the strings like:

file;manager;change;properties;behaviour;appearance;windows;MATE;
home;personal;folder;open;MATE;
bookmarks;browse;local;network;locations;MATE;

Where are they used? Should they be translated or not?

**Comment by sbadux** [comment]
Thanks a lot. Now it's more clear :) Just one question: can the "translate" them in Transifex keeping the same string?

e.g. 
Currently:
English: application-x-executable
Italian: [empty]

Translated
English: application-x-executable
Italian: application-x-executable

in this way we get 2 advantages:
-We can see the real translation %
-We avoid  that some other user will see them as untranslated and try to translate them

**Comment by rbuj** [comment]
Yes, you can translate it in that way, It's better than leaving it blank at Transifex ;-)

The standard says that the Icon desktop entry key can be translated (Value Type = localestring)
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

I sent also the PR https://github.com/mate-desktop/caja/pull/1293 to don't use the translation for the icon name.
