### ISSUE TITLE
Caja locks up when transferring file with parenthesis in name over mtp

### ISSUE THREAD

**Issue by Sl0vi** [mate-desktop/caja#1298]
#### Expected behaviour
I'm trying to copy files to my Android phone. The files should get copied to my phone.

#### Actual behaviour
If a file has parenthesis in its name, ( or ) Caja locks up for a very long time. Eventually after several minutes a dialog window appears saying that there was an error copying the file.

#### Steps to reproduce the behaviour
Plug an Android device into your computers USB port. Copy a file with a parenthesis in the name over to the Android Phone.

#### MATE general version
1.22.0

#### Package version
MATE caja 1.22.1

#### Linux Distribution
Linux Mint 19.2

**Comment by lukefromdc** [comment]
This may simply be one case of a more general problem with the gvfs MTP backend. I have observed that if ANY file transfer to an Android device hangs, caja can lock up. In some cases I have had to forcibly unmount the device and restart caja to get out of this. 

This more general issue can be a real nuisance when filling a phone to the last byte to destroy "deleted" data for security reasons, as those last few garbage files I am transferring in are slow to copy as the flash on the phone is of course slow when almost all space is gone

**Comment by lukefromdc** [comment]
In a quick test, an empty file named test(abc2).txt with a 32 KB length copied across fine. There might be a difference in the android device in question (this one is older, not going to publish the version as I don't want to help enemies attack it), or possibly in GVFS version. 

I have Debian Unstable here, can't duplicate your exact problem but have often seen the more general case. When the backend hangs up, Caja should not lock up all other windows waiting on it.

**Comment by lukefromdc** [comment]
In the very old "Nautilus – Inside the Shell" document written by  Alexander Larsson of Red Hat, Inc and still packed with caja today we have this paragraph:

"As explained above Nautilus uses asynchronous gnome-vfs operations in order to avoid
blocking the main thread, causing an unresponsive user interface. It is not allowed to wait for
a piece of information being read from a file without returning to the main loop to handle
user input while waiting."

Apparently that no longer works the way it once did, as we are now getting exactly that unresponsive user interface with GVFS plugins that did not even exist when that document was written

**Comment by Sl0vi** [comment]
OK, so I had some time to do some more testing and the weird thing is that I haven't been able to reproduce the issue at all tonight and I have no idea why it is suddenly working.

There are some errors in syslog every time I connect my phone.

```
01:38:11 kernel: [13584.921237] usb 1-5: new high-speed USB device number 12 using xhci_hcd
01:38:11 kernel: [13585.072033] usb 1-5: New USB device found, idVendor=04e8, idProduct=6860, bcdDevice= 4.00
01:38:11 kernel: [13585.072034] usb 1-5: New USB device strings: Mfr=2, Product=3, SerialNumber=4
01:38:11 kernel: [13585.072035] usb 1-5: Product: SAMSUNG_Android
01:38:11 kernel: [13585.072036] usb 1-5: Manufacturer: SAMSUNG
01:38:11 kernel: [13585.072037] usb 1-5: SerialNumber: <REMOVED>
01:38:11 upowerd[1133]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-5
01:38:11 gvfsd[2244]: Device 0 (VID=04e8 and PID=6860) is a Samsung Galaxy models (MTP).
01:38:11 upowerd[1133]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5:1.0
01:38:12 gvfsd[2244]: Error 1: Get Storage information failed.
01:38:12 gvfsd-computer[3255]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
01:38:12 gvfsd-computer[3255]: message repeated 2 times: [ g_object_unref: assertion 'G_IS_OBJECT (object)' failed]
01:39:07 gnome-terminal-[3287]: g_menu_insert_item: assertion 'G_IS_MENU_ITEM (item)' failed
01:39:18 gvfsd[2244]: PTP: reading event an error 0x05 occurred
01:39:18 upowerd[1133]: unhandled action 'unbind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5:1.0
01:39:18 kernel: [13652.085662] usb 1-5: USB disconnect, device number 12
01:39:18 upowerd[1133]: unhandled action 'unbind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-5
01:39:19 kernel: [13652.392171] usb 1-5: new high-speed USB device number 13 using xhci_hcd
01:39:19 kernel: [13652.542160] usb 1-5: New USB device found, idVendor=04e8, idProduct=6860, bcdDevice= 4.00
01:39:19 kernel: [13652.542165] usb 1-5: New USB device strings: Mfr=2, Product=3, SerialNumber=4
01:39:19 kernel: [13652.542169] usb 1-5: Product: SAMSUNG_Android
01:39:19 kernel: [13652.542172] usb 1-5: Manufacturer: SAMSUNG
01:39:19 kernel: [13652.542174] usb 1-5: SerialNumber: <REMOVED>
01:39:19 upowerd[1133]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-5
01:39:19 gvfsd[2244]: Device 0 (VID=04e8 and PID=6860) is a Samsung Galaxy models (MTP).
01:39:19 upowerd[1133]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5:1.0
01:39:19 gvfsd-computer[3255]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

I have no idea if these errors are relevant.

**Comment by howels** [comment]
I have experienced the same freezes when trying to access a share via SFTP.  The same directory is accessible via SMB but using SFTP causes the UI to freeze, usually when opening a directory containing many files/subdirectories.

**Comment by Sl0vi** [comment]
So this issue is quite old, I've moved to Linux Mint 20.1 and I haven't experienced any issues when copying to and from my phone for a while now.
I don't know if anything specifically has been done to fix this issue, but since the problem seem to have gone away and nothing new has been posted here in over a year, I guess this issue can just be closed.

**Comment by kikislater** [comment]
Issue is still here with caja 1.26
