### ISSUE TITLE
1.23.2: test suite fails and core dumps

### ISSUE THREAD

**Issue by kloczek** [mate-desktop/caja#1299]
<pre>+ xvfb-run -a /usr/bin/make -O -j48 V=1 VERBOSE=1 check
Making check in po
make[1]: Nothing to be done for &apos;check&apos;.
Making check in eel
/usr/bin/make  check-am
/usr/bin/make  check-TESTS
make[4]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/eel&apos;
PASS: check-eel
make[4]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/eel&apos;
make[4]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/eel&apos;
============================================================================
Testsuite summary for caja 1.23.2
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/eel&apos;
Making check in libcaja-extension
make[1]: Nothing to be done for &apos;check&apos;.
Making check in libegg
make[1]: Nothing to be done for &apos;check&apos;.
Making check in libcaja-private
/usr/bin/make  check-am
make[2]: Nothing to be done for &apos;check-am&apos;.
Making check in src
/usr/bin/make  check-recursive
Making check in file-manager
/usr/bin/make  check-am
make[4]: Nothing to be done for &apos;check-am&apos;.
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src&apos;
true -P ./ -f ./ui-a11y.false -s ./ui-a11y.suppr -o ui-a11y.err ./caja-file-management-properties.ui ./caja-bookmarks-window.ui
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src&apos;
/usr/bin/make  check-TESTS
make[5]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src&apos;
FAIL: check-caja
make[5]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src&apos;
make[5]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src&apos;
=====================================
   caja 1.23.2: src/test-suite.log
=====================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: check-caja
================

running caja_self_check_file_utilities
running caja_self_check_file_operations
running caja_self_check_directory

(caja:3834527): GLib-GIO-ERROR **: 23:56:49.578: Settings schema &apos;org.mate.caja.preferences&apos; is not installed
./check-caja: line 2: 3834527 Trace/breakpoint trap   (core dumped) ./caja --check --g-fatal-warnings
FAIL check-caja (exit status: 133)

============================================================================
Testsuite summary for caja 1.23.2
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://mate-desktop.org
============================================================================
make[5]: *** [Makefile:1312: test-suite.log] Error 1
make[5]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src&apos;
make[4]: *** [Makefile:1420: check-TESTS] Error 2
make[3]: *** [Makefile:1521: check-am] Error 2
make[2]: *** [Makefile:1204: check-recursive] Error 1
make[1]: *** [Makefile:1523: check] Error 2
make: *** [Makefile:501: check-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.66fyZq (%check)
</pre>

<pre>$ coredumpctl gdb /home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src/.libs/lt-caja
           PID: <b>3834527</b> (lt-caja)
           UID: 1000 (tkloczko)
           GID: 1000 (tkloczko)
        Signal: 5 (TRAP)
     Timestamp: Sat 2019-09-07 23:56:49 BST (2min 15s ago)
  Command Line: /home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src/.libs/lt-caja --check --g-fatal-warnings
    Executable: <b>/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src/.libs/lt-caja</b>
 Control Group: /user.slice/user-1000.slice/session-38.scope
          Unit: session-38.scope
         Slice: user-1000.slice
       Session: 38
     Owner UID: 1000 (tkloczko)
       Boot ID: 9ff40153c60f434f8248a9354970fdb7
    Machine ID: ddd9adc076fd4480afcea67383c00b78
      Hostname: barrel
       Storage: /var/lib/systemd/coredump/core.lt-caja.1000.9ff40153c60f434f8248a9354970fdb7.3834527.1567897009000000000000.lz4
       Message: Process 3834527 (lt-caja) of user 1000 dumped core.
                
                Stack trace of thread 3834527:
                #0  0x00007f6e97f61845 _g_log_abort (libglib-2.0.so.0)
                #1  0x00007f6e97f619e9 g_log_default_handler (libglib-2.0.so.0)
                #2  0x00007f6e97f6214b g_logv (libglib-2.0.so.0)
                #3  0x00007f6e97f62333 g_log (libglib-2.0.so.0)
                #4  0x00007f6e9810ccc5 g_settings_set_property (libgio-2.0.so.0)
                #5  0x00007f6e9805d6e1 g_object_new_internal (libgobject-2.0.so.0)
                #6  0x00007f6e9805df20 g_object_new_valist (libgobject-2.0.so.0)
                #7  0x00007f6e9805e8cd g_object_new (libgobject-2.0.so.0)
                #8  0x000055c4111bcf56 n/a (/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src/.libs/lt-caja)

<font color="#75507B"><b>GNU gdb (GDB) Fedora 8.3.50.20190824-26.fc32</b></font>
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later &lt;http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type &quot;show copying&quot; and &quot;show warranty&quot; for details.
This GDB was configured as &quot;x86_64-redhat-linux-gnu&quot;.
Type &quot;show configuration&quot; for configuration details.
For bug reporting instructions, please see:
&lt;http://www.gnu.org/software/gdb/bugs/&gt;.
Find the GDB manual and other documentation resources online at:
    &lt;http://www.gnu.org/software/gdb/documentation/&gt;.

For help, type &quot;help&quot;.
Type &quot;apropos word&quot; to search for commands related to &quot;word&quot;...
Reading symbols from <font color="#4E9A06">/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src/.libs/lt-caja</font>...
[New LWP 3834527]
[New LWP 3834643]
[New LWP 3834648]
[New LWP 3834639]
[New LWP 3834650]
[New LWP 3834633]
[New LWP 3834644]
[New LWP 3834634]
[New LWP 3834635]
[New LWP 3834641]
[New LWP 3834646]
[New LWP 3834636]
[New LWP 3834638]
[New LWP 3834637]
[New LWP 3834640]
[New LWP 3834645]
[New LWP 3834647]
[New LWP 3834642]
[New LWP 3834649]
[Thread debugging using libthread_db enabled]
Using host libthread_db library &quot;/lib64/libthread_db.so.1&quot;.
btCore was generated by `/home/tkloczko/rpmbuild/BUILD/caja-1.23.2/src/.libs/lt-caja --check --g-fatal-w&apos;.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  <font color="#3465A4">0x00007f6e97f61845</font> in <font color="#C4A000">_g_log_abort</font> () from /lib64/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f6e96da5f40 (LWP 3834527))]
/lib64/../share/gcc-9/python/libstdcxx/v6/xmethods.py:731: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  refcounts = [&apos;_M_refcount&apos;][&apos;_M_pi&apos;]
Missing separate debuginfos, use: dnf debuginfo-install at-spi2-atk-2.33.92-2.fc32.x86_64 at-spi2-core-2.33.92-2.fc32.x86_64 atk-2.33.3-3.fc32.x86_64 bzip2-libs-1.0.8-2.fc32.x86_64 cairo-1.16.0-7.fc32.x86_64 cairo-gobject-1.16.0-7.fc32.x86_64 dbus-libs-1.12.16-3.fc31.x86_64 dconf-0.33.2-2.fc32.x86_64 elfutils-libelf-0.177-1.fc32.x86_64 exempi-2.5.1-2.fc32.x86_64 expat-2.2.7-3.fc32.x86_64 fontconfig-2.13.92-3.fc32.x86_64 freetype-2.10.1-2.fc32.x86_64 fribidi-1.0.5-4.fc32.x86_64 gdk-pixbuf2-2.39.2-2.fc32.x86_64 glib2-2.62.0-2.fc32.x86_64 glibc-2.30.9000-4.fc32.x86_64 graphite2-1.3.13-1.fc32.x86_64 gtk3-3.24.11-2.fc32.x86_64 gvfs-client-1.41.91-1.fc31.x86_64 harfbuzz-2.6.1-2.fc32.x86_64 libICE-1.0.10-3.fc32.x86_64 libSM-1.2.3-5.fc32.x86_64 libX11-1.6.8-4.fc32.x86_64 libX11-xcb-1.6.8-4.fc32.x86_64 libXau-1.0.9-3.fc32.x86_64 libXcomposite-0.4.4-18.fc32.x86_64 libXcursor-1.2.0-2.fc32.x86_64 libXdamage-1.1.4-18.fc32.x86_64 libXext-1.3.4-3.fc32.x86_64 libXfixes-5.0.3-11.fc32.x86_64 libXi-1.7.10-3.fc32.x86_64 libXinerama-1.1.4-5.fc32.x86_64 libXrandr-1.5.2-3.fc32.x86_64 libXrender-0.9.10-11.fc32.x86_64 libXxf86vm-1.1.4-13.fc32.x86_64 libblkid-2.34-3.fc32.x86_64 libdatrie-0.2.12-2.fc32.x86_64 libedit-3.1-29.20190324cvs.fc32.x86_64 libepoxy-1.5.3-5.fc32.x86_64 libffi-3.2.1-2.2.fc32.x86_64 libgcc-9.2.1-1.fc32.x86_64 libgcrypt-1.8.4-5.fc32.x86_64 libglvnd-1.1.1-5.fc31.x86_64 libmount-2.34-3.fc32.x86_64 libpng-1.6.37-3.fc32.x86_64 libselinux-2.9-6.fc32.x86_64 libstdc++-9.2.1-1.fc32.x86_64 libthai-0.1.28-4.fc32.x86_64 libuuid-2.34-3.fc32.x86_64 libwayland-client-1.17.0-3.fc32.x86_64 libwayland-egl-1.17.0-3.fc32.x86_64 libxcb-1.13.1-4.fc32.x86_64 libxml2-2.9.9-4.fc32.x86_64 llvm-libs-8.0.0-8.fc31.x86_64 mate-desktop-libs-1.23.2-2.fc32.x86_64 mesa-libGL-19.2.0~rc1-3.fc32.x86_64 mesa-libglapi-19.2.0~rc1-3.fc32.x86_64 pango-1.44.6-2.fc32.x86_64 pixman-0.38.4-2.fc32.x86_64 systemd-libs-243~rc2-2.fc32.x86_64 xz-libs-5.2.4-8.fc32.x86_64 zlib-1.2.11-19.fc32.x86_64
(gdb) bt full
#0  <font color="#3465A4">0x00007f6e97f61845</font> in <font color="#C4A000">_g_log_abort</font> () at <font color="#4E9A06">/lib64/libglib-2.0.so.0</font>
#1  <font color="#3465A4">0x00007f6e97f619e9</font> in <font color="#C4A000">g_log_default_handler</font> () at <font color="#4E9A06">/lib64/libglib-2.0.so.0</font>
#2  <font color="#3465A4">0x00007f6e97f6214b</font> in <font color="#C4A000">g_logv</font> () at <font color="#4E9A06">/lib64/libglib-2.0.so.0</font>
#3  <font color="#3465A4">0x00007f6e97f62333</font> in <font color="#C4A000">g_log</font> () at <font color="#4E9A06">/lib64/libglib-2.0.so.0</font>
#4  <font color="#3465A4">0x00007f6e9810ccc5</font> in <font color="#C4A000">g_settings_set_property</font> () at <font color="#4E9A06">/lib64/libgio-2.0.so.0</font>
#5  <font color="#3465A4">0x00007f6e9805d6e1</font> in <font color="#C4A000">g_object_new_internal</font> () at <font color="#4E9A06">/lib64/libgobject-2.0.so.0</font>
#6  <font color="#3465A4">0x00007f6e9805df20</font> in <font color="#C4A000">g_object_new_valist</font> () at <font color="#4E9A06">/lib64/libgobject-2.0.so.0</font>
#7  <font color="#3465A4">0x00007f6e9805e8cd</font> in <font color="#C4A000">g_object_new</font> () at <font color="#4E9A06">/lib64/libgobject-2.0.so.0</font>
#8  <font color="#3465A4">0x000055c4111bcf56</font> in <font color="#C4A000">caja_global_preferences_init</font> () at <font color="#4E9A06">caja-global-preferences.c</font>:78
        initialized = 1
#9  <font color="#C4A000">caja_global_preferences_init</font> () at <font color="#4E9A06">caja-global-preferences.c</font>:67
        initialized = 1
#10 <font color="#3465A4">0x000055c4111dd33d</font> in <font color="#C4A000">caja_directory_get_internal</font> (location=location@entry=0x55c4119ba900, create=create@entry=1) at <font color="#4E9A06">caja-directory.c</font>:274
        directory = &lt;optimized out&gt;
#11 <font color="#3465A4">0x000055c4111dd69f</font> in <font color="#C4A000">caja_directory_get_by_uri</font> (uri=uri@entry=0x55c41126e1f8 &quot;file:///etc&quot;) at <font color="#4E9A06">caja-directory.c</font>:339
        directory = &lt;optimized out&gt;
        location = 0x55c4119ba900
#12 <font color="#3465A4">0x000055c4111dd6dd</font> in <font color="#C4A000">caja_self_check_directory</font> () at <font color="#4E9A06">caja-directory.c</font>:1713
        directory = &lt;optimized out&gt;
        file = &lt;optimized out&gt;
#13 <font color="#3465A4">0x000055c4111b0e7f</font> in <font color="#C4A000">caja_run_lib_self_checks</font> () at <font color="#4E9A06">caja-lib-self-check-functions.c</font>:35
#14 <font color="#3465A4">0x000055c4112594c9</font> in <font color="#C4A000">do_perform_self_checks</font> (exit_status=0x7ffccf227a84) at <font color="#4E9A06">caja-application.c</font>:1821
        perform_self_check = 1
        version = 0
        browser_window = 0
        open_in_tabs = 0
        kill_shell = 0
        autostart_id = 0x0
        no_default_window = 0
        remaining = 0x0
        self = 0x55c411891110
        options = 
            {{long_name = 0x55c411288e42 &quot;check&quot;, short_name = 99 &apos;c&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277fc, description = 0x55c411288e48 &quot;Perfo--Type &lt;RET&gt; for more, q to quit, c to continue without paging--
rm a quick set of self-check tests.&quot;, arg_description = 0x0}, {long_name = 0x55c411266e8d &quot;version&quot;, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277f8, description = 0x55c411288e71 &quot;Show the version of the program.&quot;, arg_description = 0x0}, {long_name = 0x55c411269922 &quot;geometry&quot;, short_name = 103 &apos;g&apos;, flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x55c411891018, description = 0x55c411288e92 &quot;Create the initial window with the given geometry.&quot;, arg_description = 0x55c41127e2b6 &quot;GEOMETRY&quot;}, {long_name = 0x55c411288ec5 &quot;no-default-window&quot;, short_name = 110 &apos;n&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277e8, description = 0x55c411288ed7 &quot;Only create windows for explicitly specified URIs.&quot;, arg_description = 0x0}, {long_name = 0x55c411288f0a &quot;no-desktop&quot;, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x55c411891008, description = 0x55c411288f15 &quot;Do not manage the desktop (ignore the preference set in the preferences dialog).&quot;, arg_description = 0x0}, {long_name = 0x55c411288f66 &quot;force-desktop&quot;, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x55c41189100c, description = 0x55c411288f74 &quot;Manage the desktop regardless of set preferences or environment (on new startup only)&quot;, arg_description = 0x0}, {long_name = 0x55c411286518 &quot;tabs&quot;, short_name = 116 &apos;t&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277f0, description = 0x55c411288fca &quot;Open URIs in tabs.&quot;, arg_description = 0x0}, {long_name = 0x55c41128686b &quot;browser&quot;, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277f4, description = 0x55c411288fdd &quot;Open a browser window.&quot;, arg_description = 0x0}, {long_name = 0x55c411264358 &quot;quit&quot;, short_name = 113 &apos;q&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277ec, description = 0x55c411288ff4 &quot;Quit Caja.&quot;, arg_description = 0x0}, {long_name = 0x55c41127487b &quot;&quot;, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_STRING_ARRAY, arg_data = 0x7ffccf227810, description = 0x0, arg_description = 0x55c411288fff &quot;[URI...]&quot;}, {long_name = 0x0, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        context = 0x55c411896ca0
        error = 0x0
        argc = 1
        argv = 0x55c411889ac0
        files = &lt;optimized out&gt;
        idx = &lt;optimized out&gt;
        len = &lt;optimized out&gt;
#15 <font color="#C4A000">caja_application_local_command_line</font> (application=0x55c411891110, arguments=&lt;optimized out&gt;, exit_status=0x7ffccf227a84) at <font color="#4E9A06">caja-application.c</font>:1937
        perform_self_check = 1
        version = 0
        browser_window = 0
        open_in_tabs = 0
        kill_shell = 0
        autostart_id = 0x0
        no_default_window = 0
        remaining = 0x0
        self = 0x55c411891110
        options = 
            {{long_name = 0x55c411288e42 &quot;check&quot;, short_name = 99 &apos;c&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277fc, description = 0x55c411288e48 &quot;Perfo--Type &lt;RET&gt; for more, q to quit, c to continue without paging--
rm a quick set of self-check tests.&quot;, arg_description = 0x0}, {long_name = 0x55c411266e8d &quot;version&quot;, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277f8, description = 0x55c411288e71 &quot;Show the version of the program.&quot;, arg_description = 0x0}, {long_name = 0x55c411269922 &quot;geometry&quot;, short_name = 103 &apos;g&apos;, flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x55c411891018, description = 0x55c411288e92 &quot;Create the initial window with the given geometry.&quot;, arg_description = 0x55c41127e2b6 &quot;GEOMETRY&quot;}, {long_name = 0x55c411288ec5 &quot;no-default-window&quot;, short_name = 110 &apos;n&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277e8, description = 0x55c411288ed7 &quot;Only create windows for explicitly specified URIs.&quot;, arg_description = 0x0}, {long_name = 0x55c411288f0a &quot;no-desktop&quot;, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x55c411891008, description = 0x55c411288f15 &quot;Do not manage the desktop (ignore the preference set in the preferences dialog).&quot;, arg_description = 0x0}, {long_name = 0x55c411288f66 &quot;force-desktop&quot;, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x55c41189100c, description = 0x55c411288f74 &quot;Manage the desktop regardless of set preferences or environment (on new startup only)&quot;, arg_description = 0x0}, {long_name = 0x55c411286518 &quot;tabs&quot;, short_name = 116 &apos;t&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277f0, description = 0x55c411288fca &quot;Open URIs in tabs.&quot;, arg_description = 0x0}, {long_name = 0x55c41128686b &quot;browser&quot;, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277f4, description = 0x55c411288fdd &quot;Open a browser window.&quot;, arg_description = 0x0}, {long_name = 0x55c411264358 &quot;quit&quot;, short_name = 113 &apos;q&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7ffccf2277ec, description = 0x55c411288ff4 &quot;Quit Caja.&quot;, arg_description = 0x0}, {long_name = 0x55c41127487b &quot;&quot;, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_STRING_ARRAY, arg_data = 0x7ffccf227810, description = 0x0, arg_description = 0x55c411288fff &quot;[URI...]&quot;}, {long_name = 0x0, short_name = 0 &apos;\000&apos;, flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        context = 0x55c411896ca0
        error = 0x0
        argc = 1
        argv = 0x55c411889ac0
        files = &lt;optimized out&gt;
        idx = &lt;optimized out&gt;
        len = &lt;optimized out&gt;
#16 <font color="#3465A4">0x00007f6e9811ee82</font> in <font color="#C4A000">g_application_run</font> () at <font color="#4E9A06">/lib64/libgio-2.0.so.0</font>
#17 <font color="#3465A4">0x000055c41116e34d</font> in <font color="#C4A000">main</font> (argc=3, argv=0x7ffccf227c88) at <font color="#4E9A06">caja-main.c</font>:271
        retval = &lt;optimized out&gt;
        application = 0x55c411891110
(gdb) 
</pre>

**Comment by raveit65** [comment]
No idea what you did here. Please use this repo for f32.
All packages are built.
https://copr.fedorainfracloud.org/coprs/raveit65/MATE-1.23.x/

**Comment by kloczek** [comment]
If you will look closer on caja.spec fused to build package on corp that spec does not have at all %check section or is not run `make check`.
My package as well builds when I have disabled %check.
This faiult is on running included in caja test suite.

**Comment by raveit65** [comment]
Ok, if you need that......

**Comment by kloczek** [comment]
Someone imolemented that test suite and it was some reason. Inn't it?
That crash mean that something is wrong with caja or test suite.

**Comment by kloczek** [comment]
1.25.2 seems is ok.
Closing.
