### ISSUE TITLE
icon view adds dash character to entry name on line break

### ISSUE THREAD

**Issue by muesli4** [mate-desktop/caja#1314]
#### Expected behaviour

I would expect that the editor doesn't add misleading symbols to the name string of an entry. This option should be opt-in or at least provide an opt-out.

#### Actual behaviour

Longer entries that lead to line breaks lead to adding a dash character. The behavior cannot be disabled.

#### Steps to reproduce the behaviour

Switch to icon view (or go to desktop) and create a file with a very long filename. The filename is separated by a new line and a dash.

#### MATE general version

1.22.2

#### Package version

caja-1.22.2-1

#### Linux Distribution

Archlinux

#### Link to downstream report of your Distribution

None available.

**Comment by sc0w** [comment]
It was already reported in https://github.com/mate-desktop/caja/issues/1284

and it was fixed with https://github.com/mate-desktop/caja/commit/b50e36b639aca25c8bf3d21dc1547fc6f7a6f442
