### ISSUE TITLE
Caja cannot be built against mate-desktop 1.23.3 ; error in fm-properties-windows.c

### ISSUE THREAD

**Issue by FredBezies** [mate-desktop/caja#1343]
#### Expected behaviour

Caja building

#### Actual behaviour

Caja is broken while processing fm-properties-windows.c. There is a missing reference to mate_desktop_thumbnails_scale_down_pixbuf

Seems to be related to this commit: https://github.com/mate-desktop/mate-desktop/commit/2bce55bfb71a354402499b497f42d0fe6851350b

#### Steps to reproduce the behaviour

Try to build caja with Mate-Desktop 1.23.3.

#### MATE general version

1.23.3

#### Package version

1.23.2

#### Linux Distribution

Archlinux

#### Link to downstream report of your Distribution

Not done.

Here is a screenshot of the bug:

![VirtualBox_Arch Mate 1 23_19_01_2020_17_31_51](https://user-images.githubusercontent.com/8571419/72684618-6fbe8c00-3ae2-11ea-90c3-8200ba0d7398.png)

**Comment by rbuj** [comment]
All references to `gdk_pixbuf_scale_simple` were removed from caja in https://github.com/mate-desktop/caja/commit/13d04135dda574bbaa51f56df1783778f423e0f2

**Comment by FredBezies** [comment]
What about providing a new development version?

**Comment by rbuj** [comment]
Try updating your local copy of caja, I think you should have no problem after pulling latest commit.

**Comment by FredBezies** [comment]
I try to grab the patch and apply it. It could be simpler to release a new development version of Caja anyway.

**Comment by raveit65** [comment]
> What about providing a new development version?

Coming soon.

**Comment by raveit65** [comment]
Done, caja-1.23.3 is released.
https://pub.mate-desktop.org/releases/1.23/caja-1.23.3.tar.xz

**Comment by FredBezies** [comment]
Well, it was quick. Thanks!
