### ISSUE TITLE
Interference between caja file renaming and Mouse Preferences/Locate Pointer 

### ISSUE THREAD

**Issue by rebelxt** [mate-desktop/caja#1348]
When the option "Locate Pointer" of "Mouse Preference" is selected it interferes with the renaming of files within caja. While editing the file name, pressing ctrl (useful for copy or paste) closes the rename editing window. It is therefore no longer possible to copy or paste text to rename of file.

I realize the problem was reported in issue #770 and closed as fixed. However, in Linux Mint Mate 18.3 (Caja 1.18.5) and Linux Mint Mate 19.3 (Caja 1.22,2) the problem still exists.

**Comment by raveit65** [comment]
You need to ask linuxmint to add our fix to their caja builds.
Sorry, we can't help help you here.
