### ISSUE TITLE
 Preference is too big

### ISSUE THREAD

**Issue by xingjiapeng** [mate-desktop/caja#1381]
#### Expected behaviour
More compact preference dialog(or more tabs and less options in one tab).

#### Actual behaviour
The preference dialog is so big that I can't get the "OK" button.
![2020-04-29 15-57-32 创建的截图](https://user-images.githubusercontent.com/47733616/80573411-7e4a0700-8a32-11ea-878b-1bf4d0e816d4.png)

#### Steps to reproduce the behaviour

1. Change the environment language to Chinese 
2. Open Caja
3. Open 编辑 -> 首选项

#### MATE general version
1.24.0

#### Package version
1.24.0

#### Linux Distribution
Ubuntu MATE 20.04 LTS

Thanks!

**Comment by tamplan** [comment]
Hi,
What is your screen resolution please?

**Comment by xingjiapeng** [comment]
thanks.
switch to another distro, not happen again, close.
