### ISSUE TITLE
Custom Caja icon in Windows List applet remains after first visit of a folder with Custom Icon selected

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/caja#1394]
#### Expected behaviour
Caja icon in Windows List follows style of icon for current folder.

#### Actual behaviour
Caja icon in Windows List is default, but after visiting the folder with Custom Icon it remains custom forever.

#### Steps to reproduce the behaviour
1. Open Caja
2. Select some folder, do right mouse click on it, on Basic tab Select Custom Icon for it
3. Visit the folder with custom icon set
4. Using same Caja window visit Home folder with default icon

See screencast:

![caja-icon](https://user-images.githubusercontent.com/309456/82724557-920a2580-9cdf-11ea-9bec-a1040ccc98e2.gif)

#### MATE general version
1.24.0

#### Package version
1.24.0-1

#### Linux Distribution
Ubuntu MATE 20.04 LTS

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/caja/+bug/1880281

**Comment by raveit65** [comment]
Was it ever intended for folders?

**Comment by N0rbert** [comment]
Just tested this behaviour on Windows 10, here it works as it should.
Also by reporting this I'm helping our Ubuntu MATE user [at community](https://ubuntu-mate.community/t/caja-logo-in-the-list-of-windows/21898?u=norbert_x), as I am Ubuntu MATE QA team member :)

**Comment by raveit65** [comment]
@N0rbert @rbuj 
I am not sure if this is really an issue, btw. i don't understand the problem.
I can always restore the icon to default with the `revert` button.
![Screenshot at 2020-06-14 14-31-25](https://user-images.githubusercontent.com/961604/84593417-8b894c80-ae4c-11ea-9417-2695fadf6ca7.png)

**Comment by raveit65** [comment]
Got it, issue is the wrong icon in panel window-list applet.
