### ISSUE TITLE
inconsistently names duplicated file when filename contains dots

### ISSUE THREAD

**Issue by DamageIncorporated** [mate-desktop/caja#1395]
#### Expected behaviour
A file that gets duplicated in the same folder using the clipboard must me renamed to not overwrite the source file. Caja appends the string (Copy) between filename and extension. 
Example:

example 3. part.txt --> example 3. part (Copy).txt

#### Actual behaviour
When the filename contains one or more dots the string gets inserted right before the first dot

example 3. part.txt --> example 3 (Copy). part.txt

#### Steps to reproduce the behaviour
create a file with a filename that contains a dot-character and some text after it, followed by the usual file-extension (which is also marked by a dot)

#### MATE general version
mate-desktop 1.24.0-2

#### Package version
caja 1.24.0-1

#### Linux Distribution
Ubuntu Mate 20.04

#### Link to downstream report of your Distribution
Sorry, didn't file a report there, as I suspected a general/upstream issue.

**Comment by rbuj** [comment]
The GUI treats everything that follows the first period as the file's extension.

**Comment by DamageIncorporated** [comment]
I thought Caja shouldn't use the last period to place the (Copy) string rather than the first.

But now, when thinking about it, that would split double extensions like ".tar.gz".. So maybe the current behaviour is less harmful :-)
