### ISSUE TITLE
How to disable mounted drive icon on Fedora 32 + Mate?

### ISSUE THREAD

**Issue by ruthan** [mate-desktop/caja#1405]
Hello,
 i have old problem, i cant find settings for it. How to disable mounted drive icon on Fedora 32 + Mate? 
  Its somewhere hidden or missing.

**Comment by selectiveduplicate** [comment]
You can disable them using dconf-editor.

`/org/mate/caja/desktop/volumes-visible`.

**Comment by ruthan** [comment]
Thanks very mauch, but it would make sense add it some gui tool in future.

**Comment by selectiveduplicate** [comment]
> Thanks very mauch, but it would make sense add it some gui tool in future.

dconf-editor is a gui tool. Can you close this issue?

**Comment by ruthan** [comment]
But its not part of mate desktop, or its someone in panels / preferences etc, link on it? Also if im not wrong gconf tools, is very ugly one - zillion of options not understadable for normal user.

**Comment by ruthan** [comment]
I dont agree that is closed.. its user experience sucks.
