### ISSUE TITLE
Cannot unmount volumes from sidebar

### ISSUE THREAD

**Issue by hamishmb** [mate-desktop/caja#1410]
#### Expected behaviour
Clicking on the eject/unmount button should eject/unmount volumes.

#### Actual behaviour
Caja seems to attempt to do this, but also navigates to the drive at the same time and remounts it. This seems to happen even if you're currently browsing the volume in Caja.

#### Steps to reproduce the behaviour
1. Insert a USB drive with a mountable volume.
2. Wait for the volume to be mounted.
3. Open Caja and click the unmount button in the sidebar.
4. Be navigated to the volume at same time as/instead of the volume being unmounted.

#### MATE general version
1.22.2

#### Package version
1.22.2-2+tricia

#### Linux Distribution
Linux Mint 19.3 MATE

#### Link to downstream report of your Distribution
Not needed as distro is Linux Mint?

**Comment by hamishmb** [comment]
Can no longer reproduce - it's just started working. Sorry for the noise.

**Comment by raveit65** [comment]
> Not needed as distro is Linux Mint?

Who said this bullshit?

We' re ignoring reports when you ignore our template!!!!

**Comment by hamishmb** [comment]
Mint says to report it here, unless it's specific to Mint only (https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/where.html).

Either way, I don't think this bug is valid. No need to be rude.
