### ISSUE TITLE
seahorse for MATE

### ISSUE THREAD

**Issue by Weem** [mate-desktop/caja#142]
Is it possible in the future to add support for encryption and decryption from the context menu? I still remember some applet in GNOME 2 was.

**Comment by Jordi3** [comment]
I'm very interested in this feature.
Being Caja a fork of Nautilus should not be too difficult to fork seahorse-nautilus!

**Comment by darkshram** [comment]
Here you have it, @Jordi3, @Weem and @acrobat1.
https://github.com/darkshram/seahorse-caja/
Needs caja 1.18.0.
Enjoy!

**Comment by wandth** [comment]
Cool. Hope it ends up in the mint repos soon.
