### ISSUE TITLE
File Operations dialog incorrectly displays throughput speed when files are queued

### ISSUE THREAD

**Issue by dominix** [mate-desktop/caja#1420]
#### Expected behaviour

display real copy speed in octet/s  since the beginning of the copy of the current file proceeded. 

#### Actual behaviour

display an average speed deducted from time since the beginning of the copy of the first file in the pool, instead of the beginning of copy of the current file been proceeded. 

#### Steps to reproduce the behaviour
copy a file to destination, then add another file to copy to the same destination so the operations is queued, then notice the difference in displayed throughput in the file operations window when the second file is copied.
 
#### MATE general version
1.24.0

#### Package version
caja           1.24.0-1     amd64

#### Linux Distribution
ubuntu 20.04 LTS

**Comment by dominix** [comment]
one solution could be to not reset the speed counter between files when they are queued, so the average will be related to some realistic throughput.
or, if you reset the speed counter, please reset both speed and time counter. I have the feeling that currently only the speed counter is reset.

**Comment by lukefromdc** [comment]
I've noticed this for years

**Comment by jaimeaxel** [comment]
Any progress on this one?
This has been happening from way before the bug report and is still happening in 1.26+.

**Comment by lukefromdc** [comment]
I haven't worked on this myself, being rather task-saturated. If this does NOT happen on either Nemo or on Nautilus though, that would mean one of them found a fix we could port over. If it still happens on all three, it's a pre-fork Nautilus bug nobody ever found a fix for
