### ISSUE TITLE
Caja inconsistent creation of link-type launchers by dragging from browsers 

### ISSUE THREAD

**Issue by Lantizia** [mate-desktop/caja#1433]
Hopefully some pictures are worth a thousand words...

Dragging a URL from Chrome or Firefox to **mate-panel** creates launchers...
![bitmap3](https://user-images.githubusercontent.com/10448369/87962062-8a33eb00-caae-11ea-9fb9-a30e88403ded.png)

Dragging a URL from Chrome or Firefox to **pluma** pastes the text of the URL...
![bitmap2](https://user-images.githubusercontent.com/10448369/87962134-a20b6f00-caae-11ea-8dc0-a90ba24e323b.png)

Dragging a URL from Firefox to **caja** **DOES** create launchers, but from Chrome it **DOES NOT**...
![bitmap](https://user-images.githubusercontent.com/10448369/87962195-b8b1c600-caae-11ea-8137-cfb1203fbd4d.png)

This issue has been around for years on numerous releases.  I mostly **only** use LTS releases of Ubuntu MATE so that'd mean I've seen this on MATE 1.12, 1.20 and more recently 1.24.

I can also confirm that this problem exists if dragging into a normal **caja** window (i.e. not the Desktop)... it just reacts as if you're not dragging anything at all (i.e. no little question mark appears next to your mouse cursor, like it does when dragging from Firefox).

There is a work around, which is to drag them to **mate-panel**, then drag that launcher to **caja**, then finally remove the launcher from **mate-panel**.  Not only is this time consuming and messy... but also the launchers created by **mate-panel** seem to be inconsistent with those created by **caja** (e.g. if using something that works like Firefox).  The launcher made by **mate-panel** seem to lack the 'Link to' in the name, use a different icon and other slightly different properties.

Any thoughts?

This is a really useful feature if you're trying to archive off some unfinished work (and half-read tabs) into a folder to pick up a project later.  Naturally on Linux this means freedesktop ".desktop" launcher files... where as on a Mac you'd have ".webloc" files and on Windows you'd have ".url" files (nothing a little bash script can't handle and pass to xdg-open)... but the same deal ultimately... it'd be nice to restore this functionality to regain some feature parity with other OS's.

**UPDATE**

I have just noticed that this doesn't even behave consistently with Firefox either.  Depending on the website (or perhaps contents of the URL or title of the page maybe?) Caja will sometimes instead try to copy the web page instead!  This has been witnessed when dragging from Konqueror too.  However in both cases, dragging to a **mate-panel** is still fine.

Give this URL a go in Firefox to see what I mean...   [https://www.linuxfoundation.org/](https://www.linuxfoundation.org/)

**Comment by lukefromdc** [comment]
Not having Chrome installed (or trusting Google) I cannot test this. Hopefully someone on the team with Chrome already installed can have a look at this

**Comment by Lantizia** [comment]
Does it help to say that if you also try this with Opera or Chromium, you get **precisely** the same results as Chrome too?

Naturally they're all based on Chromium... so I thought I'd install Konqueror.  Slightly different issue with that... dragging to a panel works just fine as usual... but dragging to the desktop or an open Caja window causes it to try and copy the webpage itself - very odd.

**Comment by lukefromdc** [comment]
I have none of those either, but the odds of someone on the team being able to duplicate this just went up with three browsers affected instead of just one. This looks like Firefox does something unique that works.

**Comment by Lantizia** [comment]
Can't be that unique if Chrome / Opera / Chromium all work when dragged to **mate-panel**... I would have thought it would be **caja** doing something different to **mate-panel** as much as anything else?

**Comment by lukefromdc** [comment]
I do not myself know how that works, will leave this for someone with one of the affected browsers to work on

**Comment by raveit65** [comment]
Confirmed, creating a link from chrome to caja desktop or another caja window doesn't work.
But it does work with nemo file-manager.
When using firefox i see a question mark during drag&drop to caja.
This is complete missing with chrome.

**Comment by Lantizia** [comment]
Updated the issue as this appears to affect multiple browsers (including Firefox) and also seems to have different results dependent on what URL you actually drag out... oddly.  See the end of the original post.

**Comment by rbuj** [comment]
@raveit65 did you press ctrl ?

https://github.com/mate-desktop/caja/blob/969fe79d5b420b89548da7a81fb46a42044b8665/libcaja-private/caja-dnd.c#L349-L366

**Comment by rbuj** [comment]
btw dnd on desktop: 
https://github.com/mate-desktop/caja/blob/969fe79d5b420b89548da7a81fb46a42044b8665/src/file-manager/fm-directory-view.c#L2009

**Comment by raveit65** [comment]
No, i didn't pressed crtl when using  chrome. And here pressing crtl doesn't help (PR not tested yet).

**Comment by raveit65** [comment]
Confirmed, pressing crtl change the drag&drop icon when using firefox.
But with firefox the default works correct without pressing crtl.

**Comment by raveit65** [comment]
@Lantizia 
PR fixes the issue with chrome browser for me. You should test it.

**Comment by raveit65** [comment]
PR works fine with chromium too.
@lukefromdc 
There is a ungoogle version of chrome https://github.com/Eloston/ungoogled-chromium
This Version works very strict in result you can't use the google webstore for extensions for example ;)
RPM-Fusion ships this version of chromium for fedora.

**Comment by Lantizia** [comment]
I just recompiled the Caja 1.20.2 package that Ubuntu 18.04 comes with (haven't quite made the move to 20.04 yet) adding your commit as a patch in debian/patches...

wget https://github.com/mate-desktop/caja/commit/891cdf78f0da741f3fa8c07d9b99a5cd95fd7c16.patch -O debian/patches/2000_urldndfix.patch

Work great so far, but I've only been trying it for 5 minutes... it's odd that my previous comments showed some websites **did** and some **did not** work when using Firefox (resulting in a copying task instead)... any ideas what the culprit was for that?  You'd think a URL would be a URL, regardless of where it points to.

Talking of inconsistencies... Is there any reason why **mate-panel** and **caja** generate these launchers so wildly differently... and is there anyway we can have them call the same routine?

e.g. if you drag to **mate-panel** (where you can, if you like, **then** drag it to **caja** afterwards... which was what I was doing to workaround the original bug) you get a launcher with these details...

**Launcher name (becomes filename if dragged to **caja**):** The Linux Foundation – Supporting Open Source Ecosystems
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Name=The Linux Foundation – Supporting Open Source Ecosystems
Comment=Open URL: https://www.linuxfoundation.org/
Icon=applications-internet
Name[en_GB]=The Linux Foundation – Supporting Open Source Ecosystems
Comment[en_GB]=Open URL: https://www.linuxfoundation.org/
Icon[en_GB]=applications-internet
URL=https://www.linuxfoundation.org/
Type=Link
```

And if you drag directly to **caja** you get...

**Launcher filename:** Link to The Linux Foundation – Supporting Open Source Ecosystems
```
[Desktop Entry]
Encoding=UTF-8
Name=Link to The Linux Foundation – Supporting Open Source Ecosystems
Type=Link
URL=https://www.linuxfoundation.org/
Icon=mate-fs-bookmark
```

What gives it away the most is how the name/filename of the launcher is inconsistent (i.e. 'Link to' is added) and also the one created by caja refers to an icon my system doesn't even have called **mate-fs-bookmark**?  Is this a hang over from GNOME?

**Comment by raveit65** [comment]
> I just recompiled the Caja 1.20.2 package that Ubuntu 18.04 comes with (haven't quite made the move to 20.04 yet) adding your commit as a patch in debian/patches...
> 
> wget https://github.com/mate-desktop/caja/commit/891cdf78f0da741f3fa8c07d9b99a5cd95fd7c16.patch -O debian/patches/2000_urldndfix.patch
> 
> Works great so far, but I've only been trying it for 5 minutes... it's odd that my previous comments showed some websites **did** and some **did not** work when using Firefox (resulting in a copying task instead)... any ideas what the culprit was for that? You'd think a URL would be a URL, regardless of where it points to.

No idea, is it worse that it works now ?
> 
> Talking of inconsistencies... Is there any reason why **mate-panel** and **caja** generate these launchers so wildly differently... and is there anyway we can have them call the same routine?
> 
Different projects, different developers and no world dictator in the last 20 years. What do you expect?
Maybe Trump like to eliminate this humanity......

> e.g. if you drag to **mate-panel** (where you can, if you like, **then** drag it to **caja** afterwards... which was what I was doing to workaround the original bug) you get a launcher with these details...
> 
> **Launcher name (becomes filename if dragged to **caja**):** The Linux Foundation – Supporting Open Source Ecosystems
> 
> ```
> #!/usr/bin/env xdg-open
> [Desktop Entry]
> Version=1.0
> Name=The Linux Foundation – Supporting Open Source Ecosystems
> Comment=Open URL: https://www.linuxfoundation.org/
> Icon=applications-internet
> Name[en_GB]=The Linux Foundation – Supporting Open Source Ecosystems
> Comment[en_GB]=Open URL: https://www.linuxfoundation.org/
> Icon[en_GB]=applications-internet
> URL=https://www.linuxfoundation.org/
> Type=Link
> ```
> 
> And if you drag directly to **caja** you get...
> 
> **Launcher filename:** Link to The Linux Foundation – Supporting Open Source Ecosystems
> 
> ```
> [Desktop Entry]
> Encoding=UTF-8
> Name=Link to The Linux Foundation – Supporting Open Source Ecosystems
> Type=Link
> URL=https://www.linuxfoundation.org/
> Icon=mate-fs-bookmark
> ```
> 
> What gives it away the most is how the name/filename of the launcher is inconsistent (i.e. 'Link to' is added) and also the one created by caja refers to an icon my system doesn't even have called **mate-fs-bookmark**? Is this a hang over from GNOME?

Renamed to avoid file conflicts. gnome-fs-bookmark --> mate-fs-bookmark

**Comment by Lantizia** [comment]
> > Talking of inconsistencies... Is there any reason why **mate-panel** and **caja** generate these launchers so wildly differently... and is there anyway we can have them call the same routine?
> 
> Different projects, different developers and no world dictator in the last 20 years. What do you expect?
> Maybe Trump like to eliminate this humanity......

I've no idea how you've managed to have such a peculiar reaction to this query!?  I guess I was just wondering if there was some common library that MATE components (e.g. caja, panel, etc...) could (or do) utilise for the generation of freedesktop.org conforming launchers.  If that's not the case then fair enough.  It was also more directed at @rbuj who has kindly created this pull request.

**Comment by raveit65** [comment]
This was a joke. I am out now. Help yourself....

**Comment by Lantizia** [comment]
> ```
> 
> URL=https://www.linuxfoundation.org/
> Icon=mate-fs-bookmark
> ```
> 
> 
> What gives it away the most is how the name/filename of the launcher is inconsistent (i.e. 'Link to' is added) and also the one created by caja refers to an icon my system

**Comment by Lantizia** [comment]
Haven't spotted any issues after further testing (including the extra 3 commits for how the launchers are written) so marking this as closed (which presumes these pull requests make it into caja admittedly).

**Comment by Lantizia** [comment]
OK so I've spotted some odd issues, but not sure if it's related to the above changes or not...

Here are three different contents of the launcher with three strangely different reactions...

```
[Desktop Entry]
Version=1.0
Type=Link
Name=Some Link
URL=https://bacon.tv/s
Icon=applications-internet
```

![image](https://user-images.githubusercontent.com/10448369/88858162-7fd0ca00-d1ef-11ea-88bc-9878b559ef05.png)

```
[Desktop Entry]
Version=1.0
Type=Link
Name=Some Link
URL=https://bacon.domain.tv/s
Icon=applications-internet
```

![image](https://user-images.githubusercontent.com/10448369/88858238-9bd46b80-d1ef-11ea-950f-f2473ae55e92.png)

```
[Desktop Entry]
Version=1.0
Type=Link
Name=Some Link
URL=https://sub.tv/s
Icon=applications-internet
```

![image](https://user-images.githubusercontent.com/10448369/88858343-c292a200-d1ef-11ea-9b18-efca0944c986.png)

These reactions are consistent each time for each of the links I was testing above.  The actual URL's are made up as I was trying to determine which characters/combinations make it do different things... 

It's really odd.  Of course if you put something like http://google.com in then it opens just fine... which is why I've not caught this until now.

**Comment by Lantizia** [comment]
I did write another issue here as a comment... but I can't possibly think how this would be related to the work already done above - must be an existing but different bug relating to how these launchers (now fixed in their **creation**) now don't always actually open!...

See my new issue #1438

**Comment by rbuj** [comment]
> I did write another issue here as a comment... 

@Lantizia do not create cross-references to other issues.
