### ISSUE TITLE
New window opens in same folder as original window

### ISSUE THREAD

**Issue by Ferryfolk** [mate-desktop/caja#1434]
#### Expected behaviour
With one tab or window open opening another tab or window should open in home folder.

#### Actual behaviour
Opening a new window or tab opens same folder as original window or tab. User unlikely to want to do this.

#### Steps to reproduce the behaviour
As described above.

#### MATE general version
1.24.0

#### Package version
1.24.0-linuxmint1

#### Linux Distribution
Linux Mint Mate 20.

**Comment by rbuj** [comment]
I disagree you about the content of new tabs or windows and I think the current behavior is the right one. Plus, you can quickly switch from shortcuts.
