### ISSUE TITLE
Caja inconsistently **opens** URL launchers!

### ISSUE THREAD

**Issue by Lantizia** [mate-desktop/caja#1438]
OK so issues with Caja not creating launchers properly when URLs are dragged and dropped to it - have been fixed with #1433 

This issue is about how odd opening these launchers (whether generated by Caja or not, it doesn't matter) seems to work differently dependant on the URL...

```
[Desktop Entry]
Version=1.0
Type=Link
Name=Some Link
URL=https://bacon.tv/s
Icon=applications-internet
```

![image](https://user-images.githubusercontent.com/10448369/88858162-7fd0ca00-d1ef-11ea-88bc-9878b559ef05.png)

```
[Desktop Entry]
Version=1.0
Type=Link
Name=Some Link
URL=https://bacon.domain.tv/s
Icon=applications-internet
```

![image](https://user-images.githubusercontent.com/10448369/88858238-9bd46b80-d1ef-11ea-950f-f2473ae55e92.png)

```
[Desktop Entry]
Version=1.0
Type=Link
Name=Some Link
URL=https://sub.tv/s
Icon=applications-internet
```

![image](https://user-images.githubusercontent.com/10448369/88858343-c292a200-d1ef-11ea-9b18-efca0944c986.png)

These odd "reactions" are consistent each time for each of the links I was testing above.  The actual URL's are made up as I was trying to determine which characters/combinations make it do different things... 

It's really odd.  Of course if you put something more "every day" like https://google.com in... then it opens just fine... which is why I've not caught this until now.

Note: dragging any of these launchers to a **mate-panel** and then clicking them... they open fine.  So this must be a **caja** thing again.

**Comment by rbuj** [comment]
Some remote links do not open with the web browser, where is the problem?

tes.sh: double-click on kernel.txt.desktop and qr-card.txt.desktop
```
cat <<EOF > kernel.txt.desktop
[Desktop Entry]
Encoding=UTF-8
Name=Link to kernel.txt
Type=Link
URL=https://www.kernel.org/doc/Documentation/sysctl/kernel.txt
Icon=mate-fs-bookmark
EOF
cat <<EOF > qr-card.txt.desktop
[Desktop Entry]
Encoding=UTF-8
Name=Link to QR Card
Type=Link
URL=https://documentation.libreoffice.org/assets/Uploads/Documentation/en/QR5/Quick-reference-guide-Libreoffice5.x-En.odt
Icon=mate-fs-bookmark
EOF
```

**Comment by Lantizia** [comment]
OK so when I test using the two launchers you've provided there (just running that code block in a terminal to generate them) ... I see **pluma** seems to directly access the URL with the text file and **libreoffice** seems to directly access the URL with the odt file.

Surely this means **caja** is either...
1. Doing a quick HTTP request **itself** (prior to opening anything) and downloading (even if partially) some of the URL's destination... to check the mime type of the content?  ... or...
2. Just looks at the file extension at the end of the URL?  This would be equally terrible for URL's that end in things like .php / .cgi / .dll where you *may* have registered an application to open them - but they're actually just outputting web pages!?

I would expect that **caja** should simply deal with http:// and https:// URL's with the default handler for those protocols on the desktop - namely this is usually a web browser.

I know **mate-panel** doesn't have this issue with the examples you have provided - they open in a web browser no problem.  Surely the behaviour between **mate-panel** and **caja**, in terms of what occurs when launchers are opened - should be consistent?

**Comment by Lantizia** [comment]
Ultimately it doesn't matter if Caja does the aforementioned   **1.**  or  **2.**  to "guess" what to do with the link.

Both ways of guessing would be equally as crazy.

HTTP is still the **hypertext transfer protocol**, so without additional information (which caja can't know and shouldn't be obtaining - it is a file manager after all)... the assumption is it's for **hypertext** :).  So those links should open in whatever program is the default for **http://** and **https://**, period!

Sure, if the web server returns a different mime-type... and that web browser knows what to do in those circumstances (like open another application)... then that is fair enough.  

But it shouldn't be the job of caja really.  Also (again) **mate-panel** doesn't have this issue and just opens whatever handles **http://** and **https://** for these launchers.

Also it's not wise to directly give URLs to whatever application is associated with that **TOTALLY GUESSED** file type... as caja is assuming that all applications will understand http:// or https:// (or maybe odd things like gvfs://)... when that is a pretty wild assumption.

**Comment by rbuj** [comment]
Have you considered the [PUT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT) or [POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST) methods in your hypothesis?

**Comment by Lantizia** [comment]
I'm not sure how any of that is relevant?  Caja should not be making http requests of any kind.

**Comment by rbuj** [comment]
I don't know, but his can be useful for WebDAV users.

**Comment by Lantizia** [comment]
WebDAV users would use the 'Connect to Server' option in Caja to use a WebDAV server.  In what way would a WebDAV user make use of a freedesktop-spec .desktop launcher?  Additionally in what way can Caja use them **now**, if any? 

Plus, the behaviour of opening a launcher through MATE Caja or MATE Panel, should (in my opinion) be consistent... and MATE Panel simply looks at the application which handles http / https and passes that application the URL, plain and simple!

**Comment by rbuj** [comment]
Yes you are right, in fact it does not matter whether or not you can save the modified file, as well as it is not a software error to open a remote file type via http with the application associated with the type and or content of the file.

**Comment by Lantizia** [comment]
But as I've already stated you can't possibly know the type unless Caja is making a HTTP request and a proper mime type is received in the headers... and even if one is received... Caja can't possibly know if the application associated with that type can even handle http or https URL's.

Flip side... if Caja is just guessing based on how the URL ends, then this is equally dumb as many things (especially web pages) are rendered by CGI scripts that leave their file extension (e.g. .cgi, .php, .dll, etc...) at the end of the URL... so this if those extensions are associated... you're going to have a bad time awful.

I am absolutely astounded that you have closed this issue.

What is the point in Caja doing **anything** with URL launchers if it can't properly save them (e.g. bad drag and drop handling **and** bad handling of long titles) or open them!

**Comment by rbuj** [comment]
web pages are not rendered by scripts... it's dynamic content.

**Comment by Lantizia** [comment]
The content of web pages are often created by server-side scripts... what on earth are you on about?

**Comment by rbuj** [comment]
This is transparent to the client, the client only sees html.

**Comment by Lantizia** [comment]
And?  That's got nothing to do with what I am talking about.

I'm talking about two **completely separate** circumstances... in **one** circumstance I am assuming Caja **guesses** the application to open **based on the ending** of the URL...

https://signin.ebay.co.uk/ws/eBayISAPI.dll

Is that meant to maybe open Wine's rundll32 ?!  Seriously!  It just serves a web page... it'd be stupid if that URL was passed to Wine if that was associated with files ending dll.

https://www.php.net/docs.php

Is that meant to open whatever PHP development IDE or Text Editor the user has associated with PHP files?

However in the **OTHER CIRCUMSTANCE** if Caja is making a HTTP request **itself** and reading **Content-Type:** in the HTTP headers this...

https://documentation.libreoffice.org/assets/Uploads/Documentation/en/QR5/Quick-reference-guide-Libreoffice5.x-En.odt
Content-Type: application/vnd.oasis.opendocument.text

**Could** open in LibreOffice sure, as that application understands HTTP locations.  But if they're **not** using that and using say **AbiWord**, that that **doesn't** understand HTTP locations.

So is Caja maintaining a list of what applications **can** and **can't** understand HTTP URL's so that it knows which it should and shouldn't pass directly to an application?!

It's seriously messed up...

And again again again... completely contradicts how MATE Panel behaves when opening the same links - it just calls whichever application handles HTTP.

I swear at this point you are purposefully ignoring half the logic I am writing in to these posts, this just simply doesn't work... even the original post at the top shows the crazy errors you get!

**Comment by rbuj** [comment]
I could not reproduce your issues with the links below which have been opened with the default web browser:
```
$ cat Sign\ in\ or\ Register\ \|\ eBay.desktop 
[Desktop Entry]
Encoding=UTF-8
Name=Link to Sign in or Register | eBay
Type=Link
URL=https://signin.ebay.co.uk/ws/eBayISAPI.dll
Icon=mate-fs-bookmark
$ cat PHP\:\ Documentation.desktop 
[Desktop Entry]
Encoding=UTF-8
Name=Link to PHP: Documentation
Type=Link
URL=https://www.php.net/docs.php
Icon=mate-fs-bookmark
```

**Comment by Lantizia** [comment]
Right so that would imply Caja **does** look at Content-Type: in the HTTP header.

Which I've also said is bad... won't repeat myself - see above.

**Comment by rbuj** [comment]
From my point of view, you are formulating a series of unfounded hypotheses in order to create a non-existent error.

**Comment by Lantizia** [comment]
Not to mention web pages that change dependant on region, or web pages that no longer exist.

This whole bug report started because I was on a VPN to the USA and wanted to drag this URL in to Caja...

https://acorn.tv/stationx/

It worked... while the VPN was up.  But when it wasn't (I'm in the UK) it redirects to https://uk.acorn.tv/stationx/ and Caja doesn't know how to handle re-directions it would seem...

![image](https://user-images.githubusercontent.com/10448369/91660140-55af4800-eacc-11ea-8923-3d739775b271.png)

So instead of it opening a web browser where I can see the redirection occurring, and then see a proper error web page... I get that cryptic message instead!

You get the same problem with links to things that no longer exist...

https://github.com/myniceproject

So if that page **had** existed, and you wanted to visit that later on... to find it no longer exists... you wouldn't even get a web page telling you it didn't exist any more... some 404 error pages even guide you to where you might be able to find the content.

**Comment by Lantizia** [comment]
> From my point of view, you are formulating a series of unfounded hypotheses in order to create a non-existent error.

And from my point of view you are purposefully ignoring a absolutely boat load of logic I have already provided in order to not acknowledge a valid bug.

**Comment by Lantizia** [comment]
Caja is a file manager, it has no place opening HTTP links **at all**.

It should just do what **MATE Panel** does... and simply call whatever application is associated with the corresponding protocol.

**Comment by rbuj** [comment]
You're wrong, there is no issue fetching files from URIs with http(s) schema:
https://github.com/mate-desktop/caja/blob/b340338baf81a74d20f09a00fb715a7d2c0add5e/libcaja-private/caja-file.c#L752

**Comment by Lantizia** [comment]
You have an odd ability of saying something that is completely unrelated, yet seemingly closely related, to the situation - in order to win some kind of odd point that doesn't exist?

What exactly has that line of code, got to do with anything I've raised so far?

**Comment by rbuj** [comment]
I leave this conversation.

**Comment by Lantizia** [comment]
Well remembering of course that resources on the web shift and change their URL as time goes on, and that the only way to know what may have happening is to actually see it open it in a web browser anyway and look at what you get instead...

You **leave the conversation** with the following **provable** circumstances still **completely broken**... 

**(and these are just the ones discovered so far)**

### The web page has since gone 404 not found...
```
[Desktop Entry]
Version=1.0
Type=Link
Name=404 Not Found
URL=https://en.wikipedia.org/wiki/Does_Not_Exist
Icon=applications-internet
```
![image](https://user-images.githubusercontent.com/10448369/91697391-f2272800-eb68-11ea-8700-21a89b458bdc.png)

### Same thing oddly occurs if it is 404 on a site with a broken certificate, is it bypassing this check?
```
[Desktop Entry]
Version=1.0
Type=Link
Name=404 Not Found on an insecure site
URL=https://bacon.tv/s
Icon=applications-internet
```
![image](https://user-images.githubusercontent.com/10448369/91697534-34e90000-eb69-11ea-877d-2f24bc65b590.png)

### How about servers that are slow (or never) to respond?
```
[Desktop Entry]
Version=1.0
Type=Link
Name=Servers that never respond or are slow
URL=https://sub.tv/s
Icon=applications-internet
```
![image](https://user-images.githubusercontent.com/10448369/91697650-62ce4480-eb69-11ea-87b4-50583d31e652.png)

### Or when connection is now refused, you **SOMETIMES** get the file archiver oddly opening?
```
[Desktop Entry]
Version=1.0
Type=Link
Name=When a connection is refused
URL=https://bacon.domain.tv/s
Icon=applications-internet
```
![image](https://user-images.githubusercontent.com/10448369/91697759-8db89880-eb69-11ea-81b4-1531e9349041.png)

### Then there is a simple HTTP 302 redirection it can't handle...
```
[Desktop Entry]
Version=1.0
Type=Link
Name=When there is a 302 redirect
URL=https://www.icann.org/topics/idn/
Icon=applications-internet
```
![image](https://user-images.githubusercontent.com/10448369/91697873-be003700-eb69-11ea-8ae6-1f94ad4838c8.png)

### Lastly when it knows the document type, but Caja has no idea if the application associated with it even understands https://...
```
[Desktop Entry]
Version=1.0
Type=Link
Name=Have AbiWord be the default for ODT for this test
URL=https://documentation.libreoffice.org/assets/Uploads/Documentation/en/QR5/Quick-reference-guide-Libreoffice5.x-En.odt
Icon=applications-internet
```
![image](https://user-images.githubusercontent.com/10448369/91698242-4ed71280-eb6a-11ea-8060-264941fc6285.png)

--------------------------------------------

All of which can be solved by simply removing the ability for Caja to "check" (forming it's own HTTP requests) these URL's!

It just needs to do what **MATE Panel** already does... and just open any links (http://, https://, ftp://, etc... whatever protocol) in whatever application is **REGISTERED** as the default application for that protocol!

Whatever bright idea someone once had, that has now resulted in the multiplicity of odd behaviours above ... likely stemming back from the days of Nautilus.  It was a **bad idea** and likely poorly tested and conceived at a time when the WWW was much younger.

Even if the goal was to somehow use "freedesktop.org Desktop Entry files" to create some kind of poor-mans symlink to online/network resources that Caja could pass to applications.  I've yet to have seen anyone use them in this way, and as I've already stated... **Caja has no way of knowing what applications can and can't handle these links!**

But lets say you wanted to keep this hideous feature, all the file managers I have found... have long since accepted that the best way to handle WebDAV resources is to acknowledge that http:// and https:// is just too ambiguous / confusing / misleading... and have moved on to using webdab:// dav:// and dav:// (their officiality varying when reading RFC's [here](https://tools.ietf.org/html/rfc2518) and [here](https://tools.ietf.org/html/rfc4918) and also when looking at [service names](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xml)).

This **includes** Dolphin, PCManFM, Nautilus and Thunar... as evidenced [here](https://wiki.lxde.org/en/PCManFM#Features), [here](https://docs.nextcloud.com/server/15/user_manual/files/access_webdav.html) and [here](https://wiki.archlinux.org/index.php/WebDAV#Thunar).

But when it comes to a simple http:// or http:// URL... Caja has no place forming **HTTP** requests itself... it should open the damn thing in whatever application is the default registered application for that protocol.

**Comment by rbuj** [comment]
> OK so issues with Caja not creating launchers properly when URLs are dragged and dropped to it - have been fixed with ...

@Lantizia do not create cross-references to other issues.
