### ISSUE TITLE
Cannot rename in icon view

### ISSUE THREAD

**Issue by braikar** [mate-desktop/caja#1440]
Since the latest update, rename in caja works in compact view, list view, but in icon view it's not working.
Version 1.22.2

**Comment by lukefromdc** [comment]
Try resizing the window wider until more icons appear per row , or hiding the sidebar temporarily. There is a bug that has been around a while (and which I have never been able to find) that can sometimes block renaming in icon views under certain exact width conditions.

**Comment by braikar** [comment]
Ooh, thanks for the help, it works, that's indeed a funky bug!

**Comment by smithtim** [comment]
For anyone coming across this, it was never fixed, and is being tracked at #1444 and #1747.
