### ISSUE TITLE
Caja does not save URL launchers with long titles

### ISSUE THREAD

**Issue by Lantizia** [mate-desktop/caja#1446]
This bug assumes you've patched your copy of Caja to actually work with dragging and dropping URL's from web browsers into Caja (inc. the desktop), as that was very broken for Chrome and in some cases of Firefox.  See this issue... https://github.com/mate-desktop/caja/issues/1433

#### Expected behaviour
It should actually save them when they are dragged and dropped, maybe it should truncate the title to make it work - who knows.

#### Actual behaviour
It doesn't do anything, just acts like you didn't drag and drop anything when you release the mouse (but at least the mouse cursor is correct for dragging and dropping a URL).

#### Steps to reproduce the behaviour
So here is a web page I wanted to "drag and drop" in to a caja folder, try it for yourself...
https://github.com/bjoernkarmann/project_alias

I started to play around and it seems like titles over 247 chars seem to have the issue, here is one I made myself with 248 :)
http://5r.tf/testpage.html

#### Additional reading
If you're interested in this URL-related Caja bug, here are some other greatest hits (so far)...
https://github.com/mate-desktop/caja/issues/1433
https://github.com/mate-desktop/caja/issues/1438

**Comment by rbuj** [comment]
This constraint is because of the [maximum filename length](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits) which in most files is about 255 characters.

**Comment by Lantizia** [comment]
Wait, no why is this closed?  Seriously!

I get that there are restrictions on some filesystems (in terms of length of filenames), I'd already suspected that... but surely Caja can do better than just **silently refuse** to make the file?

Wouldn't truncating it be better?

**Comment by rbuj** [comment]
I don't think anyone uses more than 255 characters as a description of a web page, but if you think this will improve the robustness of caja there is no problem reopening the issue and marking it as RFE.

**Comment by Lantizia** [comment]
This is not a feature request!

The "feature" of being able to save URL's (and the title of the web page it points at) as a freedesktop-spec URL launcher... is **already a feature**

The issue is that it is broken in a circumstances that has not before been considered.  That doesn't make it a feature request!

It's a bug, plain and simple.

Filenames on some filesystems might need to be <=255 but HTML <title/> tags can hold more, so this needs to be accounted for in the very design of the function which has this bug!

**Comment by rbuj** [comment]
What does w3c recommended for title length? Do not use more than 50-60 characters.
https://www.w3schools.com/tags/tag_title.asp

**Comment by rbuj** [comment]
I leave this conversation.

**Comment by Lantizia** [comment]
What on earth has a recommendation from w3schools.com, got to do with what is and is not valid?

**Comment by raveit65** [comment]
Does this work with other linux browsers, eg. nautilus or dolphin?

**Comment by rbuj** [comment]
> What on earth has a recommendation from w3schools.com, got to do with what is and is not valid?

length < 64 characters
https://www.w3.org/Provider/Style/TITLE.html

**Comment by Lantizia** [comment]
You realise you just completely took that out of context right?...

"The title should ideally be less than 64 characters in length. That is, many applications will display document titles in window titles, menus, etc where there is only limited room"

So we're on about a line which say **ideally**... is not a specification document... and lastly that page has stood like that for AT LEAST 23 years...

http://web.archive.org/web/19970605040035/http://www.w3.org/Provider/Style/TITLE.html

Which means desktop resolutions have kind of improved since then.

**Comment by Lantizia** [comment]
> I leave this conversation.

Welcome back by the way.

**Comment by Lantizia** [comment]
What a completely hideous and lazy fix for something that would be so simple to rectify.

Especially since Caja is already known to truncate file names when they get too long... e.g. take a 0 byte file with a 255 length file name... and drag it (holding down Ctrl so it'll make a copy) alongside itself...

![image](https://user-images.githubusercontent.com/10448369/91764330-043bb180-ebcf-11ea-9ac9-fd1345096667.png)

Bingo you get a file which has had 7 characters removed so it can fit in ... " (copy)" at the end.

![image](https://user-images.githubusercontent.com/10448369/91764383-1c133580-ebcf-11ea-8407-3703783d63d8.png)

Wouldn't it be better if long web page titles were truncated instead and something like " (truncated)" got appended at the end?

**Comment by Lantizia** [comment]
Also, I wouldn't be so harsh on your attempts to fix this issue if it wasn't for the completely absurd hard time you've given me on proving this bug (and others)... even going so far as to mark this a feature request!  When it is not!

I was never asking for you to start coding anything... I'm happy to have a crack at that myself.  But the first step has got to be to actually **accept** that a bug exists with 1 or more people confirming that a) it exists, b) it's a bug, and then c) we move on to talk about possibilities for fixing it.

Your style in dealing with people, who are just trying assist in perfecting software, has a lot to answer for.

**Comment by rbuj** [comment]
If caja doesn't display an error message when a Create Link operation has not been completed, that is a software error AKA (also known as) bug, and shortening the filename of a link for this case [1] is a RFE (Request For Enhancement). However, other team members may consider this to be a bug fix. Note that after attaching "Link to " to a filename that has the maximum number of characters it should probably be shortened, but this is another issue which could be labeled as bug fix.

[1] Using a long title in the header of an html file is a human error. Human errors that can cause non critical strange behavior, they need to be solved in order to improve the robustness.

**Comment by Lantizia** [comment]
It's human error in your opinion, but not in anyway you've yet to factually prove.

But 'human error' certainly works as a good description for something else I had in mind, not this mind you.

**Comment by rbuj** [comment]
@Lantizia do not create cross-references to other issues, I mean the additional reading section.

**Comment by raveit65** [comment]
@Lantizia 
Again, does nautilus, nemo or dolphin or support opening those links?
