### ISSUE TITLE
Size of 'Side Pane' pop-up (right click on item) is not correct

### ISSUE THREAD

**Issue by oratosquilla-oratoria** [mate-desktop/caja#1473]
#### Expected behaviour
The pop-up should fit all the items and do not show scrollbar buttons at the top and bottom.

#### Actual behaviour
The pop-up sometimes has the correct size and sometimes not.

#### Steps to reproduce the behaviour
![popup_size](https://user-images.githubusercontent.com/15127577/101688150-81df4b00-3a63-11eb-9a99-4a7e491e0c15.gif)

#### MATE general version
1.24.1

#### Package version
Caja 1.24.0

#### Linux Distribution
Tested on Manjaro and Ubuntu MATE 20.10

#### Link to bugreport of your Distribution
Reproduced on 2 OSes so not distro-specific

**Comment by oratosquilla-oratoria** [comment]
The information about the bug is updated.

**Comment by lukefromdc** [comment]
Changes in GTK3 in early 2019 created some problems with submenus in particular, which were fixed by merging the 
wip/fix-submenu-size branch in Feb that year, this might be more fallout from the underlying change that made that necessary. I remember vaguely a whole bunch of menu size issues at that time

**Comment by Xmetalfanx** [comment]
just found this issue as it's something I have dealt with for awhile and finally decided to look into ... that general time frame (@ 2019 at some point) seems about when I noticed it for the first time... I think I have seen this in Caja on Solus Budgie (I happen to like Caja better then their defaults) too

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/1571 fixes this, needs one unused variable cleaned up and then will be ready to go so far as I can tell

**Comment by AngryPhantom** [comment]
Can confirm this. Debian Stable 11 (Bullseye). Caja: 1.24.0-1, mate-desktop: 1.24.1-2.
