### ISSUE TITLE
Caja can't start

### ISSUE THREAD

**Issue by nneo16** [mate-desktop/caja#1507]
#### Expected behaviour
caja should open its window

#### Actual behaviour
sudo caja
caja: symbol lookup error: caja: undefined symbol: mate_desktop_thumbnail_scale_down_pixbuf

#### Steps to reproduce the behaviour
sudo caja
caja: symbol lookup error: caja: undefined symbol: mate_desktop_thumbnail_scale_down_pixbuf

#### MATE general version
Mate 1.24.1

#### Package version
apt-cache showpkg caja
Package: caja
Versions: 
1.20.3-1+b1 (/var/lib/apt/lists/deb.debian.org_debian_dists_buster_main_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/deb.debian.org_debian_dists_buster_main_binary-amd64_Packages
                  MD5: 2d27e6d6f085ec92e7532bd116bd9d0a
 Description Language: 
                 File: /var/lib/apt/lists/deb.debian.org_debian_dists_buster_main_binary-i386_Packages
                  MD5: 2d27e6d6f085ec92e7532bd116bd9d0a
 Description Language: en
                 File: /var/lib/apt/lists/deb.debian.org_debian_dists_buster_main_i18n_Translation-en
                  MD5: 2d27e6d6f085ec92e7532bd116bd9d0a
Reverse Depends: 
  mate-desktop-environment-core,caja 1.20.2-2~
  mate-session-manager,caja
  caja-dropbox,caja
  caja:i386,caja
  syncthing-gtk,caja
  caja-owncloud,caja
  caja-owncloud,caja
  caja-nextcloud,caja
  caja-nextcloud,caja
  mate-session-manager,caja
  caja-common,caja 1.9.0
  exe-thumbnailer,caja
  caja-seahorse,caja
  caja-rename,caja
  caja-eiciel,caja
  caja-admin,caja
  caja-common,caja 1.9.0
  atril,caja
Dependencies: 
1.20.3-1+b1 - caja-common (5 1.20.3-1) desktop-file-utils (0 (null)) gvfs (0 (null)) libcaja-extension1 (5 1.20.3-1+b1) libglib2.0-bin (0 (null)) libglib2.0-data (0 (null)) mate-desktop (0 (null)) shared-mime-info (0 (null)) libatk1.0-0 (2 1.12.4) libc6 (2 2.14) libcairo-gobject2 (2 1.10.0) libcairo2 (2 1.10.0) libexempi8 (2 2.5.0) libexif12 (2 0.6.21-1~) libgail-3-0 (2 3.0.0) libgdk-pixbuf2.0-0 (2 2.22.0) libglib2.0-0 (2 2.41.1) libgtk-3-0 (2 3.21.4) libice6 (2 1:1.0.0) libmate-desktop-2-17 (2 1.19.2) libnotify4 (2 0.7.0) libpango-1.0-0 (2 1.20.0) libpangocairo-1.0-0 (2 1.14.0) libselinux1 (2 1.32) libsm6 (0 (null)) libstartup-notification0 (2 0.2) libx11-6 (0 (null)) libxml2 (2 2.7.4) caja-common (3 1.20.0-2~) libcaja-extension (3 1.10.0) libcaja-extension1 (3 1.10.0) mate-session-manager (3 1.8.1-7) gvfs-backends (0 (null)) engrampa (0 (null)) gstreamer1.0-tools (0 (null)) meld (0 (null)) caja-common (3 1.20.0-2~) libcaja-extension1:i386 (3 1.10.0) caja-common:i386 (3 1.20.0-2~) caja-common:i386 (3 1.20.0-2~) caja:i386 (32 (null)) libcaja-extension:i386 (3 1.10.0) mate-session-manager:i386 (3 1.8.1-7) 
Provides: 
1.20.3-1+b1 - caja:i386 (= 1.20.3-1+b1) 
Reverse Provides: 
caja:i386 1.20.3-1+b1 (= 1.20.3-1+b1)

#### Linux Distribution
uname -a
Linux debian10 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux

#### Link to bugreport of your Distribution (requirement)
https://www.debian.org/Bugs/Reporting

**Comment by raveit65** [comment]
>> Link to bugreport of your Distribution (requirement)

>> https://www.debian.org/Bugs/Reporting

No bugreport , no mercy!....ignoring!

**Comment by rbuj** [comment]
Please, upgrade mate-desktop to 1.23.3 or a newer version, and check wether your system is up to date including all MATE components. If you have any further questions about the maintenance of your system, please contact your system administrator.

**Comment by rbuj** [comment]
The error you reported here is because you updated mate-desktop but you didn't update caja.
