### ISSUE TITLE
Caja didn't show any thumbinails in list mode

### ISSUE THREAD

**Issue by geplus** [mate-desktop/caja#153]
Latest version of Caja (1.6.2) didn't show any thumbinails in list mode. The same happens for the folders that use an image as icon.
Also, the thumbinails of .XCE images aren't showed in all view modes, despite other file managers (PC Man FM and Thunar) show them.
I've already try to set Show Thumbnails to alwais, but it's the same.

Also, when you are in list view and you middle-click to a folder one time for open a folder in a tab, the folder doesn't open: you must middle-click twice, despite the preferences settings.

Also using ffmpeg thumbnails, any video preview is showed in list mode, and in compact view mode isn't showed under 150% dimensions.

On Nautilus,Thunar etc. everything works good. so I'm sure it's a problem related Caja.

I hope these issues will be resolved soon, these thumbinails bug ruin one of the best Linux file managers ever.
##

**Comment by monsta** [comment]
I'm not sure what's wrong here... isn't the list view mode supposed to have just small *file type* icons to the left of filenames?
Thumbnails of size *that small* don't seem to be useful to me. You want thumbnails, you switch to icon view.

**Comment by geplus** [comment]
nemo has thumbinails in list mode, so why caja didn't? I think it's a bug, surely. Thumbinails in list mode are usefull for my daily usage

**Comment by raveit65** [comment]
Nemo is nemo and caja is caja :)

**Comment by monsta** [comment]
Yes, I see them in Nemo. Doesn't look good in my opinion. I'd rather see one icon per file *type* than very small thumbs that are useless unless you set zoom to high enough value. :confused: 

I also couldn't find any option to turn them on/off...

**Comment by geplus** [comment]
an option for turn it on/off could be the right way

**Comment by Carmina16** [comment]
Thumbnails in the list view are very convenient feature and it needs to be enabled.

**Comment by markusneg** [comment]
I also think it should be enabled. Dependent on the zoom level, list views also can have quite big thumbnails.

**Comment by epgfm** [comment]
I agree with @geplus, having more options is the MATE way.

**Comment by desconocidos** [comment]
I have upgraded my system from Ubuntu 12.04 to Ubuntu Mate 16.04

Now I can no longer see previews of my graphics files in List View.
Preferences -> Preview is set correctly. **Are you sure this isn't a bug?**

I can see the previews in Icon View but that is no use to me. I need to be able to compare files at a glance, being able to see roughly what the image looks like, filetype, file size and date.

![image](https://cloud.githubusercontent.com/assets/29224739/26820610/ad5da73a-4aa3-11e7-8377-91374f126699.png)

**Comment by monsta** [comment]
There was no MATE in Ubuntu 12.04. Did you use some external repo for it?

**Comment by desconocidos** [comment]
@monsta You are right. I forgot to mention that I was using Nautilus in Ubuntu 12.04. This was replaced by caja in Ubuntu Mate 16.04. They seem identical apart from the lack of List View preview.

**Comment by rranke** [comment]
I am using ubuntu-mate 18.04.3 LTS with caja 1.20.2

This problem still exists and is not fixed.  
This ticket was opened six years ago, on "24 Aug 2013".

Is there hope that this will get fixed soon?

Thanks.

**Comment by raveit65** [comment]
This is a new feature and in master branch , you need to wait for mate-1.24.
Or ask ubuntu at launchpad to include this commit as patch for 18.04.

**Comment by rranke** [comment]
To wait for mate-1.24?

So, what is the time horizont here? 
Can i assume, that in some weeks or months, i can run sudo apt-get update+upgrade on my 18.04 and caja will be updated automatically?

BTW, is this really a "NEW" feature? 
I dont think that is a NEW feature. I think this is a BUG, because in nautilus on ubuntu 18.04 this thumbnail thing works fine.

Greets

**Comment by raveit65** [comment]
> So, what is the time horizont here?

Beginning of next year. Also 1.20 has reached EOL since half a year. Sorry, we are a small team, we don't make new releases for 1.20 any more.
Again, the only way for you is to asked at launchpad ubuntu to add this as patch.

> I dont think that is a NEW feature. I think this is a BUG.

Why, only why you don't see a preview ?
Does caja crash without this?
