### ISSUE TITLE
Removing larger folders is slow

### ISSUE THREAD

**Issue by ZuseZ4** [mate-desktop/caja#1537]
#### Expected behaviour
The folder is removed quickly (<10s).

#### Actual behaviour
It takes 1:12 minutes.
Using https://doc.rust-lang.org/std/fs/fn.remove_dir_all.html to delete the folder takes 2 seconds.

#### Steps to reproduce the behaviour
download https://static.rust-lang.org/dist/rustc-1.53.0-src.tar.gz
(or any other larger project) and unpack it. Possibly even build to increase the size further.
Permanently delete it afterwards.

#### MATE general version
1.24.0

#### Linux Distribution
Ubuntu mate 20.04

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu-mate/+bug/1936275

**Comment by lukefromdc** [comment]
From what I've heard in thr past this has something to do with gvfs and effects all Nautilus-based file managers

**Comment by ZuseZ4** [comment]
So, shall we close this as won't-fix?

**Comment by lukefromdc** [comment]
We probably should, given GVFS is the culprit and we can't fix GVFS here
