### ISSUE TITLE
Caja's toolbar icons are dark grey on black, illegible in Linux Mint 20.2

### ISSUE THREAD

**Issue by artisticfox8** [mate-desktop/caja#1543]
#### Expected behaviour
Iconset is switched to light icons (Mint-Y-Dark-Red), so I can see icons clearly like in other programs (i. e. Xviewer)

#### Actual behaviour
Icons stay dark grey. Screenshots attached

#### Steps to reproduce the behaviour
Switch to Mint-Y-Darker-Red Controls, Mint-Y-Dark-Red and Mint-Y-Red icons

#### Linux Distribution Linux Mint 20.2
icon bugs in caja](
![screenshot icon bugs in caja](https://user-images.githubusercontent.com/77014769/128566288-ce94636e-e9ed-4fc2-9ea7-24340ecc3718.png)
correctly applied icons in xviewer
![correctly applied icons xviewer](https://user-images.githubusercontent.com/77014769/128566294-00ec7e36-81c4-4fc2-9a6a-1606444dec47.png)

**Comment by raveit65** [comment]
Mate-icon-theme is default from Mate. not mint themes.
File out a report against your distro.

**Comment by lukefromdc** [comment]
I don't think we support automatically switching any iconset in a manually edited theme either. In fact, doing so would potentially override some user's deliberate choice. You need to directly select the correct icons for your gtk theme in any custom theme.

**Comment by artisticfox8** [comment]
> I don't think we support automatically switching any iconset in a manually edited theme either. In fact, doing so would potentially override some user's deliberate choice. You need to directly select the correct icons for your gtk theme in any custom theme.

if you want to sacrifice usability yes. This isn't some obscure theme I found on a forum, this is one of the default themes. Why can Xviewer team do it correctly, while you can't?

**Comment by lukefromdc** [comment]
The default themes in Mint are not thr same as MATE's own default themes and we do not maintain somone else's themes

**Comment by artisticfox8** [comment]
> The default themes in Mint are not thr same as MATE's own default themes and we do not maintain somone else's themes
> […](#)
> On 8/7/2021 at 6:00 AM, "artisticfox8" ***@***.***> wrote: > I don't think we support automatically switching any iconset in a manually edited theme either. In fact, doing so would potentially override some user's deliberate choice. You need to directly select the correct icons for your gtk theme in any custom theme. if you want to sacrifice usability yes. This isn't some obscure theme I found on a forum, this is one of the default themes. Why can Xviewer team do it correctly, while you can't? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#1543 (comment)](https://github.com/mate-desktop/caja/issues/1543#issuecomment)- 894633459

Ok, but why does Xviewer, also a Mate program apply correct icons? If my icon theme was wrong, XViewer woukd have the bug too. It does not

**Comment by lukefromdc** [comment]
Xviewer is NOT one of ours, I think it's Mint's program and part of their Xapps suite

**Comment by artisticfox8** [comment]
> I don't think we support automatically switching any iconset in a manually edited theme either. In fact, doing so would potentially override some user's deliberate choice. You need to directly select the correct icons for your gtk theme in any custom theme.

You see, if I set icons to light, I would break stuff elsewhere, where the icons are on a white background

**Comment by lukefromdc** [comment]
That sounds like someome wrote a Mint theme (probably intended for Cinnamon and not for MATE) that will have trouble with any icon set offered when used in MATE.

My own theme (UbintuStudio_Legacy) mixes light and dark elements and thus required a great deal of attention ro detail to avoid whitr on white, dark on dark, or other no-contrast scenarios.

**Comment by artisticfox8** [comment]
> Xviewer is NOT one of ours, I think it's Mint's program and part of their Xapps suite
> […](#)
> On 8/7/2021 at 7:41 PM, "artisticfox8" ***@***.***> wrote: > The default themes in Mint are not thr same as MATE's own default themes and we do not maintain somone else's themes > […](#) > On 8/7/2021 at 6:00 AM, "artisticfox8" ***@***.***> wrote: > I don't think we support automatically switching any iconset in a manually edited theme either. In fact, doing so would potentially override some user's deliberate choice. You need to directly select the correct icons for your gtk theme in any custom theme. if you want to sacrifice usability yes. This isn't some obscure theme I found on a forum, this is one of the default themes. Why can Xviewer team do it correctly, while you can't? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#1543 (comment)](https://github.com/mate- desktop/caja/issues/1543#issuecomment)- 894633459 Ok, but why does Xviewer, also a Mate program apply correct icons? If my icon theme was wrong, XViewer woukd have the bug too. It does not -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#1543 (comment)](https://github.com/mate-desktop/caja/issues/1543#issuecomment)- 894698883

If you made it work it would be brilliant!

**Comment by lukefromdc** [comment]
I do not have time to work on that, and its not our responsability. That's why
this report is closed

**Comment by artisticfox8** [comment]
> I do not have time to work on that, and its not our responsability. That's why this report is closed
> […](#)
> On 8/9/2021 at 7:59 PM, "artisticfox8" ***@***.***> wrote: > Xviewer is NOT one of ours, I think it's Mint's program and part of their Xapps suite > […](#) > On 8/7/2021 at 7:41 PM, "artisticfox8" ***@***.***> wrote: > The default themes in Mint are not thr same as MATE's own default themes and we do not maintain somone else's themes > […](#) > On 8/7/2021 at 6:00 AM, "artisticfox8" ***@***.***> wrote: > I don't think we support automatically switching any iconset in a manually edited theme either. In fact, doing so would potentially override some user's deliberate choice. You need to directly select the correct icons for your gtk theme in any custom theme. if you want to sacrifice usability yes. This isn't some obscure theme I found on a forum, this is one of the default themes. Why can Xviewer team do it correctly, while you can't? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#1543 (comment)](https://github.com/mate- desktop/caja/issues/1543#issuecomment)- 894633459 Ok, but why does Xviewer, also a Mate program apply correct icons? If my icon theme was wrong, XViewer woukd have the bug too. It does not -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#1543 (comment)](https://github.com/mate- desktop/caja/issues/1543#issuecomment)- 894698883 If you made it work it would be brilliant! -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#1543 (comment)](https://github.com/mate-desktop/caja/issues/1543#issuecomment)- 895500403

Thanks for telling me! Please tell me where to report this and I will!

**Comment by lukefromdc** [comment]
Report would be against whatever package contains mint's themes, presumably on mint's bug reporting system
