### ISSUE TITLE
Caja cannot access Win SMB1(aka NT1) shares

### ISSUE THREAD

**Issue by joakim-tjernlund** [mate-desktop/caja#1548]
#### Expected behaviour
Access to share

#### Actual behaviour
Error: Function not implemeted

#### MATE general version
1.24

#### Package version
mate-base/caja-1.24.1
mate-extra/caja-extensions-1.24.1
#### Linux Distribution
Gentoo

#### Link to bugreport of your Distribution (requirement)
None

**Comment by L-U-T-i** [comment]
Have you tried with:

```
[global]
	client min protocol = NT1
	server min protocol = NT1

```
settings in /etc/samba/smb.conf (on both machines)?

I've noticed similar issues after samba 4.10 to samba 4.11.2 upgrade, and that resolved the problem...

**Comment by joakim-tjernlund** [comment]
The remote server has since then been upgraded and the problem went away.
