### ISSUE TITLE
Sort order inverted

### ISSUE THREAD

**Issue by DennisHeine** [mate-desktop/caja#1552]
#### Expected behaviour
When sorting ascending, the earliest entry should be shown first
(the triangles at the top of the list view)

#### Actual behaviour
Ascending sort order shows the entries descending

#### Steps to reproduce the behaviour
Switch to list view and click on the triangle in the header.

#### MATE general version
Linux Mint 20.2 Uma

#### Package version
1.24.0

#### Linux Distribution
Linux Mint 20.2 Uma

#### Link to bugreport of your Distribution (requirement)
fu

**Comment by lukefromdc** [comment]
in list view,clicking on the header of any column selects sorting by that attribute, further clicking on it toggles sort ascending and sort descending

**Comment by raveit65** [comment]
> Linux Mint 20.2 Uma
> #### Link to bugreport of your Distribution (requirement)
> 
> fu

Hallo Dennis Heine,
was heist `fu` in deinem Wortschatz?
Meinst du `fuck you`?

Hello Dennis Heine,
what means  `fu` in in your vocabulary ?
Do you mean `fuck you`?

**Comment by DennisHeine** [comment]
No need for swearing, i ment "for you".
Jut replacing that filled triangle with an arrow (even though that's how window does handle those sorting symbols) will hopefully solve that misinterpretation.

**Comment by raveit65** [comment]
Column order of creation date / access date / change date are sorted in the same way like nemo/nautilus or mozilla thunderbird did.
Looks like you misunderstood the meaning of the symbol.
In result there is no issue and no need for a code change.
