### ISSUE TITLE
Caja 

### ISSUE THREAD

**Issue by CaptainDesAstres** [mate-desktop/caja#1553]
#### Expected behaviour

I want Caja to startup!

#### Actual behaviour

Since I update Debian to Bullseye release, Caja don't work anymore. There is no file manager in desktop view and if I tried to launch it in terminal, I get a GTK error:

`19:42:34 tyler-durden@Desktop-Mayhem:~$ caja
(caja:166170): Gtk-WARNING **: 19:43:45.932: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
Initializing caja-open-terminal extension
Erreur de segmentation`

Alternatively, I, sometimes, get this error:

`19:42:16 tyler-durden@Desktop-Mayhem:~$ caja 
Could not register the application: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`

(Using --force-desktop or --no-desktop don't change anything.)

#### Steps to reproduce the behaviour

I don't know

#### MATE general version

caja: 1.24.0-1
mate-core: 1.24.0+4
mate-desktop:1.24.1-2

#### Package version

libgtk2.0-0: 2.24.33-2
libgtk-3-0: 3.24.24-4

#### Linux Distribution

Debian, recently update to Bullseye

#### Link to bugreport of your Distribution (requirement)

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934791&archived=False&mbox=no&mboxmaint=no
(It's not actually MY report but this 2 years old  bug seems to be the same)

**Comment by mbkma** [comment]
maybe try to remove [caja-open-terminal](https://packages.debian.org/sid/caja-open-terminal)

**Comment by CaptainDesAstres** [comment]
> maybe try to remove [caja-open-terminal](https://packages.debian.org/sid/caja-open-terminal)

Removing caja-open-terminal did not solve the problem, but removing all other packets starting by "caja-" did. I don't know which one was the problem coming from…
