### ISSUE TITLE
few option when i right click on caja

### ISSUE THREAD

**Issue by jakbin** [mate-desktop/caja#1555]
#### Expected behaviour

When i right click on caja inside a folder . I Want more option like - open other terminals emulator , powershell etc
And most important - give option to open code editor or ide here.

#### Actual behaviour
When i right click on caja inside a folder , its give only these option. 
![right_click](https://user-images.githubusercontent.com/65591973/133917715-0c2163ba-5851-488d-b6f0-fdf436570803.png)
)

#### Steps to reproduce the behaviour
right click on caja inside a folder ,

#### MATE general version
1.24

#### Package version
1.24.0-1

#### Linux Distribution
parrot os 4.11 

#### Link to bugreport of your Distribution (requirement
[parrot os](https://github.com/parrot/parrot)

**Comment by lukefromdc** [comment]
Those come from extensions e.g the option to compress a file comes from an extension inatalled by Engrampa. A program you want to open from caja's right-click menu needs to install an extension. 

Installing the caja-extensions package will get you several useful ones, notably open-in-terminal
