### ISSUE TITLE
Caja does not show icons of applications in /usr/share/applications and asks user for confirmation on launch of desktop-files here

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/caja#1562]
#### Expected behaviour
Caja 1.24.1 on Ubuntu MATE 21.04 shows icons and is able to launch applications when user click on desktop-files as shown below on screencast

![caja-1-24-hirsute](https://user-images.githubusercontent.com/309456/136568315-b3ff3d69-30b5-4729-8889-b79a8cb94eb0.gif)

#### Actual behaviour
Caja 1.26.0 on Ubuntu MATE 21.10 does not show icons and asks user for confirmation on launch of desktop-files here as shown below on screencast

![caja-1-26-impish](https://user-images.githubusercontent.com/309456/136573239-69f0a77e-e960-4eb8-b83b-44267322dece.gif)

#### Steps to reproduce the behaviour
1. Have Caja 1.26 installed
1. Navigate to /usr/share/applications
1. Look at list of blank icons
1. Try to launch some application from the shown list

#### MATE general version
1.26

#### Package version
1.26.0-0ubuntu1

#### Linux Distribution
Ubuntu MATE 21.10

#### Link to bugreport of your Distribution (requirement)
https://pad.lv/1946492

Note: It may be OK for Nautilus, but not acceptable for Caja. For me this functionality is critical.

**Comment by raveit65** [comment]
```
[rave@f33-orig caja]$ git bisect bad
4a7fe0f438ab37bcb483ac63627b86872da6c1b8 is the first bad commit
commit 4a7fe0f438ab37bcb483ac63627b86872da6c1b8
Author: rbuj <robert.buj@gmail.com>
Date:   Mon Nov 23 21:53:17 2020 +0100

    caja-directory-async: trust only system launchers

 libcaja-private/caja-directory-async.c | 7 +------
 1 file changed, 1 insertion(+), 6 deletions(-)
```
from https://github.com/mate-desktop/caja/pull/1468

Btw. how to biscet with git (i susspect you're native German speaker)
https://www.kleinweby.de/2012/03/git-bisect-wer-hat-wann-was-kaputt-gespielt/
