### ISSUE TITLE
audio preview crashed caja

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#157]
Orrginal report at fedora bugzilla:
mate-file-manager-1.6.1-1.fc19: audio_child_died: Process /usr/bin/caja was killed by signal 11 (SIGSEGV)
https://bugzilla.redhat.com/show_bug.cgi?id=959444

First some details. Indeed, yesterday i was previewing some flac file before it crashed. (but forgot about them.) Right now, i can reproduce it like this:

preview a flac file for a few seconds, next preview an mp3 file. caja dies instantly.

th problem is: abrt does not catch this, and if i run it in gdb like this:

run /home/cornel/

i can not reproduce it.

if i try to kill the background process (caja -n), it is respawned immediately. 
How can i debug this?

backtrace:
https://bugzilla.redhat.com/attachment.cgi?id=791501

**Comment by MurKit** [comment]
It is 2016, Linux Mint Mate 17.3 and audio preview still crashes caja 1.12.7
And it seems like I have no gstreamer to tweak

**Comment by kelebek333** [comment]
You can try to install gnome-media package for gstreamer-properties

sudo apt-get install --no-install-recommends gnome-media

@MurKit
