### ISSUE TITLE
Feature request: unify titlebar and menubar (like KDE 4.10 or Firefox)

### ISSUE THREAD

**Issue by geplus** [mate-desktop/caja#159]
In KDE you can put the menu bar on titlebar, or replace the menubar with a "menu bar button" setted in the titlebar, for increase the window's space.
Firefox also does a similar thing in Windows OS, with tabs on titlebar and Firefox button on the left of the titlebar.

A similar feature for have more space in your window is very usefull, even in the notebooks and the PCs with a small monitor.

**Comment by monsta** [comment]
This sounds like what gnome guys do in their CSD apps...

**Comment by monsta** [comment]
I don't think we'll be implementing this. It's not just Caja, we'd need to apply this to every app launched in MATE to keep it consistent. A feature that seems simple on the outside, but would take quite a lot of work on the inside.
