### ISSUE TITLE
Caja: issues with Russian localization related to "Creation date" or "Date Created"

### ISSUE THREAD

**Issue by HectorB-2020** [mate-desktop/caja#1590]
#### Expected behaviour

Menu "**Edit**" (RU: "**Правка**"), "**Preferences**" (RU: "**Параметры**"), 

1. First tab "**Views**" (RU: "**Вид**"),
 "**Arrange items:**" (RU: "**Выстраивать объекты:**") drop-down menu. 
  Item "_By Creation date_" should be translated to Russian.
  ++Embedded tab "_Tree view_" should also be translated to Russian.
  
2. Third tab "**Display**" (RU: "**Внешний вид**"), "**Icon Captions**" (RU: "**Подписи к значкам**")
  All three drop-down menus should be fully translated to Russian including "_Date Created_".
3. Fourth tab "**List Columns**" (RU: "**Столбцы поиска**")
  Item  "_Date Created_" must be translated to Russian.

#### Actual behaviour
Even with
```
LANG=ru_RU.UTF-8
LANGUAGE=ru_RU.UTF-8
```
the mentioned above strings are left in English.

#### Steps to reproduce the behaviour
Run `caja`, click on menu "**Edit**", open "**Preferences**".

#### MATE general version
MATE 1.26.0

#### Package version
1.26.0

#### Linux Distribution
Ubuntu 21.10 with latest updates

**Comment by raveit65** [comment]
Again, we're using transifex for our translations. We can't fix it here !
Please become a member of your language team at transifix and fix translations there.
https://www.transifex.com/mate/MATE/languages/
