### ISSUE TITLE
Caja produces a lot of xsession errors

### ISSUE THREAD

**Issue by duck7000** [mate-desktop/caja#1605]
#### Expected behaviour
Caja does not produce xsession errors

#### Actual behaviour
This errors are repeatedly produced:
```
** (caja:619): CRITICAL **: 19:03:27.809: caja_bookmark_get_location: assertion 'CAJA_IS_BOOKMARK (bookmark)' failed

(caja:619): GLib-GIO-CRITICAL **: 19:03:27.809: g_file_get_uri: assertion 'G_IS_FILE (file)' failed

(caja:619): GLib-GObject-CRITICAL **: 19:03:27.809: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

#### Steps to reproduce the behaviour
Start Caja, doubleclick a directory and click back button. Those errors are produced

#### MATE general version
V1.26

#### Package version
Caja V1.26.0-1

#### Linux Distribution
Manjaro Mate latest edition fully up to date

Link to support forum thread
https://forum.manjaro.org/t/caja-produces-a-lot-of-xsession-errors/100010

This errors are produced every time you open a directory or open a left pane location so xsession-errors is flooded with errors.

So what are does errors mean?
And how to prevent those errors from happening? They seems to be critical.

**Comment by duck7000** [comment]
It looks like nobody cares?
The errors may not be the biggest problem i guess, flooding xsession-errors is imho

**Comment by lukefromdc** [comment]
I'm not getting these, all I get is this text, first line probably specific to my system:

(caja:1674): Gtk-WARNING **: 19:08:19.828: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
Initializing caja-sendto extension
Initializing caja-xattr-tags extension
Initializing caja-share extension
Initializing caja-open-terminal extension
Initializing caja-image-converter extension
Initializing caja-wallpaper extension

**Comment by duck7000** [comment]
That is very strange.
I'm not the only one that has this errors, on the manjaro forum someone else tested this and he gets the same errors?
even on fedora(gnome) and Arch (i3) as well.
I tested this on Linuxmint Mate and the errors are also there

What system do you use, i mean on witch Linux OS do you use Mate?

And your output above is from terminal right? I'm talking about errors saved in xsession-errors

**Comment by lukefromdc** [comment]
I am on Debian Unstable w locally compiled GTK3

**Comment by lukefromdc** [comment]
Also yes, it's the .xsession-errors file I checked, looking for all references to caja.
Got same text as in a root instance of caja opening in terminal

**Comment by duck7000** [comment]
Mm i'm lost here, basically you say it works in Debian but not in all other OS?

**Comment by lukefromdc** [comment]
That's all I've ever tested it on: I work on bare metal, live system (w a backup root partitiom available if I kill it). I have neither experience working with VMs nor a landline over which to download installers to test other distros.

Thus I am saying I am having no issues with this on one disto and one install used across one desktop and one laptop. I am saying I cannot duplicate the issue, NOT making any claims about its validity on any other system, distro, or installed instanxe

**Comment by duck7000** [comment]
Okay i understand, it wasn't meant to rant.
If you can't duplicate the issue i will close it for now i guess
