### ISSUE TITLE
caja: create new document/folder disabled when there is no empty space in filelist window

### ISSUE THREAD

**Issue by brummerle** [mate-desktop/caja#1610]
#### Actual behaviour
I found a bug in the the right mouseclick context menu?
Doing a right mouseclick in the filelist - without selecting a file/folder - normaly shows "create folder/document".
But if the filelist fills the complete windows, there's no chance to do a right mouseclick without selecting a file/folder, then the context menu switches to the respective options of the selected item. Then there's no chance to create a document/folder in the respective main folder. 

#### Steps to reproduce the behaviour
right mouseclick: see screenshots

#### MATE general version
Linux Mint 20.2 uma

#### Package version
Caja 1.24.0

#### Linux Distribution
Linux Mint 20.2 MATE, mit Linux 5.4.0-96-generic

#### Link to bugreport of your Distribution (requirement)
![20220203_210112](https://user-images.githubusercontent.com/98983930/152421895-0f8b71e4-95cd-4729-8530-d437d3178a40.jpg)
![20220203_210051](https://user-images.githubusercontent.com/98983930/152421903-046ebe8c-ca02-4efb-a718-52168b35fcf7.jpg)

**Comment by zhuyaliang** [comment]
All systems are like this, including ```windows``` Switch the display mode to ```icon view```

**Comment by lukefromdc** [comment]
Closing as this is said to be normal and expected behavior
