### ISSUE TITLE
Caja timestam wrong

### ISSUE THREAD

**Issue by Ishmaely** [mate-desktop/caja#1621]
#### Expected behaviour
Files in directories have correct date modified stamp.

#### Actual behaviour
Files modified yesterday and closed yesterday stamped as (Date modified) today.

#### Steps to reproduce the behaviour
Create text document and save at 4 pm yesterday
View file list in Caja browser at 9 am today.
DATE MODIFIED is 4 pm today - 7 hours from now

#### MATE general version
1.24.0

#### Package version
1.24.0
![caja_wonk](https://user-images.githubusercontent.com/101211516/157306683-b9b2b955-5fa4-41d5-aec1-5534d9660700.jpg)

#### Linux Distribution
Mint 20.2

**Comment by lukefromdc** [comment]
Check that your system clock is not 7 hours off

**Comment by Ishmaely** [comment]
Local time, UTC and RTC all correct. Terminal command "ls -l" on a problem file shows correct timestamp. When the file is older than yesterday midnight the correct value is shown in Caja. It appears that the issue is Caja displaying "TODAY" when it should display "YESTERDAY".

**Comment by lukefromdc** [comment]
I honestly don't know a lot about configuring system time, but this sounds
like you have part of the system on universal and part of it on local time.
I have mine on off-network local time so my configuration would not tell
me much about how your works unless you have the same.

Probably someone else here more familiar with the time system will have to help.

**Comment by Ishmaely** [comment]
****@***:~$ timedatectl
               Local time: Wed 2022-03-09 11:00:00 CST 
           Universal time: Wed 2022-03-09 17:00:00 UTC 
                 RTC time: Wed 2022-03-09 17:00:01     
                Time zone: America/Chicago (CST, -0600)
System clock synchronized: yes 

In my example above my panel clock shows the correct date and time while the file timestamp is displayed as "TODAY". The error is more than 12 hours off in one instance which would indicate the issue is not system time related. The only similar issues I have seen were due to the LOCALE value, however mine is: LC_TIME="en_US.UTF-8" - which is correct.

**Comment by Ishmaely** [comment]
I found a caja crash report from the time when this issue started.

**Comment by pdarkoni** [comment]
This issue is not related to accuracy of system time but formating of time. Caja show modification/creation date correctly if you choose other two types of date format in preferences.

I'm not familliar with C and cannot suggest fix but I believe the issue is around line 4880 in caja-file.c. File modification/creation date is compared with constant G_TIME_SPAN_DAY (which is last 24 hours) instead of time span from midnight.
