### ISSUE TITLE
Default view not sorting by file type

### ISSUE THREAD

**Issue by f15x28** [mate-desktop/caja#1628]
#### Expected behaviour
If we set Edit > Preferences > Views > Default View > Arrange items: By Type, then directories should by default (e.g.: directory which caja has never navigated to) be sorted by type.

#### Actual behaviour
If we set Edit > Preferences > Views > Default View > Arrange items: By Type, then directories by default (e.g.: directory which caja has never navigated to) are NOT sorted by type. That is to say, files of the same type are not listed next to each other. Not sure what they are sorted by, could be filename.

In order to get the default view to actually arrange items by type, I have to set Edit > Preferences > Views > Default View > Arrange items: By Modification Date, which is messed up.

This bug has existed for years. I am surprised it has not bothered enough people to make enough people complain so that it would be fixed by now. Or perhaps people got fed up and just migrated to Cinnamon (I'm kidding, I'm kidding! I have used MATE for many years and never felt attracted to Cinnamon).

#### Steps to reproduce the behaviour
1. In a terminal (NOT caja), create a directory called "test1". Can create the directory anywhere, does not matter, could be in the home directory.
2. In a terminal (NOT caja), copy files of different types to the "test1" directory. Copy at least two files per type. E.g.: two PDFs, two TXT files, two PNG files.
3. In caja, set Edit > Preferences > Views > Default View > Arrange items: By Type.
4. In caja, navigate to the "test1" directory. Will see that files are NOT sorted by type. That is to say, files of the same type are not listed next to each other. Not sure what they are sorted by, could be filename.

5. In a terminal (NOT caja), create a directory called "test2". Can create the directory anywhere, does not matter, could be in the home directory.
6. In a terminal (NOT caja), copy files of different types to the "test2" directory. Copy at least two files per type. E.g.: two PDFs, two TXT files, two PNG files.
7. In caja, set Edit > Preferences > Views > Default View > Arrange items: By Modification Date.
8. In caja, navigate to the "test2" directory. Will see that files are now sorted by type.

#### MATE general version
1.26.0

#### Package version
Sorry, I don't know what this means :-(

#### Linux Distribution
$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal

$ uname -a
Linux losangeles 5.17.5-051705-generic #202204280727-Ubuntu SMP PREEMPT Fri Apr 29 23:10:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
name@losangeles:~$ 

#### Link to bugreport of your Distribution (requirement)
I am so sorry, I really don't know how to do this. I went to the Linux Mint GitHub and tried to open a bug report there, but it basically redirected me to the MATE GitHub. Please, please, please do not ignore my bug report just because I don't know how to link to the bugreport of my distro. I really spend a long time writing this up in a way that I think will make it easy for you to understand :-(

**Comment by thesquash** [comment]
This should get fixed once my pull request #1635 is merged.  Apparently the list of default sort-order choices was (basically) stored in three different places, and for reasons unknown ("code rot"?), the lists got totally out of sync.  I certainly hope that PR fixes the problem; it worked for me.

**Comment by thesquash** [comment]
My pull request #1635 has been merged, and this will thus not be an issue in the future.  This issue may be closed.
