### ISSUE TITLE
"caja --no-desktop" fails outside of mate-terminal

### ISSUE THREAD

**Issue by shmibs** [mate-desktop/caja#164]
when opening a mate-terminal and running caja --no-desktop, without caja running already, caja ignores the desktop as expected. however, when run from anywhere else (e.g. urxvt, dmenu, startup scripts), the option is ignored and a desktop window is drawn.

**Comment by stefano-k** [comment]
https://github.com/mate-desktop/caja/commit/23b75dadd35f039a8cd93111528a8a66dde8888e
