### ISSUE TITLE
1.26.1.1: wrong git tag?

### ISSUE THREAD

**Issue by kloczek** [mate-desktop/caja#1650]
Looking on https://github.com/mate-desktop/caja/compare/v1.26.1.1...v1.26.1 I think that adding that tag was probably kind of mistake.

**Comment by raveit65** [comment]
No, this tag is used for glib version reduced version of caja for rhel8. See release description.
https://github.com/mate-desktop/caja/releases
For normal fedora please do not use this releases.
Thy are named differently.
caja-glib-2.50-1.26.2.tar.xz and caja-glib-2.50-1.26.1.tar.xz

**Comment by kloczek** [comment]
Looks like there is no dist tar ball for 1.26.2.1 on https://pub.mate-desktop.org/releases/1.26/

**Comment by raveit65** [comment]
Yes, because [caja-glib-2.50-1.26.2.tar.xz](https://pub.mate-desktop.org/releases/1.26/caja-glib-2.50-1.26.2.tar.xz) has only old 3 old commits more which are already in [caja-1.26.1.tar.xz](https://pub.mate-desktop.org/releases/1.26/caja-1.26.1.tar.xz)

**Comment by raveit65** [comment]
Please check release notes, everything is written there..

**Comment by kloczek** [comment]
Looks messy .. higher version with lover build dependencies 🤔
