### ISSUE TITLE
Access denied when utilizing caja-connect-server 

### ISSUE THREAD

**Issue by pa5tlife** [mate-desktop/caja#1651]
#### Expected behaviour
Logging in to remote server via SFTP should connect like it did before I made this change, but does not.

#### Actual behaviour
Prompts with window that read "Access was denied" after changing `~/.ssh/config` to include the following lines:
> Host *
>         IdentitiesOnly=yes

#### Steps to reproduce the behaviour
Have too many SSH keys or hosts in PC like me, Change ssh config to include above lines and attempt to use caja to connect to remote server. You will be denied. 

#### MATE general version
1.24.1-2 amd64

#### Package version
1.24.0-1 amd64

#### Linux Distribution
Debian Bullseye 5.10.0-16-amd64

#### Link to bugreport of your Distribution (requirement)
Sorry I dont know how to Linux that good. 

Thanks for your help

**Comment by rbuj** [comment]
Have you tried mounting it from the command line? maybe the error comes from the GVFS ssh backend [1]. I don't know if the backend allows the authentication using keys, previously sent via ssh-copy-id.
```
$ gio mount ssh://host/path
```
[1] https://gitlab.gnome.org/GNOME/gvfs/-/blob/master/daemon/gvfsbackendsftp.c

**Comment by pa5tlife** [comment]
I'm sorry I haven't replied.  My issue was that I had multiple keys with the same names. I ended up deleting the redundant ones, and changing all the ssh config back to what I had before adding the line `IdentitiesOnly=yes` and it is working again like normal. 

Not sure exactly what was happening, but I seem to have resolved my issue.
