### ISSUE TITLE
list/icon mode folder content view inconsistencies

### ISSUE THREAD

**Issue by ldelaprade** [mate-desktop/caja#1668]
#### Expected behaviour
Open folder content should display in my prefered default mode: list, compact, or icon view

#### Actual behaviour
Each new folder opening resets itseld to the icon view mode

#### Steps to reproduce the behaviour
- have a folder displayed in list view
- double-click a sub folder
- it's back to icon view

#### MATE general version
1.24.0

#### Package version
?

#### Linux Distribution
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

#### Link to bugreport of your Distribution (requirement)
?

**Comment by lukefromdc** [comment]
What is saves is your selected view preference for that particular folder This is more difficult to implement so surely deliberate on the part of the original authors

**Comment by ldelaprade** [comment]
From my perspective as a user, that's not good enough. I should be able to define what's the default mode when none was selected for the just now displayed folder

**Comment by lukefromdc** [comment]
There is the option to change the default for NEW(not previously visited) folders in caja's preferences dialog. This does not change the format for previously visited folders as doing so would erase user preferences set when they were last opened (actually what was in use when they were last closed). For a new user account this default would be applied to all folders.



You can trash your existing user settings and set MATE up as though on a new account by going to your home directory and moving all the hidden ( .something) directories and files to a backup folder, then reconfiguring everything. Open caja once, set the preference in that dialog, then for the window you had open and that should work.

Lastly, note that we are a small team w no paid tech support
