### ISSUE TITLE
Feature request: don't install mate-desktop if you just want caja

### ISSUE THREAD

**Issue by killertofus** [mate-desktop/caja#1671]
if you are are on another distro ie awesomewm

**Comment by lukefromdc** [comment]
mate-desktop is just a library,not the whole DE. Installed size of my locally compiled
.deb package is 4.7MB. The code in mate-desktop is used by several packages but
only has to be maintained once. Also note that if we ever port to GTK4 we could 
move widgets dropped from GTK4 to mate-desktop
