### ISSUE TITLE
Caja File Size Calculation is Incorrect

### ISSUE THREAD

**Issue by ghostplant** [mate-desktop/caja#1683]
For example, the file size in caja file property should be (byte_size / 1024 / 1024) in MB. The current calculation seems to be (byte_size / 1000 / 1000) MB.

**Comment by cwendling** [comment]
1000 units is in line with current standards, e.g. [Wikipedia](https://en.wikipedia.org/wiki/Megabyte).  1024 units use MiB nowadays.

**Comment by ghostplant** [comment]
So, is there a configuration to see/change to MiB? The size doesn't completely align with all other tools and all other platforms since their default standard is to report MiB. This makes me hard to compare 2 file size between 2 platforms / net-disk, etc.

**Comment by cwendling** [comment]
As a matter of fact there is: *Preferences → Display → Size → Show file sizes with IEC units*.

**Comment by ghostplant** [comment]
Great! Thanks you.
