### ISSUE TITLE
Apparently spontaneous crash

### ISSUE THREAD

**Issue by DrReD** [mate-desktop/caja#1685]
I reported an apparently spontaneous crash to fedora, hoping the crash data produced by the ABRT tool could somehow be useful: https://bugzilla.redhat.com/show_bug.cgi?id=2150392

I've been instructed to move the issue upstream, so here I am. :-)

**Comment by lukefromdc** [comment]
If anyone else gets the same crash, the key part of the backtrace seems to be:

```
Thread 1 (Thread 0x7f49a6faef00 (LWP 78232)):
#0  0x00007f49a84fef9d in g_hash_table_fetch_key_or_value (is_big=3, index=3072172, a=0x557a41cf0aa0) at ../glib/ghash.c:394
No locals.
#1  g_hash_table_foreach (hash_table=0x557a419b1120, func=0x557a40049ee0 <get_one_value_callback>, user_data=0x7ffe86e068d0) at ../glib/ghash.c:2094
        node_hash = 357688284
        node_key = <optimized out>
        node_value = <optimized out>
        i = 3072172
        version = 18
        __func__ = "g_hash_table_foreach"
```

I looked at the backtrace of another report of the same or a similar issue,again crash is in glib/ghash.c 
 
https://bugzilla.redhat.com/show_bug.cgi?id=1888948
A mention of dropbox (using caja-dropbox extension?) in that backtrace, and a crash on a "file not found" error:
```
#0  0x00007f444c07d96d in g_hash_table_fetch_key_or_value (is_big=3, index=5037142, a=0x560a0d3b8d50) at ../glib/ghash.c:2061
2061	../glib/ghash.c: No such file or directory.
[Current thread is 1 (Thread 0x7f444ac1af40 (LWP 104797))]
```
Never had this crash myself on Debian Unstable with locally built MATE, GTK3, and glib, but probably different compiler options for everything, different glib version, different GTK3 version/build options etc. 

In one backtrace we have "no locals" at ../glib/ghash.c:394 and in the other we have "file not found" at ./glib/ghash.c:2061

Assuming this does not come from a glib bug (which could be version-specific) we may be passing bad data to it somehow.

Again, I can't duplicate this but if we get more reports of this, hopefully this information will jump-start digging into it for whoever can duplicate it.
