### ISSUE TITLE
Press F2 in empty directory: instant crash

### ISSUE THREAD

**Issue by rudolphi** [mate-desktop/caja#1718]
#### Expected behaviour
Do nothing

#### Actual behaviour
Instant crash

#### Steps to reproduce the behaviour
Open empty directory and press F2 (rename)

#### MATE general version
1.26.0

#### Package version
1.26.0

#### Linux Distribution
5.19.0-41-generic #42~22.04.1-Ubuntu

**Comment by lukefromdc** [comment]
This looks like a duplicate of https://github.com/mate-desktop/caja/issues/1551
which turned out to be an issue with Bulky (a bulk renamer) in LinuxMint.

Are you on LinuxMint or do you otherwise have Bulky installed? If not, maybe another extension is causing a similar problem

**Comment by rudolphi** [comment]
Yes, you are right, it is Linux Mint - I did not know that this is the root cause, thanks very much. I will ask them to resolve the problem.
