### ISSUE TITLE
Update number of directory items in caja when their content is changed outside caja. Feature request

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/caja#1720]
#### Expected behaviour
In both test cases:
The "Size" column value should be updated to "1 item"

#### Actual behaviour
In both test cases:
* ~/randomfile is displayed
* For both the ~/test1/ and the ~/test2/ directory: the "Size" column value is "0 item"

#### Steps to reproduce the behaviour
* Test case 1: mkdir ~/test1/ && touch  ~/randomfile ~/test1/testfile
* Test case 2: In caja create directory ~/test2/. Then run: touch  ~/randomfile ~/test2/testfile

#### MATE general version
ubuntu-mate-core_1.290_amd64.deb

#### Package version
caja_1.26.1-1_amd64.deb

#### Linux Distribution
Ubuntu 22.04, and Ubuntu 23.04

**Comment by davidhedlund** [comment]
Personal note: I also filed this issue for [GNOME Files](https://gitlab.gnome.org/GNOME/nautilus/-/issues/2985)

**Comment by mbkma** [comment]
I think you'll need to edit your issue @GnomeFiles as well :)

**Comment by davidhedlund** [comment]
> I think you'll need to edit your issue @GnomeFiles as well :)

What?

**Comment by lukefromdc** [comment]
Copy of https://github.com/mate-desktop/caja/issues/1719 these should be consolidated into one feature request

**Comment by lukefromdc** [comment]
Thanks, no problem
