### ISSUE TITLE
"Open in Terminal" does not open the selected directory

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/caja#1736]
#### Expected behaviour
* The selected directory in caja should be opened in File -> "Open in Terminal" (in this case ~/.config/, not ~/.config/)

#### Actual behaviour
* ~/.config/caja/ will be opened in the terminal, not ~/.config/
![3](https://github.com/mate-desktop/caja/assets/6416073/240b5e41-8daf-4a30-8fa7-f07791965c34)

#### Steps to reproduce the behaviour
* In caja, open a sub-directory in caja, for example ~/.config/caja
* Go back one directory level, in this case to ~/.config/
* Open File -> "Open in Terminal"

![1](https://github.com/mate-desktop/caja/assets/6416073/84fe3a49-8cee-4b50-b3fe-713678b4f65f)
![2](https://github.com/mate-desktop/caja/assets/6416073/f6826940-29cd-45b8-aa31-5fd159f9f2ce)

#### MATE general version
1.26.0

#### Package version
1.26.0

#### Linux Distribution
Ubuntu MATE 22.04, Ubuntu MATE 23.04, Trisquel 11.

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu/+source/caja/+bug/2030290

**Comment by lukefromdc** [comment]
I was just unable to duplicate this with caja and caja-extensions versions from git master (1.27 at this time). Open in terminal is part of caja-extensions, so this report should be moved there

**Comment by davidhedlund** [comment]
> I was just unable to duplicate this with caja and caja-extensions versions from git master (1.27 at this time). Open in terminal is part of caja-extensions, so this report should be moved there

Can you please help me find the repository where I should file it?

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja-extensions

**Comment by davidhedlund** [comment]
Merged to https://github.com/mate-desktop/caja-extensions/issues/118
