### ISSUE TITLE
Travis-CI Debian build is broken with master

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#1740]
#### Actual behaviour

Travis-CI Debian:testing build is broken with master
https://app.travis-ci.com/github/mate-desktop/caja/jobs/608465207#L26915
```
====================================

   caja 1.27.1: src/test-suite.log

=====================================

# TOTAL: 1

# PASS:  0

# SKIP:  0

# XFAIL: 0

# FAIL:  1

# XPASS: 0

# ERROR: 0

.. contents:: :depth: 2

FAIL: check-caja

================

running caja_self_check_file_utilities

running caja_self_check_file_operations

running caja_self_check_directory

(caja:43086): GLib-GIO-CRITICAL **: 10:35:13.829: GFileInfo created without standard::sort-order

Trace/breakpoint trap (core dumped)

FAIL check-caja (exit status: 133)
```
#### MATE general version

master
#### Package version

> 1.27
#### Linux Distribution
Debian testing

#### Link to bugreport of your Distribution (requirement)
not releasesd

Note: fedora build works fine

**Comment by lukefromdc** [comment]
That set of warnings came in with glib 2.77.1 and may date back to glib2.77.0. I was assuming it was a glib issue but neither Nautilus nor Nemo throw these warnings so there should be one or more commits in their history relevent to this

**Comment by lukefromdc** [comment]
See
https://github.com/mate-desktop/caja/pull/1743
the warnings do not appear in Nemo or Nautilus, fixing this was literally a 3 line fix across two files

**Comment by raveit65** [comment]
https://github.com/mate-desktop/caja/pull/1743 is merged.
