### ISSUE TITLE
Add "Up arrow" for "Open Parent".

### ISSUE THREAD

**Issue by Joe1962** [mate-desktop/caja#1764]
#### Expected behaviour
"Back arrow" and "Up arrow" should both be on the address bar area, with different destinations according to how you got to the current path. This is expected behaviour on most modern file managers, AFAIK.

#### Actual behaviour
There is only a "Back arrow", "Open parent" is hidden on a menu ( although there is a keyboard shortcut).

#### MATE general version
1.26.0-2 from Debian Bookworm, installed on LMDE 6.

#### Package version
Caja 1.26.1

#### Linux Distribution
LMDE 6.

**Comment by lukefromdc** [comment]
That's odd: I've always had the up arrow showing in caja, and I am using Debian Unstable.
Wonder what is different? Not seeing any gsettings preference to turn it off, and caja doesn't have
the toolbar editor.

Try reinstalling all of your caja packages, in case something got corrupted

**Comment by Joe1962** [comment]
> Try reinstalling all of your caja packages, in case something got corrupted

I'll try that tonight. I wonder if installing Mate alongside Cinammon has anything to do with it? I don´t think it should and Nemo has the Up arrow, but who knows? This is my first time really working on Mate, instead of just having a look at it with Mint Mate on a VM.

And like you mentioned, no toolbar editor. Spent some time trying to find it, LOL.

**Comment by Joe1962** [comment]
OK, my bad. In my defense, I am pretty much new to Mate and Caja. I just found the menu option: View/Main toolbar, it was disabled by default on installation of the packages. No idea why this is the default though. Should I close this?

**Comment by lukefromdc** [comment]
I have literally never seen Debian's default setup but hiding toolbars by default is not a good one. I will close this report, you might want to open one at Debian about their default (assuming this was their default and not an install issue).
