### ISSUE TITLE
Four constantly-repeated GLib-GIO-CRITICAL errors noted when launched from terminal

### ISSUE THREAD

**Issue by scott092707** [mate-desktop/caja#1783]
#### Expected behaviour
no errors

#### Actual behaviour
Four constantly repeated instances of:
```
(caja:2261560): GLib-GIO-CRITICAL **: 19:22:20.931: GFileInfo created without standard::sort-order

(caja:2261560): GLib-GIO-CRITICAL **: 19:22:20.931: file
../../../gio/gfileinfo.c: line 2107 (g_file_info_get_sort_order): should not be reached

(caja:2261560): GLib-GIO-CRITICAL **: 19:22:20.931: GFileInfo created without standard::symlink-target

(caja:2261560): GLib-GIO-CRITICAL **: 19:22:20.931: file
../../../gio/gfileinfo.c: line 2061 (g_file_info_get_symlink_target): should not be reached
```
This seemed not to be continuous, but waited for me to do something in Caja
(select?click/drag/...)

#### Steps to reproduce the behaviour
launch caja from terminal:
~$ env GTK_THEME="Ambiance-RW-scott" caja -t ~/ ~/.local ~/.local/bin .local/share/applications ~/Documents/ComputerRelated ~/Documents/ComputerRelated/logs ~/Documents ~/.config ~/.config/sway

#### MATE general version
MATE not being used.
Sway Wayland Compositor 
apt list --installed sway
sway/testing,now 1.9-1+b1 amd64 [installed]

#### Package version
apt list --installed caja
caja/testing,now 1.26.3-1+b1 amd64 [installed]

#### Linux Distribution
Debian Testing

#### Link to bugreport of your Distribution (requirement)
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1074080

**Comment by lukefromdc** [comment]
This has been fixed and the fix cherrypicked to 1.26, but there has not been a new release of caja 1.26 since 1.23 which predates this. We'll have to get that one out the door since the newer glib versions that generate this error are now in wide use

**Comment by lukefromdc** [comment]
Translations are still breaking on every package due to errors on some new languages. I will release a new caja 1.26 version with the old translations, but this is getting to be a problem. I have to figure out what package this is best reported against as it seems to affect all of them.

**Comment by lukefromdc** [comment]
1.26.4 is out with the fix for this
https://pub.mate-desktop.org/releases/1.26/caja-1.26.4.tar.xz
distros can now pick it up

**Comment by lukefromdc** [comment]
Also note that in wayland, using 1.28 is going to allow using icons on the desktop and runs under native wayland rather than xwayland.
