### ISSUE TITLE
use caja_file_info_add_emblem caja_file_info_add_emblem error: segmentation fault

### ISSUE THREAD

**Issue by xlango** [mate-desktop/caja#1791]
```c
#include <caja/libcaja-extension/caja-file-info.h>
#include <gio/gio.h>
#include <glib.h>
#include <glib/gfileutils.h>

void add_image_emblem(const char *file_path, const char *emblem_name) {
    GError *error = NULL;
    g_print("%d %s %s\n",1,file_path,emblem_name);

    //GFile *file = g_file_new_for_path(file_path);
    g_print("%d\n",2);

    CajaFileInfo *file_info = caja_file_info_lookup_for_uri(file_path);
    g_print("%d\n",3);
    //g_object_unref(file); 
    g_print("%d\n",4);
    if (!file_info) {
        g_print("get file info error。\n");
        return;
    }
    g_print("%d\n",5);
    // add emblem
    caja_file_info_add_emblem(file_info, emblem_name);
    g_print("%d\n",6);
    g_print("emblem'%s' add success！\n", emblem_name);

    g_object_unref(file_info);
}

int main(int argc, char *argv[]) {
    if (argc != 3) {
        g_print("use: %s <file_path> <emblem_name>\n", argv[0]);
        return 1;
    }

    add_image_emblem(argv[1], argv[2]);
    return 0;
}
```

I want to use this interface function to add a logo to the specified file, but the compilation runs through an error: segmentation fault.
Could you please point out the reason for my error and provide a demo of the full implementation? thank you

**Comment by lukefromdc** [comment]
I do not have time to analyze this, but if you run caja under GDB (turn it off in session required componemts and run it under GDB in a new session from a terminal) you should be able to find the exact place your code is failing.

Note that right now we are shorthanded. We can keep feature requests open in case someone outside the team wants to code one up (as you are working on) but we have to back burner most of them ourselves right now. That said, testing finished code is relatively easy unless it is a bugfix for something hard to duplicate or a request to support something most of us don't have installed.

**Comment by xlango** [comment]
My purpose is to add a logo to the file and display it in the lower right corner. Is there a corresponding interface or extension example for reference? @lukefromdc @cwendling

**Comment by xlango** [comment]
I want to use a custom image as the logo

**Comment by lukefromdc** [comment]
I cannot help with this at all, as I have never worked on the emblem adding code.
