### ISSUE TITLE
Add support for raw image thumbnails in Caja

### ISSUE THREAD

**Issue by acrobat1** [mate-desktop/caja#192]
Currently raw photographic formats (like Canon .CR2) are not supported in Caja (see issue https://github.com/mate-desktop/caja/issues/21),therefore a generic icon instead of the image preview is displayed:would it be possible to add support for this photographic format?

**Comment by Arkoprovo1996** [comment]
Worked for me ... gnome-raw-thumbnailer + thumbnailer-service
