### ISSUE TITLE
Caja trying to take over my XFCE desktop

### ISSUE THREAD

**Issue by frankzen** [mate-desktop/caja#232]
I run both Mate and XFCE and for the last while Caja is being loaded by XFCE. I have removed caja from all the autostart files, killed it with no restart , logged out and back in and caja restarts, The only way I can prevent caja from starting automatically during the xfce desktop is to move the file caja-autostart out of /usr/bin.

**Comment by wdevany** [comment]
Hi frankzen, i'm using LMDE and have the same issue; i'm too a beginner in the linux world. In my distro that folder doesn't exists... How can i resolve this? I was thinking that this behavior is result of some software we installed... ¡Salute!
