### ISSUE TITLE
Caja Does Not Launch When Using Docky

### ISSUE THREAD

**Issue by NotSoSolidSnake** [mate-desktop/caja#248]
When trying to launch the file manager with Docky it does not launch. Using the Docky trash applet will launch it though.

I haven't tried it with any other dock.

**Comment by lesimoes** [comment]
Follow the steps below (Tested and aproved in Lunx Mint 17.2 with Mate Desktop):
1- Open terminal (Crtl + Alt T)
2- Kill docky - killall docky
3- Open Caja - Caja
4- Right click in any directory and go to "Open with another application" (Or something like that, my distro is portugues)
5- Select Caja application and make sure the option "Remember ..." is marked
6- Restart docky - docky
7- Be Happy! :)

**Comment by cybermaxpower** [comment]
@lesimoes Thank you that really helped +1:

**Comment by arphenius** [comment]
@lesimoes I followed your steps and they also fixed similar problem with cairo-dock

**Comment by BreandanHeiliger** [comment]
I followed the steps and it worked.

However, when I reboot caja no longer launches from docky.
Docky is set to start when I log in.

If I quit docky and then start it again, then caja launches properly.

What can I do?
