### ISSUE TITLE
Side Pane does not show bookmarks

### ISSUE THREAD

**Issue by MartinThoma** [mate-desktop/caja#262]
I've just installed Linux Mint MATE (so I've updated from MATE 1.4 to MATE 1.6.1).
But now the bookmarks are not in the side pane and it seems as if I can't add them any longer :-(

![Alt text](http://i.imgur.com/EehGaCk.png)

Can this please be fixed?

**Comment by miraculixx** [comment]
I have the same issue on Caja 1.8.1, the bookmarks are not shown. There are bookmarks in the Bookmarks menu. This used to work until about 2 days ago when the system froze due to an out of disk space condition. I suspect Caja has some corrupt settings/preferences. How can I reset them?

```
$ inxi -S
(...) Kernel: 3.13.0-24-generic x86_64 (64 bit) Desktop: N/A Distro: Linux Mint 17 Qiana
```

**Comment by NiceandGently** [comment]
Is this issue still exists?

**Comment by MartinThoma** [comment]
I have MATE 1.8.2 and the strange behviour I described in https://github.com/mate-desktop/caja/issues/262#issuecomment-36425435 still exists.

**Comment by NiceandGently** [comment]
@MartinThoma 
but this screenshot shows nautilus and google chrome browser.
There is nothing what we can do.

**Comment by MartinThoma** [comment]
@NiceandGently Sorry, I don't know anything about the development of desktop environments / window managers. I thought MATE would manage how the save as dialogue looks like?

**Comment by NiceandGently** [comment]
@MartinThoma 
no, only mate applications we can adjust.
Nautilus is a gnome application and chrome seems to use zenity for dialog-open, which is also a gnome package.
Sorry, we can't do anything, do you agree with closing this report?

**Comment by MartinThoma** [comment]
@NiceandGently  Sorry that I wrote Nautilus. I wanted to write Caja (I checked it; I do use caja). Does that change anything?

If not, I agree with closing this report, of course.

Do you think there is a way (for the Chrome developers or for me) to fix this?

**Comment by NiceandGently** [comment]
@MartinThoma 
> You can try to ask them why they don't use the normal bookmarks.

**Comment by NiceandGently** [comment]
You can check the bookmarks for zenity (gtk3) here.
~.config//gtk-3.0/bookmarks

**Comment by MartinThoma** [comment]
@NiceandGently Very nice! Thank you very much! This is a very good work-around:

```bash
$ mv ~/.config/gtk-3.0/bookmarks ~/.config/gtk-3.0/bookmarks-backup
$ ln -s ~/.gtk-bookmarks ~/.config/gtk-3.0/bookmarks
```
