### ISSUE TITLE
unmount option for removable devices

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/caja#266]
when my usb flash drive is in, i would like to be given the option to unmount it, when i right click on it. the two options i am given are 'eject' and 'safely remove drive' and dont see why both are there if they do pretty much the same thing (make it impossible for me to remount the partition without unplug the flash and putting it back in).

**Comment by monsta** [comment]
Just like other GTK+ file managers, Caja fully depends on gvfs features in regards to these menu options.
For example, with the latest gvfs you don't even get the "safely remove" option - they ditched it.
There's nothing we can do here, it's upstream issue.
