### ISSUE TITLE
Autostart Caja with extra pane

### ISSUE THREAD

**Issue by Amet13** [mate-desktop/caja#277]
Maybe will be cool if i can autostart caja with extra pane. That's comfortably because i always work with two panels. Now i always press F3 for work with extra pane.

**Comment by Petrouchka** [comment]
It would be better if CAJA keeps the F3 (one or two panels) configuration. Must always press F3 each time we start CAJA. So, we could choose to have one or two panels and to keep it without pressing always F3.

**Comment by joakim-tjernlund** [comment]
I have the same request for our users.

**Comment by lukefromdc** [comment]
Try session saving, see if that brings it back up with two panels or not

**Comment by Rodieche** [comment]
The only way I found was with the next command : 

caja $1 && sleep 0.5 ; xdotool key --clearmodifiers F3

clearly you have to install xdotool

**Comment by Petrouchka** [comment]
This issue has been closed. Is it a duplicated report or is it abandoned ?

**Comment by proxy-m** [comment]
It is not fixed.

Somebody just close it.

**Comment by proxy-m** [comment]
It is not fixed.

Somebody just closed it.

**Comment by proxy-m** [comment]
Still not fixed.

**Comment by lukefromdc** [comment]
We are very shorthanded at this time, we don't have any paid developers whatsoever.
If anyone (including from outside the team) wants to code this up I can test it but I 
don't have time to code it up myself.

**Comment by InfoLibre** [comment]
I'm using Cinnamon since a few years, it's better and more maintained.
