### ISSUE TITLE
Generating lots of thumbnails segfaults Caja

### ISSUE THREAD

**Issue by zoqaeski** [mate-desktop/caja#279]
Browsing to a directory with lots of images (such as `/usr/share/icons/<theme_name>/*`) will cause Caja to segfault. This also occurs in Nemo and Nautilus, so I think it might be a bug upstream or in a dependency. 

**Distribution:** Arch Linux x86_64
**Version:** Caja 1.8.0
##

**Comment by monsta** [comment]
You need to install -dbg packages for every lib listed in the backtrace, and then use ```bt full``` command in gdb to get the proper backtrace. Current backtrace is useless for us.

**Comment by saligrama** [comment]
Nemo has the same problem, 6 out of 6 times. `dmesg` shows:

    [  812.718273] nemo[3244]: segfault at 7fe54075a368 ip 00007fe54aee0a0d sp 00007fe54075a370 error 6 in libfreetype.so.6.12.0[7fe54ae77000+bb000]
    [  838.868087] nemo[3263]: segfault at 7f2d780c1368 ip 00007f2d82e22a0d sp 00007f2d780c1370 error 6 in libfreetype.so.6.12.0[7f2d82db9000+bb000]
    [  858.664222] nemo[3282]: segfault at 7fca98823368 ip 00007fcab0587a0d sp 00007fca98823370 error 6 in libfreetype.so.6.12.0[7fcab051e000+bb000]
    [  895.786504] nemo[3305]: segfault at 7fbd08017368 ip 00007fbd10b3aa0d sp 00007fbd08017370 error 6 in libfreetype.so.6.12.0[7fbd10ad1000+bb000]
    [  971.194831] nemo[3383]: segfault at 7fc49d810368 ip 00007fc4a498ba0d sp 00007fc49d810370 error 6 in libfreetype.so.6.12.0[7fc4a4922000+bb000]
    [  989.362475] nemo[3484]: segfault at 7f8000003368 ip 00007f800778fa0d sp 00007f8000003370 error 6 in libfreetype.so.6.12.0[7f8007726000+bb000]

**Comment by jmssil** [comment]
I think I also get that:

[ 4056.690733] caja[2151]: segfault at 0 ip 00007fd7f455121a sp 00007ffeab32e9e8 error 4 in libc-2.19.so[7fd7f4411000+1bb000]

**Comment by monsta** [comment]
I was never able to reproduce this. I think the problem was in the old version of libfreetype or libcairo back then.
