### ISSUE TITLE
items are not spoken by orca when selecting multiple files/folders in icon view

### ISSUE THREAD

**Issue by am-dxer** [mate-desktop/caja#281]
When moving through items in icon view with the arrow keys, the Orca screen reader speaks the item that has focus for me since the fix posted a while ago. However, when I hold down the control key to select multiple items and try to move around with the arrow keys, Orca doesn't give any feedback about the focused item. Orca should speak the item that has focus as well as whether it is selected or not. This works properly in the list view mode.
##

**Comment by monsta** [comment]
@coffeeking: can you check if it's still relevant please?

**Comment by lukefromdc** [comment]
Reported as resolved by
https://github.com/mate-desktop/caja/pull/724
