### ISSUE TITLE
Copying files as root sometimes causes the desktop to change to a root desktop

### ISSUE THREAD

**Issue by ArcticVanguard** [mate-desktop/caja#284]
I was copying my music collection (ntfs, mounted on /mnt/WinE/) to a new btrfs partition (mounted on /mnt/media/) and I had to copy them as root due to certain permission issues, and at one point during the copy, my desktop locked up. When the system became operable again, the panels at the top and bottom of the screen were gone and my background was different. Then I saw it said "root's home" on the folder and the icons were different. Right clicking and opening a terminal resulted in a root terminal. A few minutes later, the panels came back and still showed me as my main user (not root).

[amelia@artemis ~]$ uname -a
Linux artemis 3.14.1-1-ARCH #1 SMP PREEMPT Mon Apr 14 20:40:47 CEST 2014 x86_64 GNU/Linux
[amelia@artemis ~]$ mate-session --version
mate-session 1.8.1

![rootdesktopbug1](https://cloud.githubusercontent.com/assets/6185965/2757612/26732e12-c986-11e3-8038-a911d075548a.png)
![rootdesktopbug2](https://cloud.githubusercontent.com/assets/6185965/2757611/267309fa-c986-11e3-8029-141b99fcbe64.png)

**Comment by NiceandGently** [comment]
Can you please use 'caja --nodesktop' if you start caja as root?
I' m pretty shure that https://github.com/mate-desktop/caja/commit/23b75dadd35f039a8cd93111528a8a66dde8888e will also fix your issue.
But that isn't released yet in 1.8 branch.
So for the momment please use the --nodesktop option.

**Comment by NiceandGently** [comment]
@monsta 
I guess after https://github.com/mate-desktop/caja/commit/4b0d231fdf8dfd6d299ec07cc933000a610f0a74
this can't happen anymore.

**Comment by monsta** [comment]
Yes, and @flexiondotorg has probably already pushed all the latest 1.10 packages into Arch repos. Closing.
