### ISSUE TITLE
regression: caja shows external drive umounted while it is still in the process of umounting

### ISSUE THREAD

**Issue by morgwai** [mate-desktop/caja#286]
In caja 1.6.2 included in linux mint 16 when I click the small "eject icon" next to a removable drive in the "places" left side pane then caja shows it umounted immediately. However it sometimes happens that it takes few seconds for the system to flush all the caches and if I check the output of `mount` command it still shows the drive as mounted. Physical removal of the drive during this time usually leads to data-loss which happened twice to me already :(
it was working fine in linux mint 15: mouse pointer was in the form of rolling circle indicating ongoing background action and caja was showing drive as mounted until system really finished its job.
##

**Comment by GDGooD** [comment]
Have no such problem a long ago. The last time I was affected by this problem is 2015 year.
For now it actually waits for finishing all writes to disks.

**Comment by lukefromdc** [comment]
Code to hold the device icon in the sidebar and show notifications when unmount/sync was still pending, and a notification that a device was ready to remove  was ported over from Nemo many years ago.

**Comment by lukefromdc** [comment]
I'm seeing in that video that the only instant change is in the displayed directory in the main window pane. The sidebar item delays and then changes to the encrypted volume. Is this happening before the encrypted device is actually safe to eject? Is this happening ONLY with encrypted devices by any chance?
