### ISSUE TITLE
Can't drag'n'drop items from "Edit -> Background And Elements" to the side pane

### ISSUE THREAD

**Issue by monsta** [mate-desktop/caja#297]
You can drag'n'drop items from "Edit -> Background And Elements" to the main Caja window to change the background to either solid color or some pattern.
You can't do the same with Caja's left side pane.

Reproduced in Mint 17 (MATE 1.8) and LMDE (MATE 1.6).

Originally reported at https://bugs.launchpad.net/bugs/1333286.

**Comment by ciaobello** [comment]
It looks really ugly having a light theme (icons) and the side panes color is also light.
My workaround was, to take the dark icons (customize) and change the background color of the Panel (menupanel) , so the icons appear in the menu and in the left pane of caja.
I faced this problem with the ARC theme

**Comment by raveit65** [comment]
create a ~.config/gtk-3.0/gtk.css with
```
/* places, treeview, history, information, emblems and notes */
.caja-side-pane notebook treeview.view,
.caja-side-pane notebook textview.view text,
.caja-side-pane notebook viewport.frame,
.caja-side-pane notebook widget .vertical {
    background-color: shade (@theme_bg_color, 1.08);
}
```
This is an example, replace **shade (@theme_bg_color, 1.08)** with a color you ever want.
Of course this is the syntax for >= gtk+-3.20

**Comment by ciaobello** [comment]
thx
