### ISSUE TITLE
Caja Desktop show "OnlyShowIn=KDE;" icons

### ISSUE THREAD

**Issue by caringi** [mate-desktop/caja#300]
After I installed KDE in my Fedora 20, appeared in my MATE desktop an icon called "Home.desktop" (not the normal MATE Home).

This Home.desktop file has an entry "OnlyShowIn=KDE;"... So it is strange.

I identified that the problem is related with this Home.desktop having an entry called "URL[$e]=$HOME"

Seems that Caja ignores the "OnlyShowIn=KDE;" due the presence of this "URL[$e]"... If I a remove the "[$e]" all works well.

**Comment by NiceandGently** [comment]
Is the problem still exists with caja-1.8.x ? in f20?

**Comment by stefano-k** [comment]
No info from user, closing now. Please reopen if you still have the issue and can paste the content of the file

**Comment by caringi** [comment]
Sorry for the delay in replying... The problem still exists in Mate 1.10.2...

Take a file with the following content as an example...
It's not supposed to be shown (due to OnlyShowIn=KDE;), but it is... The problem is related with a bug parsing "URL[$e]=$HOME" entry.

[Desktop Entry]
Encoding=UTF-8
Name=Home
GenericName=Personal Files
URL[$e]=$HOME
Icon=user-home
Type=Link
OnlyShowIn=KDE;
