### ISSUE TITLE
Caja fatal crashes in KDE

### ISSUE THREAD

**Issue by ssrublev** [mate-desktop/caja#304]
I had some crashes of Caja and realized one of the bugs is reproduced when running Caja from KDE. Here is the Fedora Bugzilla ABRT report of this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1114684 

I was advised by Wolfgang Ulbrich to fill this request here. We talked about better KDE support in Caja. I provided details of crash reproduction at the link above. It seems Caja cannot handle KDE's default "oxygen-gtk" GTK+ appearance scheme and produces a full crash.

I also wonder of other issues of my Fedora Caja installation: 1) why I can't edit Caja toolbar 2) I cannot access any Caja Plugins in Preferences, the tab has no any controls, but "mate-file-manager-extensions" package is installed.

**Comment by NiceandGently** [comment]
any news, please do a decision...i wanna close the fedora report.

**Comment by NiceandGently** [comment]
ping

**Comment by stefano-k** [comment]
https://github.com/mate-desktop/caja/commit/23b75dadd35f039a8cd93111528a8a66dde8888e

**Comment by NiceandGently** [comment]
thanks

**Comment by NiceandGently** [comment]
...it works....no crash inside kde :)

**Comment by stefano-k** [comment]
:)

**Comment by ssrublev** [comment]
Thank you!
