### ISSUE TITLE
Caja 1.8.1 overwrite file to mounted ftp sometimes causes freeze

### ISSUE THREAD

**Issue by giuspen** [mate-desktop/caja#308]
I'm running Mate 1.8.1 in Linux Mint 17.
When I copy a file from my local disk to remote ftp using caja sometimes it happens that I see the "File conflict" dialog completely empty and littler than when it details the conflict, from this moment Caja is death and I cannot even kill the process "caja -n" with "kill -9".
##

**Comment by monsta** [comment]
Does it still happen in more recent versions of Caja?

**Comment by raveit65** [comment]
No answer of reporter!
