### ISSUE TITLE
Caja should have extension for file comparison (similar to nautilus-compare)

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/caja#323]
I use Nautilus with nautilus-compare in ordinary Ubuntu 12.04.
It would be great if MATE will have caja-compare extension for Caja.

**Comment by bperrybap** [comment]
It seems like a bad thing to support extensions in nemo that are also not supported in caja.
To provide a consistent "mint" experience caja and nemo should hava the same extensions particuarly for simple extensions like this.
There was a compare extension in Nautilus2 why not just drag that one over?
The compare extension is invaluable when doing s/w development and using other extensions like rabbitvcs.
In my vew leaving this out is a regression and is effectively degrading caja in favor of nemo.
