### ISSUE TITLE
libcaja-extension has some problems with CajaVFSFile object

### ISSUE THREAD

**Issue by infirit** [mate-desktop/caja#327]
I was trying to port a python extension from Nautilus and ran into some problems. The extension add metadata (exif, mp3 etc) columns to the list-view. The extension is here, https://gist.github.com/infirit/497d589c4dcf44ffe920
- with this extension it spawns infinite cajas
- Some properties seem to be missing on CajaVFSFile

The following shows up in the logs

``` python
** (caja:27359): CRITICAL **: pygobject_register_wrapper: assertion 'PyObject_TypeCheck(self, &PyGObject_Type)' failed
Traceback (most recent call last):
  File "/home/sander/.local/share/caja-python/extensions/bsc-v2.py", line 81, in update_file_info
    file.add_string_attribute('title', '')
AttributeError: '__main__.CajaVFSFile' object has no attribute 'add_string_attribute'
```

And

```
** (caja:27359): CRITICAL **: pygobject_register_wrapper: assertion 'PyObject_TypeCheck(self, &PyGObject_Type)' failed
```
##

**Comment by monsta** [comment]
Well, whatever it was, it's fixed by now. I've successfully loaded this extension and tested artist/track/title columns on some mp3s.
