### ISSUE TITLE
Caja does not handle desktop anymore after switching to Nemo (and back)

### ISSUE THREAD

**Issue by thonixx** [mate-desktop/caja#329]
I have switched over to nemo as desktop handler for drawing desktop. Due to several issues regarding Nemo and desktop handling with Mate I have decided to go back and uninstall nemo to have Caja drawing the desktop. But in Mate 1.8.1 I don't see a gsettings key to get Caja drawing the desktop. Even if I remove Nemo and restart the desktop manager I don't see any icons and I can not interact with the desktop.

So I think there is a bug in Caja which prevents it from drawing the desktop.

**Comment by NiceandGently** [comment]
What is the result of 'gsettings get org.mate.background show-desktop-icons' ?

**Comment by thonixx** [comment]
@NiceandGently I get "true" back.

**Comment by NiceandGently** [comment]
Hmm, what happens if you start caja from a terminal without any option?

**Comment by thonixx** [comment]
Umm, this is strange now. I could force Caja drawing the desktop icons again. I have reinstalled Caja and it now shows the desktop with icons again. I therefore close this bug as it seems to be resolved by now. I only can not explain what the bug was.
