### ISSUE TITLE
Caja didn't show "Open With" dialog when double-clicking file with no default application

### ISSUE THREAD

**Issue by nachanon** [mate-desktop/caja#330]
Normally, when user tried to open a file with no application associated, Caja should ask the user which application to use for opening the file.
But when I really tried to double-click such file, nothing happened.

To reproduce:
- Browse Caja to any writable directory
- Go to File > Create Document > Empty File
- Give it a name `new.bak`
- Double-click on it.

You'll see that there's no "Open With" or similar dialog appeared.
If you right-clicked the file, you'll see that "Open with File Manager" (which does nothing) is an default action.
  
Second action in the right-click menu: "Open with Other Application..." is working as expected.
And I think this should be an default action when user double-clicked a file with no associated application.
  
P.S. On my machine, right-clicking "new.bak" and going to "Properties" will show the file type of "backup file" (application/x-trash).

Screenshots:
- [Right-click menu](https://cloud.githubusercontent.com/assets/5958794/4610928/6649c4e8-52b5-11e4-82e6-9d4f89c42221.png)
- [File properites](https://cloud.githubusercontent.com/assets/5958794/4610934/6e6228c8-52b5-11e4-99a1-90f40392ff21.png)
- [Associated application list](https://cloud.githubusercontent.com/assets/5958794/4610937/72b420ac-52b5-11e4-8018-113aad399934.png)

MATE: MATE 1.8.1 (from Debian Wheezy backports repository)
System: Debian GNU/Linux 7.0 Wheezy i386

**Comment by NiceandGently** [comment]
Is the problem still exists with latest caja-1.8.x ?
If i create a new text file with a unknown file extension, it is always  associate to pluma + i see the 'open with' option in context menu.

**Comment by monsta** [comment]
Closing due to the issue being unreproducible and the lack of feedback.
