### ISSUE TITLE
Caja: Unable to change style of bluebox search

### ISSUE THREAD

**Issue by cyb3rc0de** [mate-desktop/caja#331]
http://forums.mate-desktop.org/viewtopic.php?f=7&t=1456

I am experiencing the same issue. This box is not matching my gtk theme style and I have no idea why. How to fix this?

Any help will be appropriated.

Thanks.

**Comment by NiceandGently** [comment]
This can be set by a theme, for example in BlueMenta theme.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-2.0/apps/caja.rc#L54
and line
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-2.0/apps/caja.rc#L90
All mate themes has this code but not other the ones ;)

**Comment by NiceandGently** [comment]
marked as can be close!

**Comment by NiceandGently** [comment]
Did you test my suggestion?
