### ISSUE TITLE
Seahorse (PGP) Integration in Cata (right cklick menu -> Encrypt files...)

### ISSUE THREAD

**Issue by wandth** [mate-desktop/caja#332]
Hi,

I'm really dissapointed, that there is no Seahorse integration in Caja for encryting files with PGP (as there is for nemo & nautilus). Would it be a big effort to port one of this extensions to Caja as well?

Thx for considering such an extension for Caja!
##

**Comment by ZrN-kAyDqY** [comment]
Yes, that would be a very welcome feature request!

**Comment by ingoha** [comment]
+1

**Comment by w0www** [comment]
+1

**Comment by abickerton** [comment]
+1 In addition, I'd also like to encrypt/sign & decrypt both files and directories from the desktop.

**Comment by Petrouchka** [comment]
https://github.com/darkshram/seahorse-caja/

**Comment by monsta** [comment]
https://github.com/mate-desktop/caja/issues/142
