### ISSUE TITLE
--no-desktop argument not working on version 1.8.2

### ISSUE THREAD

**Issue by nitrofurano** [mate-desktop/caja#335]
i'm using Caja 1.8.2 (from Ubuntu 14.10 repository), and --no-desktop argument is not working - this is quite annoying, because i don't enjoy icons on desktop at all, and i use Caja a lot on window managers like WindowMaker, Fluxbox, JWM, etc.

**Comment by stefano-k** [comment]
it should be fixed with https://github.com/mate-desktop/caja/commit/23b75dadd35f039a8cd93111528a8a66dde8888e

**Comment by sileht** [comment]
Hi,

The proposed fix is unrelated, it fixes the issue when you use XDG_CURRENT_DESKTOP not when we use --no-desktop

Cheers,

**Comment by monsta** [comment]
Well... ```--no-desktop``` works for me in Debian Jessie when I run Caja in gnome-flashback session.
Caja does not manage the desktop, Nautilus does, all good.

**Comment by sileht** [comment]
@monsta:  in your case it works because gnome-flashback set XDG_CURRENT_DESKTOP to 'GNOME', 
but when XDG_CURRENT_DESKTOP is 'MATE', it doesn't works.

**Comment by monsta** [comment]
Well I thought you meant it doesn't work in DEs other than MATE, that's why I wrote about gnome-flashback.
I didn't try running Caja with ```--no-desktop``` in MATE itself.
