### ISSUE TITLE
Caja became unresponsive while copying files from LAN

### ISSUE THREAD

**Issue by tranjeeshan** [mate-desktop/caja#337]
Caja became unresponsive while I was copying files from LAN folder. I had to use xkill to close Caja, Then it wouldn't open again. Just the icon appeared in the MATE panel. 
##

**Comment by flexiondotorg** [comment]
Is this still an issue?

**Comment by HacKurx** [comment]
It's a duplicate:
https://github.com/mate-desktop/caja/issues/380#issuecomment-280464014

**Comment by raveit65** [comment]
Ok other report is newer, closing this one.

**Comment by lukefromdc** [comment]
There's a bit more to this, but it may relate to the other issue: I used to run into this with sshfs, in which if the mounted remote filesystem disappeared without being unmounted, nautilus (or now caja) would could not be restarted and a new session could not even be started until the offending filesystem was forcibly unmounted. It's an old bug
