### ISSUE TITLE
Trash is not aware of files deleted from some partition

### ISSUE THREAD

**Issue by Bachsau** [mate-desktop/caja#34]
This bug still exists in MATE, though I don't know if it's a Caja or GVFS thing...
https://bugs.launchpad.net/ubuntu/+source/gvfs/+bug/676917

**Comment by monsta** [comment]
> Steps to reproduce:
1. create file in a directory which is on a different partition then $HOME
2. gvfs-trash the file (be sure to have write permission on the partitions root directory)
3. gvfs-ls trash:// does not show it

> Btw. list-trash/empty-trash from the trash-cli package lists and empties the trash correctly.

Hmm... this is not Caja's problem then.

**Comment by Bachsau** [comment]
> Hmm... this is not Caja's problem then.

And this is why most free software is crap: No one cares! I reported this bug for GNOME in 2010, for MATE in 2012, and is still not fixed. About 99% of all bugs are never fixed. Whats wrong with you guys?!? If this is not cajas problem, fix it in gvfs, mate-vfs or wherever it is, but fix it.

**Comment by flexiondotorg** [comment]
What's wrong "with us guys" is that we work on MATE in our spare time, as volunteers, for free on Open Source. Which means patches for gvfs, mate-vfs or whatever it is are most welcome.

**Comment by Bachsau** [comment]
I don't know everything about the internal workings of MATE. If anyone can tell me the part I have to search for this bug, I might have a look at the code. I'm pretty sure its not Caja and I don't know where to look for the routines responsible for trash handling.

**Comment by monsta** [comment]
> I'm pretty sure its not Caja

Then why shout at us? :confused: 

Filing a bug about gvfs upstream (at https://bugzilla.gnome.org) might help; gvfs developers might at least explain why it happens.
If you wish to check the code, it's at https://git.gnome.org/browse/gvfs/ (+ mirror at https://github.com/gnome/gvfs).

**Comment by Bachsau** [comment]
> Then why shout at us?
Because I don't know better, but as MATE developers I thought you do. I could even have reported it for Panel. Gvfs ist just another guess. As I said, trash is a common feature. To me it not as clear as to you where it is handled.

**Comment by monsta** [comment]
One more hint about this being a gvfs issue:

>  list-trash/empty-trash from the trash-cli package lists and empties the trash correctly

We use gvfs. We don't develop it and don't know what's going on inside it. Please contact gvfs developers.

Github does not allow moving reports between projects BTW.
