### ISSUE TITLE
drag and drop to bookmarks in side pane does not work

### ISSUE THREAD

**Issue by denispr** [mate-desktop/caja#345]
dragging and dropping files to devices in side pane does work, but not to bookmarked folders.
(caja 1.8.1 on Linux Mint 17)

**Comment by NiceandGently** [comment]
https://github.com/mate-desktop/caja/commit/910b9141ac634a86d8f53fda534e33787a160efb

**Comment by monsta** [comment]
@stefano-k: how do you think, should that commit be ported to 1.8?

**Comment by monsta** [comment]
Cherry-picked to 1.8 branch: https://github.com/mate-desktop/caja/commit/ec0c8f4143d900db6968b5a73a45a08a925b6f06

**Comment by flexiondotorg** [comment]
The https://github.com/mate-desktop/caja/commit/910b9141ac634a86d8f53fda534e33787a160efb has been reverted for the 1.10.1 release because it introduces a usability regression. The MATE team need some time to determine the best solution to this issue.
