### ISSUE TITLE
caja's icon view appears to be inaccessible to orca

### ISSUE THREAD

**Issue by coffeeking** [mate-desktop/caja#356]
in mate 1.8, caja's icon view, which controlls the desktop icons and file manager  icon view exposes the needed information to enable orca to navigate the icons. In latest caja from git, this appears to be broken. I'm not sure how to give more information, other than this. In mate 1.8, orca reports 'desktop frame. Icon view layored pane 0 items.' then will navigate the desktop icons. It reports 'not selected' after each one, which could be a separate issue. But in caja from git, orca reports simply 'desktop frame.' It cannot navigate the icons anymore. Looking in src/file manager/fm-icon-container.c, the proper atk code appears to be there, so orca should be able to focus on the icons, but it can't.

**Comment by monsta** [comment]
Is this the same as https://github.com/mate-desktop/caja/issues/281 or not?

**Comment by sunweaver** [comment]
I just tested this issue on Debian jessie with the patch provided in #281.

NOTE: This issue seems unrelated. The "not-selected" problem [1] is not fixed with the patch in #281.

Mike

[1] http://bugs.debian.org/757851

**Comment by coffeeking** [comment]
just pinging this bug. This has been fixed in mate as of 1.8, but when built with gtk3 this is still broken

**Comment by monsta** [comment]
Either this or https://github.com/mate-desktop/caja/issues/479 should be closed then.

**Comment by coffeeking** [comment]
closing as fixed. The issue for gtk3 remains open though
