### ISSUE TITLE
Difficult to associate a Wine application as a handler or default handler for a file type

### ISSUE THREAD

**Issue by unxed** [mate-desktop/caja#374]
If I install Photoshop in Wine, it offers to automatically associate itself with jpeg files. This doesn't work - double clicking jpegs still opens them with the default viewer. Right clicking them also doesn't even list Photoshop as an option.

If I want to manually add Photoshop, either as the default application or something to Open With, then this too is very difficult; I have to write a script involving winepath and other complicated nonsense.

What we need is some automagical glue code that can list installed Windows applications right alongside the others. This will require generating .desktop files (with their own winepath entries inside) for every Windows application that gets installed which the user might want to open with (I believe Windows has an API for this, since there's a similar listing of applications within Windows).

**Comment by infirit** [comment]
MATE follows the freedesktop.org specs regarding menu entries and file associations. This means it is up to wine to set-up everything according to these specs and MATE will honour it.

I suggest you open a bug report with wine or your distro,
