### ISSUE TITLE
desktop icon size not deterministic

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/caja#375]
Taken from DebianBug#775525 [1]:

> setting the icon size for the desktop mostly doesn't work correctly.
>
> Caja offers seven different settings. They are called 33 % - 400 % in Caja
> (edit>preferences>views>icon view) and smallest, smaller, small, standard,
> large, larger, largest in dconf-editor (org>mate>caja>icon view).
> This way it should be easy to change between icon sizes. But in reality (at
> least in my case) changing those settings (no matter whether using Caja or
> dconf-editor) the outcome is not predictable.
> Changing to a bigger size might give you smaller icons. Setting the standard
> size might show the biggest of all. You just have to try them to get the size
> you want. Just don't expect that setting to 100 % now will give you the same
> size as setting to 100 % in five minutes will.

I tested this on latest Debian jessie and can confirm that.

[1] http://bugs.debian.org/775525

**Comment by infirit** [comment]
Does commit https://github.com/mate-desktop/caja/commit/a823778ec6c091cada6f4473413f220d6732ed7a help?

**Comment by sunweaver** [comment]
@infirit: Yes, that commit fixes the issue. THANKS!
