### ISSUE TITLE
Verbose options?

### ISSUE THREAD

**Issue by mf0hka** [mate-desktop/caja#377]
I use mate, 1.8.2 sometimes, I want to know what caja is doing. Running caja from the command line doesn't tell me much. I don't see a verbose mode in the man pages. Is verbose out put called something else? Is there such an option in caja? Can there become such an option?  Alternatively, is there some sort of logging I should look at to get an idea what caja is doing?

as a specific, caja, features a "connect to sever" option. periodically those connections fail. I want to get more information about those lost connections. where should I look?

**Comment by stefano-k** [comment]
http://wiki.mate-desktop.org/applications:caja#debug

**Comment by ojensen5115** [comment]
For anyone stumbling across this, see here:
https://wiki.mate-desktop.org/#!pages/applications-caja.md#Debug
