### ISSUE TITLE
"Open in New Window" from treeview in sidebar does not work right

### ISSUE THREAD

**Issue by anacon** [mate-desktop/caja#383]
When working with tree view in the left pane, opening the context menu and selecting "Open in New Window" does nothing at all. The function does work on folders in the right pane. Caja 1.8.2 running in Linux Mint 17.1

**Comment by monsta** [comment]
Actually, it does something: it opens the folder in the current active tab. That's not the expected behavior anyway.

**Comment by flexiondotorg** [comment]
@monsta Can you test this PR and report back?

**Comment by monsta** [comment]
Yes, will check it later.

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/caja/commit/3d3d4a2fd72d0403b097fb4d0a38edb68d0d6c83.
