### ISSUE TITLE
Caja sendto extension doesn't work with Evolution email client

### ISSUE THREAD

**Issue by nesfla** [mate-desktop/caja#384]
I'm using linux mint 17.1 MATE and Evolution 3.10.4
I added the caja sendto extension
When right clicking on a file and choosing the send to option, Evolution doesn't open a new message window.
It seems that Evolution is "reached" by the action as it starts twinkling at the bottom of the screen but no real action (a new message window with the file attached) is launched.
At Evolution forum they said this is a Caja issue.

**Comment by monsta** [comment]
Please open the issue in caja-extension repo (if it still happens).
