### ISSUE TITLE
Translation of "Desktop"

### ISSUE THREAD

**Issue by baem2** [mate-desktop/caja#386]
I did a clean new debian jessie install with MATE 1.8.x only in German.

The folder for Desktop is called "Schreibtisch" (so cd ~/Schreibtisch brings me to the Desktop). In former versions (on debian wheezy with MATE from backports) this seemed to be ~/Arbeitsfläche.

What's confusing now: In jessie, caja shows on the left "Arbeitsfläche" as a shortcut, and when you click on it (or on the folder Schreibtisch shown in ~), you end up on the Desktop, while the caja address line showing "/home/myName/Arbeitsfläche". This is especially confusing because I copied over the folder "Arbeitsfläche" from my old install and now the address line showed "/home/myName/Arbeitsfläche", but there were other contents displayed than for ~/Arbeitsfläche, because actually I was in ~/Schreibtisch ...

I hope there's something you can do about it.

**Comment by rezso** [comment]
Try xdg-user-dirs to fix this: http://www.freedesktop.org/wiki/Software/xdg-user-dirs/

**Comment by monsta** [comment]
Translations are done at Transifex - it should be corrected at https://www.transifex.com/mate/MATE/language/de/
