### ISSUE TITLE
Highlight selector doesnt appear in file list

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/caja#389]
In icon and compact view, when a file/folder isnt preselected and you press the tab key to jump through the interface, it wont show a highlight within the folder pane when it reaches there.

**Comment by monsta** [comment]
Does it happen with any theme?

**Comment by raveit65** [comment]
Hmm, do you mean the sidebar with  folder pane?

**Comment by monsta** [comment]
I think he means the main view... since "icon and compact view" are mentioned.

**Comment by raveit65** [comment]
Than i don't understand the issue.
How should a folder/file selected during switch with the tab key, if a 'file/folder isn't pre-selected'?

**Comment by monsta** [comment]
@philipzae: can you post a screenshot for better explanation?

**Comment by philipzae** [comment]
Linux Mint 17.3 Mate
Theme - Controls: Clearlooks-Phenix, Window Border: Spidey, Icons: Mint-X

Steps
1) Open Caja in icon view
2) Notice that a highlight is on the user's home folder in the Places left pane
3) Notice that there isnt a highlight on any of the files or folders in the files right area
4) Press tab repeatedly and notice the focus highlight jump to the main toolbar, location bar, and side pane
5) When focus is in the files area, you wont see the focus highlighter
6) Select the 'Desktop' folder in the files area and notice the highlight color of the icon and folder name
7) Press tab and notice that the highlight color of the icon and folder name have changed to show that the files area isnt in focus and when focus is returned to the area, the highlight color of the icon and folder name has changed back

So without a file or folder being pre-selected in the files area, there isnt any visual feedback that focus is in the files area.

**Comment by raveit65** [comment]
Does the issue exists if you're using  Controls: from Mate, Window Border: from Mate, Icons: from Mate.
If not please file a report against your distro.

**Comment by monsta** [comment]
> 7) Press tab and notice that the highlight color of the icon and folder name have changed to show that the files area isnt in focus and when focus is returned to the area, the highlight color of the icon and folder name has changed back

Works with Clearlooks-Phenix, doesn't with Mint-X.

> So without a file or folder being pre-selected in the files area, there isnt any visual feedback that focus is in the files area.

I see. Most probably it's done so in GTK+.
Do you know any app where pre-selecting in similar view does work?

**Comment by philipzae** [comment]
@raveit65 if you can point me to where i can get the Mate theme from, i'd be happy to test against it, as it isnt available in Ubuntu Mate or Linux Mint Mate. I tested Ubuntu Mate 16.04's Ambiant-MATE and TraditionalOk, and it appears clearly there, which makes me further believe this isnt a theme issue.

@monsta the same problem happens in Files 3.14.3 which ships with Ubuntu 16.04.

Weird that this issue doesnt appear in list view, but happy that it doesnt as that is the view i use. :D

**Comment by raveit65** [comment]
I'm really in doubt that mate-themes isn't installable via package-management in any debian based distro. Our default theme is Menta or BlueMenta.

**Comment by monsta** [comment]
> the same problem happens in Files 3.14.3 which ships with Ubuntu 16.04

Well, I'm not very interested in apps which have the same issue; I'm interested in hearing about apps that **don't** have it. :smile:

**Comment by philipzae** [comment]
@raveit65 Menta and BlueMenta have the same issue and their behaviour is worst than the other themes i've mentioned as there isnt a color difference when the a file or folder is preselected.

@monsta here is one - xfe. i'm assuming dolphin also does.

**Comment by monsta** [comment]
Xfe isn't a GTK+ app, neither is Dolphin.

**Comment by philipzae** [comment]
i'm assuming there are only 3 gtk+ file managers around - nautilus (and its forks), thunar, and pcmanfm - and all have the same issue. if there are any others, i'd be glad to test them.

**Comment by monsta** [comment]
Well, as I suspected, it's most probably just a GTK+ issue (or rather, lack of a feature).
We're unable to do anything with it on our side. Please file a feature request at http://bugzilla.gnome.org (for GTK+ project).

**Comment by philipzae** [comment]
Reported it to them. https://bugzilla.gnome.org/show_bug.cgi?id=768265
