### ISSUE TITLE
caja automounts USB flash drives and CD/DVD drives while session is locked

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/caja#398]
This issue reflects what has been reported to DebianBug#781608 [1].

Quoting DebBug#781608:

"""
To avoid auto-run drive-by attacks by a physically proximate attacker on
the system from USB auto-mounting screen is locked, the desktop should
delay automounting until the screen is unlocked (to not interfere with
the case of sitting back down at your system, plugging in a device,
and then unlocking your screen).

This is similar to how gnome-keyring flushes all keys the when locking
the screen.

http://www.net-security.org/secworld.php?id=10544

This was fixed in Gnome upstream and in Ubuntu:

https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/714958
https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/724285

The attached patch likely needs the dbus names changed to, e.g.,
"org.mate.ScreenSaver".

Thanks!

-Kees
"""

A patch has been provided in Debian/Ubuntu for Nautilus. I personally think this issue is worth assigning a CVE.

A side-effect of this is:

  o login as user A
  o insert a movie DVD
  o change user to user B
  o try to play that DVD

What you will experience is ons and offs when accessing the DVD, because both session (of user A and user B) try to access that DVD medium. The DVD drive motor will go on and off, it is merely impossible to eject that DVD medium, etc.

The Debian bug ships a patch from nautilus. I took a look at it, but it seems that it interferes with Caja's module concept and must be rewritten. I'd be happy if someone from upstream could pick up this task soon.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781608

**Comment by sunweaver** [comment]
@stefano-k, @monsta: I have just requested a CVE ID for this issue as recommended by Moritz Mühlenhoff from the Debian Security team.

**Comment by monsta** [comment]
I see the second part ("side effect") is already mentioned in https://github.com/mate-desktop/caja/issues/362...

**Comment by thassan** [comment]
perfect.. this was annoying as well
