### ISSUE TITLE
Can't join a hidden file to a mail, CAJA doesn't show hidden files

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/caja#399]
I write a new mail and I want to join a hidden file (the file is beginning with a dot).

The CAJA window that opens shows only normal files, not hidden files that begin with a .
So, I can't join a hidden file to my mail.

The window should show all files, including hidden files.

https://bugzilla.mozilla.org/show_bug.cgi?id=1151096

**Comment by stefano-k** [comment]
If you are writing a mail, it is not a caja window, but a window of the mail client or gtk.

**Comment by Petrouchka** [comment]
It isn't a window of the mail client, please read https://bugzilla.mozilla.org/show_bug.cgi?id=1151096

**Comment by stefano-k** [comment]
Not caja, but from gtk.

**Comment by Petrouchka** [comment]
Then, where can I make a bug report ?
