### ISSUE TITLE
[Bug] Search from hotkey opens search without the search field visible. 

### ISSUE THREAD

**Issue by nicekiwi** [mate-desktop/caja#404]
Using Ctrl+F to open Search from the desktop (when Caja is not in focus), the search window opens but the search input itself is not shown. 

![Imgur](http://i.imgur.com/qJHltht.png)

Pressing Ctrl+F again with the window in focus will show the input.

**Comment by monsta** [comment]
This is not reproducible in Caja 1.8.2 in LMDE 2 Betsy.
Which Caja version and which distro do you have?

**Comment by monsta** [comment]
Closing due to the issue being unreproducible and the lack of feedback.
