### ISSUE TITLE
caja in compact view, screws focus with long name files 

### ISSUE THREAD

**Issue by freed00m** [mate-desktop/caja#406]
Demo: http://youtu.be/lUqo938Zjgg

Minor annoyance, hope it'll be fixed someday.

**Comment by monsta** [comment]
I've found an old [Nautilus bug report](https://bugzilla.gnome.org/show_bug.cgi?id=585511) about this issue (which we obviously inherited from it).
Unfortunately, gnome devs fixed the issue in their usual fashion - they've (removed)[https://bugzilla.gnome.org/show_bug.cgi?id=676842] the compact view from Nautilus completely. No feature - no bug. So we'll have to find our own way to fix the problem.

**Comment by freed00m** [comment]
@monsta - wow they really did so :O 

Is there any way I can contribute more? Only thing I can do now is report and test bugs.

**Comment by monsta** [comment]
That's good already :)
Of course we accept bugfixes via PRs as well.
