### ISSUE TITLE
Feature request: ACLs

### ISSUE THREAD

**Issue by ge79so** [mate-desktop/caja#408]
Please could you support ACLs in the permissions tab, if configured?

**Comment by fingus** [comment]
would be very great! a tool for that would be eiciel (http://rofi.roger-ferrer.org/eiciel/) like this:
![Example from webpage](http://rofi.roger-ferrer.org/eiciel/gfx/shots/principal-0.9.png)

**Comment by monsta** [comment]
Duplicate of as https://github.com/mate-desktop/caja/issues/241, see also https://github.com/mate-desktop/caja/issues/511 for a patch for that eiciel tool.
