### ISSUE TITLE
build deb error

### ISSUE THREAD

**Issue by cpatrick08** [mate-desktop/caja#411]
Here is the error I get when I go to make the .deb of caja with GTK 3 support enabled. I can provide the whole log file if needed.

dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libmate-desktop-2.so.17 (used by debian/caja/usr/bin/caja-autorun-software)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/caja.substvars debian/caja/usr/bin/caja-file-management-properties debian/caja/usr/bin/caja-connect-server debian/caja/usr/bin/caja-autorun-software debian/caja/usr/bin/caja debian/caja/usr/lib/caja/caja-convert-metadata returned exit code 2
debian/rules:6: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

**Comment by monsta** [comment]
> with GTK 3 support enabled

You need to build the whole MATE with GTK+3, not only Caja...

**Comment by cpatrick08** [comment]
That's what I did I ran ./setgtk.py --all --gtk3     before I compiled the first package

**Comment by monsta** [comment]
And you'll need to build the whole MATE with GTK+3 from scratch, with no GTK+2 packages involved.

**Comment by cpatrick08** [comment]
I've switched to Arch Linux so you can close this issue 

Sent from Yahoo Mail on Android

**Comment by monsta** [comment]
I don't have the rights to close it - but you (as the reporter) can close it yourself :)
