### ISSUE TITLE
Feature request: map xattrs to emblems and back

### ISSUE THREAD

**Issue by pjump** [mate-desktop/caja#417]
Hi, I'm reposting here from http://forums.mate-desktop.org/viewtopic.php?f=16&t=3576

I think emblems are a great feature, but they have shortcomings mostly arising from the fact that they're only relatively loosely associated with files.
Moving files outside of caja (`mv`) and copying to a different machine are all incompatible with emblems.
Extended attributes solve this.

I think it would be great if extended attributes could show up as emblems.
Below is a simple patch for caja-1.8.1 that takes an xattr of the form `user.caja.*` and maps it to an emblem named '*' (e.g., a file with user.caja.default will get the green check mark emblem (which is named "default")).

https://github.com/pjump/caja/tree/xemblems

If anyone likes this, I'd love to polish it up, but I'm having some issues even manually testing custom builds (or even the vanilla version) on my system:

http://forums.mate-desktop.org/viewtopic.php?f=7&t=3446&p=10698#p10698
I would appreciate some help on how to fix those.

**Comment by PacmanTetris** [comment]
Why was it closed? Has this feature been implemented?
