### ISSUE TITLE
Interface for writing extensions

### ISSUE THREAD

**Issue by fekir** [mate-desktop/caja#418]
There is no interface for writing an extension in native languages, like C or C++.

If there is an interface, please provide some documentation.

I have only been able to write shell extensions (bash scripts) after finding some old nautilus example... but I would love to extend caja using c++.

Some examples of very useful extensions are cvs support, comparing files/folders using right click (like beyond compare on windows), and other tools that are available while clicking on a particular file type.

**Comment by giuspen** [comment]
You can easily write python extensions, take a look at
http://www.giuspen.com/nautilus-pyextensions/ I already wrote some you may
find useful or use as examples.

**Comment by fingus** [comment]
Thanks for this information. By the Way cherrytree is one of the most important information for me. Thanks a lot for them!

**Comment by fekir** [comment]
Thank you very much.

I assume that there is no C interface for creating extensions in some other language (since all or most of the languages are able to communicate with C functions), right?

**Comment by giuspen** [comment]
You can write extensions in C, I never made it because it requires much more effort than doing it in python, but you can start watching the existing ones on https://github.com/mate-desktop/caja-extensions
