### ISSUE TITLE
Use Compact Arrangement in Settings Views Symbols is gone after relog or restart

### ISSUE THREAD

**Issue by tspeicher** [mate-desktop/caja#420]
Choose Settings -> Views -> Symbol-View -> Compact Arrangement
-> First time, it works
-> relog or restart
-> Function is gone, no compact arrangement
-> Open Settings again -> Compact Arrangement is still selected, but does not work
-> deselect and select again and it works again

I'm using Ubuntu Mate with Virtual Box, if that makes a difference maybe.

![ubuntumate01](https://cloud.githubusercontent.com/assets/1235826/7857324/db96ea5a-052f-11e5-90ef-c087e3d4debe.jpg)
![ubuntumate02](https://cloud.githubusercontent.com/assets/1235826/7857327/db99f1d2-052f-11e5-83fe-e09dd94a36f9.jpg)
![ubuntumate03](https://cloud.githubusercontent.com/assets/1235826/7857326/db97c538-052f-11e5-8be1-f608679239cc.jpg)
![ubuntumate04](https://cloud.githubusercontent.com/assets/1235826/7857325/db97b9a8-052f-11e5-8749-6dd67cb1c83c.jpg)
##

**Comment by flexiondotorg** [comment]
This is fixed. I've just tested in Ubuntu MATE 17.04 and Ubuntu MATE 16.04 with MATE 1.16. The "Use compact layout" persists between sessions.
