### ISSUE TITLE
port nautilus-seafile to caja

### ISSUE THREAD

**Issue by bertvandepoel** [mate-desktop/caja#427]
I would be really nice if, just like nautilus-dropbox, nautilus-seafile was ported to caja. I tried to convince them on https://github.com/haiwen/seafile-client/pull/575 but they considered it not their task.

Seafile is a fully open source alternative to dropbox that can be easily self-hosted.

**Comment by monsta** [comment]
Please reopen the request at caja-extensions repo (github currently doesn't allow transfering bug reports between repos).
