### ISSUE TITLE
GTK3: unwanted unmounts for devices in sidebar

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#432]
Clicking on a mounted device for selecting it, causes unmounts.
A little video which shows the issue.
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/caja-unwanted-unmounts.ogv
Note, this happens not every time, a serious trigger is first to click in iconview.

**Comment by monsta** [comment]
Looks like you've fixed it in https://github.com/mate-desktop/caja/commit/d14fef384a435471860130f7337d5dea5bb824a0? :smile:

**Comment by raveit65** [comment]
Opps, thx for reminder :)
