### ISSUE TITLE
Notes tab in file properties dialog is missing in 1.10

### ISSUE THREAD

**Issue by DavidParkin** [mate-desktop/caja#433]
Is it my imagination or did caja previously have a note tab for each file and if so what happened to it?

**Comment by stefano-k** [comment]
Maybe it was a plugin?

**Comment by DavidParkin** [comment]
It was part of Nautilus but was removed from that, one of the reasons for moving to caja. I've recently "upgraded" to Fedora 22 and just today tried to create a note, I will check the plugins again. Meantime if someone knows where the code is I may well create a plugin if I don't find one. Must do more testing next time.

**Comment by monsta** [comment]
I have the notes tab in my Caja 1.8 in Debian Jessie.

**Comment by monsta** [comment]
Whoops, checked Caja 1.10 in Debian Testing - no notes tab. Dammit :smile:

**Comment by DavidParkin** [comment]
Just to confirm. I found fedora 21 and that had notes caja-1.8.2-1. Notes is part of the package, not a plugin.

**Comment by DavidParkin** [comment]
Would I be right in assuming that Notes has been removed because Nautilus has removed it, and Caja is staying close? If that's the case I have a plugin that is basically the old code repackaged. Please advise.

**Comment by monsta** [comment]
Caja is not "staying close" to any removal of features that people are using.

**Comment by infirit** [comment]
```src/caja-property-browser.c``` has not seen any changes so it must be caused by something else.

**Comment by DavidParkin** [comment]
caja-property-browser.c? caja-notes-viewer.c was the relevant source.

**Comment by stefano-k** [comment]
@monsta maybe a regression due to the new ability to enable/disable plugins at runtime?

**Comment by monsta** [comment]
I don't know, I didn't write that plugin system :smile:

**Comment by monsta** [comment]
Ok, ```git bisect``` showed me that the notes tab vanished after https://github.com/mate-desktop/caja/commit/451eef9b275ce006b270a3569d96e531e24dd15a...

@alexandervdm: can you please take a look at this? I can't figure out what exactly in your commit made the notes tab go away.
