### ISSUE TITLE
authentication dialog not getting focus

### ISSUE THREAD

**Issue by splace** [mate-desktop/caja#435]
after starting up caja, the first time the authentication dialog appears, the focus isn't being put in the password entry text box, no cursor, several times i have typed passwords in the open so not good.
100% repeatable.
Caja 1.8.2

**Comment by monsta** [comment]
Need some more info. What are you trying to do to make that dialog appear (e.g. open folder as root or something else)?

**Comment by splace** [comment]
happens when mounting a drive.

**Comment by splace** [comment]
just tested, no problem with it opening a folder as root.
and
if you open a folder as root, then mount a device, that also works, as it does with a second device authentication.

**Comment by monsta** [comment]
> happens when mounting a drive

Ah, that's pkexec, so this bug is known to us: https://github.com/mate-desktop/marco/issues/117.
