### ISSUE TITLE
trash can't delete directories correctly

### ISSUE THREAD

**Issue by ciddu2000** [mate-desktop/caja#440]
the function delete files from trash doesn t work properly, it hangs up when deleting directories apparently and the progress bar doesn t work.

Edit : i'm using mate 1.10 on Linux Mint 17.2 “Rafaela”

**Comment by monsta** [comment]
Never been able to reproduce this in Mint. Does it still happen with MATE 1.12 in Mint 17.3?

**Comment by ciddu2000** [comment]
It happens with a usb key here's how to reproduce the matter : 

- plug a usb key 

- copy a folder in the usb key 

- right click the folder in the usb directory and click on move to trash 

- unplug the usb key 

now you will see that the trash icon is the one which means the trash contain an item, but when you open it there will be no item at all inside. 

----- Mail original -----

De: "monsta" <notifications@github.com> 
À: "mate-desktop/caja" <caja@noreply.github.com> 
Cc: "ciddu2000" <gauthier.bruyere@laposte.net> 
Envoyé: Vendredi 25 Mars 2016 12:43:37 
Objet: Re: [caja] trash can't delete directories correctly (#440) 



Never been able to reproduce this in Mint. Does it still happen with MATE 1.12 in Mint 17.3?

**Comment by ciddu2000** [comment]
and another bug with the usb keys about the usb key icon on the desktop, here's how to reproduce it : 

- plug a usb key 

- unplug the usb key 

- right click to show the desktop menu, click on organize desktop by name 

- plug the usb key again 

you will see that the usb key icon appears above the icon of another item. 
----- Mail original -----

De: "monsta" <notifications@github.com> 
À: "mate-desktop/caja" <caja@noreply.github.com> 
Cc: "ciddu2000" <gauthier.bruyere@laposte.net> 
Envoyé: Vendredi 25 Mars 2016 12:43:37 
Objet: Re: [caja] trash can't delete directories correctly (#440) 



Never been able to reproduce this in Mint. Does it still happen with MATE 1.12 in Mint 17.3?

**Comment by monsta** [comment]
I don't get it... I see two issues described here instead of one:

1. the function delete files from trash doesn t work properly, it hangs up when deleting directories apparently and the progress bar doesn t work.

2. now you will see that the trash icon is the one which means the trash contain an item, but when you open it there will be no item at all inside.

**Comment by ciddu2000** [comment]
I have opened two new issues to describe the problems i encountered. So i closed #440. 

----- Mail original -----

De: "monsta" <notifications@github.com> 
À: "mate-desktop/caja" <caja@noreply.github.com> 
Cc: "ciddu2000" <gauthier.bruyere@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 13 Mai 2016 12:21:47 
Objet: Re: [mate-desktop/caja] trash can't delete directories correctly (#440) 



I don't get it... I see two issues described here instead of one: 

    1. 

the function delete files from trash doesn t work properly, it hangs up when deleting directories apparently and the progress bar doesn t work. 
    2. 

now you will see that the trash icon is the one which means the trash contain an item, but when you open it there will be no item at all inside.
