### ISSUE TITLE
A bug with the window Caja (the window confirmation to delete a file)

### ISSUE THREAD

**Issue by CoolAller** [mate-desktop/caja#443]
I discovered a bug with the window Caja. This bug with "window files deleting" appears when you want to delete a file pressing: Shift+Delete and if you click on "Minimize", this window can not be returned back to Desktop and file manager Caja locked. 
Another bug when using two monitors, this window (the window confirmation to delete a file) does not appear on the primary monitor, Instead it appears on the other monitor (if you assign the main monitor on the right). Also, the windows of many programs do not appear in the middle of the screen, Instead, they appear at the end of the screen (If you are using two monitors).

Sorry for my english, I hope I'm clearly described the problem.

**Comment by monsta** [comment]
> This bug with "window files deleting" appears when you want to delete a file pressing: Shift+Delete and if you click on "Minimize", this window can not be returned back to Desktop and file manager Caja locked. 

That dialog doesn't have a button for minimizing. If you still manage to do that via window menu, you can always bring it back by minimizing & restoring Caja's main window.

**Comment by CoolAller** [comment]
You are wrong. That dialog does have a button for minimizing. This option (the arrow) is on the left, where you can select minimize. After that this window can not be returned back in any way to Desktop and file manager Caja locked.

**Comment by monsta** [comment]
Yes, that's the window menu I mentioned. As I said, I've tried that option and still was able to use Caja and bring the dialog back as well. No lockups.

I've tested it in Debian Testing with MATE 1.10. What's your distro and MATE version?

**Comment by CoolAller** [comment]
Debian Jessie Mate 1.8

**Comment by monsta** [comment]
Try minimizing Caja then restoring it back, the dialog should reappear.

**Comment by CoolAller** [comment]
You are wrong to do, create any file on the desktop, then try to remove it by clicking pressing: Shift+Delete, then click minimize.

**Comment by monsta** [comment]
You could say it right from the beginning that it should be tried on desktop instead of Caja window :smile:

Yes, this time it worked: the desktop became non-functional as the minimized dialog still blocks all input.

**Comment by CoolAller** [comment]
I'm sorry that I could not explain immediately.

**Comment by CoolAller** [comment]
What about another bug when using two monitors?

**Comment by monsta** [comment]
It's a separate bug so please file a separate report.

**Comment by NiceandGently** [comment]
> Yes, this time it worked: the desktop became non-functional as the minimized dialog still blocks all input.

Damed, why i do not carfully read all before i test it :-/

**Comment by monsta** [comment]
:laughing:
