### ISSUE TITLE
Caja keyboard arrow navigation

### ISSUE THREAD

**Issue by dallmannji** [mate-desktop/caja#452]
I am using Caja in Debian 8.1 MATE desktop and would like to request
if the directory tree can be collapsed when a subfolder is highlihted using
the keyboard left arrow. 

This aids in making browsing extensive directory hierarchy's easier without
using the mouse.

**Comment by monsta** [comment]
I presume you mean the tree in the left side pane, not the list view mode of the main window?

**Comment by dallmannji** [comment]
I was using it in list view in the right pane where I expand a directory,
sub directry etc. What
would be great is if you can collapse it by just using the left arrow,
probably by jumping
back to the folder root until you reach the top level again.


On Mon, Aug 24, 2015 at 1:35 PM, monsta <notifications@github.com> wrote:

> I presume you mean the tree in the left side pane, not the list view mode
> of the main window?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mate-desktop/caja/issues/452#issuecomment-134162058>.
>



-- 
Kind Regards

Jason Dallmann

**Comment by monsta** [comment]
Ah, I see. No problem - implemented in https://github.com/mate-desktop/caja/commit/a050471613f5b7092bce1c0ae87026e91c8e23b4.

You'll need to file a bug report on Debian bug tracker to get this patch into Jessie.
