### ISSUE TITLE
Copying files in a Virtualbox shared folder

### ISSUE THREAD

**Issue by ZrN-kAyDqY** [mate-desktop/caja#453]
This issue of file corruption is brought up a few times in the Virtualbox forums but no resolution so am really not sure it is a VB 5.0 issue.  

Ubuntu MATE 15.04 host (Caja 1.8.2)
Ubuntu MATE 15.10 guest. (Caja 1.10.3)
VB Shared folder, auto mounted on the guest.  

Here is a test case:
1) Create a text file on the host called test.txt.  Use Linux/Unix line endings.  Contents are the 26 letters of the English alphabet followed by a carriage return (in hex 0A 0A).  
2) Open test.txt on the guest to verify.  
3) From the host, add a second line to test.txt, containing the 26 letters of the English alphabet followed by a carriage return (in hex 0A 0A).  Save the file.
4) From the guest, copy/paste the file test.txt
    Call it "test (copy).txt".
5) Review results in a hex editor.  27 null bytes are written in place of the letters and line feed.  See attached image.
6) Remove the second line from test.txt on the host.  Save the file.
7) Make another copy of test.txt on the guest.  This copy is okay.
![screenshot-1](https://cloud.githubusercontent.com/assets/7233894/9444376/4b0c12b6-4a54-11e5-9e98-96b76537ad37.png)

I see that it happens with Windows host/Linux guest.
https://bugs.launchpad.net/ubuntu-mate/+bug/1487042
##

**Comment by monsta** [comment]
Can you still reproduce it? I wasn't able to.

**Comment by lukefromdc** [comment]
Can't test this, all my work is on bare metal

**Comment by monsta** [comment]
I would like the reporter to check this, as this bug is old, and we don't support the mentioned versions anymore. Chances are it's fixed by now.

**Comment by monsta** [comment]
Well, no reply from the reporter. We can reopen it if the problem happens again.
