### ISSUE TITLE
TXT file "executable" on NTFS partition

### ISSUE THREAD

**Issue by Smile4ever** [mate-desktop/caja#456]
If I double click a TXT file in Caja that is stored on an NTFS partition, this file is seen as "executable" (and a window pops up, asking to do with it, similar to .sh files). However, TXT files can never be executable, they're just plain text. Please fix this.

**Comment by infirit** [comment]
>However, TXT files can never be executable

What do you think shell (.sh) scripts are? Any file can have the executable bit set with ``chmod +x``. Remove the executable bit and you will not get the options.

**Comment by Smile4ever** [comment]
Its set automatically with NTFS partitions. The owner is set to root for all files on the NTFS partition while I created the file as normal user. sudo chmod -x file.txt does not work.

**Comment by infirit** [comment]
>Its set automatically with NTFS partitions

No it isn't. It is controlled by the umask mount option. Use your favourite search engine on how to control the executable bit on ntfs mounts.

There is an option in caja's preferences to control the default behaviour so you may want to look at that.

**Comment by Smile4ever** [comment]
Thank you.
