### ISSUE TITLE
Add option to have caja not manage the desktop

### ISSUE THREAD

**Issue by LexMK** [mate-desktop/caja#460]
Caja should have an option to have it not manage the desktop, in case you want something else (like Nitrogen, in my case) to manage it.

**Comment by flexiondotorg** [comment]
Caja has the following option.

    --no-desktop                    Do not manage the desktop (ignore the preference set in the preferences dialogue).

**Comment by LexMK** [comment]
I know about that. I was suggesting to add that option in the preferences window.
