### ISSUE TITLE
After trashing file, pressing Ctrl-z too fast won't return it back

### ISSUE THREAD

**Issue by Qazjap11** [mate-desktop/caja#461]
Hi,

Accidentally was posted as a continuation of a different bug: https://github.com/mate-desktop/caja/issues/361

 Summary:
After deleting a file or folder, if I press ctrl-z too fast (less than approx. 1 second) it won't return the file back, and pressing again won't return it. On the other hand, if I wait more than 1 second, ctrl-z does work.

A bit of debugging showed that g_file_enumerate_children() in the function retrieve_files_to_restore() doesn't return the recently deleted file if too little time passed.

I'm using debian sid, caja 1.10.3-2, libglib2.0 2.44.1-1.1

**Comment by monsta** [comment]
Does that still happen with the latest glib and gvfs in Sid?

**Comment by Qazjap11** [comment]
No, it doesn't happen anymore...
glib2 2.46.1-1
caja 1.10.4-1
gvfs 1.26.1.1-1

**Comment by monsta** [comment]
Ok, looks like it was solved in either glib or gvfs.
