### ISSUE TITLE
Run application with argument when drop other icon into executable binary or script

### ISSUE THREAD

**Issue by zaps166** [mate-desktop/caja#462]
Example:
- go to "/usr/bin",
- scroll down to "pluma" binary,
- drag any text file from desktop or other Caja window on "pluma" binary,
- Pluma opens the file.
  Actual results:
- the file is moved into directory.
##

**Comment by flexiondotorg** [comment]
This is not how drag and drop works. You have to drag to a `.desktop` file. For example, drag an picture to `/usr/share/applications/` and drop on the "Eye of MATE Image Viewer".
