### ISSUE TITLE
Lost emblems

### ISSUE THREAD

**Issue by maandree** [mate-desktop/caja#464]
Today I noticed that all my emblems on files and directories have disappeared.
This there any way to recover them, even if I have to do it manually (where/how are they stored?)
##

**Comment by raveit65** [comment]
What did you do with your installation ;)
The emblems are from icon themes, ie.
/usr/share/icons/mate/size/emblems
Does your icon theme ship this emblemes?

**Comment by maandree** [comment]
I didn't mean that the emblems icons have disappear from the filesystem, they are still there
and looks exactly like they did before.
But all files and directories have suddenly lost all emblems have I added to them.

However, I do recall that after an update, the icon theme changed, and I hade to change it back.
Could the emblems have been reset at that time?

**Comment by raveit65** [comment]
Hard to say, normaly if you change the icon theme caja use the emplems from the new icon theme.
Personal i do not use emblems, i will let you know if i know where caja store this.
....somewhere in the home directory.
You can try to reproduce this with a fresh account.

**Comment by maandree** [comment]
It appears that emblems cannot even be set. When selected, nothing happens, and the next time the property window is opened for a file, the emblem selections have disappeared.

This is reproducable:
1) Create a new user.
2) Login to the new user and start X.
3) Open Caja.
4) Try to add an emblem to a file (for example that Desktop directroy that was created for no appearent reason.)

**Comment by raveit65** [comment]
Which distro are you using?
Did you file out a report at your distro to check if isn't distro related?

**Comment by maandree** [comment]
Arch Linux.
I have not reported to the distro, I will.

**Comment by maandree** [comment]
The distro has closed the bug report without resolving it.

**Comment by maandree** [comment]
This issue now as been resolved.
