### ISSUE TITLE
Caja closes when the last window closes.

### ISSUE THREAD

**Issue by maandree** [mate-desktop/caja#467]
Please add an option to revert to the old behaviour: Caja stays alive until it is manually killed,
not until the last window closes.

**Comment by monsta** [comment]
That behavior is still there. Of course, that's if you use Caja in MATE and not as root. :smile:

**Comment by maandree** [comment]
But I don't want to use MATE.

**Comment by maandree** [comment]
I guess it is due time to try get MATE 1.4 running.

**Comment by raveit65** [comment]
why not gnome-2

**Comment by maandree** [comment]
Because MATE 1.4 was better. MATE 1.4 was the best release of desktop environment yet.
