### ISSUE TITLE
caja uses 100% CPU

### ISSUE THREAD

**Issue by ghost** [mate-desktop/caja#47]
I am using Linux Mint 14 RC. After keeps using 100% CPU (actually, 101.6% according to top on a multicore machine).

In addition, this slows down browsing through directories using caja.

When all caja instances are closed, it still keeps using so much CPU.

Sometimes, killing the last caja process helps; sometimes, it just spawns another one (with no visible window open).

**Comment by sirahngelu** [comment]
I had this problem too recently
So I'm so confused why this bug still happen on my system.
(I'm using void linux)
So I trace this caja activity and I found its crawling on my void-packages folder
 (I got that from:
git clone git@github.com:yourusername/void-packages.git )
And it is huge number of files.

After I removed it all, caja is back to normal.
So for voidlinux user, if you want to build packages, use special user (do not use your main user)

Thank you.

**Comment by AhnMo** [comment]
I found same issue at my desktop.
I figure it out cpu fan is work fully, and just one process take 100% cpu resource. 
/usr/bin/caja and working directory is just my home directory. 
Anyway I kill the process.
'MATE Desktop Environment 1.12.1' is my Desktop env and ubutnu 16.04.4.
