### ISSUE TITLE
Add to Bookmarks not visible in right click

### ISSUE THREAD

**Issue by scifibob** [mate-desktop/caja#471]
I have used plenty of bookmarks in Caja earlier, but after a new OS installation, the bookmarks bar is not visible by default, so I',m unable to drag anything to it.
The only way to add something to bookmarks is to select it and select Bookmark on the menu and add it.
Then I can drag anything there.
I'm missing an option "Add to bookmarks" on the right click menu in Caja, and also the possibility to drag something to the bookmarks bar before it "exists".
Please show the bar on the left even if it's empty, so we can drag things to it.
##

**Comment by raveit65** [comment]
distro?
caja version?

**Comment by raveit65** [comment]
Did you filed out a report in your distro bug reporting system, to be shure the issue isn't distro related?

**Comment by raveit65** [comment]
Please answer to questions, otherwise i will close the report.
Btw. i can't reproduce the issue here with fedora 22/23

**Comment by monsta** [comment]
In Caja 1.12 it's possible to drag a folder to the left pane even when Bookmarks section is empty (and not shown). So it's not an issue anymore.
As for the mentioned item in the right-click menu... did it ever existed in any version of Caja?
