### ISSUE TITLE
places-sidebar (gtk3 only): media sometimes ejected on selection

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/caja#472]
In caja compiled with gtk3, clicking on a mounted volume in the places sidebar will sometime cause it to be ejected instead. Similarly, some clicks on the eject icon sometimes cause the device's root directory to be displayed instead of ejecting the device. This has been true as long as I've used caja with gtk3. This behavior is erratic, not occuring every time but occurring often enough that the sidebar entries for mounted devices should not be used. The "computer" entries, desktop icons, and disk-mounter (panel) applets all reliably open a mounted volume.

In gtk3's native places sidebar, you can easily see that the button to eject the device and to display its contents are two separate widgets. My guess is they are in the caja places sidebar too but that they are overlapping each other, each filling the entire row. 

I've had this issue with Caja versions from 1.9 continuing through current 1.11, built and run on both Ubuntu Vivid and Debian Unstable, with gtk versions from 3.14 through 3.18.

**Comment by raveit65** [comment]
yeah, i noticed this issue too.
It' simple to reproduse if you first click in caja view before you try to selest the mounted volume in sidebar.

**Comment by lukefromdc** [comment]
The patch below seems to stop the problem, though I will need to test for a while to be sure as this has been erattic on my systems. At the moment it seems to work great. The patch inserts a second and more robust cursor position check into over_eject_button to prevent it from returning TRUE when the mouse is over the left side of the entry for a mounted device

--- /home/luke/Desktop/caja-places-sidebar.c 2015-09-17 04:45:42.000000000 -0400
+++ /home/luke/Desktop/MATE_Development_Work/caja-1.11.0+git10072015/src/caja-places-sidebar.c 2015-10-12 00:10:13.035214803 -0400
@@ -1021,6 +1021,7 @@ over_eject_button (CajaPlacesSidebar *si
eject_button_size = caja_get_icon_size_for_stock_size (GTK_ICON_SIZE_MENU);

     if (x - total_width >= 0 &&

    x >= total_width - eject_button_size && x - total_width <= eject_button_size) { return TRUE; }

**Comment by lukefromdc** [comment]
I just added a second commit to put the first 80px of the sidebar always off-limits to being detected as over the eject button. It seems the column width is not always computed correctly-and that exactly how wide the sidebar is also effects the likelihood of accidental ejection.

**Comment by raveit65** [comment]
Works well, i will commit your fix.
Thank you

**Comment by raveit65** [comment]
https://github.com/mate-desktop/caja/commit/d14fef384a435471860130f7337d5dea5bb824a0
