### ISSUE TITLE
Multi-monitor - When using two displays, caja window jumps to other display after clicking link on Bookmarks side panel

### ISSUE THREAD

**Issue by ddska** [mate-desktop/caja#473]
When using two displays (single X11 session), caja file-manager window jumps from second to the first display after clicking folder link on Bookmarks side panel, if window is maximized.
I reported this bug in 2012 about nautilus (https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1027743), and it still exists.
I use Mate/Caja 1.8.2.

**Comment by monsta** [comment]
1.8.x isn't supported these days. Please try 1.10.x or ask your distro's maintainers to make a patch for 1.8.x.

**Comment by ddska** [comment]
Works OK in 1.10.2.
