### ISSUE TITLE
Default home folders are missing in left panel, in "Open File" window.

### ISSUE THREAD

**Issue by MarioMey** [mate-desktop/caja#475]
I have Ubuntu-Mate 14.04 x64.

In the left panel of Caja, I have these groups:
- Dispositivos (Devices)
- Marcadores (Markers or Favorites)
- Equipo (System)
- Red (Net)

Inside "Equipo", I have
- mario (Home)
- Escritorio
- Sistema de archivos
- Documentos
- Descargas
- Música
- Imágenes
- Vídeos
- Papelera

This places don't appear in an "Open file" window, from any application: Firefox, Eye of Mate... even inside Caja (when I try to open a new pattern).

This is my Caja:
![caja-default](https://cloud.githubusercontent.com/assets/4954109/10710159/500d7496-7a22-11e5-82e9-210054b906d2.png)

This is Open File:
![caja-open-file](https://cloud.githubusercontent.com/assets/4954109/10710161/5f374f50-7a22-11e5-99a7-521cfc96928b.png)
##

**Comment by flexiondotorg** [comment]
What issue are you reporting exactly?

**Comment by MarioMey** [comment]
That the folders under title "Equipo" (Documents, Images, Music, etc) don't appear in Open file window.

I still have this issue... but remember that I'm using Ubuntu Mate 14.04 64x. I didn't test any newer version! (there're 6 more!).

**Comment by monsta** [comment]
14.04 is EOL by now, so we need to know if it still happens in the latest versions

**Comment by MarioMey** [comment]
Now, I'm with Debian 9 with MATE Desktop Environment 1.16.2.
Firefox "Open" dialog is different. Also, eom's. That missing folders... now appear.

I can't open a "Open file" dialog in Caja to test it... how can I do it?

**Comment by monsta** [comment]
So it was just [GtkFileChooserDialog](https://developer.gnome.org/gtk3/stable/GtkFileChooserDialog.html). It's not a part of Caja, it's a part of GTK+3.
