### ISSUE TITLE
gtk3 version of caja's icon view is inaccessible to orca

### ISSUE THREAD

**Issue by coffeeking** [mate-desktop/caja#479]
in the gtk3 version of caja, assistive screen reader orca can't see the icons. THis affects not only caja but the desktop icons as well, as caja handles those. I'm currently in contact with joanmeri diggs, the lead orca developer for more information to help you guys solve it
##

**Comment by coffeeking** [comment]
Closed issue 356. Just tested caja from latest git. Still broken. According to joanmeri diggs, the desktop isn't firing object:stateChanged:focused events, so orca can't see the icons.

**Comment by coffeeking** [comment]
I'm not sure where else to post this. The applications menu on the top panel now says "applications" when opened, so that's been fixed. However, if the menu is put on the bottom panel and uses a single menu rather than a menu for apps, a menu for places, and a menu for settings, it's not labeled. In fact, orca doesn't see it as a menu. THis could be an orca issue though.

**Comment by monsta** [comment]
Both mentioned menu applets are a part of ```mate-panel``` package. But indeed, how do we make a menu button with just icon and no text visible to orca? :smile:

**Comment by raveit65** [comment]
There are some commits in nautilus upstream during 2.90 to 3.2 development.
Looks like we should backport them.

**Comment by monsta** [comment]
@coffeeking: it might be that https://github.com/mate-desktop/caja/pull/652 fixed this. Can you check this?

**Comment by flexiondotorg** [comment]
@coffeeking Can you test and confirm this is fixed?

**Comment by raveit65** [comment]
i guess we can close this one.
