### ISSUE TITLE
Switching/closing tab doesn't change the icon on taskbar

### ISSUE THREAD

**Issue by zaps166** [mate-desktop/caja#492]
Let's have two tabs:
1. /home/user (folder icon)
2. /home/user/Desktop (desktop icon) - current

Then switch to tab 1 and notice that the icon is not changed (still has desktop icon).
##

**Comment by monsta** [comment]
@zaps166: fixed in https://github.com/mate-desktop/caja/commit/887c8e8608f51f59bf520ba691e9eb9077d8e92d, but there's a related issue which I described here: https://github.com/mate-desktop/caja/pull/619#issuecomment-247020227.
