### ISSUE TITLE
spelling-error-in-manpage usr/share/man/man1/caja-file-management-properties.1.gz (excutable -> executable)

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/caja#493]
I: caja-common: spelling-error-in-manpage usr/share/man/man1/caja-file-management-properties.1.gz excutable executable
N: 
N:    Lintian found a spelling error in the manpage. Lintian has a list of
N:    common misspellings that it looks for. It does not have a dictionary
N:    like a spelling checker does.
N:    
N:    If the string containing the spelling error is translated with the help
N:    of gettext (with the help of po4a, for example) or a similar tool,
N:    please fix the error in the translations as well as the English text to
N:    avoid making the translations fuzzy. With gettext, for example, this
N:    means you should also fix the spelling mistake in the corresponding
N:    msgids in the *.po files.
N:    
N:    Severity: minor, Certainty: possible
N:    
N:    Check: manpages, Type: binary
N:

**Comment by ericcurtin** [comment]
Fixed in f6fb54d
