### ISSUE TITLE
Caja crashes on file "move to trash" for btsync monitored folders

### ISSUE THREAD

**Issue by run4flat** [mate-desktop/caja#496]
This bug was originally reported at https://bugs.launchpad.net/ubuntu-mate/+bug/1532011; I am reposting here based on a suggestion in that thread.

I have a number of folders that I share with other machines via Bittorrent Sync. When I try to "delete" a file from one of these folders (or a file in a subfolder) by hitting the "Delete" key in Caja, or by dragging the file and dropping it on the trashcan, Caja crashes.

* Removing the file in the terminal does not cause trouble (Caja immediately reflects that the file is gone).
* Deleting the file in Caja (Shift-Delete) does not cause a crash
* If the file is in a folder not monitored by btsync, then I can delete it with the delete key or by dragging it to the trash without producing a crash

**Comment by flexiondotorg** [comment]
What version of Ubuntu MATE?

**Comment by monsta** [comment]
@run4flat: we can't do anything about this if you don't even tell us the version of Ubuntu...

**Comment by flexiondotorg** [comment]
No feedback. Will reopen if the reporter provides the requested information.
