### ISSUE TITLE
Caja cannot handle "sftp" locations.

### ISSUE THREAD

**Issue by maandree** [mate-desktop/caja#504]
This issue may be up to 3 years old, this is the first time I tried it in 3 years.

GNU distribution: Arch Linux
Package: caja-1.12.2-1
All optional dependencies are installed: gstreamer, gvfs-smb

When I click on an sftp bookmark I get the error message `Caja cannot handle "sftp" locations.`.

When I click on File → Connect to Server the “Server Details” area, in the dialogue, is disabled and there is a big red error message at the top saying: “Can't load the supported server method list. Please check your GVfs installation”.

gvfs is installed and gvfsd and gvfsd-fuse are running, probably curtsey of caja.
##

**Comment by maandree** [comment]
This issue has now been solved.

**Comment by supercom32** [comment]
Do you mind telling people how you solve your issue?
