### ISSUE TITLE
Gtk3.19: FMIconView is ALWAYS transparent, hard to theme

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/caja#505]
Beginning just before GTK 3.19.7, a reordering of GTK's drawing system caused the FMIconView to not apply any background color set, so theming the .view class can only affect icons, entries, and the rubberband, never the window background. This should be transparent on the desktop, but in the past the .view style class would set a background color for icon views in navigation windows. Now only the foreground color is applied in all windows.

The means any theme using a window background color different than the view color must theme the underlying scrolled window to the desired color, and makes dark themes with light views (like mine) difficult to get right. The scrollbars when a treeview is selected cannot be made to not have a white box on top if a white background in the icon view is desired, for instance.

I tested this be building Cana with a widget name set for FMIconView, and also tested application of the .view class by theming the foreground(text) color. The fg color was applied both with and without the widget name, the background color was never applied to the window background in any case. The .view class CAN theme the background of the sidebar, so this is specific to the icon views. Nemo and Nautilus are also affected. 

Right now I cannot find a pre-build binary of Nautilus 3.19 and I do not have a GNOME build environment set up, but GNOME might do something about this in Nautilus that could be copied. Alternately they might not, on the grounds that Adwaita doesn't need anything done to allow different window background and nautilus icon view colors. Nautilus, BTW, cannot now be fixed: any attempt to set a background on ANY widget will put that color on the desktop too.

Also selecting patterns and colors does not work right now, about to file a second issue for that

**Comment by raveit65** [comment]
Hmm, this does work here with gtk+-3.18/16/14 and latest caja from master.
Example BlackMate
```
/* background of all views */
CajaNavigationWindow .view {
    background-color: @less_dark_color;
	color: @theme_fg_color;
    border-color: transparent;
}
```
I recall that a change for GtkStyleContext is needed for 3.20.

**Comment by lukefromdc** [comment]
This is a gtk3.20 only issue, just came up less than a dozen commits before gtk3.19.7 was released. Previous GTK 3 versions are not affected, and it also has no effect on themes where the file manager view color and window background color are the same.

**Comment by lukefromdc** [comment]
Another thing about GTK3.19/3.19: Most of the CajaNavigationWindow style selectors no longer work. Also, deprecated widgets were never ported to css nodes, so they have NO valid selectors in many cases. Thus I am forced to use long widget chains unlikely to be used in another app to theme things like Caja list views and now even to make the navigation window view white with an otherwise dark theme.

**Comment by raveit65** [comment]
All this make me very said.
Ii'm really thinking about to bury MATE for fedora 24 and only build for rhel7/centos7 which use gtk+-3.14.
I hate bastards who have jobs from linux companys and try to steal the time from free devs with their ideas which are for gtk4.

**Comment by lukefromdc** [comment]
Abandoning MATE for newer builds is really not a good option for me. if GTK were to become truly unthemable an older version could be forked but that is only worthwhile if the newer version won't support 3ed party themes at all, GTK3.20 is nowhere near that. Any widget that just needs a name can be given one, especially for things like the offical MATE themes that develop along with the MATE applications. These in turn would guide 3ed party theme authors just as Adwaita does for GTK itself.

**Comment by raveit65** [comment]
Luke,
do you want to come in the team and help me to port themes to 3.20?
I started with BlueMenta already and i'm pretty sure i will get this finished when gtk+-3.20 will be released.
But i don't have any clue where i should find the time to port the other themes.
maybe if the day have 76 hours..........

**Comment by lukefromdc** [comment]
Might be able to help, I don't have infinite time but I often do have "downtime" between other things I am doing. BlackMATE is probably closest to what I use, I can start with that one.  

Here's the code snippet I am using to deal with the icon view colors:

window.background>*>paned>box>paned>box>notebook>stack>box>box>scrolledwindow.frame{
	background-color: #ffffff;
}

Most items are a simple string search and replace in Pluma, it's things like this that are the exception. I can "rough port" a theme quite quickly, it's getting the fine detalis right that requires regular usage of the theme in question and I am not wiling to switch away from my theme for day to day usage as I have used it all the way back to 2008 when it was simply gtk-theme-ubuntustudio.

I'll set up a branch for BlackMATE and see what I can do with it

**Comment by raveit65** [comment]
Thank you very much :)
This helps me a lot, i've already set up a 3.20 brach for mate-themes where you can fork from.

**Comment by raveit65** [comment]
err.....master is for gtk+-3.20

**Comment by raveit65** [comment]
err.......again
there is a branch for 3.20.
Master is always the same like latest branched gtk branch

**Comment by lukefromdc** [comment]
Anyway, I have a download of that and am working on BlackMATE right now, it's
clearly gtk3.18 or earlier css code in gtk-widgets.css

**Comment by lukefromdc** [comment]
https://github.com/lukefromdc/mate-themes/tree/gtk3.20-dev2

Carries with work I did tonight to get BlackMATE to mostly work with gtk3.19.7.
Much of the theming of individual apps had to be left as there are no valid 
selectors, application window names are no longer recognized unless they are
set with gtk_widget_set_name and use the # selector prefix.

Probably lots left to do but this can be used and looks mostly like it did in GTK 3.18.

First thing I did was merge the existing GTK 3.20 branch to mine, though that made
no changed files from master. Then simply replaced all the text in the files in question
with the new versions, Github automatically created the diffs to show with the commits.

I estimate I've got about 8 hours of work in that port job but but bulk of it is done.

**Comment by raveit65** [comment]
hehe, i will test it later.
Here is a styling for CajaPropertyBrowser which i want to use for the other branches.
/* backgrounds and emblems */
/* left side */
CajaPropertyBrowser .vertical .horizontal GtkScrolledWindow GtkViewport .vertical {
    background-color: transparent;
    border-radius: 5px 0px 0px 5px;
    background-image: linear-gradient(to top,
                                      @toolbar_gradient_base,
                                      @toolbar_gradient_bottom);
}

Btw. if you like to make something better or nicer......go for it ;)

**Comment by lukefromdc** [comment]
If you push yout existing BlueMenta work to github I might be able to mostly finish
it for you. We are snowed in here by the east coast blizzard. Unless the power goes
out and stays out I should have enough time to get it into as good shape as what I just
did for BlackMATE.

**Comment by lukefromdc** [comment]
OK, I counrt a total of 11 desktop themes that will have to be ported assuming we
don't plan to drop any of them.  Once you've done one it's about 8 hours work to 
rough port one, maybe 4 more to finish. The kicker is this: Mint will  be updating
to Ubuntu's 16.04 release this Spring, but that will be GTK3.18. I don;t know if 
Mint will then sit on Ubuntu LTS again for the next 4 years, but if they do they
won't ever have to support this exact version of GTK3. Thus they might not port
anything this time around.

Between the two of us we can port a selection of themes, but we'll need more hands
if 11 are to be supported. That's a lot of themes for just one or two developers to 
deal with.   

First port always takes the longest, the things I learn the hard way on my own theme are
quickly reapplied to anything else I port. Should be the same for everyone else.

**Comment by raveit65** [comment]
> Between the two of us we can port a selection of themes, but we'll need more hands if 11 are to be supported. That's a lot of themes for just one or two developers to deal with.

I've opend a report for it in mate-themes, let us talk there because here we have another issue.
https://github.com/mate-desktop/mate-themes/issues/101

**Comment by raveit65** [comment]
Is this a prob for you to style FMIconView after latest style class commits?
With 'caja-window notebook' and 'caja-desktop' at the begin it should be easy to style it.
Maybe we can close this report now.

**Comment by lukefromdc** [comment]
Makes no difference. Either way the .view class is recognized, the problem is that
gtk does not draw a background at all in the FMIconView no matter what the 
theme. The background color will appear only in places like inside the rubberband
if not overriden by the rubberband theming. The color is in fact reported in gtk inspector,
but it is never drawn.

Only two fixes appear possible: either add a frame or some other widget between the
FMIconView and the scrolledwindow in navigation windows only, or accept that the
scrolled window or something beneath it must carry the background. I will experiment
to see if I can make the former work myself, the latter works but has the issue with any
part of the scrolled window not covered by the treeview in list mode. No way to dkstinguish
between list mode and icon mode in the scrolled window, as you can't theme a widget
based on its child.

In my theme the background color is a medium gray but the base color (for views etc)
is white. Adwaita they are the same or nearly so, so the GTK/GNOME devs don't 
get an issue from this. They have had problems with Nautilus wanting to put the 
theme background color on the desktop, but the icon view and toplevel windows
were the only widgets in Nautilus that didn't put their background colors on the
desktop.

**Comment by lukefromdc** [comment]
I cannot find the place where the icon container (.view) is packed into the icon view (.frame and is a scrolled window). Packing the icon container into a  box, then the box into the scrolled window would be one way to fix this right, but of course it does nothing for Nemo and Nautilus. This might simply be an unfixable GTK bug unless all three file managers are patched. Net effect is to force squares at the top of the scrollbars when a list view is selected, nothing more. Bigger trouble if future scrolled window versions in later gtk versions cannot draw a background either.

**Comment by raveit65** [comment]
Well, i will take a look into it if i found the time for it.
Btw. using 'scrolledwindow' was the situation before i add the 'view' class a while ago.
https://github.com/mate-desktop/caja/commit/aeccda42c6da068ec646b9be32c1e9e96ac09353

**Comment by lukefromdc** [comment]
OK, worst case is we go back to that. The .view class cannot set the background
anymore. Will be interesting to see what Nautilus does about this.

**Comment by lukefromdc** [comment]
I finally found a fix for this by applying the .view style class to and only to the scrolled windows under icon views and compact views while not applying it to scrolled windows under list views, submitted this PR:

https://github.com/mate-desktop/caja/pull/513

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/caja/commit/e5c29655e5301b6d4ba19a3d4970745804039c0e
We should take a look either the old view class will work again in future.
