### ISSUE TITLE
GTK3: Backgrounds and Emblems dialog does not work [$10]

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/caja#506]
While emblems can stll be set from item preferences or the emblems sidebar, the "backgrounds and emblems" is is now mostly nonfunctional. When loaded for the first time, a few emblems can be seen-in a very short, 1 icon deep scrolled window that is difficult to control except by the end arrows. Dragging a pattern from it to a folder background has no effect.

In "colors" or "emblems" the scrolled window is initially empty. Same in emblems if you have clicked on colors or emblems at least once since Caja was started. Changing the GTK theme will bring up the contents of the scrolled window, and they will show after changing the theme back. Emblems can actually be applied to an item this way, but dragging and dropping anything else is ignored.

This is not limited to gtk3.19, I just tested in gtk3.18 as well and got the exact same results.
##

**Comment by raveit65** [comment]
Yes, here is something to do.
Port to GtkGrid , GtkStyleContext............

**Comment by raveit65** [comment]
This expand the GtkScrolledWindow and make the scrollbars usable.
https://github.com/mate-desktop/caja/commit/b058255bef4dab6ce19c6b056af2b32cd2e386a0
A possible style selector:
```
CajaPropertyBrowser .vertical .horizontal .vertical GtkScrolledWindow .frame {
    background-color: @theme_base_color;
}
```

**Comment by lukefromdc** [comment]
For GTK3.20 I will have to work out a "widget chain" equivalent to the no-longer-recognized
CajaPropertyBrowser selector.

**Comment by lukefromdc** [comment]
window.background>box>box>box>scrolledwindow>viewport.frame 

This widget chain will match for GTK3.19, it will show the scrolled window but it
stays 1 icon deep and the icons still don't appear except the patterns on initially
opening the window.  I will watch for any accidental matches to anything else in 
using my theme.

**Comment by raveit65** [comment]
I noticed for other gtk+ branches that BlackMate already use a differrent bg without using this chain.

**Comment by lukefromdc** [comment]
Won't need it, that kind of widget chain is only required in GTK3.19/20 because
GNOME took out support for old style widget names. Now only cssnodes, style
classes installed by the app, and #something widget names are supported.,

**Comment by lukefromdc** [comment]
OK, that commit opens up the scrollbar windows (I was confused earlier, thinking the
theming work recommended was supposed to do that.) Themes easily enough-but the
issue of disappearing icons and ignored backround D &D is still there.

**Comment by lukefromdc** [comment]
Applying custom backgrounds to folders has never worked in GTK3 and the invasive changes necessary to get the desktop to work in GTK 3.21 probably prevent it from ever being used in GTK 3.22 and later builds. Custom backgrounds work in exactly one place:  they can be dragged and dropped into the "information" sidebar and will be displayed there but will not be saved and are gone in the next window opened.

**Comment by raveit65** [comment]
Currently i started to port GtkColor to GdkRGBA here, but i don't think that this will solve the problem.
And i don't have the skills to rewrite  a complete new code for this.
Personal i don't think that this is a necessary feature, so i have disable the menu entry for fedora f25.
http://pkgs.fedoraproject.org/cgit/rpms/caja.git/tree/caja_0033-do-not-show-property-browser-in-menu.patch?h=f25
As we are a small team and nobody starts to work on it since 2 years, we should simply drop the browser.
Well, a few user will blame us, but we should be realistic.

Btw. i found out that resizing the window shows the missing context.

**Comment by sc0w** [comment]
debian bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828158

**Comment by lukefromdc** [comment]
I just confirmed that to support folder backgrounds in GTK 3.22 will require entirely new code. The changes for the GTK 3.22 desktop forced code like this example in fm-directory-view.c behind GTK 3.20 and lower only selectors:

```
EelBackground *
fm_directory_view_get_background (FMDirectoryView *view)
{
	return eel_get_widget_background (fm_directory_view_get_background_widget (view));
}
```
That is because the transparent desktop required the removal of all the previous background code from everything that could ever be rendered on the desktop in order to work. On the other hand, the new code for a noncomposited desktop background does work, doesn't break the composited transparent desktop, and is not that complex.

Thus,. the algorithm that that should work for folder backgrounds in GTK 3.22 would be one based on the noncomposited desktop background code, except for  reading 
CAJA_PREFERENCES_BACKGROUND_SET, 
CAJA_PREFERENCES_BACKGROUND_COLOR,
CAJA_PREFERENCES_BACKGROUND_URI	

instead of a filtered subset of the root window for the image or color to use with cairo. If this works,  it could be backported to all GTK3 builds, and if that does not work changing the background system to the GTK 3.22 system for all GTK 3 builds would enable its use.  I'm guessing this might actually be simpler code anyway,

**Comment by Kakashi-sensei** [comment]
Any updates on this?

**Comment by lukefromdc** [comment]
It is possible to set a background on a window by modifying the GTK theme itself, in GTK 3.21 and Caja 1.15.4 that background image must be set on .caja-navigation-window .widget.view , the very same widget that refused to accept background colors with the older 1.14 code in GTK 3.20. If the background is set on the scrolledwindow, the normal background color appears over it at least with the 1.15.4 changes and GTK 3.21.

**Comment by monsta** [comment]
Interesting, resizing the window brings the items back. However, when you switch between emblems/colors/backgrounds via buttons on the left, items disappear again and a new resize is needed.

**Comment by monsta** [comment]
I see that code for background stuff in icon view is disabled in https://github.com/mate-desktop/caja/commit/c8ea6aafe576d204b4423c868754b4580c52d397 for 3.21. Wonder what it will do in 3.20 though...

**Comment by raveit65** [comment]
#include <eel/eel-background.h> was disabled for the desktop redraw issue with 3.21

**Comment by monsta** [comment]
I know - I meant the code for background stuff in "normal" icon view (directories, not desktop) was disabled there as well.

**Comment by monsta** [comment]
Ok, switching to Ubuntu 16.10 which has 3.20 - current Debian Testing which has 3.21 isn't a welcome place now :smile:

**Comment by lukefromdc** [comment]
That code had to be disabled for the GTK 3.21 desktop change or
I got a torrent of "bad pixmap" errors and a nonworking desktop.
If someone got backgrounds in navigation windows working in GTK 3.20,
that change could be put behind a "if this is the desktop" runtime selector.

**Comment by monsta** [comment]
Yes, I'm also interested in making it work in 3.14 and 3.18, these are versions in current Mint releases.

**Comment by lukefromdc** [comment]
If anyone gets backgrounds working in navigation windows, I'll work up code to enable it in GTK 3.21 and above by limiting the removal of the background code to the case of it being on the desktop. That part should be relatively easy as caja-icon-container.c already uses at least one such selector

**Comment by monsta** [comment]
Funny fact (tested with 3.21): dragging a color from this dialog into a mate-terminal window sets the background color there. :open_mouth:

**Comment by monsta** [comment]
Hmm, I don't get it... ```eel_background_set_up_widget``` function in ```eel/eel-background.c``` seems to set only the default color, using ```gdk_window_set_background_rgba``` or ```gdk_window_set_background```, depending on GTK+ version.

Yet the color change works in GTK+2 when I enable ```background-set``` key and set ```background-color``` to some non-default value in ```org.mate.caja.preferences``` schema. Where is it actually assigned to the widget?

**Comment by monsta** [comment]
So I've managed to make background color work - but with GTK+ 3.18 only.
For some reason, using a pattern created for surface didn't work for it, so I created a pattern from currently stored background color. It worked.

```diff
diff --git a/eel/eel-background.c b/eel/eel-background.c
index 2734cdc..298588d 100644
--- a/eel/eel-background.c
+++ b/eel/eel-background.c
@@ -522,20 +528,22 @@ eel_background_set_up_widget (EelBackground *self)
     if (!in_fade)
     {
         cairo_pattern_t *pattern;
-        pattern = cairo_pattern_create_for_surface (self->details->bg_surface);
-        gdk_window_set_background_pattern (window, pattern);
-        cairo_pattern_destroy (pattern);
-
 
         if (self->details->is_desktop)
         {
+            pattern = cairo_pattern_create_for_surface (self->details->bg_surface);
+            gdk_window_set_background_pattern (window, pattern);
+            cairo_pattern_destroy (pattern);
             set_root_surface (self, window, gtk_widget_get_screen (widget));
         }
         else
         {
+            GdkRGBA c = {0};
+            mate_bg_get_color (self->details->bg, NULL, &c, NULL);
+            pattern = cairo_pattern_create_rgba (c.red, c.green, c.blue, c.alpha);
 
-            gdk_window_set_background_rgba (window, &color);
-
+            gdk_window_set_background_pattern (window, pattern);
+            cairo_pattern_destroy (pattern);
         }
 
         gdk_window_invalidate_rect (window, NULL, TRUE);
```
So, it's a hack, and it also doesn't work at all with GTK+ 3.20.
According to API docs, ```gdk_window_set_background_pattern``` is marked as deprecated only in 3.22, but it looks like they already broke it in 3.20. I guess I'll have to mess with style context functions instead.

**Comment by shirishag75** [comment]
@monsta please keep on gtk 3.22 to see if any further breakage is happening as on Debian testing/soon to be Debian stretch - 3.22.5 is the version being used 

```
[$] gtk3-demo --version                                                                                                          
gtk3-demo 3.22.5
```

**Comment by lukefromdc** [comment]
The background handling code changed in Caja for GTK 3.22 but not for 3.20, so anything working in GTK 3.18 but not 3.20 broke in GTK itself. For GTK 3.22, the removal of background handling from the icon-container probably can be special cased to apply only to the desktop.

**Comment by monsta** [comment]
Hmm looks like it's not broken in 3.20... In mate-panel, both ```gdk_window_set_background_rgba``` and ```gdk_window_set_background_pattern``` are used to set the background color or image on the panel (in ```panel-background.c``` code). That works fine with 3.20 in my Ubuntu 16.10 VM.

In Caja both functions don't work with 3.20. (I've changed the code above to simply set color from ```mate_bg_get_color``` via ```gdk_window_set_background_rgba```, without patterns, and that didn't work too.)

Maybe some problem is with choosing the right window to use...

```C
    if (EEL_IS_CANVAS (widget)) {
        window = gtk_layout_get_bin_window (GTK_LAYOUT (widget));
    } else {
        window = gtk_widget_get_window (widget);
    }
```

So for the icon view, the GdkWindow used for setting background color or pattern is the one obtained from ```gtk_layout_get_bin_window```, not from the widget itself. Maybe we lack some CSS somewhere for that?

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/731 is debugged and ready to go, and should close this issue.

**Comment by raveit65** [comment]
The UI needs to be fixed for changing the tabs w/o resizing the window.
Also i noticed the fg color changing does not work for dir backgrounds with dark bgs with gtk3 build.
I think this needs to be done for gtk3 too.
https://github.com/mate-desktop/caja/pull/526

**Comment by raveit65** [comment]
I found out that 'alt + left-or-right-click' does the same as resizing the window if those gsetting keys are set.
```
[rave@mother ~]$ gsettings get org.mate.Marco.general mouse-button-modifier
'<Alt>'
```

**Comment by monsta** [comment]
For now, the only way I found is this small change:
```diff
diff --git a/eel/eel-wrap-table.c b/eel/eel-wrap-table.c
index 0d77b44..bfff933 100644
--- a/eel/eel-wrap-table.c
+++ b/eel/eel-wrap-table.c
@@ -192,7 +192,7 @@ eel_wrap_table_size_request (GtkWidget *widget,
     content_dimensions = wrap_table_get_content_dimensions (wrap_table);
 
     /* The -1 tells Satan to use as much space as is available */
-    requisition->width = -1;
+    requisition->width = content_dimensions.width;
     requisition->height = content_dimensions.height + gtk_container_get_border_width (GTK_CONTAINER (widget)) * 2;
 }
 
```
This makes the dialog contents visible, but every time you click on a category button on the left, the dialog becomes wider by 6-12 px, and there's no way to shrink it back. :disappointed:

**Comment by lukefromdc** [comment]
Current behavior is all of the items in "backgrounds and emblems" can be sucessfully used somewhere in Caja. Background colors and patterns work just fine  in the main view, in the sidebar they work in the "information" sidebar only, plus the black with back arrow "reset to default" does not work on the sidebar. Colors and patterns cannot be set for the default places sidebar. Emblems can be set on folders just fine.

As mentioned above, you still have to resize the dialog window after changing tabs to make the contents visible. I think the above code would be better than the current situation as the dialog is never open for long, and users will think the dialog is simply broken if they do not know that simply resizing the window will show the contents. Especially ugly is that the window must be resized after changing tabs even if closed and reopened.

**Comment by monsta** [comment]
> I think the above code would be better than the current situation as the dialog is never open for long, and users will think the dialog is simply broken if they do not know that simply resizing the window will show the contents.

There's another problem with this patch... when the dialog is closed, it's not destroyed, it's just hidden, so when user opens it again, it's still the same. In other words, the width isn't reset back to its default value. You need to restart Caja for that.

**Comment by lukefromdc** [comment]
Where else is eel-wrap-table used? Changes for this could affect other things.

**Comment by monsta** [comment]
It's used in the file/folder properties window (emblems tab) and the sidebar (emblems section again).

**Comment by raveit65** [comment]
Guys,
@marosg42 found out that only pressing the alt key is needed to bring back the content, if this key is used as mouse-modifier.

**Comment by lukefromdc** [comment]
If we can't fix this we could document that with a label in the GUI, but better to find and fix it

**Comment by raveit65** [comment]
It look like it is related to button mnemonic function, because if i only press the alt button a short time nothing happens.
But just in the moment if you see the '_' in Button text, the right side will redraw

**Comment by raveit65** [comment]
Btw. using the mnemonic keyboard keys works out of box here. In my language crtl+m (pattern), crtl+f (color) and crtl+e (emblems).
So it looks like that something with the buttons is wrong if using the mouse.
I noticed also with gtk3-inspector that we have radio buttons with 'draw-indicator = false' on the left side.
Setting this to true with gtk3-inspector will show you the 'radio' indicator from the button.
Maybe it helps to use a normal GtkButton with .text-button and .image-button style class?

**Comment by monsta** [comment]
These buttons just trigger the callback function that changes the actual content. I don't think changing them to something else would affect anything. But you can try of course :slightly_smiling_face:

**Comment by monsta** [comment]
Mnemonics work because holding Alt seems to be the key. Try using spacebar to push the buttons (and up/down to move between them). It won't have the same effect.

**Comment by lukefromdc** [comment]
I did some testing today, and found that adding 
`
    gtk_widget_queue_resize(widget);
`
underneath 
```

    content_dimensions = wrap_table_get_content_dimensions (wrap_table);
 
     /* The -1 tells Satan to use as much space as is available */
-   requisition->width = -1;
     requisition->height = content_dimensions.height + gtk_container_get_border_width (GTK_CONTAINER (widget)) * 2;

```
would cause the contents of a newly selected backgrounds and emblems dialog to show up after a bit of a delay, but also spam logs with a ton of 

`Allocating size to GtkGrid 0x55f27295a140 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
`

nuisance warnings for many widgets within caja if the places sidebar (or probably at least some of the others) is showing.

The earlier patch simply worked by forcing the window to resize, causing the contents to show up, again after a delay. That, however, had the side effect that the window could only be resized to a larger side and never a smaller one by the user. The change of size between the three possible dialogs seems to be normal, caused by them just taking up a different amount of space.

**Comment by monsta** [comment]
I experimented with that too, got the same result. The window only got larger as the minimum size request got bigger every time.

**Comment by lukefromdc** [comment]
From these results I'm guessing any kind of forced resize is a kludge, not a fix at the root. The problem is the widget displaying the icons is failing to redraw, so that the old dialog's icons are removed but the new set is never drawn unless the window is resized, which forces a redraw. We could use  gtk_widget_queue_resize(widget) as a kludge (and slow icon appearance at that) if we could just find a way to keep it from spamming logs with 
`
gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?`

**Comment by monsta** [comment]
I recall I used something like that (manually queue resizing), but that didn't work. Maybe I used it in some wrong function, and you'll have more luck than me.

**Comment by lukefromdc** [comment]
What did you try other than gtk_widget_queue_resize(widget) which is what spams logs with all those warnings?

**Comment by monsta** [comment]
I can't remember now...

**Comment by lukefromdc** [comment]
This just drew a new report on another website about still being an issue in 1.20:

https://www.linuxquestions.org/questions/linux-desktop-74/backgrounds-and-emblems-is-still-broke-in-mate-1-20-a-4175623441/

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/917 makes the dialog window constant show up, though with a few seconds delay on changing between patterns, colors, and emblems. Not perfect but usable

**Comment by lukefromdc** [comment]
The final code for 
https://github.com/mate-desktop/caja/pull/917
fixes this so the browser contents show up immediately. See details at 
https://github.com/mate-desktop/caja/pull/917#issuecomment-365173858
