### ISSUE TITLE
Wrong Shift+Del behaviour while renaming files

### ISSUE THREAD

**Issue by dark-penguin** [mate-desktop/caja#509]
When renaming files in Caja, pressing Shift+Del does not "cut the selected part of the name"; 
instead, it works as if you wanted to "permanently delete" the file. Ctrl+X works as expected, however.

To reproduce:
- Press F2 on any file to rename it
- Press Shift+Del to cut the highlighted part of the name

Expected behaviour:
- It cuts the highlighted part of the file name.

Observed behaviour:
- Renaming stops, and a confirmation dialog appears: "Are you sure you 
  want to permanently delete this file?"

Some people argue that this is the expected behaviour, but it is certainly not. Why would I want to delete the file while I'm in the process of renaming it? I'm editing text at the moment, so the text-edition shortcut should take priority. If I did want to delete the file, I would have quit the text selection mode first and go back to selecting files, and then pressed Shift+Del to delete it. Well, Ctrl+X does not try to cut the file; it cuts the text. Delete does not delete the file, it deletes text. So should Shift+Del.

Turns out, Nemo used to have this problem several years ago (I see in there on Debian Squeeze), but they have fixed it (I don't see it in Linux Mint 17.3/LMDE2).
##

**Comment by monsta** [comment]
Fix is now released in version 1.18.5.
