### ISSUE TITLE
Drag and drop multiple files to a single '.desktop' entry

### ISSUE THREAD

**Issue by antipatico** [mate-desktop/caja#510]
Hi,
I have a little problem with caja: I would like to drag and drop multiple files in one '.desktop' entry without launching it one time for each file.
I tried with shift+drop and ctrl+drop but nothing...
Is it possible?
Thanks
##

**Comment by flexiondotorg** [comment]
It depends on the application your dropping on to. For example, drag multiple text files to Pluma will open Pluma once and open each file in a tab. In any case, this isn't a Caja issue :-)

**Comment by antipatico** [comment]
I'm pretty sure it was a caja problem since I couldn't use a script due to that behavior.
Anyway I don't use caja anymore so I can't test it anymore, sorry
