### ISSUE TITLE
Eiciel port for Caja

### ISSUE THREAD

**Issue by darkshram** [mate-desktop/caja#511]
I have done it. Did not need too much manpower. I know this is not a Caja component, but a couple of years ago somebody asked about it: https://github.com/mate-desktop/caja/issues/241

Patch works just with eiciel 0.9.8.3. Do not try with later versions (won't build with caja). Download eiciel 0.9.8.3, untar, apply patch, do autoreconf -fi, build and install. Feel free to modify patch.

![screenshot at 2016-01-30 13 21 26](https://cloud.githubusercontent.com/assets/10327500/12697930/dd235650-c754-11e5-9fd4-5ff6a0453a6c.png)

[eiciel-0.9.8.3-caja-support.patch.zip](https://github.com/mate-desktop/caja/files/110953/eiciel-0.9.8.3-caja-support.patch.zip)

**Comment by raveit65** [comment]
What is eiciel ?

**Comment by darkshram** [comment]
Eiciel is graphical application to manage file ACL entries (setfacl and getfacl). See http://rofi.roger-ferrer.org/eiciel/

**Comment by monsta** [comment]
Not sure what you want us to do about it... and https://github.com/mate-desktop/caja/issues/241 is closed already.

**Comment by darkshram** [comment]
Sorry if I was not clear. **It's a feature request** (or more like a fork request). Currently there is not support for for access control lists (ACLs) and extended attributes (xattr) in Caja. ACLs and xattr are widely used in corporate environments. Nautilus has the support for these through the eiciel extension. I did a patch to build eiciel extension for caja. I have re-packaged a patched eiciel as mate-eiciel in my distro (as seen in the screenshot).

I referenced #241 because somebody already asked for the same thing. Stefano closed that issue because the lack of manpower [yes, I know and understand the project already mantains too much packages] to port the eiciel extension to mate, **which I just did**

**Comment by monsta** [comment]
Ok, so the extension is ready and working, then we don't have to fix anything and can close this issue :smile:
You can notify the reporter of #241 - I don't remember anyone else asking for it. If someone else asks for it we can simply show this report.

**Comment by Ulgrimar** [comment]
Thanks a lot for this great Extension.

**Comment by flexiondotorg** [comment]
@darkshram Please fork eiciel and apply your patches and host it somewhere like GitHub and post the URL here. I can only package this for Arch, Debian and Ubuntu if a upstream project exists. You create the project and I'll work on the packaging ☺️ Thanks for working on this!

**Comment by mixmastamyk** [comment]
I'd like this too, @darkshram, did you notice flexiondotorg's offer?

**Comment by mixmastamyk** [comment]
Oh and how about a new name that is readable and pronounceable while you're at it?  ;)

**Comment by darkshram** [comment]
@mixmastamyk Not, until now. For the time being, the *.src.rpm for the GTK2 port is available [here](http://www.alcancelibre.org/al/aldos/1.4/mate/source/repoview/mate-eiciel.html). Will have to work (and find the needed time) to review, patch and test a GTK3 eiciel version now MATE 1.18 is available.

**Comment by darkshram** [comment]
@flexiondotorg @mixmastamyk I have just done the fork of eiciel.
https://github.com/darkshram/mate-eiciel/
Please, e
![virtualbox_aldos-test_21_09_2017_21_37_13](https://user-images.githubusercontent.com/10327500/30728962-9f6873bc-9f21-11e7-8421-7891f981e023.png)
![virtualbox_aldos-test_21_09_2017_23_06_57](https://user-images.githubusercontent.com/10327500/30728961-9f6778a4-9f21-11e7-8a49-5e803ded8d45.png)

njoy!

**Comment by flexiondotorg** [comment]
@darkshram, Brilliant! Thank you 😀

**Comment by monsta** [comment]
@flexiondotorg @darkshram can you guys please comment on https://github.com/mate-desktop/caja-extensions/pull/33?
I think there's no need to do additional work to implement something that eiciel already has.

**Comment by mixmastamyk** [comment]
When does this land?  Am on Ubuntu Artful, but don't see mate-eiciel:

```
⏵ apt-cache search eiciel
eiciel - graphical editor for POSIX ACLs and extended user attributes
⏵ apt-cache policy eiciel
eiciel:
  Installed: (none)
  Candidate: 0.9.11-3
  Version table:
     0.9.11-3 500
        500 http://us.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
```
