### ISSUE TITLE
Caja falls when I try to delete a file in trash

### ISSUE THREAD

**Issue by AntonKarmanov** [mate-desktop/caja#512]
I can move a file in /media/HDD/.Trash-1000/files free, but when I am trying to delete it with Del key, caja falls without any messages. Deleting with Shift + Del is ok, as well as deleting from ~/.

**Comment by raveit65** [comment]
Sounds like a old bug which is fixed?
Why do you think anyone can help you without to know which distro, mate, and caja version are you using?
....sorry my cristal ball is dead ;)

**Comment by AntonKarmanov** [comment]
Oh, sorry.
Ubuntu Mate 15.10, Mate-Desktop 1.10.2-1 and Caja 1.10.4.

**Comment by monsta** [comment]
Try 1.12 from the [official PPA](https://launchpad.net/~ubuntu-mate-dev/+archive/ubuntu/wily-mate).

**Comment by AntonKarmanov** [comment]
Yes, thank you! Seems it is ok now.
