### ISSUE TITLE
Caja crash upon opening Trash containing a file with '%' symbol in its name

### ISSUE THREAD

**Issue by synthakai** [mate-desktop/caja#514]
how to reproduce:
1. create a file with the '%' symbol in its name (or rename an existing file)
2. move file to Trash with Del button or context menu item
3. click Trash in caja side pane

expected result: 
caja opens Trash

the result I have:
caja crashes

to stop caja from crashing I have to manually navigate to the respective partition, to the /media/*/.Trash-*/files folder and remove the file in question.

Linux Mint 17.3 Rosa 64-bit

$ dpkg -p caja
Package: caja
...
Installed-Size: 3302
Maintainer: Stefano Karapetsas <stefano@karapetsas.com>
Architecture: amd64
Multi-Arch: foreign
Version: 1.12.1-1+rosa
...
Size: 821644
...

**Comment by monsta** [comment]
Recently fixed in https://github.com/mate-desktop/caja/commit/b2737bb68c81e4095aa14c94fc93eb2acdd00ce0. We'll prepare a new 1.12.x release soon.

**Comment by synthakai** [comment]
ok, thank you :)

**Comment by monsta** [comment]
Fix released in 1.12.4. Wait for @clefebvre to push it to Mint repos...

**Comment by monsta** [comment]
Ok, Caja 1.12.4 is in Mint 17.3 repos now.

**Comment by synthakai** [comment]
cool, it works fine now.
thanks guys :)
