### ISSUE TITLE
gtk3.19: Desktop opens at 1/4 screen or less with newest GTK 3.19 GIT master

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/caja#522]
https://git.gnome.org/browse/gtk+/commit/?id=cdc580463e409a9b7e5f1480afa68d875ff3ff65 causes the desktop window to shrink down to a very small size. Unless GNOME decides to revert this all filemanagers must now expliclty maximize the desktop.

https://github.com/lukefromdc/caja/commit/cf42c2ed4a86c65ecf9847f539788710dd740558

Will fix this, but it's probably worth waiting to see if GTK devs really decide to keep this code as right now Nautilus and Nemo are broken too. Do they even test with icons on the desktop?

**Comment by raveit65** [comment]
wtf,
well, we need to monitor nautilus changes.

**Comment by lukefromdc** [comment]
I have run into all kinds of ugly bugs in Compiz with the offending commit. Caja must open before compiz or my code won't work, and if the panel opens after it it cannot redraw the space underneath it after hiding the panel or changing panel bg. Much testing to do, not sure if this is a bug GTK will fix, something I can find a way to fix in compiz, or something that I can fix in applications. Gnome-panel doesn't get the redrawing issue no matter when started, so that's a starting point. Ugly mess so close to GNOME's release!

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/524 is a new PR from a brand new branch with a much simpler fix that works in Compiz as well as Marco, Mutter, IceWM, etc.  Turns out that GTK commit doesn't like gtk_window_set_resizable false on the desktop window at all. I put it behind a GTK 3.18 or earlier only switch, now ALL the problems I was getting from that GTK commit are gone, panel's fine too.

**Comment by raveit65** [comment]
Ok, i will test it if next gtk+ version with the culprit commit is available in fedora f24.
Thank you

**Comment by lukefromdc** [comment]
GTK 3.19.12 was just released on the evening of 3.14.2016, and another last-minute change to gtkwindow.c did not fix or even seem to address this problem, dealing with another issue instead.

I tested GTK 3.19.12 as release with Caja from mate-desktop/master, the partial desktop opening is still here so my commit or another that does the same job is still needed.  Any different solution would need to be tested in both Marco and Compiz, as Compiz is an outlier as WM's go and the hardest to make work with desktop issues. Both Nautilus and Nemo cause compiz redraw issues right now, so Caja with https://github.com/mate-desktop/caja/pull/524 applied may be the only gtk3 file manager that can render icons on the whole desktop with gtk3.19.12 at the moment.

Thus, a GTK tarball has made it to release with the problem commit, should appear shortly in Fedora. A comment on the new gtk window commit
https://git.gnome.org/browse/gtk+/commit/?id=d61c2b4cce38eb480aa53f8fdb08c4b181e2aa99
implies that further work on window resizing will wait until after a GTK 3.20 branch is split out from master, implying that the previous bad commit now will go all the way to release.

Nautilus's devs will see it shortly, will be interesting to see what they do.

**Comment by lukefromdc** [comment]
OK,  the Nautilus devs just caught this, they have a new "WIP' nautilus branch to split out desktop handling entirely-but the first commit to it addresses this issue:

https://github.com/GNOME/nautilus/commit/cf79068dc70c87e963e217e2e8ae149ee5ed1872
"desktop-window: avoid wrong size "

Turns out that setting a default size for the normal windows causes this on the desktop, so this commit sets it to -1 on the desktop to stop this unwelcome behavior. Will test it momentarily in Caja

**Comment by raveit65** [comment]
What a weird issue, first i didn't saw what was wrong after install of gtk+-3.19.12 in a VM.
Thanks for the fix.
https://github.com/mate-desktop/caja/commit/92607629fc6b2503f28e79dcc73e3ac9ed72bffa

**Comment by lukefromdc** [comment]
GTK just tried to fix this in GTK itself for Nautilus
https://git.gnome.org/browse/gtk+/commit/?id=3e3d29f7b73381dd328e5213e0dca04d3e4f8048
instead of Nautilus merging https://github.com/GNOME/nautilus/commit/cf79068dc70c87e963e217e2e8ae149ee5ed1872 from their now-gone desktop split branch to master. Unfortunately their fix DID NOT WORK for an older build of Caja from before
https://github.com/mate-desktop/caja/commit/92607629fc6b2503f28e79dcc73e3ac9ed72bffa 
I rolled Caja back and tested, and no, GTK devs did not fix it for Caja, meaning we can't revert this. Fortunately, current Caja works just fine, no problem at all. I will find out later if they even fixed Nautilus with this and without the previous Nautilus commit which never made it to master, possibly because of their code freeze for next week's release.

**Comment by lukefromdc** [comment]
Here's why the fix the gtk devs decided to use 
https://git.gnome.org/browse/gtk+/commit/?id=3e3d29f7b73381dd328e5213e0dca04d3e4f8048
only helps Nautilus and not Caja or Nemo:
It simply special cases windows that set both a default size on their gtk window and a size request on the corresponding gtk widget, such as the Nautilus desktop. 

Well in Caja, ` gtk_widget_set_size_request()`  is behind a GTK2 only switch, while `gtk_window_set_default_size` is used unconditionally. Thus the case GTK 3 devs special-cased does not apply to Caja (apparently not to Nemo either) so the fix Nautilus devs came up with only to discard when GTK was fixed for them is still needed for both Caja and Nemo.

**Comment by raveit65** [comment]
Does it not work with the replacement gtk_widget_get_prefered_size in gtk3 part of the code?

**Comment by lukefromdc** [comment]
I tested it with Caja from before our fix, Nemo without that same fix
applied by myself, and
Nautilus. Only Nautilus worked.

On 3/19/2016 at 5:11 AM, "Wolfgang Ulbrich"  wrote:

	Does it not work with the replacement gtk_widget_get_prefered_size in
gtk3 part of the code?

**Comment by lukefromdc** [comment]
The only place that appears in caja-icon-container.c is in 
caja_icon_container_search_position_func
It appears in caja-spatial-window.c in menu_popup_pos 
and in both cases is redefined in GTK 2 cases. I did not find
it in caja-window.c or caja-desktop-window.c at all when using
mate-search-tool to search the whole source directory for it.
On 3/19/2016 at 5:11 AM, "Wolfgang Ulbrich"  wrote:

	Does it not work with the replacement gtk_widget_get_prefered_size in
gtk3 part of the code?

**Comment by raveit65** [comment]
yes, this widget is not used in those file (caja-window.c or caja-desktop-window.c)

PS: you can use 'grep' for searching in code, example:
'grep -nr gtk_widget_set_size_request *'
n= show line numbers
r= recursive (Read all files  under  each  directory)

grep is a nice tool, see man grep for more options
