### ISSUE TITLE
Caja doesn't respect hidden files in properties window

### ISSUE THREAD

**Issue by zaps166** [mate-desktop/caja#527]
My Caja doesn't show hidden files as default (otherwise it works). When I have hidden file or directory then it is not respected in property window, so the calculated size and object count is incorrect.

Tested with 1.12.6 and master: ce7cc9580809d4017c74b0128f7e82f94eb173d9

Steps to reproduce:
1. Don't show hidden files/directories as default:
![1](https://cloud.githubusercontent.com/assets/6239090/14027680/2f83c136-f1f9-11e5-90a1-77a2b6f0c3d3.png)
2. Create two files inside a directory.
3. Hide one of them (add dot "." before the name).
4. Press F5 (it hides the file) and optionally press Ctrl+H to show hidden files.
5. Open property for the directory:
![2](https://cloud.githubusercontent.com/assets/6239090/14027681/30e073b2-f1f9-11e5-93bb-0b7230c19890.png)

Expected results: Caja shows real directory object count and real directory size even if there are hidden files/directories.
Otherwise we can see e.g. that the directory have 1MiB and it real contents will have e.g. 100GiB. It is misleading...
##

**Comment by zaps166** [comment]
Any news about this?

**Comment by flexiondotorg** [comment]
I've just tested this on Ubuntu MATE 17.04 with MATE 1.17 and on Ubuntu MATE 16.04 with MATE 1.16. I can't reproduce the issue. I created two directories and follows:

  * `Test\1.txt`
  * `Test\2.txt`
  * `Test Hidden\.1.txt` <- Hidden
  * `Test Hidden\2.txt`

Displaying the properties for both folders, with *or without* "Show hidden and backup files" enabled, displays a count of 2 files for each folder.

**Comment by zaps166** [comment]
Hmm, weird. My OS: ArchLinux/Manjaro, Caja 1.16.1 GTK2:

[CajaHiddenFilesBug.mp4.txt](https://github.com/mate-desktop/caja/files/712474/CajaHiddenFilesBug.mp4.txt)

Please remove `.txt` extension - github can't upload other extensions, even zip.

**Comment by zaps166** [comment]
@flexiondotorg

Just tested on Ubuntu 17.04 with Mate 1.17.2 (zesty-desktop-i386.iso, 4a5c6ff2e00a401c222be973390c2348fefd1021). The bug exists, I can reproduce it:
[Ubuntu-17.04.mp4.txt](https://github.com/mate-desktop/caja/files/721101/Ubuntu-17.04.mp4.txt)
