### ISSUE TITLE
Accessible text of icons is concatenated without spaces

### ISSUE THREAD

**Issue by Joanmarie** [mate-desktop/caja#530]
Steps to reproduce:
1. Enable display of file size in icon view
2. Switch to icon view
3. In a terminal, launch the attached pyatspi accessible-event listener
4. Arrow around in Caja to change the selected icon
5. Examine the text reported by the accessible-event listener

Expected results: There would be whitespace (e.g. a newline char) separating each line of text displayed beneath the icon.

Actual results: There is no whitespace separating each line of text displayed beneath the icon.

Sample output:
installer_linux.sh111.0 MB
index.html1.1 MB
mt7601u-master.zip68.9 kB

Impact: Orca speaks the two lines as if they are a single line because all it knows is what it gets when it asks for the displayed text via AT-SPI2.

Most of the time this is not a big deal because speech synthesizers speaking things like "zip68.9" will have to say "zip 68.9". However, if the file extension ends with a digit, such as "mp4", you wind up with accessible text like "foo.mp4109.8 MB", and that text gets spoken as "foo.mp 4109.8 MB" (where "4109" will, depending on the user's settings, be spoken as "four thousand one hundred nine").

Listener: Delete the 'txt' extension before launching it. Github didn't like the ".py".
[text.py.txt](https://github.com/mate-desktop/caja/files/197858/text.py.txt)
##

**Comment by coffeeking** [comment]
hi. This happens in mate 1.12 as well as mate 1.10. Thanks joanie for the pyatspi listener

**Comment by lukefromdc** [comment]
On my files, this gives a whitespace only if there is a whitespace in the filename, with Caja 1.17.1.  The only text under them is the filename, which is a single string, not a concatenation of strings.

Adding a whitespace to a filename where none actually exists makes the filename incorrect, meaning if it was read back exactly the same way the file would not be found.

**Comment by lukefromdc** [comment]
It's worth keeping in mind, with a filename under an icon there is one string, and the only thing breaking it into multiple lines is the limit to the length of one line. This changes with options such as "use compact layout"  which is not the same thing as compact view.

**Comment by cwendling** [comment]
> On my files, this gives a whitespace only if there is a whitespace in the filename, with Caja 1.17.1. >The only text under them is the filename, which is a single string, not a concatenation of strings.
>
> Adding a whitespace to a filename where none actually exists makes the filename incorrect, meaning if it was read back exactly the same way the file would not be found.

Hum, I wonder if there isn't a misunderstanding here.  What I believe this report is about, and what #692 fixes (and it still works for me in 1.17.1, also with the linked listener script) is concatenating the file size/number of items information which is displayed at some zoom levels (Display/Icon Captions).

In @Joanmarie list, I believe she has the files
* *installer_linux.sh* which is 111.0 MB
* *index.html* which is 1.1 MB
* and *mt7601u-master.zip* which is 68.9 kB.

Not the literal names shown in the report.  So the point was adding a space when creating a new information (here, `name + size`), not altering the name to split like the on-screen layout.

BTW, it's worth noting that the info reported through AT-SPI doesn't change dynamically with the zoom levels: you have to change directory and come back (e.g. recreate the accessible objects) for this info to update.  Not sure it's a big issue though, but important for testing.

**Comment by monsta** [comment]
Ok, I will close this as fixed then, and cherry-pick the fix to 1.16 branch too.
