### ISSUE TITLE
Build failure after commit /9a86c2cbc0b1e75f9073461ead8bc2d917694921

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/caja#536]
Building over GTK 3.20, Caja did not complete the build after commit
https://github.com/mate-desktop/caja/commit/9a86c2cbc0b1e75f9073461ead8bc2d917694921

got this error:

(filepath redaacted)src/caja-window.c:685: undefined reference to `caja_window_remove_trash_monitor_callback'
collect2: error: ld returned 1 exit status

**Comment by monsta** [comment]
Line 685 in ```src/caja-window.c``` now contains ```caja_window_finalize_menus``` call after that commit - seems like you have the previous version of that file...

**Comment by lukefromdc** [comment]
You are right: I had not seen that there were three changed files and  only got the first one. Got all three now, and a sucessful build. Closing this, problem was on my end caused in part by having to work around limited bandwidth
