### ISSUE TITLE
Missing file white_ribs.png

### ISSUE THREAD

**Issue by holiveros** [mate-desktop/caja#538]
The file https://github.com/mate-desktop/caja/blob/master/data/browser.xml references a pattern "white_ribs", but it's corresponding .png file does not exists, nor https://github.com/mate-desktop/caja/blob/master/data/patterns/Makefile.am references it either.
##

**Comment by raveit65** [comment]
Indeed, the file is missing, but also in older nautilus releases.
So i guess we will remove the file from browser.xml.

**Comment by monsta** [comment]
Gone since 2001 :smile:
https://git.gnome.org/browse/nautilus/commit?id=2861839801462c2e49ce82acc00e2c0d2bc53107

They forgot to remove the reference from ```browser.xml```, hence we inherited it.

**Comment by monsta** [comment]
So we can either remove the reference or re-add the file:
https://git.gnome.org/browse/nautilus/plain/data/patterns/white_ribs.png?id=67fe94b16fc294a3c81fd8527d119fcc5338c26d

**Comment by raveit65** [comment]
+1 for re-adding if the image is valid and does not create any fallout.

**Comment by flexiondotorg** [comment]
Removed the reference to White Ribs. Fixed via https://github.com/mate-desktop/caja/commit/8c1479a4b032a56bd90b7cb38238e097061b1bc5
