### ISSUE TITLE
Gtk3.21:  Showing sidebar causes segfault

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/caja#540]
Beginning with the May 6 commit to GTK 3.21 0f116135f4a5033ce4e9dfa19f10624701fa615c , attempting by any means to open a Caja navigation window causes a segfault. Reverting GTK, hiding the sidepane, then updating to current master GTK 3.21 again stops the segfault. 

The offending commit is

	0f116135f4a5033ce4e9dfa19f10624701fa615c 

"Avoid emitting ::style-set by name
GtkStyle is deprecated, but we still emit ::style-set quite
a bit, so lets at least not be slow while doing it."

https://github.com/mate-desktop/caja/pull/539
puts the offending GtkStyle instances (those in caja-sidebar-title.c) behind GTK 3.20 and earlier only selectors and lets Caja windows open with the sidebars showing in recent GTK 3.21.

**Comment by raveit65** [comment]
Nice :-/
latest gtk+ commit history looks like we can expect more fallout.
Btw. is style-set not for gtk2 and this needs ported style-updated for gtk3?
.......maybe I confuse something.

**Comment by lukefromdc** [comment]
I'm sure this is in fact only meant for GTK2, there are more places in Caja where the initial GTK3 port missed that but this is the only one that segfaults-for now. I suspect in the other places it isn't doing much given I saw no effect from its removal from my build. I tested my built package all the way down to GTK 3.16 with no problems. Caja built with GTK 3.20 or later won't run on GTK 3.14 but that's not new.

Meanwhile I'll pull GTK 3.21 again today for more tests...

**Comment by lukefromdc** [comment]
Yes, there is more fallout from GTK 3.21: a drag and drop problem in mate-search-tool. I found the offending GTK commit and possibly the error, but not a solution as of yet as none of it matched a quick search of the source in mate-utils:
https://github.com/mate-desktop/mate-utils/issues/142

**Comment by monsta** [comment]
Interesting... so ```style_set``` is meant to be simply removed, not replaced with some new property?

**Comment by raveit65** [comment]
@lukefromdc 
See https://github.com/mate-desktop/mate-panel/blob/master/mate-panel/panel-widget.c#L455
Here style_set is replaced with style_updated
Can you try to replace the property please?
I can't check this for myself as i didn't have a installation with 3.21 for the moment.

**Comment by lukefromdc** [comment]
OK, I'll test that today

**Comment by lukefromdc** [comment]
That was just to see if it worked, and I found no adverse effects and
limited it to GTK 3.21+.

**Comment by lukefromdc** [comment]
I have never done this kind of port without reference to a much closer match
than this. So far this is defeating me, I may not be able to port this
anytime soon though I will experiment with it for now. I was able to set uo
a GtkStyleContext but not to retrieve font properties from it.

It appears that this function updates fonts used in the "information" panel
for the sidepane only, don't know if it also updates the font used in the
button that chooses between sidepane options. The only place this file
is referred to by another file is in caja-information-panel.c

On the other hand, I just did some quick tests, firing up the Caja information
pane and changing application fonts repeatedly, all changes were applied 
immediately even without this function built or used. Thus, it appears that 
the font properties are being applied by default at least in GTK 3.21 and 
that nothing else needs to be done to apply them. As a result, this function
appears to be redundant at least in GTK 3.21.

To test this in an older version, replace my GTK 3.21 build selectors with
GTK 3.0 and build over an older version, then restart Caja, set the sidepane
to show "information" and try changing application fonts.

**Comment by lukefromdc** [comment]
One more thing: There are a lot of bugs in GTK 3.21 right now, including another segfault in certain scrolled windows that crashes saving to a new filename from Pluma, Gedit, probably everything using that dialog. That one GTK will have to fix, this other segfault might also be fixed upstream. Still leaves us with a function never ported to GTK3 that appears to do exactly nothing that GTK is not already doing by default.

**Comment by raveit65** [comment]
I would leave the report a while open until more ppl testing this.
I will update to rawhide if f24 is released, in 4 weeks or so.
But at least we need to do something, because Martin will switch Mate in ubuntu-16-10 to gtk3 and i want switch with f25 to gtk3 which will come with gtk+-3.22.
Personal i would prefer a port to style-updated, but at least you and @monsta have more knowledge about codding than me.
I found several commits how to convert it in our code and i will try it out if i'm using 3.21.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/554
fixes the a better way, by porting the two offending functions over to use GtkStyleContext instead of GtkStyle in all GTK3 versions

**Comment by raveit65** [comment]
Thank you, i will test this as soon as possible.
Sounds like we have to put **porting deprecated GtkStyle to GtkStyleContext** to our roadmap for 1.16 as we want switch to gtk+3.
Fedora 25 will come with gtk+-3.22, so it seems impossible to use Mate desktop (gtk3) there without doing this for all applications.
@monsta  any thoughts?

**Comment by monsta** [comment]
I actually thought most of our apps are already ported to GtkStyleContext for GTK+3 builds... any other apps left beside Caja?

**Comment by raveit65** [comment]
Most apps use GtkStyle, only few are fixed.
In last dev cycle i fixed only what i could find at gnome-git
So what i know is that those apps needs some love.
mate-panel
mate-applets
mate-control-center
atril
etc.
Btw. the build log will show you the truth.

**Comment by monsta** [comment]
Oh well, looks like more work once again... :smile:

**Comment by lukefromdc** [comment]
Yeah-the OSD window in mate-settings-daemon
https://github.com/mate-desktop/mate-settings-daemon/pull/145

There is also a mess in mate-utils with a function that has an issue
with gitk_widget_realize in 3.21 but works OK with gtk_widget_show
to do the same thing implicitly. Only thing is, the entire function is 
supposed to resize dictionary windows to fit the text and I've never
once seen that work with any version of GTK3.

**Comment by lukefromdc** [comment]
This fix gets Caja to run but changing fonts in the "information" panel remains an issue. The old function sometimes but did not always work in GTK 3.20 and earlier, sometimes applying a font change right away, but when changing down it was not applied until a second font change or a Caja restart. This was the function that segfaulted in 3.21.  This fix gets Caja running with GTK 3.21 but applying a change of font to the "information" panel does require a restart. Possibly this was caused by not also porting over the whole rest of the file so that "style_previous" could be used by the new version. It is accepted as an input for compatability but is not used at the moment.

I will play with this some more today, it would be nice to get the information labels to always update fonts with everything else. If I don't find this, we could put this behind a GTK 3.21 switch for now, but the previous function is so inconsistant in it's action that may not be worth it. This needs to be fixed right for all GTK 3  versions prior to the release of 3.16.

**Comment by lukefromdc** [comment]
Dynamic resizing of the "information" panel title font as the sidebar width is changed works. The issue is changing the font bearing more detailed information as the system font changes  both now (must restart) and before with older GTK versions(inconsistant results). Also, in GTK 3.21 that font, like the font used in Gedit's main text window comes up 4 sizes smaller than it is set to due to changes in font parsing. Only a few things are affected by this, seems to be the px to pt transition again

**Comment by lukefromdc** [comment]
https://github.com/lukefromdc/caja/commit/69c3ae9e36dbfffc11a743e796860add80f92a72 on  new branch 
https://github.com/lukefromdc/caja/tree/gtk3.21fixes3
brings back a normal font size for the information sidebar's "more information" label. Minimum and maximum values being set somewhere else make this a fixed or nearly fixed size, not changeable by changing system fonts. In other words, increasing the default size back to a usable value hits a maximum somewhere and also become the miniumum, don't know why.

**Comment by raveit65** [comment]
I set up a VM with fedora rawhide, mate gtk3 and gtk+-3.21.1, but i see any crash with caja.
When do get them?

**Comment by raveit65** [comment]
Or is the culprit commit not in 3.21.1 release?

**Comment by lukefromdc** [comment]
The offending commit 0f116135f4a5033ce4e9dfa19f10624701fa615c came out on May 6, while 3.21.1 came out on April 27.

 BTW, I looked at the Information sidebar font behavior with my latest work, it matches almost exactly what I got in the a Mint 1.14 MATE test boot from a CD: No font change in "more information" label no matter what the application font.  Using a default GtkLabel here might make that font changeable with all the others

**Comment by lukefromdc** [comment]
https://github.com/lukefromdc/caja/tree/gtk3.21fixes4 
makes the "more information" label text in the information sidebar change size with the system application font for the first time I've ever seen it work both changing up and down, all GTK3 versions. Same size text all GTK3 version too, no more GTK 3.21 vs GTK 3.20 size difference. The portion of "style_set" that atttempts to resize this text does not work properly in any GTK version I've tested. Removing that code makes the labels work and resize properly. Probably should be done in GTK2 as well but I've got no way to test that.

For GTK3., this branch keeps the GtkStyle port of the function dynamically resizing title text, though that needs a forced redraw to follow a system font change. Resizing the sidebar will do it as will restarting Caja. 

The older (closed) commit that disabled the entire "style set" function actually turned out to work best of all, with both dynamic resizing of the title text and changing the sizes of both labels to follow system (application) font changes working perfectly. I will clean it up, rebase and repost it as a 5th alternative. The "style set" function does not work right and apparently never did, even in GTK2.

**Comment by lukefromdc** [comment]
https://github.com/lukefromdc/caja/tree/gtk3.21fixes5
is original PR code applied to all GTK 3 versions and rebased to current mate-desktop/master. Disables style_set entirely as it has never worked. Best font handling of anything tested, though resizing the headline down with a change of system font still takes a forced redraw (resize the sidebar or restart). I'll leave all of these options for discussion for now, but using this one locally.

**Comment by raveit65** [comment]
OK, 3.21.1 release is from 2016-04-27, so i can't test the fixes at the moment.

**Comment by raveit65** [comment]
You should be able to do different PRs to master branch, imo.
i.e gtk3.21fixes5 --> master
gtk3.21fixes4 --> master

**Comment by raveit65** [comment]
btw. i found an example of porting style_set to style_updated, maybe this is useful.
https://github.com/mate-desktop/caja/commit/e2942ccb6206376293044bf0f7c885505e6a1113

**Comment by lukefromdc** [comment]
I've done that before but didn't want to make things too complex. I will probably
play with this a bit more and then submit another one

**Comment by lukefromdc** [comment]
I used another example from mate-panel's clock but found that the function
would work but would not update until a redraw-and worked better in both 
labels with this function not used. Worst of all, even booting an old GTK2
Mint install showed fonts not updating as the system font was changed. My
guess is this is left over from the early days of GTK2 and broke sometime in
the GNOME 2 era or shortly therafter. I am also assuming that the ability of
early GTK2 to handle some of the font updating with font changes was not
what it is now, thus these functions. 

Does anyone have a history file on caja-sidebar-title.c from the days when it was
nautilus-sidebar-title.c?

**Comment by monsta** [comment]
> Does anyone have a history file on caja-sidebar-title.c from the days when it was nautilus-sidebar-title.c?

Yes, it's here: https://git.gnome.org/browse/nautilus/log/src/nautilus-sidebar-title.c

**Comment by lukefromdc** [comment]
I didn't find anything obvious in looking through that file history, thanks for finding it!

I just found another issue. I ported the update_title_font to GtkStyleContext without any trouble, gettting results essentially the same results as my last effort. The  dynamic resizable text works, proving the function works, but when the sidebar is opened up wide for plenty of space and the font then changed the title font won't update until a redraw forced by resizing the sidebar. This function, unlike style_set MUST be used as it is what gives the larger font that resizes with available space on the info sidebar.

It turns out that not only is gtk_widget_modify_font deprecated, but so is it's  replacement, gtk_widget_override_font. GTK devs say this:

"gtk_widget_override_font has been deprecated since version 3.16 and should not be used in newly-written code.

This function is not useful in the context of CSS-based rendering. If you wish to change the font a widget uses to render its text you should use a custom CSS style, through an application-specific GtkStyleProvider and a CSS style class."

I was wondering if that deprecated function was the cause of the font resize issues, but now I think the whole logic flow of this code is the problem for following system font changes. Right now the font is being read by 

gtk_style_context_get (context, state, GTK_STYLE_PROPERTY_FONT, &font_desc, NULL);

and then interacted with and modified. If the system font is changed, the last modification to the PREVIOUS font is probably what the code above will still pick up! In other words, there is no way to get the new font into either function until a redraw or restart momentarily invokes the system font again. To apply a change from the system in realtime would mean it would have to be read from the global label font most likely, but last time I tried that I got a segfault.  I'll have to play with that some more, I'll need a way to access the global GtkLabel style context without getting a segfault.

I will add the change to update_title_font to branch 5 as it causes no new problems and removes one deprecated item.  If I find a way to read the font from the global GtkLabel I should be able to get both functions to work, though the "more information" label seems to work better without it, especially in terms of having the same size text in all GTK3 versions including GTK 3.21. With it, we get larger text in 3.16/18/20 and smaller text in 3.21.

**Comment by lukefromdc** [comment]
New PR #558 seems to give best results. based this in the fixes4 branch but made new branch to clean it up as otherwise it was 4 commits.

Can resize "more information" label in realtime with system font changes, no segfaults in GTK 3.21, can't find anymore instances of GtkStyle in this file.

**Comment by lukefromdc** [comment]
New PR https://github.com/mate-desktop/caja/pull/559 fixes both the segfaults and all other instances of Gtkstyle I could find in Caja, seven files in all

**Comment by lukefromdc** [comment]
Segfaults are done, so closing this issue but creating new issue
https://github.com/mate-desktop/caja/issues/562 to discuss the rest of the deprecation fixes, including that nasty GtkStyle mess in eel-background.c that looks like any fix will require changes to mate-desktop.
