### ISSUE TITLE
problem of read only when copying a file on a usb device

### ISSUE THREAD

**Issue by ciddu2000** [mate-desktop/caja#542]
here's how to reproduce the issue on caja 1.12.6 :
- plug a usb device 
- delete a file on it
- remove it from the trash
- drag and drop a file in the usb device
  
  caja will show that messagebox : "Erreur lors de la copie de « file.avi »
  Erreur lors de la copie du fichier dans /run/media/ciddu2000/LINUX MINT.
  afficher plus de details
  Erreur lors de l'ouverture du fichier « /run/media/ciddu2000/LINUX MINT/file.avi » : Système de fichiers accessible en lecture seulement"
##

**Comment by flexiondotorg** [comment]
Duplicate of #565
