### ISSUE TITLE
Renaming to anything with a Z in it does not work

### ISSUE THREAD

**Issue by grizzler0031** [mate-desktop/caja#546]
Shift+Z reloads the window. This means renaming a file to something with a capital Z in it is impossible. Please get rid of this key shortcut. F5 does the same thing anyway.

**Comment by monsta** [comment]
Which distro and which version of Caja?

Shift+Z shows the search entry with Z typed in it for me.
Pressing F2 to rename a file and then pressing Shift+Z adds Z to file name.

**Comment by grizzler0031** [comment]
Debian Testing, Caja version 1.12.7. The function Shift+Z to reload is even mentioned in the View menu.

This is weird. I wanted to create a screen print to show what it looked like, so I opened the menu, put the mouse pointer on the Reload entry and pressed Ctrl+Print to print the current screen. The Shift+Z in the menu changed to Ctrl+Print the moment I pressed that. Then I pressed F2 and it changed to F2, F4 and it became F4, etcetera. No matter what key (combination) I press, that's what it becomes. Same with all the other menu entries, so I assume I've stumbled onto a "key shortcut reprogramming functionality" I wasn't aware of. I assume this is documented somewhere? I checked the available documentation yesterday, to find a way to change the Shift+Z, but I couldn't find any.

Never mind then. I changed it to F5 and Shift+Z now behaves as it should.

**Comment by monsta** [comment]
Yes, seems like menu was in some kind of "edit shortcut mode". The actual behavior of Print Screen would be... to do nothing in this case: you can't make a screenshot while you're in the opened menu. IIRC it's a limitation of GTK+ itself (or maybe even Xorg).

Now I wonder how to enter that mode deliberately... it's one of these things in MATE I still have to discover yet. :smile:

**Comment by grizzler0031** [comment]
Well, on my system Caja appears to be in that mode permanently...

**Comment by monsta** [comment]
Ah, there it is. Run ```mate-appearance-properties``` -> Interface tab -> Editable menu shortcut keys -> uncheck it. That should fix it, now you can press any shortcuts safely when a menu is opened.

**Comment by monsta** [comment]
I already forgot it was added at some point - no wonder, I never tried this feature :smile:

**Comment by grizzler0031** [comment]
I wish I hadn't "found" it (LOL!). Would have saved us both from wasting time.

Thanks.

By the way, I've got my screenshot with the menu open, now I no longer need it. Took a bit of fiddling with the delay function of the screenshooter though...

**Comment by monsta** [comment]
Yes, it's possible via delay option, I heard about that.
