### ISSUE TITLE
Recursive owner/group/permission setting does not work via open as admin

### ISSUE THREAD

**Issue by ge79so** [mate-desktop/caja#547]
To replicate:
Open a folder to which only root has access "as administrator" from context menu
Change owner, group, permissions of a subfolder and click "Apply Permissions to Enclosed Files"

Ownership/groups/permissions of enclosed files/folders are not changed, but should be.
caja 1.8.2 on ubuntu 14.04.4
##

**Comment by ge79so** [comment]
I think this is partly a duplicate of 

https://github.com/mate-desktop/caja/issues/537

but the problem extends to more than just permissions.

The default UID/GID for root on Ubuntu seems always to be zero - it has been in this case.

sudo chown -R and chmod -R succeed

**Comment by flexiondotorg** [comment]
Duplicated of #537.
