### ISSUE TITLE
Move to wastebasket (or view trash?) fails via "Open as admin"

### ISSUE THREAD

**Issue by ge79so** [mate-desktop/caja#548]
Open a folder to which only root has access with "open as admin..." on context menu
make a copy of a file and move the copy to trash
Apparent success, but...
Trash cannot be opened - "operation not supported"
File does not appear in normal user's wastebasket and appears to be unrecoverable.

**Comment by ge79so** [comment]
caja 1.8.2 on ubuntu 14.04.4

**Comment by monsta** [comment]
It's in gvfs: https://bugzilla.gnome.org/657055

You can access root's trash folder manually though, it's in ```/root/.local/share/Trash/```.

**Comment by raveit65** [comment]
As root you can use the command line tool 'trash-cli'
