### ISSUE TITLE
Compact icons view in Caja-Mate

### ISSUE THREAD

**Issue by colibris79** [mate-desktop/caja#550]
I am using Linux Mint 17.3 64 bit. In caja, if I change the icons view to compact layout and I open a few folders the icons show in compact mode. After unchecking that option all the folders I have opened in the compact view before, remain in contact view. Restarting caja or the computer doesn't change the view in this folder (it is stuck in compact view)

**Comment by raveit65** [comment]
This is a per folder setting, you need to reset that for every folder.

**Comment by colibris79** [comment]
Thanks, I thought the general settings should go over per folder settings
