### ISSUE TITLE
move across rows with left/right cursor key in icon view

### ISSUE THREAD

**Issue by arxo** [mate-desktop/caja#553]
Navigating the icon view would be much easier if you could use the left/right cursor keys to switch to the previous/next item even at the borders of a row (right now, navigation stops at the borders of the current row instead of continuing on the previous/next row - you have to move up/down manually).

**Comment by phisigma** [comment]
I just switched to Mate/Caja a few days ago, and indeed, I miss this feature, that is default in most other file managers (?), very much.
I see no reason for not doing it this way, and it would fit better to the behaviour when marking items via Shift + arrow keys over several rows.

Is there a quick workaround for this?

**Comment by kn00tcn** [comment]
that is interesting, arrows work fine for me in 1.14.1, from the last item it moves to the first item of the next row, & then back to the last item of the previous row, etc

maybe this is an obsolete request? what version are you two running?

**Comment by phisigma** [comment]
1.12.7. And yes, this ticket seems to be obsolete. I just ran caja under Debian testing and this feature is implemented there.

**Comment by arxo** [comment]
I am running 1.14.1 and it does not work. However my build from the Ubuntu MATE PPA uses GTK2, not GTK3, so maybe that makes a difference.

**Comment by flexiondotorg** [comment]
This issue only affects builds against GTK2+. When Caja is built against GTK3+ it works as requested.

**Comment by flexiondotorg** [comment]
@raveit65 @monsta Are we going to fix this for Caja when built against GTK2+? If not, this can be closed.

**Comment by raveit65** [comment]
improbable

**Comment by monsta** [comment]
Sounds like a missing feature in GTK+2 widget. I think we'll move to GTK+3 for 1.18 release anyway.

**Comment by arxo** [comment]
I'm fine with closing this if it works in the GTK+3 build.
