### ISSUE TITLE
Deprecation dev talk

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/caja#562]
New issue to discuss dealing with remaining deprecated widgets etc in Caja. Still some nasty messes in eel-background.c, some of which will require changes to mate-desktop to fix. I'm guessing that some of the problems with custom backgrounds for folders that do not work come from problems in this file.

The use of GtkStyle in eel_background_ensure_realized is not easily ported to GtkStyleContext, as the necessary colors (no matter which ones selected)  come up as missing style properties in the information sidebar when running from terminal. This acts like  self->details->widget does not yet have ANY style properties at that stage in the code, yet when GtkStyle is used style->base[GTK_STATE_NORMAL];  and style->bg[GTK_STATE_NORMAL]; seem to work, as the info panel can be drawn in themes that won't draw its background properly when this function is broken.

Also a GdkColor vs GtkRGBA conflict, resolving that is an issue that affects mate-desktop as well. Big ugly mess. There is another instance of GtkStyle in this file but that one seems to be more easily fixed and generated no obvious problems in testing.
##

**Comment by raveit65** [comment]
I created a branch for that https://github.com/mate-desktop/caja/tree/dev-style-context
With 2 commits where i sorted the 2 remaining files a bit for better reading.

**Comment by lukefromdc** [comment]
I just built and tested the dev-style-context branch and can confirm that it behaves the same as before. Hopefully this code will be easier to work on, I got nowhere last night

**Comment by lukefromdc** [comment]
We've got a new deprecation to worry about, courtesy of GTK: gdk_cairo_create, which appears all over caja, mate-panel, and mate-applets.  Keep in mind that when they fork GTK4 they probably remove all the deprecated stuff. They promise GTK4 will be stable but they've deprecated so much stuff it will take years for everything to catch up.

**Comment by raveit65** [comment]
Well, i'm thinking the same as you that we need to fix all the deprecated stuff. After i finished with mate-terminal i will start with that one here.
I'm also a bit in worry about missing port GtkTable to GtkGrid of some files in caja. Because GtkTable is deprecated since 3.0.
caja-window.c
caja-navigation-window.c
caja-spatial-window.c
caja-property-browser.c
There are commits in nautilus for it but i wasn't lucky to use them all, last year.
https://git.gnome.org/browse/nautilus/log/?qt=grep&q=gtkgrid

**Comment by lukefromdc** [comment]
That new GTK deprecation came with severe breakage it turns out. Caja background drawing is corrupted with failures to redraw on change and light shadow portions of icons full dark, Marco draws plain black decorations-on all MATE themes, stupidly forgot to test Adwaita but will later. Firefox draws a solid black window except for part of the address bar-and THAT one we can't fix. 

Just to develop against this requires rolling back Firefox to a GTK2 version, don't know if GNOME is going to revert or fix this or just expect all app developers to fix it. We can probably fix Caja and Marco (most of the rest of MATE including the panel is OK), but distros will have some ugly choices to make if Firefox stays broken and Mozilla is slow to fix it,

**Comment by raveit65** [comment]
I'm still wondering why functions gdk_cairo_create and gtk_widget_send_expose doesn't work any more, if it is only declared as deprecated.

**Comment by lukefromdc** [comment]
GTK devs tried and failed 3 days ago to fix the issues generated with the gdk_cairo_create 
https://git.gnome.org/browse/gtk+/commit/?id=222bcf1a71dbd879fe39bfb9239c093b1da6bb4d
https://git.gnome.org/browse/gtk+/commit/?id=0ca59bf85a13b8dc5b516d311df9c37e43566c1f
These didn't work, since then only ONE new commit to GTK: a translation update. Someone is probably trying to fix this, and if they can't do it they may have to roll back this mess just as I had to locallyl

**Comment by lukefromdc** [comment]
new PR to dev-style-context to replace all instances of gtk_cairo_create with cairo_create:
https://github.com/mate-desktop/caja/pull/574
No effect on the issue with the newest GTK3.21 but does avoid one of the new deprecations with no ill effects observed on this end

**Comment by raveit65** [comment]
closing this
