### ISSUE TITLE
Can't associate CD audio and DVD audio with softwares

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/caja#569]
Linux Mint MATE 18 beta 64-bit with Caja 1.14.1.

In Caja preferences :

1) DVD audio can be associated with nothing.

1) I installed Clementine. Clementine can be associated with all supports excepted “CD audio” (the association isn’t kept, “CD audio” stays associated with “Doing nothing”).

These 2 bugs are not present in Linux Mint MATE 17.3 64-bit with Caja 1.12.7.

![screenshot at 2016-06-12 21 19 16](https://cloud.githubusercontent.com/assets/3955499/15993356/807c70be-30e3-11e6-9492-adf3843108e7.png)

**Comment by monsta** [comment]
http://blog.linuxmint.com/?p=3038

> Please report bugs below in the comment section of this blog.

Is something unclear in that statement from Clem? :confused:

**Comment by clefebvre** [comment]
Hi,

I can't reproduce the issue with CD Audio:

- I install clementine, set everything as in the picture.. and everything stays like that then.
- clementine doesn't handle the audio CD mimetype so it doesn't appear as an option in the first combo. That's a bug on clementine though, not MATE.
- No application installed on the system handles the audio DVD mimetype, so there's no choice available in Action and the combo is greyed out.. that's not a bug.

Imo, this issue can remained closed.

**Comment by Petrouchka** [comment]
Thank you for the test and your answer. I will report this bug in Clementine bugtracker.
