### ISSUE TITLE
Feature Idea "Stackable File Format"

### ISSUE THREAD

**Issue by ulgrimar** [mate-desktop/caja#576]
Hi,
the idea is if you have many files in a directory with the same name (eg. mydog001.jpg until mydog999.jpg AND myhusband001.jpg until myhusband999.jpg) they show them as "virtual folder". It means you see just two vDirectorys "mydog" and "myhusband". If you click on "mydog" you see the files.
This would be helpfull if you have many files in one directory. I suppose this would be a good plugin, maybe not for the core itself.
##

**Comment by monsta** [comment]
This surely should be done in an extension, not in Caja code
