### ISSUE TITLE
Bulk rename files or folders.

### ISSUE THREAD

**Issue by Dorson** [mate-desktop/caja#588]
Caja is missing an essential feature for work.

The bulk rename is not possible at this point. Caja needs a working mass rename tool. It is very much required for anybody who renames hundreds of files, vacation photos or files for merging with the "cat" command.

So far, I have only seen the Thunar file manager that can do it under Linux natively:

http://www.freesoftwaremagazine.com/files/posts/screenshot1.png

There is an option for plugins or extensions, but there is no plugin that is maintained at this time. There are external tools, but it's not good, if an essential future is missing.

I ended up installing Thunar over caja, because I need to rename multiple files more than once a day for work.

How hard would it be to just copy the code over from Thunar or some other bulk rename tool ?

Here is the code example from the renamer tool of Thunar:

https://github.com/xfce-mirror/thunar/blob/master/thunar/thunar-renamer-dialog.c

I hope this helps someone a lot !
##

**Comment by jhasse** [comment]
There's now an extension for this: https://tari.in/www/software/cajarename/

**Comment by monsta** [comment]
Nice, that extension should help with this feature.

**Comment by flexiondotorg** [comment]
`caja-rename` is packaged for Debian unstable and Ubuntu 17.10 and newer.
