### ISSUE TITLE
Caja 1.14.1 sometimes segfaults when opened

### ISSUE THREAD

**Issue by smikkelsendk** [mate-desktop/caja#594]
Fedora 24 - Caja 1.14.1
The problem existed already when I was running Fedora 23, and have continued after upgrading to Fedora 24. Sometimes Caja segfaults when being started.

I have attached two core_backtraces that might help investigate what goes wrong.

[core_backtrace_1.txt](https://github.com/mate-desktop/caja/files/366878/core_backtrace_1.txt)

[core_backtrace_2.txt](https://github.com/mate-desktop/caja/files/366877/core_backtrace_2.txt)

**Comment by raveit65** [comment]
http://fedoraproject.org/wiki/StackTraces#gdb

**Comment by smikkelsendk** [comment]
For some reason I cannot reproduce when running from gdb or starting it manually from terminal. It has to be started either with menu: Places - Home/Desktop/Documents or by right clicking a torrent in Transmission and selecting Open Folder. I tried to add the --no-desktop option when running from gdb, but that did not seem to be enough to reproduce.

Here you can see the dmesg output showing the recent crashes.
[17099.098958] caja[14625]: segfault at 100000009 ip 00007fd08f7303c8 sp 00007fffe0370930 error 4 in libc-2.23.so[7fd08f6b4000+1b9000]
[17236.074419] caja[15183]: segfault at 100000009 ip 00007f2b4303b3c8 sp 00007ffcc3355d70 error 4 in libc-2.23.so[7f2b42fbf000+1b9000]
[17493.527674] caja[16584]: segfault at 100000009 ip 00007f0b5bf6a3c8 sp 00007fff2eebc7e0 error 4 in libc-2.23.so[7f0b5beee000+1b9000]
[17832.061129] caja[18463]: segfault at 100000009 ip 00007fbb905883c8 sp 00007ffdb33155f0 error 4 in libc-2.23.so[7fbb9050c000+1b9000]
[17969.252398] caja[18822]: segfault at 100000009 ip 00007fe6aa8643c8 sp 00007ffe4c565900 error 4 in libc-2.23.so[7fe6aa7e8000+1b9000]

**Comment by smikkelsendk** [comment]
Now I got some ABRT generated backtrace, maybe that can be more helpful.

The backtrace4.txt happened when i from ABRT clicked "Open problems data directory". So other programs opening Caja really seems to be triggering this. But it does not happen every time.

[backtrace3.txt](https://github.com/mate-desktop/caja/files/367200/backtrace3.txt)

[backtrace4.txt](https://github.com/mate-desktop/caja/files/367199/backtrace4.txt)

**Comment by smikkelsendk** [comment]
Now I got some more debug packages installed and got a coredump analyzed with gdb.
[gdb.txt](https://github.com/mate-desktop/caja/files/367203/gdb.txt)

**Comment by monsta** [comment]
Ok, so the stacktrace has only functions from other libs, including libglib, libdl and even libc. Caja just calls a function from glib, and then it goes out of our control. Please open a report about glib at Fedora bugzilla.

**Comment by smikkelsendk** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1357854

**Comment by smikkelsendk** [comment]
The problem seems to disappear as soon as I switch from NVIDIA to Nouveau driver (Using NVIDIA driver obtained from rpmfusion).
NVIDIA library is present in the backtrace, but I dont know exactly how that is messing up things.

**Comment by raveit65** [comment]
@smikkelsendk 
A tip from one of rpmfusion nvidia maintainer.
https://devtalk.nvidia.com/default/topic/522835/linux/if-you-have-a-problem-please-read-this-first/
How to debug and file out a report there.

**Comment by kn00tcn** [comment]
what about negativo's packaged driver? he might also have an idea if you mention the problem to him

**Comment by smikkelsendk** [comment]
After switching from NVIDIA driver provided by RPM Fusion to the official NVIDIA Driver installer, the problem has gone away. So maybe RPM Fusion has mixed incompatible kernel module and libraries, or done some unfortunate patch to the driver.

**Comment by kn00tcn** [comment]
it appears 367.35 came to rpmfusion a couple days after your initial post, also nv's site is at 367.44 at the moment, & your first backtrace seems to be 367.27

i should have asked you to specify exactly which versions since 'rpmfusion's driver doesnt work' is the wrong way to describe situations

i'm also wondering if you used kmod or akmod from rpmfusion
