### ISSUE TITLE
Middle Mouse scroll

### ISSUE THREAD

**Issue by ibjsb4** [mate-desktop/caja#595]
Kernel: 4.4.0-30-generic x86_64
Desktop: MATE 1.14.1
Distro: Ubuntu 16.10
Caja: 1.14.1-1

Cannot (horizontal) scroll caja files with mouse without pressing "Shift" key.
##

**Comment by Magician24** [comment]
Can confirm having the same issue. Middle mouse scroll not working in Compact View for horizontal scrolling without pressing Shift.

Running Ubuntu MATE 16.10 Release with Caja 1.16.

**Comment by monsta** [comment]
Scrolling in compact view is now fixed as of version 1.17.
