### ISSUE TITLE
crashes on jpeg2k preview

### ISSUE THREAD

**Issue by JazzMaster** [mate-desktop/caja#596]
I had a jpeg2 in my uploads folder and caja kept crashing. when I ls-ed the folder I saw the issue. Jpeg2k support is still dodgy at best in linux but gwenview can see them if they use standard method, nasa imagery and such dont use that.

delete the offender and caja works ok. support seems to be installed. problem is on jessie, stretch and ubu 16 dont seem to be affected, but have other nasties in store for you.

**Comment by monsta** [comment]
We don't support MATE 1.8 (which is in Jessie) these days.
