### ISSUE TITLE
crashes on super slow connections via sshfs

### ISSUE THREAD

**Issue by JazzMaster** [mate-desktop/caja#597]
was trying to update my website and I popped open a sshfs session as usual. well the linksys router was openwrt and non cooperative, leaving me with .07 of my bandwidth, as such ..dial up speeds on break-neck cable modem lines...well caja doesnt like that.

I would up wputting the file and smacking the router a very hard reset. none the less, an issue to look at..

**Comment by JazzMaster** [comment]
note to self: kepp the firmware at factory, not openwrt...GYAH!

**Comment by raveit65** [comment]
looks like an local issue?

**Comment by monsta** [comment]
Looks like an issue with unknown version of Caja :smile:
