### ISSUE TITLE
caja crashes every time on folders that contain music

### ISSUE THREAD

**Issue by bth73** [mate-desktop/caja#598]
Doesn't anybody test stuff before it goes out? Music files on computers - ever hear of it?

**Comment by raveit65** [comment]
yes, i've about 10 GB music on my disks and no problemes to browes them with caja
Looks like some of your files are corrupt or your disk is faulty.

PS: It is not wise to other people to insinuate error if you want to help

**Comment by lukefromdc** [comment]
No problems here either with mp3 files, .wav files etc. I use MATE in a video editing setup that was orignally an audio editor and never have seen this in GTK3 builds nor back when i used 1.6 or 1.8 with GTK2.
