### ISSUE TITLE
Caja for MEGAsync

### ISSUE THREAD

**Issue by nesfla** [mate-desktop/caja#599]
As we have a Caja Dropbox, could it be possible to have a Caja MEGASync for the ones using MEGAsync linux app (they have a nautilus app)?

**Comment by raveit65** [comment]
Well, i see distro installer packages but no link to the source code.
https://mega.nz/#sync!linux

**Comment by monsta** [comment]
It seems to be here: https://github.com/meganz/MEGAsync
But I doubt we'd be making an app for that... we're quite busy these days.

I'd make a feature request in their repo first.

**Comment by jemadux** [comment]
still no addon for caja ... sometimes i dont use mate for that reason ... the community not support it , megasync not support ..

**Comment by lukefromdc** [comment]
This I have to leave for others. I don't have accounts on most of the
corporate owned or ad supported sites and don't know much about
them.
