### ISSUE TITLE
caja use high cpu

### ISSUE THREAD

**Issue by kuchaguangjie** [mate-desktop/caja#606]
I am running linux mint mate 18.0 , when I refresh desktop with `F5`, it keeps in refreshing status (the icons on desktop is not showing), and there is a process called `caja` use 100% cpu, I need to reboot to solve this, and it happens from time to time.

Mint mate 17.2 don't have this issue, but 18.0 do, any idea ?
##

**Comment by raveit65** [comment]
Can you please file out a report at linunxmint first?
I can't reproduce this in in fedora with Mate-1.14, This looks like an installation or linunuxmint issue.
Thank you

**Comment by kuchaguangjie** [comment]
@raveit65 It seems there are similar issue in previous caja version years ago, refer to: https://forums.linuxmint.com/viewtopic.php?t=145959 , but it's declared fixed, I am wondering maybe some similar cause produce this issue.

Anyway, I reported a bug here: https://bugs.launchpad.net/linuxmint/+bug/1610895

**Comment by raveit65** [comment]
in forum report this mate report is mentioned.
https://github.com/mate-desktop/caja/issues/38
Which was caused by a issue with glib. This needs to be tracked down by linuxmint guys.

**Comment by mnestor** [comment]
I had this happen in 1.12 and 1.14 on Ubuntu 16.04 turned out to be caused by the background image not existing. Changed it to a valid image and the issue went away.

**Comment by rmeineke** [comment]
Have had this happen on my Ubuntu Mate machine any number of times...to the point of completely reinstalling the OS. Just happened across this thread and the comment left by  @mnestor immediately solved the problem for me. Thanks!

**Comment by sc0w** [comment]
I can confirm this issue

**steps to reproduce:**

with `system -> preferences -> look and feel -> appareance`

I set the background image on a .png file

in a terminal y rename the .png file with mv

y go to appearance again and I click in the name of the non existent file

cpu caja goes to 100%

click in another existent file, cpu caja is ok

**Comment by lukefromdc** [comment]
I just found that I cannot duplicate this with mate 1.19 from master as my overall MATE stack, Caja 1.19.0 from today's git master, and Debian Unstable with GTK 3.22.19 and glib 2.53.6. If I set an image as the background and delete the image, if the appearance window is still open the thumbnail simply gets replaced with the last horizontal gradient background to be set, and the former (and loaded) image continues to display at least as long as I ran this test. No high CPU use, though this is an 8-"core" AMD FX running the test.

**Comment by lukefromdc** [comment]
Finally managed to duplicate this, didn't catch the part that you have to go BACK to the non-existant file's filename. The appearance window correctly deletes the thumbnail, but Caja ramps up to about 1 core's worth of CPU divided among several cores. My guess is the code for finding the image loops or sticks on not finding it, so the fix is to include a sanity check for a missing image.

**Comment by kuchaguangjie** [comment]
I almost never change my background, the image should be there always.
In my case, it's when I press `F5` to refresh the desktop that the same issue occurs, though just occasionally, not always.

**Comment by sc0w** [comment]
seems the function `mate_bg_load_from_gsettings` doesn't work properly in mate-dekstop?

https://github.com/mate-desktop/mate-desktop/blob/76ba14c7c1d10952b0bf7037badbefc93bb643e5/libmate-desktop/mate-bg.c#L360

**Comment by monsta** [comment]
@sc0w: is the real issue in `mate_bg_load_from_gsettings`?

**Comment by sc0w** [comment]
@monsta probably, that function is called by mate-settings-daemon too:

https://github.com/mate-desktop/mate-settings-daemon/blob/6c076109eb3c0e4c0f4f197c45bf8a5d87df0db1/plugins/background/msd-background-manager.c#L351

https://github.com/mate-desktop/mate-settings-daemon/blob/6c076109eb3c0e4c0f4f197c45bf8a5d87df0db1/plugins/background/msd-background-manager.c#L308

but I can't experience similar bug with mate-settings-daemon, I think if the fix works, it is enough

**Comment by monsta** [comment]
There is some setting which makes m-s-d manage the desktop background instead of Caja, but it's usually off, so m-s-d doesn't do anything there.
