### ISSUE TITLE
Gtk+-3.21 desktop background-fade regression

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#612]
With gtk+-3.21 we have a regression left caused by a gtk+ change.
https://git.gnome.org/browse/gtk+/commit/?id=2c7b21718f18ab743cd79784ae28cad582f58503
With latest changes in caja and m-s-d this issue is mostly fixed.
https://github.com/mate-desktop/caja/pull/602
https://github.com/mate-desktop/mate-settings-daemon/pull/157
https://github.com/mate-desktop/caja/commit/8c926115c99100a581abfd20dced5dfbe4922792
https://github.com/mate-desktop/caja/commit/f5164f75918a8e65ccde9565c4fd9f366064172e

My current results:
- case with compositor and desktop icons.
  changing desktop backgrounds/wallpapers works but no fade effect.
- case w/o compositor and with desktop icons.
  changing desktop backgrounds/wallpapers works but no fade effect.
- case with compositor and w/o desktop icons.
  Changing desktop backgrounds/wallpapers works but no fade effect.
- case w/o compositor and w/o desktop icons
  Changing desktop backgrounds/wallpapers and background-fade works well. :smile:

Sounds like it isn't a big deal but it will break transition backgrounds which are the default in rhel/centos. Here are different colors used for night, morning, day, afternoon.
And we have the cosmos background slide show. 
##

**Comment by lukefromdc** [comment]
Cinnamon just got background-fade working as of version 3.2:  
http://segfault.linuxmint.com/2016/11/cinnamon-3-2-released/

Their libcinnamon-desktop/gnome-bg-crossfade.c is quite different than our mate-bg-crossfade.c and h. A direct replacement and changing all instances of "gnome" to "mate" with proper case did not yield a buildable result, but looking through this might find that problem where composited fades are reportedly rendered to a 3ed surface which is never displayed.

**Comment by lukefromdc** [comment]
Merging https://github.com/mate-desktop/caja/pull/731 will fix this now that that PR is debugged

**Comment by JosephMcc** [comment]
The background fade in Cinnamon is quite different. It's actually handled by muffin using Clutter. Not a solution that would work for you guys.

**Comment by raveit65** [comment]
Fixed with https://github.com/mate-desktop/caja/pull/731 for 1.18 and 1.16 branch.
All tarballs are released.
