### ISSUE TITLE
Desktop icons overlap when inserting external media

### ISSUE THREAD

**Issue by artgtan** [mate-desktop/caja#617]
I'm using Ubuntu MATE 16.04 / MATE 1.14.1.

Keep aligned is checked.

Inserting external media causes its icon to overlap on top of an existing icon for mounted drives.

This was previously described here:
https://bugs.launchpad.net/ubuntu-mate/+bug/1407381

I can provide screenshot if necessary.

**Comment by mratmartinez** [comment]
Some weeks ago I noticed this again. But it happened in this way:  
1) I plugged my cellphone, then the MTP icon appeared  
2) Plugged a USB flash drive and it appeared over the previous icon. So there are 2 icons in the same place.

I also can provide a screenshot if necessary.
