### ISSUE TITLE
gtk3: pressing f2 does not open the rename dialog. Also, the new folder dialog is not accessible with orca

### ISSUE THREAD

**Issue by coffeeking** [mate-desktop/caja#622]
steps to reproduce
Set caja to list view by pressing alt+v and then pressing l. Highlight a folder or file, it doesn't matter which. Press f2 to open the rename popup. The dialog should pop up and get the focus. Nothing seems to happen. Also, try pressing control+shift+n to create a new folder. The dialog does show up and is readable by orca, however it doesn't seem to get the focus, so typed characters aren't entered into the dialog, leaving an "untitled folder" item. Note that this only affects list view, icon view works as it should.
##

**Comment by kn00tcn** [comment]
your F2 test is also with orca installed/running? (is it a screen reader?)

i'm always on list view, F2 has never failed i dont think

**Comment by mhussaincov** [comment]
hi there,
gnome-orca is indeed a screen reader.
kendle, you recken a dbug.out may work to help Isolate the issue on orca's end?
could be a fallback incase it is a orca issue?
are there any d-bug tools that can be used with mate?
thanks,
Majid Hussain
thanks,
Majid Hussain

On 26/10/2016, kn00tcn <notifications@github.com> wrote:
> your F2 test is also with orca installed/running? (is it a screen reader?)
>
> i'm always on list view, F2 has never failed i dont think
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mate-desktop/caja/issues/622#issuecomment-256303197


-- 
kind regards,
Majid Hussain

**Comment by kn00tcn** [comment]
i'm just a regular user that tries multiple ideas & workarounds like a homemade QA, dont know much about debugging or how mate really works

one part of isolation is trying to see if something you specifically installed is causing problems, although sometimes it still ends up being unclear which side is having the problem

it's quite interesting that it's only on list view... i have an idea, try disabling every column except name in the caja preferences for list view, maybe F2 will work then, although the other difference i notice compared to the other views is that right arrow opens a tree of every item inside a particular folder

**Comment by lukefromdc** [comment]
On my setup with Caja 1.17(development branch), Orca not installed, and GTK 3.22, using F2 to open a rename dialog works fine in a list view. I have no idea if it worked or not in the past, because with my mouse-driven workflow I was unaware this shortcut existed until now.

**Comment by kn00tcn** [comment]
lolz? F2 has been rename in multiple OSs for many years (the way F5 is refresh, F1 is help, F11 is fullscreen), i would end up mixing mouse & keyboard depending on which hand is closer to end up working as fast as possible

actually in caja, it appears single left click does NOT rename like windows, so mouse workflow isnt even an option (opening a whole context menu or going to the top menu just to rename is not something that anyone should have to do repeatedly)

**Comment by lukefromdc** [comment]
I've normally used the right-click dialog for renaming, simply because I never used Windows long enough to know there was any other way from that source. This is one of the reasons mulitple testers are needed for packages: not all features are known to all users. Anyway, on my setup, click on a file and hit F2 and you get the rename dialog in all three views: icon, list, and compact. Caja 1.17/Gtk3.22

**Comment by raveit65** [comment]
Using F2 works here out of box in fedora 24 with caja-1.17/gtk+-3.20.
Do we speak about caja compiled with gtk2 or gtk3?

**Comment by kn00tcn** [comment]
i didnt say it was a windows only hotkey (but i dont know its history)

**Comment by monsta** [comment]
@coffeeking: so we need more info on this. Rename with F2 works for us like before.

**Comment by coffeeking** [comment]
hi

I'm so sorry I took so long. Using latest caja from git, the rename 
dialog works like it should, both in gtk2 and 3. Also, caja from latest 
stable mate, 1.16, also works as it should, in both gtk2 and 3. I've ha 
a lot of computer issues lately so I've been behind on my bug filing. 
It's been fixed now.

Thanks
