### ISSUE TITLE
Debian Unstable: GTK 3.21.5+Caja 1.14.2  bring back desktop redraw failure and segfaults

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/caja#627]
Debian Unstable just got GTK 3.21.5 so they could bring in the prerelease beta of GNOME 3.22. Since they are shipping MATE 1.14 with caja 1.14.2, the result is that caja is now broken.  

Unless something got backported to 1.14.2, this means the segfault caused by the information sidebar 
https://github.com/mate-desktop/caja/issues/540
and the desktop redrawing failure 
https://github.com/mate-desktop/caja/issues/604

will both affect any users of MATE on Debian Unstable updated as of Sep 1, 2016. Thus, Debian needs to either update for 1.15.4, or a point release of 1.14 needs to merge these commits in order to work:

https://github.com/mate-desktop/caja/pull/559 (sidebar segfauilt fix)
https://github.com/mate-desktop/caja/pull/607 (fix desktop redraw composited)
https://github.com/mate-desktop/caja/pull/607(fix desktop redraw noncomposited)
and these two cleanups:
https://github.com/mate-desktop/caja/commit/c7daae8ae33f89e99573f6303b707ff1475b34c8
removed too much of caja.css but got rid of a no longer needed portion
https://github.com/mate-desktop/caja/commit/e5cb35ed5701a28b7a91cf2919f8695f9c8776af
brought back the part needed for the compositing case.

Might be easier to do a 1.14.999 tarball from 1.15.4 for Debian?

**Comment by lukefromdc** [comment]
I have also submitted a bug report to Debian over this

**Comment by raveit65** [comment]
I've no idea and for me it is a bit crazy to want to switch to gtk+3, but do not use 1.15 releases where  the most fixes for  gtk3 are in.
......looks llike they are victims by their own update politics.

**Comment by raveit65** [comment]
@sunweaver

**Comment by lukefromdc** [comment]
Either they ship Caja 1.15.4 (perhaps calling it 1.14.99), we put out a special
tarball for 1.14, or MATE breaks on Debian Unstable and stays broken until
1.16 gets out. If that happens I will advise them to refer users to the 1.15.4
build on my Archive repo
https://archive.org/details/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme
Package is at 
https://archive.org/download/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme/caja-gtk3.22_1.15.4-11uke1_amd64.deb
but that link will break when master gets another version bump.It's replacement will
be the one to use then, though this one will then go into 'previous_versions."

They also shipped a broken version of libglib-2.0-dev today, breaking building
caja and who knows what else-anything needing a single missing .la file that
somehow get left out.

**Comment by Skamasle** [comment]
I upgrade today not see this :(

A lot of things broken, I solve some downgrade libgtk to 3.20 -> http://snapshot.debian.org/package/gtk%2B3.0/3.20.9-1/#libgtk-3-0_3.20.9-1

Some thing broken also display manager, some body know somethinig about that ?

System -> preferences -> hardware -> displays show a black screen

Screanshot -> http://imgur.com/a/Tgh4I

So is imposible change display back to laptop, no errors in logs :/

**Comment by lukefromdc** [comment]
I haven't had any trouble with the xrandr applet or application in the entire
GTK 3.21 development cycle, and I frequently rebuild GTK3 from git master
and would have seen this if it affected my own machine. Of course I was
also frequently recompiling mate-settings-daemon so if this is a compile
time issue it would go away when Debian ships a new build of the same 
package.

**Comment by gradinaruvasile** [comment]
I have 2 machines with Debian Stretch/Testing on them, on both caja crashes with GTK 3.21.5 and both have the black xrandr applet (the latter i think it's broken for some time prior to gtk 3.21).
Since then i use arandr for monitor setup.

**Comment by lukefromdc** [comment]
The crash is a segfault caused by the "information" sidebar's code in 1.14 containing a deprecated command that GNOME did not maintain properly so it segfaults. This is fixed in the 1.15 development series that will become 1.16/ For now I would suggest rolling back GTK to 1.20-or using 
caja-gtk3.22_1.15.4-11uke1_amd64.deb
and
mate-settings-daemon-gtk3.22_1.15.1git20160804-1luke1_amd64.deb   
https://archive.org/details/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme
If you use these you will have to replace ALL of the caja packages with the single "caja-gtk3.22" Debian package, and all of the mate-settings-daemon packages with the single "mate-settings-daemon-gtk3.22" package. Rolling back GTK3 and waiting for Debian to release MATE 1.16 might make more sense for you.

**Comment by lukefromdc** [comment]
The panel xrandr applet just broke here too, looks like a GTK3.21 update that
just came in. Try Arander, it works for now. Trying to start GNOME's xrandr
application got an error about not being able to get the display settings, though
I'll have to test that in GNOME to be sure it's not just because m-s-d and not
g-s-d is running. That used to work however...

**Comment by lukefromdc** [comment]
Just opened this issue for the xrandr capplet:
https://github.com/mate-desktop/mate-control-center/issues/251
and have confirmed that problem came from glib2.49.6 and not the GTK version.

**Comment by raveit65** [comment]
> I have 2 machines with Debian Stretch/Testing on them, on both caja crashes with GTK 3.21.5 and both have the black xrandr applet (the latter i think it's broken for some time prior to gtk 3.21).

 Sadly, debian Mate maintainers can but don't want to upgrade to 1.15 and want to wait for 1.16.
So, there is nothing what we can do here, as all is fixed by our side.
I suggest to file out a report at debian to wake up those guys.

**Comment by gaetanov62** [comment]
I had same problem after updating GTK and I'm not able to fix it. I would like to know for a repository update in Debian Stretch.

**Comment by lukefromdc** [comment]
You could manually install the caja-gtk3.22 and mate-settings-daemon-gtk3.22
packages from 
https://archive.org/details/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme

but this is not a Debian repo and I don't know of any Ubuntu PPAs either with development
versions of MATE. The two packages in question are checkinstall .debs containing all of
Caja in one package and all of mate-settings-daemon in the other. You can download
them and install them with "dpkg -i --force-all <path-to-package>". I do not know how to
set up an APT repo and don't have paid server space with root access anyway.

**Comment by xinomilo** [comment]
you could downgrade to previous working gtk versions from http://snapshot.debian.org/ and even use it as a debian repo (official).

**Comment by gaetanov62** [comment]
I have added snapshot repository but if I try to downgrade gtk  to a previous version the system wants to remove caja, mate-applets mate-desktop-environments mate-desktop-environments-core gdebi and many other gir1.2* packages.

**Comment by lukefromdc** [comment]
I do not have anywhere near the bandwidth to experiment with this by 
setting up a system from installers and have never installed MATE with
GTK3 from Debian's packages, having built my own from the start. Thus
I cannot help much with that. Using dpkg --force-all will install any package
from a .deb but you thin have to fix any breakage manually.

**Comment by gradinaruvasile** [comment]
Here we have a discussion about this topic and also the method of downgrading the needed gtl+ packages:
http://forums.debian.net/viewtopic.php?f=6&t=129703&sid=dfd36bb814d764900dc3db419a030423

**Comment by d-faure** [comment]
For the record, here's how I managed this:
* Edit `/etc/apt/source.list` with:

```
deb http://snapshot.debian.org/archive/debian/20160818T221621Z/ unstable main contrib non-free
```

* Update the package list, bypassing the expiration watchdog:

```
apt-get -o 'Acquire::Check-Valid-Until=false' update
```

* Install the offending packages with the desired version explicitely specified:

```
apt-get install libgtk-3-0=3.20.9-1 libgtk-3-bin=3.20.9-1 libgail-3-0=3.20.9-1 gir1.2-gtk-3.0=3.20.9-1
```

* Lastly,  instruct `apt-get` to keep these packages untouched by upgrades. Edit `/etc/apt/preferences` and pin-point the installed packages with a high enough priority:

```
Package: libgtk-3-0
Pin: version 3.20.9-1
Pin-Priority: 1001

Package: libgtk-3-bin
Pin: version 3.20.9-1
Pin-Priority: 1001

Package: libgail-3-0
Pin: version 3.20.9-1
Pin-Priority: 1001

Package: gir1.2-gtk-3.0
Pin: version 3.20.9-1
Pin-Priority: 1001
```

The `/etc/apt/source.list` file could then be edited to restore the original package source specification.

**Comment by gaetanov62** [comment]
Great d-faure, I have solved easily with your suggestion. Thank you a lot.

**Comment by lukefromdc** [comment]
I've set up a PR with a fix for the xrandr capplet (mate-display-properties) issue with glib 2.19.6 and later as in current Debian Unstable:
https://github.com/mate-desktop/mate-control-center/pull/252

**Comment by vereten** [comment]
Thank you d-faure

**Comment by xinomilo** [comment]
caja 1.16.0 has landed in Unstable, just upgraded, and everything seems to work ok.

**Comment by Skamasle** [comment]
Thanks for update :)

**Comment by lukefromdc** [comment]
I am now finally able to tell users of my Archive site they can pull their packages from Debian except for the theme, compiz, and network-manager-gnome packages.
