### ISSUE TITLE
File name mixup

### ISSUE THREAD

**Issue by burdi01** [mate-desktop/caja#628]
Seen with caja 1.15.4 from http://slackware.uk/msb/current/1.15/x86_64/ by willysr
Also seen with caja 1.14.1 from the mate PPA for Xubuntu 16.04.1

![screenshot](https://cloud.githubusercontent.com/assets/9949014/18198533/c7a7f784-70fc-11e6-9579-7691237f8c35.png)

**Comment by raveit65** [comment]
@willysr ^^^

**Comment by willysr** [comment]
Mine is 
```
willysr@desktop:/usr/share/icons/Tango$ ls -al                                                                                                               
total 36                                                                                                                                                     
drwxr-xr-x  7 root root 4096 Feb 27  2008 .                                                                                                                  
drwxr-xr-x 28 root root 4096 Sep  2 07:08 ..
drwxr-xr-x 12 root root 4096 Feb 27  2008 16x16
drwxr-xr-x 12 root root 4096 Feb 27  2008 22x22
drwxr-xr-x 11 root root 4096 Feb 27  2008 24x24
drwxr-xr-x 12 root root 4096 Mar  6  2009 32x32
-rw-r--r--  1 root root 6798 Mar  6  2009 index.theme
drwxr-xr-x 11 root root 4096 Feb 27  2008 scalable
```

**Comment by burdi01** [comment]
Grumpff: I see what the problem is! When I modify a "system" file I keep the original and a copy of the new version such that after an update I can reconstruct my version.
```
root@riposo:/usr/share/icons/Tango# diff index.theme{.orig,}
4c4,5
< Inherits=gnome,crystalsvg
---
> #Inherits=gnome,crystalsvg
> Inherits=hicolor,Adwaita,crystalsvg
495c496
< Name[en_US]=index.theme.orig
---
> Name[en_US]=index.theme.copy
root@riposo:/usr/share/icons/Tango#
```
When I use caja to copy/paste a new version to .copy caja changes the "internal" name. That is why I normally do a cli "cp -a index.theme{,.copy}, but obviously I did the caja thing at one point in the past ...

Thank you for responding.
Kind regards, Dick

**Comment by burdi01** [comment]
I assume this caja behavior to be as designed ...
:(
