### ISSUE TITLE
Caja doesn't launch on Debian Testing

### ISSUE THREAD

**Issue by FaTony** [mate-desktop/caja#636]
Package version: 1.14.2-1.

When I try to launch Caja, I get this:

(caja:10713): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2202:16: not a number

(caja:10713): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2202:16: Expected a string.

(caja:10713): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3157:14: not a number

(caja:10713): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3157:14: Expected a string.

(caja:10713): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3658:14: not a number

(caja:10713): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3658:14: Expected a string.

(caja:10713): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3959:62: Using one color stop with linear-gradient() is deprecated.

(caja:10713): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3992:61: Using one color stop with linear-gradient() is deprecated.

(caja:10713): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4008:61: Using one color stop with linear-gradient() is deprecated.

(caja:10713): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4024:59: Using one color stop with linear-gradient() is deprecated.

(caja:10713): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4038:62: Using one color stop with linear-gradient() is deprecated.

(caja:10713): Gtk-WARNING **: Theme parsing error: mate-applications.css:214:16: not a number

(caja:10713): Gtk-WARNING **: Theme parsing error: mate-applications.css:214:16: Expected a string.

**Comment by lukefromdc** [comment]
Theme parsing errors normally don't prevent an app from starting, I've
only seen that happen once, with a segfault on a deprecated item in
mate-utils with GTK 3.18 last year. These errors are coming from a theme
that uses the old font code with GTK 3.21. Try BlackMATE, you should not
get these errors but probably nothing else will change.

**Comment by FaTony** [comment]
Same thing, changing theme didn't solve anything.

**Comment by FaTony** [comment]
OK, this seems to be a duplicate of #540.
