### ISSUE TITLE
cannot launch caja

### ISSUE THREAD

**Issue by carlzoo** [mate-desktop/caja#638]
When I click on computer, caja does not launch. Tried typing caja in terminal, the result is 
`(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3717:14: not a number

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3717:14: Expected a string.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3744:65: Using one color stop with linear-gradient() is deprecated.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4370:56: Using one color stop with linear-gradient() is deprecated.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4403:62: Using one color stop with linear-gradient() is deprecated.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4420:62: Using one color stop with linear-gradient() is deprecated.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4436:59: Using one color stop with linear-gradient() is deprecated.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4450:62: Using one color stop with linear-gradient() is deprecated.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:5793:17: Not using units is deprecated. Assuming 'px'.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:5793:17: Expected a string.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:5798:11: Not using units is deprecated. Assuming 'px'.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:5798:11: Expected a string.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:5833:17: Not using units is deprecated. Assuming 'px'.

(caja:3108): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:5833:17: Expected a string.

(caja:3108): Gtk-WARNING **: Theme parsing error: mate-applications.css:528:16: not a number

(caja:3108): Gtk-WARNING **: Theme parsing error: mate-applications.css:528:16: Expected a string.
`
but caja does not launch.
The operating system is Debian testing.

**Comment by raveit65** [comment]
Debian Mate mantainers needs to update to mate 1.15.x, file out a report there and ask for a update.
