### ISSUE TITLE
Feature request: Provide an option not to display folder size in list view

### ISSUE THREAD

**Issue by qazwsxedcgit** [mate-desktop/caja#642]
This is a feature request because of a usability issue. When displaying a folder containing a number of subfolders as well as files, with the "size" column enabled, as it is by default, caja will descend into subfolders to figure out how many items they contain.

If they contain many (> 100) items, if there are many subfolders, or both, it takes quite a long time to build up the list view. This long response time, while totally subjective, does slow down workflow.

The simple way around this would be to only display sizes of files, but not item counts of subfolders in the "size" column. This is for example what the Libreoffice file open dialog does. When displaying the same place in the file system in list view, it is noticeably faster than caja in list view.
##

**Comment by kn00tcn** [comment]
i forgot to make this request, yes i need an option to never count folder items

some of my fraps folders have tens of thousands of files, not to mention most OS folders

**Comment by kn00tcn** [comment]
I'M AN IDIOT, the option was there the whole time in caja settings>preview>folders count>never

dont know how long it's been there

**Comment by raveit65** [comment]
I hope you agree with closing the report.
