### ISSUE TITLE
Wrong font color (black) in caja-1.16.0 with dark background

### ISSUE THREAD

**Issue by nokangaroo** [mate-desktop/caja#643]
This seems to have an issue before. The font color of the filenames in icon view does not
change to white with a dark caja background color.

The following change in the mate-desktop package seems to fix it (at least for gtk2):
```
--- mate-desktop-1.16.0/libmate-desktop/mate-bg.c	2016-07-02 10:54:50.000000000 +0200
+++ mate-desktop-1.16.0/libmate-desktop/mate-bg.c	2016-09-29 14:02:02.296621080 +0200
@@ -1327,9 +1327,9 @@
 		g_object_unref (pixbuf);
 	}
 
-	intensity = ((guint) (color.red * 65535) * 77 +
-		     (guint) (color.green * 65535) * 150 +
-		     (guint) (color.blue * 65535) * 28) >> 16;
+	intensity = (color.red * 77 +
+		     color.green * 150 +
+		     color.blue * 28) >> 16;
 
 	return intensity < 160; /* biased slightly to be dark */
 }
 
```

This reverts the change from mate-desktop-1.14.1

Update: When I open 2 folders in 2 new tabs, the font color in the newly opened tabs
will still be black (most of the time, but not always).

**Comment by raveit65** [comment]
double posting !!!
