### ISSUE TITLE
drawing glitch when moving icons

### ISSUE THREAD

**Issue by Safari77** [mate-desktop/caja#645]
xrefresh fixes it.
caja 1.16.0, gtk 3.22.0.
![cajacap](https://cloud.githubusercontent.com/assets/3876865/19002281/f237d358-8753-11e6-8a34-3fa7d4921591.png)
[https://drive.google.com/file/d/0B9h02pRWKaODbzBfeG53Q1BYd00/view?usp=sharing]
download mkv to view, viewing in google does not work.

**Comment by lukefromdc** [comment]
I cannot use google services on my machines as they don't work right over
Tor and I am not willing to expose my machines to their trackers. Videos
can be uploaded to Archive.org, which uses no trackers and is not supported
by ads.

Is this the issue where the background appears distorted in the icon square
when the icon is being moved, then settles down when the icon is dropped?

I had that problem during the GTK 3.21 development cycle but have not seen
it recently. Are you using compositing or not? When compositing is not used
the background of the icon becomes the theme background color in GTK 3.22.
It was exceptionally difficult to get the desktop to work at all when GTK 3.21
introduced radical changes, then more work to get it to function without
compositing.

**Comment by Safari77** [comment]
I believe you described the same bug I have now.

Compositing is disabled, because if I enable it, I get tearing in video (mplayer opengl with Intel).

**Comment by lukefromdc** [comment]
I don't know of any way to fix that in GTK 3.22, those here who know more
about working with Cairo than I do might be able to come up with something
but it might be quite complex if it is doable at all.

**Comment by lukefromdc** [comment]
One solution to that is compiz with the right settings if you can install it.
Ubuntu's builds have messy issues with CSD apps when used with 
unpatched GTK 3.16 or later. I applied a patch Ubuntu rejected to 
create builds that work in Debian. If you are using Ubuntu MATE
though, install compiz and use it for the simplest fix.

**Comment by raveit65** [comment]
I don't see that here with 1.16 in fedora 25.
[rave@mother ~]$ rpm -qa glib2
glib2-2.50.0-1.fc25.x86_64
[rave@mother ~]$ rpm -qa gtk3
gtk3-3.22.0-2.fc25.x86_64

**Comment by raveit65** [comment]
Maybe an issue with graphic driver or mesa?

**Comment by Safari77** [comment]
With compositing (mate setting or using compton), when I move icon, it leaves a clone of the icon behind and xrefresh does not fix it ☺️

I don't think this is Intel driver bug, other programs do not have trouble..  I have Fedora 24.

**Comment by raveit65** [comment]
Hmm, i'm using f24 too.
Do you use my coprs repo?
https://copr.fedorainfracloud.org/coprs/raveit65/Mate-GTK3/
Here are latest 1.15 builds. I don't want update the repo to 1.16 to avoid upgrade path issue with f25.
Gtk3 builds starts with -11 as version to update normal fedora repos.
But there is no real different between latest 1.15 and 1.16, except translation updates.
Maybe you have a bit time to install a f24 VM with the coprs repo to confirm the issue.

**Comment by raveit65** [comment]
> xrefresh fixes it.
caja 1.16.0, gtk 3.22.0.

You did update f24 to gtk+-3.22 by hand?
W/o rebuilding half fedora i wouldn't do that.

**Comment by Safari77** [comment]
There were not many packages to rebuild in addition to gtk3 and mate* , maybe two

**Comment by raveit65** [comment]
A lot of packages are build for gtk+-3.20 in fedora 24.
Anyway, i don't have the issue in f24 with gtk+-3.20.9 and as i said before i don't have it with f25 and gtk+-3.22.

**Comment by lukefromdc** [comment]
The screenshot shows what looks like the utterly nasty results of building Caja 1.15/1.16 with GTK 3.20 or earlier and then updating GTK to GTK 3.22. Same as using Caja 1.14 or earlier with GTK 3.22, as the changes to get the desktop to work with GTK 3.22 were put behind build time selectors to avoid regressions in GTK 3.20 or earlier builds. This was particularily important because the first generation fix (based on Nautilus code) only worked with compositing and later commits handled the noncomposited case.

Build order is thus important in this kind of manual update! If you built caja before you built and installed GTK 3.22 (over 3.20), this visual glitch is exactly what would be expected.

**Comment by Safari77** [comment]
I didn't know about this gtk compatibility bug. But caja works ok after I recompiled it! Thanks.

**Comment by lukefromdc** [comment]
That's what is has to have been. When you recompiled against 3.22, you brought into use the GTK 3.22 compatabiltiy changes. Your sucessful fix by recompiling confirms it.

**Comment by raveit65** [comment]
> There were not many packages to rebuild in addition to gtk3 and mate* , maybe two

maybe snow....maybe rain :)

**Comment by raveit65** [comment]
I just updated the gtk3 repo to 1.16 for f24/23/rhel7/centos7 and other rhel clones.
https://copr.fedorainfracloud.org/coprs/raveit65/Mate-GTK3/builds/
Honestly, why not testing f25 alpha with Mate gtk3 and gtk+-3.22 from regular fedora repos?
