### ISSUE TITLE
start menu shortcuts created by wine are unusable

### ISSUE THREAD

**Issue by unxed** [mate-desktop/caja#648]
steps to reproduce
1. download any windows application, for example, faststone image viewer from here:
   http://www.faststone.org/FSViewerDownload.htm
2. install using wine
3. try to open installed app from start menu
4. it will result in "file not found" message

corresponding wine's issue:
https://bugs.winehq.org/show_bug.cgi?id=41439
##

**Comment by unxed** [comment]
Not reproducing in Linux Mint 18.1 MATE x64 running Wine 1.8.

Can someone retest it?

**Comment by monsta** [comment]
How is it related to Caja?
