### ISSUE TITLE
caja version 1.16 build fail with mate-desktop-1.16.0 in gtk+2

### ISSUE THREAD

**Issue by bhzhu203** [mate-desktop/caja#655]
CC       check-program.o
  CCLD     libeel-2.la
  CCLD     check-program
./.libs/libeel-2.a(eel-background.o): In function `init_fade':
/root/mate2/mate-desktop-1.16.0/caja/eel/eel-background.c:585: undefined reference to `mate_bg_crossfade_set_start_surface'
/root/mate2/mate-desktop-1.16.0/caja/eel/eel-background.c:579: undefined reference to `mate_bg_get_surface_from_root'
/root/mate2/mate-desktop-1.16.0/caja/eel/eel-background.c:580: undefined reference to `mate_bg_crossfade_set_start_surface'
./.libs/libeel-2.a(eel-background.o): In function `eel_background_ensure_realized':
/root/mate2/mate-desktop-1.16.0/caja/eel/eel-background.c:440: undefined reference to `mate_bg_create_surface'
./.libs/libeel-2.a(eel-background.o): In function `set_root_surface':
/root/mate2/mate-desktop-1.16.0/caja/eel/eel-background.c:536: undefined reference to `mate_bg_set_surface_as_root'
/root/mate2/mate-desktop-1.16.0/caja/eel/eel-background.c:531: undefined reference to `mate_bg_create_surface'
./.libs/libeel-2.a(eel-background.o): In function `fade_to_surface':
/root/mate2/mate-desktop-1.16.0/caja/eel/eel-background.c:606: undefined reference to `mate_bg_crossfade_set_end_surface'
collect2: error: ld returned 1 exit status

gtk+2 version   2.24

**Comment by monsta** [comment]
That means you're trying to build Caja with GTK+3 while linking it against GTK+2 build of libmate-desktop. That won't work.

**Comment by bhzhu203** [comment]
No , I mean I want build Caja with GTK+2 in default command line " ./configure --prefix=/usr/  --sysconfdir=/etc  --localstatedir=/var" the same as building mate-desktop package,mate-desktop is linking against GTK+2.

Why i dont want to build caja with GtK+3? Because mate-desktop with Gtk+3 doesn't
 work well yet, like  drop-down menu  not woring . Thanks.

**Comment by monsta** [comment]
Caja uses ```mate_bg_crossfade_set_start_surface``` and other mentioned functions only in GTK+3 build. This error simply can't happen in GTK+2 build.

**Comment by bhzhu203** [comment]
Maybe something wrong in configure sript ?
My system is x86-64 LFS, and there are GTK+2 and GTK+3 installed.

Here are config logs.

[config-mate-desktop.txt](https://github.com/mate-desktop/caja/files/522202/config-mate-desktop.txt)
[config-caja.txt](https://github.com/mate-desktop/caja/files/522203/config-caja.txt)

**Comment by bhzhu203** [comment]
I have found out what happened
 there.   
First  I  search “gtk” word in the  configure  script  , it shows that : 
  2.0) GTK_API_VERSION=2.0
       GTK_REQUIRED=2.24.0
       GAIL_API_VERSION=
       LIBUNIQUE_VERSION=1.0
 But I have libunique-3.0 installed .So I uninstall the libunique-3.0 and install libunique-1.0, finally caja build suceed.   

Thanks.
