### ISSUE TITLE
drag & drop icon on desktop, ghost icon shows.

### ISSUE THREAD

**Issue by zhangn1985** [mate-desktop/caja#656]
attached is 7zipped video grabbed by ffmpeg, during drag & drop.

please check the left-top of the video.

[out.avi.zip](https://github.com/mate-desktop/caja/files/520920/out.avi.zip)

or, here is some detail in the video.

![out_0001](https://cloud.githubusercontent.com/assets/832666/19257909/0fdc0c9e-8fa6-11e6-8575-b69e724c600c.png)
my test OS and Mate desktop.

begin drag:
![out_0988](https://cloud.githubusercontent.com/assets/832666/19257928/3d87ca8e-8fa6-11e6-8143-a2f6d40b034f.png)

ghost icon shows, on left-top:
![out_0989](https://cloud.githubusercontent.com/assets/832666/19257931/4f04c35c-8fa6-11e6-89dd-63981e38ea08.png)

also exists on debian testing, Mate 1.16

**Comment by lukefromdc** [comment]
A lot of video artifacts there, I really could not see ghost icons left behind
but rather ghosting around everything in the video. Was this a video issue?
If that's what your desktop looks like I would suspect a video driver issue or
possibly a window manager issue.

Was this with or without compositing, and if not using Marco what window 
manager?  Sometimes I will see a faint distortion of the background around
an icon while moving it, but not very often anymore. Used to be common
earlier in the 1.15 cycle when Caja was first ported to what was then GTK 3.21
but now I rarely see that.

**Comment by zhangn1985** [comment]
use Marco with compositing.
the ghost icon shows only very short time maybe around 17ms.
you can decode the video into png, and check it pre-frame, you can find the ghost icon.

also in this file, left-top:
https://cloud.githubusercontent.com/assets/832666/19257931/4f04c35c-8fa6-11e6-89dd-63981e38ea08.png

**Comment by zhangn1985** [comment]
this also happens when disable marco compositing.

**Comment by lukefromdc** [comment]
I'm using compiz normally and don't see it at all. Same in a test in Marco. 
Possibly 17ms is too fast for me to see, possibly your monitor ghosts 
images that long? All LCD monitors generate some ghosting due to a finite
fade time-and some of the expensive ones liked by photo editors are disliked
by gamers because they trade fast response for color accuracy.

**Comment by zhangn1985** [comment]
:-)

**Comment by zhangn1985** [comment]
on debian testing
![out_0434](https://cloud.githubusercontent.com/assets/832666/19292440/a5768d9e-904e-11e6-9f8c-e6ba13fc64a2.png)
magic selection... happens after drop

![out_0512](https://cloud.githubusercontent.com/assets/832666/19292447/b9ca579e-904e-11e6-8106-cb630be8f92d.png)
ghost icon happens at beginning of drag.

update in case someone has e.......

**Comment by zhangn1985** [comment]
and the video I just grabbed.
[out.mpg.zip](https://github.com/mate-desktop/caja/files/523185/out.mpg.zip)

once again, please decode it into png file, then you can find what happens.

**Comment by lukefromdc** [comment]
That REALLY looks like monitor ghosting-except that a screenshot would not capture what is an analog phenomenon happening after the digital circuits are done doing their job. The video has a lot of flicker to it, much more than I usually get in a screenshot video. 

I cannot duplicate this on Debian Unstable and have never observed anything like this on my hardware. What hardware are you using, what video drivers, and what kind of video connection? The flicker and general artifacts look a lot like what a bad case of external RF interference with a VGA connected monitor would look like, except only a video camera would pick that up. Unless you only get that in the video, you've got bigger problems with your video setup. If its just the video, an interaction between the capture framerate and the monitor framerate may be the culprit in the video quality, None of those would be cause by Caja. 

As a test, try installing Nemo or Nautlius, then turning off desktop icons in MATE. For that open deconf-editor, and set org>mate>desktop>background>show-desktop-icons to false. Then in terminal run either "nemo" or "nautilus-desktop" depending on what you just installed and move some icons around. The code for rendering the background is almost exactly the same, so you should also see the same results.

If this is being captured by a screenshot video and not a camera, video drivers may be to blame, I don't see anything in Caja's code that could do this.

**Comment by zhangn1985** [comment]
captured by ffmpeg (x11grab), not by any external camera.
two machine are intel video card, drivers from debian/ubuntu repo, default xorg.conf.

**Comment by lukefromdc** [comment]
My guess than is video drivers, I've heard plenty of bad things about Intel video drivers. If not that I have no further idea, but try the Nemo/Nautilus test. It's only anything in MATE if those give different results.

**Comment by zhangn1985** [comment]
sorry for your time.

**Comment by kn00tcn** [comment]
OP is trying to show how the currently dragged icon flickers on the top left for one frame when the dragging starts, it's seen in that last screenshot, it's not about monitor ghosting

i sometimes randomly see similar where a tooltip shows up on the top left corner of the screen instead of by my mouse cursor, i've even had firefox's addressbar dropdown start at the top of the screen instead of where the non-maximized browser window is (i use compiz)

**Comment by kn00tcn** [comment]
do you still see it? i think i see wrong positions of tooltips in xfce, so maybe it's a gtk issue
