### ISSUE TITLE
"show in folder" in chrome/chomium downloads just opens folder in caja, but does not selects particular file

### ISSUE THREAD

**Issue by unxed** [mate-desktop/caja#680]

**Comment by kn00tcn** [comment]
what version of mate, chrome, OS?

works in firefox, right?

**Comment by unxed** [comment]
chrome 54.0.2840.100 (64-bit)
mint 18 x64
mate 1.14

**Comment by raveit65** [comment]
Indeed the download isn't selected which works out of box with firefox.
Looks like firefox is the better browser :-)
Btw. i don't see that it is a Mate/caja issue if firefox can do that.
Does this work with a alternative file-browser as system default?

**Comment by raveit65** [comment]
Same with nemo or nautilus as default file-browser.
Due it doesn't work with any linux filebrowser i suggest to file out a report against google chrome.
Sorry, show me one browser where it works and i will re-open the report.

**Comment by kn00tcn** [comment]
i'm also curious about chromium or any of its forks

we still cant conclude if it's some too old or too new api issue, such as something that works in gnome3 but not 2

boy speaking of this, maybe caja's search->open parent location should highlight the file?

**Comment by raveit65** [comment]
> we still cant conclude if it's some too old or too new api issue, such as something that works in gnome3 

Does it work in gnome-shell?
I dn't see why mimetypes function should be different in gnome-shell.

**Comment by unxed** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=667042#
