### ISSUE TITLE
gtk3-migration-branch

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#683]
origin comment from @lukefromdc 
https://github.com/mate-desktop/caja/pull/618#issuecomment-261607255

Here are some anwsers to questions raised in commit comments that can be difficult to find because of the length of that page. They appeared under indivdual changed files, of which there are 105 listed.

1: A GTK_VERSION_CHECK inside a negation of it was found in the removal of the GTK3 selectors. This was almost certainly a result of using Pluma to replace all libunique selectors with GTK version selectors in the first commit. That gave very screwy results but somehow still built. That should all be gone with the next commit, the only remaining GTK_VERSION_CHECK instances should be those for specific GTK 3 versions. Those for 3.14 probably can go too, since previous discussion has indicated that only 3.14 and newer are to be supported and I've got configure.ac set up to require 3.14 or later

2: init_css was removed from caja-application.c because that function is in the removed libunique block, in the GtkApplication block the equivalalent function is called init_icons_and_styles as there is more in it

3: The caja-main.h file is not used in GtkApplication builds because the original Nautilus commits for GtkApplication removed nautilus-main.h and most of the porting was an application of these commits to Caja with only the changes needed
to accomodate changes in Caja since it was forked off.

**Comment by raveit65** [comment]
Ok, that makes everything clearer.
I added some corrections today, if you agree i will squash those commits to origin migration commit https://github.com/mate-desktop/caja/commit/f3963da1a001cef4df37aed4e96175e27736c6f2.
I suggest that another person, maybe @monsta, do a second review, as this is really a mega commit.

**Comment by lukefromdc** [comment]
Don't squash yet! The desktop is not rendering right, with icons showing only on the top edge. I am trying to bisect that right now

**Comment by monsta** [comment]
I'll check this tomorrow

**Comment by raveit65** [comment]
oh desktop is black......i will bisect

**Comment by lukefromdc** [comment]
Found the bad commit:
https://github.com/mate-desktop/caja/commit/aa919157cd5fafef16ff9279666e8fda0798e915
caja-spartial-window: don't use a define for deprecated gtk_{h/v}box_new

**Comment by lukefromdc** [comment]
I don't see how in the world that vbox/box change broke the desktop but that's the commit that came up bad on a bisect

**Comment by raveit65** [comment]
I was still wondering why i found deprecated line 'vbox = vbox = gtk_vbox_new (FALSE, 0); (FALSE, 0);' today.
But i recall that it has a reson why this line wasn#t ported, but i forgot it.....sorry to much commints here.
Without testing i thing reverting this line back will fix the issue, as the other deprecation 'gtk_hbox_new' was already replaced w/o the culprit commit.
Sec let me test to revert this single line.

**Comment by lukefromdc** [comment]
We won't find a fix for that in Nauitlus nor Nemo because the spatial window (upon which the Caja desktop is based) was removed prior to Nautius 3.0.

**Comment by raveit65** [comment]
Yeah, this line is the culprit.
I rebased the branch/commit, please test again.

**Comment by raveit65** [comment]
This is really a 1 billion dollar question why a simple deprecation fix does not work here and why the spartial window has an influence for the desktop.

**Comment by lukefromdc** [comment]
Ok, the rebased version works on the desktop with GTK 3.22. We might want to hold squashing until all reviews are finished in case someone has to bisect again for another bug. Then squash the whole mess before it merges to master

**Comment by raveit65** [comment]
```
    vbox = gtk_vbox_new (FALSE, 0);
    gtk_widget_set_hexpand (vbox, TRUE);
    gtk_widget_set_vexpand (vbox, TRUE);
```
Maybe using 'gtk_widget_set_vexpand' is forbidden with 'gtk_box_new (GTK_ORIENTATION_VERTICAL, 10);'

**Comment by lukefromdc** [comment]
The desktop window IS a spatial window, Nautilus changed it to a navigation window between 2.32 and 3.0.

**Comment by monsta** [comment]
That's really weird, that change shouldn't break the desktop :confused:

**Comment by monsta** [comment]
Huh... it's not the first time we hit this bug: https://github.com/mate-desktop/caja/commit/5968f6bb40c334a797175ebeeb946d76163ce288

**Comment by raveit65** [comment]
yeah, i forgot it :-)

**Comment by monsta** [comment]
@lukefromdc: should we convert desktop to navigation window some time later? Or would it bring some issues?

**Comment by monsta** [comment]
Added some corrections & cleanups to migration branch, hope I didn't screw anything up :smile:
They're meant for the future squashing of course.

**Comment by monsta** [comment]
Ok, looks good so far. I did only a quick test though, didn't check all Caja features...

**Comment by lukefromdc** [comment]
Conversion of the desktop to a navigation window is possible, but might break the spatial window option because right now any window opened from a navigation window is also a navigation window.  Also, any bug breaking spatial windows on the desktop should be checked to see if it also breaks normal spatial windows before deciding that converting the desktop to a navigation window fixes it.

If we remove spatial windows we lose a feature that we already have gotten at least one bug report on when someone wanted to use it and did not know how, thus there are users out there of that feature.

**Comment by monsta** [comment]
Ok, so this is not so simple...

**Comment by monsta** [comment]
I hope I'll get to merging migration branches for base packages (libmatekbd, mate-desktop...) tomorrow - unless @raveit65 finds some bugs in them. :smile:

Then we can get to merging this migration branch as well.

**Comment by raveit65** [comment]
I do not really understand why someone use the spartial mode, but as caja is the only browser who support this very rare case of usage we should not drop it w/o a good reason.

**Comment by raveit65** [comment]
I re-checked mate-desktop https://github.com/mate-desktop/mate-desktop/commit/8a956aff7c687459cf40d18dfb8dee68bc13d1c6 and found a few issues in mate-rr-labeler, see my comments on commit.
For mate-bg.c i removed some forgotten gtk2 bits.

I think only testing if a package builds/install and works is not enough after a migration commit.
I will review all commits by hand and state here if it is done.
Using
```
grep -nr GTK_CHECK_VERSION *
```
and
```
grep -nr '#define' *
```
are useful wapons here ;-)

**Comment by raveit65** [comment]
And do we really need libmate-about ?
I think all packages use GtkAbout with gtk+-3.

**Comment by raveit65** [comment]
Libmatekbd commit https://github.com/mate-desktop/libmatekbd/commit/002845e5d9a1272b12dc493ea8b2426951069310 seems to be fine.
I tried it very hard but found no issue ;-)

**Comment by monsta** [comment]
I've removed ```mate_rr_labeler_get_color_for_output``` completely since it's not used in GTK+3 build of any package that depends on libmate-desktop.

Thanks for finding the missing GTK+2 bits - don't know how I missed that :smile:

**Comment by raveit65** [comment]
libmatemixer does not have any gtk2 only bits.
What about libmateweather?
libgnomeweather does not work with mate-panel yet and it shows for our capital city berlin only one weather station. We have 3.
If nobody minds i will start with a migration branch for libmateweather.

**Comment by monsta** [comment]
It's true that we use GtkAboutDialog everywhere, but it turned out that mate-about tool still uses our forked dialog. So I decided to convert it later and proceeded to migrate other packages.

**Comment by raveit65** [comment]
> So I decided to convert it later and proceeded to migrate other packages.

+1

**Comment by monsta** [comment]
I skipped migration of libmateweather as I still hope to adapt our applets to libgweather before 1.18. So for now I use ``` --with-gtk3``` for it.

**Comment by raveit65** [comment]
>  So for now I use --with-gtk3 for it.

Ok, i agree. Than i start with review m-s-d yet or do you want to merge another package first?

**Comment by monsta** [comment]
Better do a review first, it won't hurt :smile:

**Comment by raveit65** [comment]
m-s-d looks fine so far, except that i would exclude some changes into single commits, see my comments at https://github.com/mate-desktop/mate-settings-daemon/commit/ba7a493782e8dee6fab82fe0adb36108d00a078a

**Comment by raveit65** [comment]
mate-media seems to be fine.

**Comment by raveit65** [comment]
I found one confusion in https://github.com/mate-desktop/mate-panel/commit/3a3f3e5c1fd40ed8a06c2c98e2e04005b72e7124
Not sure if it is wrong, see my comment.
.....what a mega commit.

**Comment by monsta** [comment]
In m-s-d, ```draw_bg_after_session_loads``` function is only called with GTK+ < 3.22, hence the version check. I can move it to a separate commit, no problem.

With dconf changes it's even easier, it can be simply pushed to master (dconf < 0.13 is really old so that won't cause breakages).

**Comment by monsta** [comment]
In mate-panel, ```panel_widget_unrealize``` function is only used with GTK+ < 3.18, just like ```panel_widget_realize``` (which is above it).

**Comment by raveit65** [comment]
> In mate-panel, panel_widget_unrealize function is only used with GTK+ < 3.18, just like panel_widget_realize (which is above it).

I thought this is a bugfix, but i wasn't sure ;-)

**Comment by lukefromdc** [comment]
Just found one missed selector in eel-canvas.h using grep, will fix it now

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/commit/c5ab08e373499c1f889bbb7afef691db60f2fda0
takes out the last 3, 0, 0 GTK version selector. Grep still finds a torrent of GTK 3.16 and GTK 3.20 selectors that need to stay until nobody is using anything but the last version of GTK3, years away

**Comment by lukefromdc** [comment]
grep -nr '#define' * does not find any instances of VBOX or HBOX in caja dev-gtk3-migration as of now

**Comment by lukefromdc** [comment]
Just got a succesful build and run with GTK 3.16, so with my normal GTK 3.22 builds it looks like we didn't mess up the GTK3.xx(non-zero) version selectors we had to keep

**Comment by raveit65** [comment]
about marco https://github.com/mate-desktop/marco/commit/40e26ed6d0e9ef84522ad0723f630bd7d796beec
Looks like you add some extra jobs to this commit.
Sorry, at some places i don't understand this commit w/o an extra explanation.
But rest looks good.
I would prefer that everything which isn't a simple removal of the GTK_VERSION_CHECKS goes into an extra commit, for better understanding after some months/years.
We have so much commits from previous Mate devs which nobody else understand now without a documentation.
I know this is an extra work but we should avoid to work like this.
........but maybe it's only my poor coding knowledge ;-)

**Comment by raveit65** [comment]
> c5ab08e
takes out the last 3, 0, 0 GTK version selector. Grep still finds a torrent of GTK 3.16 and GTK 3.20 selectors that need to stay until nobody is using anything but the last version of GTK3, years away

Thank you, so caja is ready to merge to master now?

**Comment by raveit65** [comment]
In mate-screensaver https://github.com/mate-desktop/mate-screensaver/commit/030632057c5c65a46d218c9ed2ffed5277513c6e i found only one part which isn't clear for me see my comment.

**Comment by lukefromdc** [comment]
As far as I can tell Caja is ready, I'm using a buiild from this right now with no new issues but I'm only one tester.

**Comment by monsta** [comment]
Ok, let me check... so in mate-screensaver, ```get_best_visual``` is only called from ```get_best_colormap_for_screen``` which is for GTK+2 only. I can make a separate commit with placing ```get_best_visual``` inside version check block if you wish.

**Comment by monsta** [comment]
@lukefromdc: last time I tested Caja it seemed alright for me. I think you can squash & merge already.

**Comment by monsta** [comment]
Added some answers to marco commit (I felt they should be there in the context - for better explanation).

**Comment by monsta** [comment]
Let's wait for @raveit65. As for me, I'm fine with removing the branch as it's merged already.

**Comment by raveit65** [comment]
It's ok for me to remove the branch(es) as the commits were tested and they are in master. We can't test it more the minimize the risk of such big commits.

**Comment by lukefromdc** [comment]
Branch removed, closing this issue too

**Comment by monsta** [comment]
There's also ```dev-GtkApplication3``` branch left - is it needed now?

**Comment by raveit65** [comment]
hmm, the issue was fine for giving a hint about the state of a review for a package.
...i can re-open it if needed ;-)

**Comment by lukefromdc** [comment]
I will remove the dev-GtkApplication3 branch, it has done its job and nobody has had to bisect those commits. If it really came to that, I have source tarballs of every single change I ever made in that branch anyway.
