### ISSUE TITLE
CPU using 60%

### ISSUE THREAD

**Issue by kajzersoze** [mate-desktop/caja#686]
Updated caja to the latest git version and I've noticed a problem where cpu is using 60% on system startup, there is nothing in system monitor showing which process is causing it, when I kill the caja process with `'killall -9 caja'` cpu usage goes back to normal, right away I suspected commit 276eb145ce96d5f75f8d3901daf6310f60ddbb81 so I did some bisecting and indeed with this commit there's this problem while with 969e4d021fe49654fe6e5ee7e88c920fec126505 everything is okay. I tried this couple of times so it's 100%.
Also, I've noticed that prior to that culprit commit (276eb145ce96d5f75f8d3901daf6310f60ddbb81) you could see caja process in the system monitor even if caja is not opened, with that commit that's not the case anymore, there is one process with no name which I suspect is the caja (prior to that culprit commit there was no process with no name).

**Comment by lukefromdc** [comment]
I've not had that problem even once using GTK 3 all the way back to version 1.10. Check to make sure you are not thumbnailing a bunch of files, as that will do it.

**Comment by kajzersoze** [comment]
I never had that problem either, using gtk3 since it became available (forgot when that happened) , well I have two folders that I use, with pictures, one has 422 items and other 277, so yeah ok but again .. there's no that problem before that commit, so I don't know what to say.

**Comment by raveit65** [comment]
I don't see a process without name in system-monitor or top and cpu usage is fine here, not more than 4-8 % when i am browsing through different folders with a lot of files.

Do you see that with small folders?

Sadly this is a mega commit and migration branch is deleted.
Local i have this branch, here latest commit is 'test-eel-labeled-image: don't use a define for deprecated gtk_{h/v}box_new' before we rebased all in one commit. I think here are the last  1 or 2 commits from @lukefromdc missing.

**Comment by raveit65** [comment]
Ok, for 1 or 3 secs i saw a high cpu load if i am opening a folder with a lot of wallpapers. But only the first time.
The second i opened the folder cupu load is normal.
So it has something to do with thumbnailing images.

**Comment by kajzersoze** [comment]
It doesn't happen when I browse the folders, it just happens on startup, cpu usage is on 60% and it's stuck there for a long time (I think I left it for an hour) until I kill it.
I'm on gentoo, could be something gentoo specific for some reason, but I can reproduce it easily.

`EGIT_COMMIT=276eb145ce96d5f75f8d3901daf6310f60ddbb81 emerge -1 caja` - problem
`EGIT_COMMIT=969e4d021fe49654fe6e5ee7e88c920fec126505 emerge -1 caja` - no problem

**Comment by monsta** [comment]
> Also, I've noticed that prior to that culprit commit (276eb14) you could see caja process in the system monitor even if caja is not opened, with that commit that's not the case anymore, there is one process with no name which I suspect is the caja (prior to that culprit commit there was no process with no name).

Well that's really weird... @lukefromdc any ideas on that behavior?

**Comment by lukefromdc** [comment]
System monitor process naming would have changed because Caja now uses GtkApplication rather than libunique to force all invocations to a single process and send calls from subsequent invocations to that one process.  I have not seen the unnamed process ever, but on my system caja starts with the session,

**Comment by monsta** [comment]
Same here, I'm running latest Caja so it's with GtkApplication, and I see no unnamed process.

**Comment by kajzersoze** [comment]
Made 2 screenshots, because there is no room to feet them all in 1 screenshot
You can see in the 2nd ss the last process with no name, and that there is no caja process.
Also if you notice that blue bar applet (cpu load bar) is around middle, when I hover over it says 60%) and it stays like that until I kill caja process.

![t1](https://cloud.githubusercontent.com/assets/11412353/20635269/373951f6-b35b-11e6-865b-009a010a402f.png)
![t2](https://cloud.githubusercontent.com/assets/11412353/20635270/3c011dae-b35b-11e6-904a-4f31327ab62c.png)

**Comment by lukefromdc** [comment]
I cannot reproduce this and never once saw this during the entire development of the GtkApplication port. Sure that unnamed process isn't your thumbnailer? Keep in mind that mate-system-monitor does not update instantly.  if it's not your thumbnailer, possibly some kind of hang before
` g_set_prgname ("caja"); `
runs? Very, very little happens in the mainloop before that call with GtkApplication, so  an issue with the session calling caja should also be considered.

You might consider removing all traces of your caja install, then installing it again and seeing if you still get this. A simple test to see if it is something in your home directory is this: make a new user on your machine and log in as that user. There will of course be nothing or nearly nothing to thumbnail and no stale configuration settings.  See if you still get this problem. If you do, try moving your hidden (.xxx) directories to a backup folder and logging in. If no change, move all those directories back, if the problem is fixed configure your desktop anew.

**Comment by kajzersoze** [comment]
Already tried with a new user and it was the same thing, didn't move the folders though, I'll try that when I can and report back.

**Comment by lukefromdc** [comment]
If a new user did not fix this, moving the folders won't either.  Do you have any Caja extensions installed? if so which ones?  I absolutely cannot reproduce this. What versions of mate-desktop, mate-settings-daemon, and mate-session-manager are you using?

**Comment by kajzersoze** [comment]
Everything Mate is from the git.
Extensions I use :
![screenshot at 2016-11-26 02-33-38](https://cloud.githubusercontent.com/assets/11412353/20637233/fe04e5f0-b380-11e6-8883-885d0baee6a8.png)

**Comment by lukefromdc** [comment]
Test Caja with all extensions disabled, see what happens. If it starts normally, re-enable them one at a time. Here's my extension list:
Wallpaper, Atril properties, Engrampa, Gksu, Open Terminal, which includes all of yours except Send To

**Comment by kajzersoze** [comment]
Disabling all extensions didn't help, still happens.

**Comment by lukefromdc** [comment]
Are you running Caja with mate-desktop 1.17 as well? You mention updating caja,  what are your GTK version, glib version, and mate-desktop version? Version of mate-settings-daemon could also be an issue if you are using GTK 3.22.

A new install of all of mate from git master on another partition should definately NOT do this

**Comment by kajzersoze** [comment]
Interesting thing is that if I kill caja then cpu goes to normal, caja is listed in sys monitor (if started) , if not started then there's no caja and no empty name process.
Problem is only on startup.
After I reported a problem I went back to the previous commit which was good and then recompile to the bad commit to check something, then go back to the good one etc., but now I'll stay with this latest and see if the problem occurs after some time of usage. If it's just on startup I can live with that (killing it every time), until someone else experience this or we figure out what's going on with it.

**Comment by kajzersoze** [comment]
Already said that I'm using latest mate, so everything is 1.17, not just caja.
gtk is 3.22.4 , glib 2.50.2

**Comment by lukefromdc** [comment]
What is the underlying distro?  Also, try turning thumbnailing all the way off and see what happens on startup.  I'm running out of ideas myself. Can anyone else duplicate this here?

**Comment by lukefromdc** [comment]
One more clue that may help: can you post all mentions of caja in your xsession-errors file?

**Comment by kajzersoze** [comment]
Gentoo x64

```
(caja:17263): Gtk-WARNING **: Theme parsing error: gtk.css:3482:8: not a number
(caja:17263): Gtk-WARNING **: Theme parsing error: gtk.css:3482:15: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
(caja:17359): Gtk-WARNING **: Theme parsing error: gtk.css:3482:15: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
```

and then it repeats those lines until 

`(caja:18910): Gtk-WARNING **: Theme parsing error: gtk.css:3482:15: Using Pango syntax for the font: style property is deprecated; please use CSS syntax`

**Comment by kajzersoze** [comment]
Where do I turn off thumbnailing ?

**Comment by kajzersoze** [comment]
Setting "Show thumbnails" to "Never" didn't help, same thing happened.

**Comment by lukefromdc** [comment]
Setting to "never" does turn thumbnailing off. I see only theme errors in xsession-errors. Not much more I can do since I can't duplicate this for testing.  Can anyone else here duplicate this?

Seems to be some kind of issue with how caja is started-maybe a timing issue with something else? As a workaround, try having a script start with your session with just one line:

`killall caja`

so it can restart normally as you have reported. I have no idea what's doing this, but I've had nasty interactions between compiz and mate-panel that seem to be session startup timing issues and require similar workarounds in compiz.

**Comment by kajzersoze** [comment]
Hmm, yeah it could be compiz, though I don't have mate-panel problems.
Well, that's easily tested, I can replace compiz with marco.
I'll do that in a min and report back.

**Comment by kajzersoze** [comment]
Made two videos, didn't know where to upload them for this, if quality on that site isn't good let me know and I will host those files somewhere.
I made two videos because sometimes `killall -9 caja` isn't enough and you have to do it several times before it's finally killed, sometimes once is enough, so first video is doing it once and 2nd is killing it few times.

Video no.1 : https://vid.me/buNy
Video no.2 : https://vid.me/f5GE

Note that cpu usage is slightly higher because of recording, around 10%-15%

**Comment by kajzersoze** [comment]
Well, I solved this by removing filemanager from required-components-list in dconf, I don't need Caja autostarting anyway since I don't use it for desktop. Apart from that autostart issue there are no other problems. Now, why this happens only in my case remains a mystery, maybe future will tell.

**Comment by lukefromdc** [comment]
If you were not using caja for desktop, I assume you had org>mate>desktop>background>show-desktop-icons set to false?

**Comment by lukefromdc** [comment]
If you were not using caja for desktop, I assume you had org>mate>desktop>background>show-desktop-icons set to false?   If so I think I just found your bug: a restart loop. I set the caja-desktop file back to showing startupnotify-true and got the classic "million caja window buttons" restart loop symptom. This means some later change messed up the work I did in the GtkApplication port to ensure that so long as exit-with-last-window is set to FALSE this restart loop would not occur. Obviously this is not being properly applied, because Caja is doing the same thing with or without it. I'll look into that

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/commit/ddc5a987ce8bee804a83a72049217a6fcc5cf0c4
should put an end to this problem, it did in my testing. Note that the combination of show-desktop-icons=FALSE with exit-with-last-window=TRUE has always done this and will still do this.  To fix that would require disabling exit-with-last-window in a MATE session as the way GtkApplication works combined with how the libegg code works blocks setting the session manager to no restart unless done at the start of the mainloop, at which point the Caja settings have not yet been initialized.

**Comment by kajzersoze** [comment]
> If you were not using caja for desktop, I assume you had org>mate>desktop>background>show-desktop-icons set to false?

Yes, I had that set to false.

**Comment by lukefromdc** [comment]
OK, the restart loop was your bug. Can you test caja from git master today or after today (with
https://github.com/mate-desktop/caja/commit/ddc5a987ce8bee804a83a72049217a6fcc5cf0c4 ) to confirm this is fixed?

**Comment by kajzersoze** [comment]
I can, but I think you said that if I have no icons on desktop set, that it can't be fixed then ?
If that's the case then I don't see a point, I don't want icons on desktop.

**Comment by lukefromdc** [comment]
Caja running in "daemon" mode is used to do things like automounting flash drives if automount is turned on (as it is be default). Thus it needs to work with or without icons on the desktop. Before my last commit I was able to duplicate the restart loop by turning desktop icons off, now Caja works fine here with or without icons on the desktop

**Comment by kajzersoze** [comment]
I brought back filemanager in required-components-list, updated to latest git master.
I can confirm that ddc5a98 fixes this bug. There is no empty process name, no cpu eating, there is caja process listed and everything is fine.

**Comment by monsta** [comment]
Wow. I didn't even think of that setting being the cause. Probably because I never really tested Caja with it...
