### ISSUE TITLE
Segfault when browsing Windows Network if a server has an empty name

### ISSUE THREAD

**Issue by dougg3** [mate-desktop/caja#689]
I have tested on Ubuntu MATE 16.04 with caja 1.12.7 as well as Ubuntu MATE 16.10 with caja 1.16.0.

If a Samba server on the local network has an empty name, caja will segfault in eel_ref_str_ref. To reproduce:

1. On a different machine, install samba and manually set its NetBIOS name to an empty string by editing /etc/samba/smb.conf and adding this line under the [global] section:
    * `netbios name = ""`
2. On the other machine, restart nmbd:
    * `sudo service nmbd restart`
3. On your computer, run `smbtree -N` to verify that the other machine has an empty name. You should see a line like this, with emptiness after the \\\\:
    * `\\ ubuntu-mate-2 server (Samba, Ubuntu)`
4. Now, on your computer, browse to the Windows network in caja by going to Places -> Network and opening the "Windows Network" folder.
5. Open the folder corresponding to the workgroup that the other machine belongs to.
6. caja will segfault.

Here is the top of the stack trace:
    eel_ref_str_ref ()
    ?? ()
    caja_file_new_from_info ()
    ?? ()
    ?? ()

It's not necessarily uncommon for a server to have an empty name; [nmbd used to have a bug](https://bugzilla.samba.org/show_bug.cgi?id=10896) that would set the default provided NetBIOS name to an empty string if the computer's hostname was too long.

This exact same problem used to occur in Nautilus until it was fixed last year. [See this bug report and patch](https://bugzilla.gnome.org/show_bug.cgi?id=700507). It appears that the crash in caja manifests itself in a slightly different way, though, because naively applying the analogous fix to caja didn't seem to fix the problem when I tried it.

**Comment by kn00tcn** [comment]
i was thinking 'if empty string, insert name as 'untitled server' for example, but... what happens when multiple servers have the same name or same no name?

other DEs or distros or file managers or even browsers handle this fine?

**Comment by dougg3** [comment]
Based on my limited testing, if you have two servers with the same name, only one will appear in the list. This is repeatable in Mac OS X, Windows, and caja's network browsers, as well as smbtree -N.

Interestingly, I just discovered while testing tonight that the quotes I added to smb.conf to give it a blank name actually seem to be included as part of the server name, because Mac OS X's network browser shows the server's blank name as "" with quotes included, even though smbtree -N doesn't show the quotes.  Either way, OS X seems to handle browsing the no name server just fine. Windows 10 doesn't show the blank server in its list at all. I don't have easy access to older Windows versions for testing. In my opinion that's probably an acceptable way to handle this situation too. Nautilus just shows an icon with no label below it -- at least it did the last time I tested after they fixed the bug. caja segfaults.

Both Mac OS X and smbtree -N behave identically with multiple no-named servers: if two servers have the same no name, only one of the servers will appear in the list.

**Comment by kn00tcn** [comment]
i realized, the obvious thing to do is name untitled servers by their mac or ip address (or both)

**Comment by rbuj** [comment]
Someone from **Ubuntu QA** should check that this issue still exists on a xenial up to date system running samba, because I'm unable to reproduce the SEGV on Fedora 34.
- case 1: setting a large **netbios name** such as `XABCDEFGHIJKLMNOPQRSTUVWXYZ` it's replaced by `\0`, which is different to NULL. (has [this samba bug](https://bugzilla.samba.org/show_bug.cgi?id=10896) been fixed on xenial?)
- case 2: setting a null **netbios name** on xenial, setting `netbios name =` in smb.conf, causes a segment violation when browsing the network on caja 1.26 (is it an actual caja bug?)
- case 3: setting an invalid **netbios name** using not allowed characters such as "" (2x double quotation mark) on xenial, `netbios name = ""` in smb.conf, causes a segment violation when browsing the network on caja 1.26  (is it an actual samba bug?)

IMHO the display name cannot null as it's an inconsistency, a fact that is more harmful than beneficial.

### Test on Fedora 35
- case 1: no issue
```
[robert@localhost ~]$ sudo cat /etc/samba/smb.conf
# See smb.conf.example for a more detailed config file or
# read the smb.conf manpage.
# Run 'testparm' to verify the config is correct after
# you modified it.
#
# Note:
# SMB1 is disabled by default. This means clients without support for SMB2 or
# SMB3 are no longer able to connect to smbd (by default).

[global]
	workgroup = SAMBA
	security = user

	passdb backend = tdbsam

	netbios name = XABCDEFGHIJKLMNOPQRSTUVWXYZ

	printing = cups
	printcap name = cups
	load printers = yes
	cups options = raw

[homes]
	comment = Home Directories
	valid users = %S, %D%w%S
	browseable = No
	read only = No
	inherit acls = Yes

[printers]
	comment = All Printers
	path = /var/tmp
	printable = Yes
	create mask = 0600
	browseable = No

[print$]
	comment = Printer Drivers
	path = /var/lib/samba/drivers
	write list = @printadmin root
	force group = @printadmin
	create mask = 0664
	directory mask = 0775

[share]
        comment = My Share
        path = /home/robert/share
        writeable = yes
        browseable = yes
        public = yes
        create mask = 0644
        directory mask = 0755
        write list = user
[robert@localhost ~]$ sudo systemctl restart smb
```
![Screenshot at 2022-02-03 10-00-52](https://user-images.githubusercontent.com/10171411/152311884-f6fb4444-4b11-4747-ae64-2ff9f484a63d.png)

- case 2: no issue. It isn't displayed on the caja window after clicking on `Browse Network`.
```
[robert@localhost ~]$ cat /etc/samba/smb.conf
# See smb.conf.example for a more detailed config file or
# read the smb.conf manpage.
# Run 'testparm' to verify the config is correct after
# you modified it.
#
# Note:
# SMB1 is disabled by default. This means clients without support for SMB2 or
# SMB3 are no longer able to connect to smbd (by default).

[global]
	workgroup = SAMBA
	security = user

	passdb backend = tdbsam

	netbios name =

	printing = cups
	printcap name = cups
	load printers = yes
	cups options = raw

[homes]
	comment = Home Directories
	valid users = %S, %D%w%S
	browseable = No
	read only = No
	inherit acls = Yes

[printers]
	comment = All Printers
	path = /var/tmp
	printable = Yes
	create mask = 0600
	browseable = No

[print$]
	comment = Printer Drivers
	path = /var/lib/samba/drivers
	write list = @printadmin root
	force group = @printadmin
	create mask = 0664
	directory mask = 0775

[share]
        comment = My Share
        path = /home/robert/share
        writeable = yes
        browseable = yes
        public = yes
        create mask = 0644
        directory mask = 0755
        write list = user
[robert@localhost ~]$ sudo systemctl restart smb
```
- case 3: no issue. The **netbios name** is set to `""`, which is different to NULL and `'\0'`

![Screenshot at 2022-01-31 09-26-12](https://user-images.githubusercontent.com/10171411/151761348-f11e816e-0138-4ca8-8deb-05ceaf712cbc.png)

```
[robert@localhost ~]$ sudo cat /etc/samba/smb.conf
# See smb.conf.example for a more detailed config file or
# read the smb.conf manpage.
# Run 'testparm' to verify the config is correct after
# you modified it.
#
# Note:
# SMB1 is disabled by default. This means clients without support for SMB2 or
# SMB3 are no longer able to connect to smbd (by default).

[global]
	workgroup = SAMBA
	security = user

	passdb backend = tdbsam

	netbios name = ""

	printing = cups
	printcap name = cups
	load printers = yes
	cups options = raw

[homes]
	comment = Home Directories
	valid users = %S, %D%w%S
	browseable = No
	read only = No
	inherit acls = Yes

[printers]
	comment = All Printers
	path = /var/tmp
	printable = Yes
	create mask = 0600
	browseable = No

[print$]
	comment = Printer Drivers
	path = /var/lib/samba/drivers
	write list = @printadmin root
	force group = @printadmin
	create mask = 0664
	directory mask = 0775

[share]
        comment = My Share
        path = /home/robert/share
        writeable = yes
        browseable = yes
        public = yes
        create mask = 0644
        directory mask = 0755
        write list = user
[robert@localhost ~]$ sudo systemctl restart smb
```

### Valid NetBIOS Name
It isn't NUL, in such case it isn't broadcasted. When it isn't set, it is automatically generated. It's 15 characters wide, and the following characters are allowed: alphanumeric characters a-z, A-Z, 0-9 and `! @ # $ % ^ & ( ) - ' { } . ~` characters

REF https://www.oreilly.com/library/view/using-samba/1565924495/ch01s03.html#ch01-SECT-3.2

**Comment by dougg3** [comment]
The long server name bug in Samba was fixed long ago, and I can confirm that xenial’s version of Samba is unaffected by it (unless you manually set an invalid name). My point is that the presence of a computer with an older, broken version of Samba on my network can cause my modern Caja to crash, and IMO that’s a Caja bug. Nautilus doesn’t crash in the same circumstance.

I don’t think it’s valid to test on one specific Fedora version and say the bug isn’t reproducible. Samba networking is much more complicated than that. Networking behavior changes based on what machines are on your network, especially with Samba. The instructions that I’ve provided cause a xenial VM to take over as the master browser. My videos are from a 21.10 VM on the same network. I have noticed the same behavior as you when newer OSes are the master browser, but when an older Samba is the master browser, which is a situation that’s definitely possible to happen because it’s an election process, the problem happens. That’s why my test instructions use 16.04 as the master browser. I’m confident your Fedora setup will also crash if you are on a network with a 16.04 master browser and an invalid name.  You do have to go inside the WORKGROUP folder inside Windows Network though — your screenshots aren’t in that location.

Keep in mind that gvfs caches things too, so if you make changes to the setup you have to kill gvfsd and Caja to retest accurately.

I do agree with what you’re saying about the quotes. Double quotes aren’t allowed in NetBIOS names. I think by specifying a name only containing double quotes, older Samba is stripping out invalid characters and leaving it as an empty string. Your screenshots seem to be an example of a newer behavior that does allow double quotes (maybe newer Samba protocol?)

**Comment by raveit65** [comment]
I will do some test with actual  RHEL/Centos long-term versions over the weekend.

**Comment by rbuj** [comment]
I ran the test on Fedora 34 and Fedora 35 because they are the supported versions of Fedora now. SMB1 is disabled by default on both versions of Fedora, so the workgroup is disabled.

I can't test samba on [Ubuntu 16.04 LTS](https://ubuntu.com/16-04) because it's supported until 2026 through Canonical’s Extended Security Maintenance (ESM).

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
```
```
# apt-get upgrade -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done

*The following packages could receive security updates with UA Infra: ESM service enabled:
  libpam0g libpolkit-gobject-1-0 libdjvulibre-text bluez libwebp5 libdns-export162 libqpdf21 dbus-x11 gstreamer1.0-alsa libisccfg140 intel-microcode libdbus-1-3 python-samba linux-libc-dev xserver-common vim-common libnss3-nssdb libcurl3 python-avahi libgrilo-0.2-1 gstreamer1.0-plugins-base-apps libpam-modules openssl bluez-cups imagemagick ntfs-3g libwbclient0 libsystemd0 linux-image-generic-hwe-16.04 libgd3 libavahi-glib1 libgs9 dbus samba samba-dsdb-modules libicu55 binutils libmagickwand-6.q16-2 squashfs-tools bind9-host linux-generic-hwe-16.04 libavahi-common-data dnsutils libavahi-common3 python3-pil libpython3.5 python3.5 openssh-sftp-server python3.5-minimal libpolkit-agent-1-0 libisc160 udev gstreamer1.0-plugins-base passwd libpam-runtime isc-dhcp-common libx11-6 libudev1 libwebpdemux1 libavahi-ui-gtk3-0 libaspell15 samba-libs apport gdisk imagemagick-6.q16 libmagickcore-6.q16-2-extra libisc-export160 libcaca0 python3-apport avahi-daemon samba-common systemd-sysv libavahi-core7 libgcrypt20 liblwres141 libglib2.0-bin liblz4-1 libpam-systemd libgstreamer-plugins-base1.0-0 distro-info-data libsndfile1 samba-vfs-modules avahi-dnsconfd gstreamer1.0-x ghostscript systemd login gir1.2-gst-plugins-base-1.0 libpolkit-backend-1-0 libwebpmux1 libpam-modules-bin openssh-server libx11-data ghostscript-x aspell libopenexr22 libsmbclient smbclient openssh-client samba-common-bin libmagickcore-6.q16-2 libgs9-common avahi-autoipd libdns162 qpdf libglib2.0-data bluez-obexd openjdk-8-jre-headless policykit-1 libdjvulibre21 apport-gtk libxml2 cpio libnss3 ca-certificates vim-tiny imagemagick-common libisccc140 avahi-utils linux-headers-generic-hwe-16.04 cron libpython3.5-stdlib linux-tools-common libbind9-140 libbluetooth3 libexiv2-14 libavahi-compat-libdnssd1 python3-lxml libpython3.5-minimal libavahi-client3 isc-dhcp-client avahi-discover python3-problem-report libglib2.0-0 libcurl3-gnutls libx11-xcb1 libssl1.0.0 tzdata
Learn more about UA Infra: ESM service for Ubuntu 16.04 at https://ubuntu.com/16-04

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by rbuj** [comment]
There is no SEGV on Ubuntu 18.04 up to date:

![silly-samba-test](https://user-images.githubusercontent.com/10171411/152523444-faa33c44-64b8-4621-9a8c-45f609beb90b.png)

**Comment by dougg3** [comment]
I don’t think you’re going to see the bug happen unless there’s a WORKGROUP. In that last 18.04 screenshot, the server showed up as “” which I believe means it’s using SMB2.

**Comment by rbuj** [comment]
`""` is also displayed when smb1 is used.

The screenshot below shows the samba status from the remote client through a ssh session.
(sambashare was mounted using `network:///` from caja).

<img width="1180" alt="Captura de pantalla 2022-02-05 a les 18 41 47" src="https://user-images.githubusercontent.com/10171411/152652884-d3a86c80-e7c4-4939-918e-e0b85a622a5b.png">

After clicking on "Windows Network" on Fedora 34/35:

<img width="955" alt="Captura de pantalla 2022-02-05 a les 19 01 31" src="https://user-images.githubusercontent.com/10171411/152653390-3ecb6b30-b1ce-41c9-b63d-f39d8f6863f2.png">

**Comment by dougg3** [comment]
Weird....when I test using Ubuntu following the directions from the pull request, I don't see the "". It shows up as smb-server- instead, and browsing the WORKGROUP works.

My goal here definitely isn't to waste everyone's time -- if you don't think this is a big enough issue to bother patching, we can just close this issue and pull request. I originally ran into this bug while at work 5 years ago, when I couldn't browse the WORKGROUP because Caja would crash. I tracked it down to a buggy Linux machine on the network that had one of the buggy versions of samba installed. I just wanted to patch it in case anyone else ran into the same situation I ran into.

**Comment by rbuj** [comment]
- In 2013, Microsoft marked SMB1 as [deprecated](https://docs.microsoft.com/ca-es/archive/blogs/josebda/the-deprecation-of-smb1-you-should-be-planning-to-get-rid-of-this-old-smb-dialect).
- The last supported Windows operating system that can only negotiate SMB1 is Windows Server 2003 ([deprecated as of 2015-07-14](https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2003-)). 
- The linux kernel 4.18 introduced the module parameter [disable_legacy_dialects](https://github.com/torvalds/linux/commit/f92a720ee9d5d4e76a9621ce0812aef133c7b981) four years ago. 
- In 2019, Samba 4.11 [disabled](https://wiki.samba.org/index.php/Samba_4.11_Features_added/changed#SMB1_is_disabled_by_default) the SMB1 protocol in the Samba server and client utilities by default. ([discontinued as of 2021-03-09](https://wiki.samba.org/index.php/Samba_Release_Planning#Discontinued_.28End_of_Life.29))
- The linux kernel removed definitely the support for NTLM and weaker authentication algorithms [17 days ago](https://github.com/torvalds/linux/commit/76a3c92ec9e0668e4cd0e9ff1782eb68f61a179c#diff-9da6c9cec14d939ab18e7037291932a32d5b394f6b74e1eb18b9c77909701bb6).
- In addition, the double quotes are not allowed in [NetBIOS computer names](https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou#netbios-computer-names).

**Comment by dougg3** [comment]
Closing because this issue is no longer reproducible on modern Samba networks.
