### ISSUE TITLE
new caja windows swallow the first typed letter

### ISSUE THREAD

**Issue by lagerspetz** [mate-desktop/caja#695]
This occurs at least on Linux Mint 18, and 18.1. This does not occur on LMDE2.

Steps to reproduce:
1. Open a new Caja window, for example from Mint Menu -> Home Folder.
2. Type "temp".
3. See that the box at the bottom contains only "emp" and "Templates" is not selected. 

What I expected to happen:
1. Open a new Caja window, for example from Mint Menu -> Home Folder.
2. Type "temp".
3. See that the box at the bottom contains "temp" and "Templates" is selected. 

inxi -Fz:
System:    Host: lagerspe-UX303LN Kernel: 4.4.0-21-generic x86_64 (64 bit)
           Desktop: MATE 1.16.1  Distro: Linux Mint 18 Sarah
Machine:   System: ASUSTeK (portable) product: UX303LN v: 1.0
           Mobo: ASUSTeK model: UX303LN v: 1.0
           Bios: American Megatrends v: UX303LN.204 date: 09/01/2014
CPU:       Dual core Intel Core i7-4510U (-HT-MCP-) cache: 4096 KB 
           clock speeds: max: 3100 MHz 1: 2013 MHz 2: 2001 MHz 3: 1594 MHz
           4: 812 MHz
Graphics:  Card-1: Intel Haswell-ULT Integrated Graphics Controller
           Card-2: NVIDIA GM108M [GeForce 840M]
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa) FAILED: nouveau
           Resolution: 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Haswell Mobile
           GLX Version: 3.0 Mesa 11.2.0
Audio:     Card-1 Intel 8 Series HD Audio Controller driver: snd_hda_intel
           Card-2 Intel Haswell-ULT HD Audio Controller driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.4.0-21-generic
Network:   Card-1: Intel Wireless 7260 driver: iwlwifi
           IF: wlp2s0 state: up mac: <filter>
           Card-2: Atmel
           IF: null-if-id state: N/A speed: N/A duplex: N/A mac: N/A
Drives:    HDD Total Size: 256.1GB (43.3% used)
           ID-1: /dev/sda model: SanDisk_SD6SB1M2 size: 256.1GB
Partition: ID-1: / size: 11G used: 5.4G (57%) fs: ext4 dev: /dev/sda8
           ID-2: /home size: 110G used: 91G (88%) fs: ext4 dev: /dev/sda7
           ID-3: swap-1 size: 8.39GB used: 0.00GB (0%) fs: swap dev: /dev/dm-0
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 57.0C mobo: N/A
           Fan Speeds (in rpm): cpu: 2200
Info:      Processes: 237 Uptime: 21 min Memory: 1945.1/7873.0MB
           Client: Shell (fish) inxi: 2.2.35

**Comment by lukefromdc** [comment]
This does not occur (cannot be duplicated) on my rather hacked Debian Unstable with GTK 3.22.5 and Caja 1.17.1

**Comment by kn00tcn** [comment]
boy that inxi dump is useless

so the first character (including numbers or shift+number to get a symbol) is always missing & it never jumps to the first item named after that character? what gtk version does mint use, i guess same for the debian one? what happens if you type really fast? (i have seen yumex-dnf with out of order characters when typing too fast for example)

**Comment by lagerspetz** [comment]
Hi,i also cannot replicate this on debian or mint Debian edition (based on debian stable). Mint 18 has this problem and uses the same gtk as Ubuntu 16.04.

**Comment by kn00tcn** [comment]
hey, you didnt specify if it's list/icon/compact view, are all three broken?

i think you need to make a bug report directly to mint if it's the only place it happens

seems like a common task to do in caja though, so wouldnt many other pepole have noticed? isnt mint one of the most widely used OSs? well... guess that would be mint cinnamon

**Comment by raveit65** [comment]
Linuxmint did not do what all other major distros  (fedora, ubuntu, debian) did.
Here we switched Mate complete to gtk+-3 with Mate 1.16 release.
Sorry, gtk+-2 isn't really supported anymore as we are a small team and the day have not 96 hours ;-)
So, linuxmint downstream is is responsable to fix issues if they do not follow upstream with Mate 1.16 release.
And i am really missing a link to a downstream report to be sure it isn't linuxmint distro specific.

**Comment by kn00tcn** [comment]
if i understood what i saw, fedora24 is gtk2 for some things, while f25 added more gtk3 things (that or the gtk theme got updated more... which would be weird, fragmenting users)

so fedora isnt fully gtk3 yet, although f24 is only supported for the next half year, makes me wonder about those annoying LTS distros that avoid updating things, what are they going to do over the next few years?

i saw some other thread that made me think of this one https://www.reddit.com/r/xfce/comments/5ljf8a/super_weird_and_annoying_ctrl_bug/ OP, is it possible you've got some 'compose key' or similar feature happening?

**Comment by lagerspetz** [comment]
Hi kn00tcn, I started thinking after reading your post, and checked my desktop machine. This behavior is not happening there, even though that is also Mint 18.1. However, it has not been updated to the latest packages yet.

Also, this is not happening on the laptop any more. Perhaps something was fixed by the Linux Mint folks. Thank you anyway.

**Comment by mahfiaz** [comment]
This bug is alive and well in Ubuntu 16.04 (which I intend to use for a few more years). The original reporter also saw it in the Ubuntu version of Mint.

I currently have installed:
caja-1.12.7
libgtk2.0-0:amd64-2.24.30-1ubuntu1
libgtk-3-0:amd64-3.18.9-1ubuntu3.2

**Comment by mahfiaz** [comment]
Report against Ubuntu: https://bugs.launchpad.net/ubuntu/+source/caja/+bug/1674570
Report against Linux Mint: https://bugs.launchpad.net/linuxmint/+bug/1651905
