### ISSUE TITLE
Better German translation for "zusätzliche Leiste"

### ISSUE THREAD

**Issue by JokerGermany** [mate-desktop/caja#701]
A Better Translation would be "zusätzliches Fenster" or "doppelte Ansicht"
![translation zusatzliche leiste](https://cloud.githubusercontent.com/assets/10880193/21643261/a1edbea6-d287-11e6-8002-24daacc297c1.png)

**Comment by raveit65** [comment]
Translation are managed via transifex.
Become a member of german translation group and fix it there ;-)
https://www.transifex.com/signin/?next=/mate/MATE/translate/
Aber ich bin einverstanden mit deiner Übersetzung von wahrscheinlich 'Panel' --> doppelte Ansicht.
