### ISSUE TITLE
Mouse wheel doesn't move scrollbar when caja is on compact view

### ISSUE THREAD

**Issue by ThanosApostolou** [mate-desktop/caja#703]
When caja is on compact view, then I can move the scrollbar with the mouse click (grab), but I can't move it with the mouse wheel.

This behavior is present with caja version 1.16.x series, on Ubuntu MATE 16.10 and Manjaro MATE edition gtk3 build. However, it works fine with caja version 1.16.x series on Gecko Rolling (opensuse tumbleweed). 

So I believe it has something to do with the gtk3 build. Maybe opensuse uses a gtk2 build (and that's why it doesn't get affected), or maybe the opensuse team has done manual patches in order to fix the problem.

**Comment by raveit65** [comment]
And why do you don't report it to ubuntu first?
We are not ressponsable fo distro related issues.
Btw. on fedora with Mate gtk3 i don't see this issue.

**Comment by monsta** [comment]
Wait... wasn't it fixed in https://github.com/mate-desktop/caja/pull/674?

**Comment by raveit65** [comment]
now i know why i don't see the issue with 1.17 here :-)
we can try to backport it

**Comment by monsta** [comment]
Ok, 1.16.2 is released with the fix.
