### ISSUE TITLE
Add "Open With Other Application" option when you right click on desktop entry (file)

### ISSUE THREAD

**Issue by ThanosApostolou** [mate-desktop/caja#709]
When you right click on a file for example `test.desktop` then it shows normally the "Open With" option. However, if you edit the file and add the line `[Desktop Entry]` then it doesn't show it anymore.
![screenshot at 2017-01-08 17-18-15](https://cloud.githubusercontent.com/assets/21288843/21750914/0601669e-d5c7-11e6-91e0-de0a8c952c0f.png)

![screenshot at 2017-01-08 17-19-30](https://cloud.githubusercontent.com/assets/21288843/21750919/1e0b55ba-d5c7-11e6-98c6-e9afa20416f8.png)

I edit desktop entries a lot because I like to test various settings and change options like language and stuff that aren't available from right clicking and choosing properties. So, I always need to open separately pluma or create a custom caja script in order to change those files. Also caja scripts aren't available when I open caja as root if I need, for example, to edit stuff from /usr/share/applications.

**Comment by lukefromdc** [comment]
Check to make sure you are not getting the bug where an edited "foo.desktop" file gets saved as "foo.desktop.desktop" as Nautilus got a commit to deal with that at one point. If we are getting that in Caja I will have to find and apply that commit.

**Comment by ThanosApostolou** [comment]
@lukefromdc  Editing a foo.desktop file still remains a foo.desktop file. The only case that I see that happening, is when you try to rename a `foo.desktop` file to `foo2.desktop` while this desktop entry has been marked as trusted, or has executable permissions. Then, caja changes the desktop entry's name to `Name=foo2.desktop` but it also renames the file to `foo2.desktop.desktop`.

**Comment by sixsixfive** [comment]
also please do this for all files (eg. *.theme files), since its annoying to open a terminal every time to open a simple text file

**Comment by lukefromdc** [comment]
What version of Caja are you using? Caja 1.17 (git master) changed this behavior to match Nemo and Nautilus, and these commits were backported to current Caja 1.16 but not until after 1.16.1 came out. If you are using Caja 1.16, these changes should be in 1.16.2 when it comes out. 

These are the commits as applied to git master:

https://github.com/mate-desktop/caja/commit/5432a415dadbd8db34081037645e0c38457900ec
Show "open with" menu for desktop and theme files 

https://github.com/mate-desktop/caja/commit/5432a415dadbd8db34081037645e0c38457900ec
Show "open with" tab in properties window when "open with" menu available

https://github.com/mate-desktop/caja/commit/91dcd8a19665b6738f8304db127f45b503e00ce3
file: don't consider all desktop files caja links

**Comment by ThanosApostolou** [comment]
Awesome!!! I use caja 1.16.1 (gtk3 build on manjaro) as I don't feel comfortable with dev releases. I'm looking forward to 1.16.2 release!😃
