### ISSUE TITLE
Renaming files is impossible

### ISSUE THREAD

**Issue by sixsixfive** [mate-desktop/caja#710]
![screenshot at 2017-01-10 04-09-52](https://cloud.githubusercontent.com/assets/3780774/21792572/0be4f39e-d6eb-11e6-9d88-34ea6782e93b.png)

due the embed css its almost impossible to rename a file in caja(1.16.1), the only way that works is to rename the file in list view, the better would be to drop the included css so that the default style for the gtkentry is used(like it is on list view).

**Comment by lukefromdc** [comment]
What theme is this? All of the MATE themes plus Adwaita work. If this is removed from the CSS, lots of themes that don't explicitly support MATE will have this problem. This is definately a problem with the theme.

**Comment by sixsixfive** [comment]
>What theme is this?

my own litte humble one https://github.com/sixsixfive/Hedera

the issue is with that file: https://github.com/mate-desktop/caja/blob/master/data/caja.css and its symbolic colornames(there is no rule how to name them but it expects the color names from the adwaita theme so if it meets a non-adwaita based theme it breaks)

also is there any reason whis this entry should look different than other entys? (eg: entrys always have a border around to make them visible, they also always use the selected base colors)

**Comment by lukefromdc** [comment]
Look at the code in any of the MATE light themes like Menta to see how to make this work.  You can easily add that symbolic color, it's almost impossible to write that sort of file without using the Adwaita symbolic colors (unless you want to hardcode colors and overrride all themes)  because almost all other themes use them. Just define that color as whatever name you replaced it with and your theme should work. We are not taking out the css file and breaking Caja for many other themes plus GTK3's default.

**Comment by sixsixfive** [comment]
>We are not taking out the css file and breaking Caja for many other themes plus GTK3's default.

how should this happen? adwaita entys are fine on the listview i see no reason why they shouldnt work on the iconview (its also weird that caja doesnt follow the style of iconviews eg: gtk3-demo)

anyway good luck here I did a GTK3 theme(gtk3-demo, gtk3 widget factory) if caja wants to use something other than i'm out, cheers!.

**Comment by lukefromdc** [comment]
Adwaita was nearly unusable in Caja without this file. Nemo uses a file like this too though it is not the same.

**Comment by raveit65** [comment]
> the issue is with that file: https://github.com/mate-desktop/caja/blob/master/data/caja.css and its symbolic colornames(there is no rule how to name them but it expects the color names from the adwaita theme so if it meets a non-adwaita based theme it breaks)

All our themes aren't based of adwaita, so what you say here is wrong.
Send me a payment an i fix your theme in 2 secs ;-)
