### ISSUE TITLE
Change line with left/right arrows

### ISSUE THREAD

**Issue by rafafaf29** [mate-desktop/caja#713]
Hi,
I recently took a look on Caja 1.16 in Debian Stretch (testing), and i discovered that the possibility of changing line just using left and right arrows disappeared (when i highlight the last item of a line and go right, i am now stuck on this last item, instead of being able to go at the first item of the next line).

I tried also on Ubuntu (Caja 1.12), and notice the same behavior, so I think it probably is not a bug, but a decision. But it breaks my whole workflow when browsing through large numbers of folders, so i wonder if there was a setting/option/anything that could bring back the old behavior (like Caja 1.8 in debian Jessie) .

Thanks anyway for all this work !

**Comment by lukefromdc** [comment]
This should be fixed by https://github.com/mate-desktop/caja/pull/699 so if you can build Caja 1.17 (git master) this should work again.  This has been cherrypicked to the 1.16-backports branch, so when the next 1.16 release comes out and Debian builds it you should find this fixed.

**Comment by rafafaf29** [comment]
Ok ! I won't try to build Caja myself, I will wait for Debian to do it well, but it's good to know it is going to be fixed eventually :)
Thank you

**Comment by flexiondotorg** [comment]
Fix via https://github.com/mate-desktop/caja/pull/699

**Comment by monsta** [comment]
Yeah, I need to give some more testing to that branch and make PR for 1.16 branch eventually...
