### ISSUE TITLE
Copy file with Question mark puntuation in filename fail

### ISSUE THREAD

**Issue by math3os** [mate-desktop/caja#715]
I were copying Music files from a nfs mounted drive and it fail on a file with a question mark in it (?). 
Question mark in filename seem to be supported in nemo, thunar and bash.
Some test : 
- Unable to open file with question mark in it's name.
- Unable to create file with a question mark in it's name.

**Comment by kn00tcn** [comment]
but what file system?

although i just renamed something to ? on an ntfs drive... that's not supposed to be allowed in windows, wonder what happens if i boot it

are you sure it's a standard... i guess ascii or en-us character, not a unicode one?

**Comment by math3os** [comment]
I
Oh i tought it was à nfs mount but i changes it to samba à while ago. So may be it explain everyting. 
Also, on host system fs is zfs (zfsonlinux).  Zfs seem to support question mark on filename. I didnt look about samba at thé moment may be tomorrow

**Comment by math3os** [comment]
Ok, I tried it again and it works.  May be i were totally confuse and i tried to create file on fat32 sdcard with caja and with nemo on my nfs drive (inside two folders with same name). Sorry for inconvenience.
