### ISSUE TITLE
[feature request] brisk menu as default (after its beta period)

### ISSUE THREAD

**Issue by kn00tcn** [mate-desktop/caja#717]
holy, i just ran into this https://solus-project.com/2016/12/30/solus-announces-first-release-of-brisk-menu/

this is exactly what a standard menu is supposed to be, quick session controls right at the bottom, an item for the entire control center right above, a search field....

they mentioned they will 'work with' ubuntu mate, but i find it odd they didnt directly mention mate upstream (what is up with ubuntu related mate... mint has a moden theme & already its own menu, ubuntu has a fork of mint's menu, did they not contact us upstream?)

anyway it's a little early now, brisk needs to add a few options such as moving the search field to the bottom

as upstream, are we able to easily add new required packages or does every distro maintainer have to do that?

(on a related note, i want to make a nice theme as well & have that added to every distro automatically... that or enable arc theme or mint's fork of it called mint-y, maybe adjust mint's green into mate's green)

**Comment by raveit65** [comment]
What does this have to do with caja?
From my point of view changing a default will always make trouble with other uses who like the old default ;-)
I tried to use mintmenu as default in fedora in early MATE days, believe me most users weren't amused.
At least distro maintainers can edit or write an own layout file for the panel and load it via a gsettings override.
https://github.com/mate-desktop/mate-panel/tree/master/data
http://pkgs.fedoraproject.org/cgit/rpms/mate-desktop.git/tree/mate-fedora-f25.gschema.override#n8
Gsettings override files should use priorities like what i do for fedora.
ie. 10_mate-fedora.gschema.override
http://pkgs.fedoraproject.org/cgit/rpms/mate-desktop.git/tree/mate-desktop.spec#n168
10 is for vendor, in result an admin or user can override it with up to 99 priority.

If you really like to discuss this at upstream level please use mate-panel which is reponsible for loading a specific menu.

**Comment by flexiondotorg** [comment]
Adding support for Brisk Menu is a distro decision. Ubuntu MATE are funding the  Brisk development and as a result it is packaged for Debian and Ubuntu. It should soon be available in both distros archives. 

But thanks for highlighting Brisk, it certainly is a great project with lots of potential ☺️

This is also filed under Caja, not the right place, so I'll close this.

**Comment by kn00tcn** [comment]
oops, in my excitement i forgot to file it under mate-panel or mate-applets, sorry

oh nice, you (raveit65) are maintaining fedora, i might have to compile some theme issues later (though i updated to f25 so there's less gtk2 now), but anyway great job with the seemingly fresh updates

flexion, it's mate in the less noob friendly distros that concern me with their lack of menu key + start typing app search specifically lacking as an available preinstalled applet (well, i guess xfce's whisker menu is in a similar situation being a separate distro package)

solus' wording makes it very compelling since they aim to be distro agnostic & gtk3

**Comment by cinnamoner** [comment]
@flexiondotorg Hi Marin! I very much like your proactiveness. You're virtually everywhere.
@kn00tcn Have you checked the UKUI menu? Seems decent to me.
