### ISSUE TITLE
Can Caja manage NextCloud overlay icons?

### ISSUE THREAD

**Issue by ldmpub** [mate-desktop/caja#718]
Hi,

Is it possible to have overlay icons in Caja showing file/folder synchronization state when using NextCloud client?

Best regards,

**Comment by flexiondotorg** [comment]
Yes, but that would require integration code in the Nextcloud client itself.

**Comment by ldmpub** [comment]
Hi,

Sorry to bother you but this extension claims to "provide overlay icons to visualize the sync state in the caja file manager" without any change to Nextcloud client, see: http://rpmfind.net/linux/rpm2html/search.php?query=nextcloud-client-caja

I must confess I'm lost between theses 2 opposite answers to my initial question. ;-(.
Best regards,

**Comment by raveit65** [comment]
This is really new for me.
https://admin.fedoraproject.org/pkgdb/package/rpms/nextcloud-client/
http://pkgs.fedoraproject.org/cgit/rpms/nextcloud-client.git/commit/?id=312fc4aaeb579cc7f6fd9f99912ac2c3253253e7

**Comment by raveit65** [comment]
https://github.com/owncloud/client/pull/5262
