### ISSUE TITLE
open in new tab: tasklist icon immediately changes to new tab's folder icon

### ISSUE THREAD

**Issue by monsta** [mate-desktop/caja#719]
This is kind of follow-up to https://github.com/mate-desktop/caja/issues/492, something I noticed when testing https://github.com/mate-desktop/caja/pull/619.

When I right-click on some folder with its own icon (Desktop, Music, etc.) and select "Open in new tab", then the taskbar icon immediately changes to that folder's icon. So, the new tab is opened in the background, and I didn't switch to it yet, but the taskbar icon is already changed.

Same thing happens when using middle-click on a folder (which opens it in a new tab). Opening a folder from the sidebar in a new tab is affected as well.

@bl0ckeduser @zaps166 do you guys have any ideas about this?

**Comment by bl0ckeduser** [comment]
I can confirm the issue happens for me, no idea of a fix yet though.
Very busy with life atm so can't do much about it soon. Sorry for the
delay in answering your message.

**Comment by monsta** [comment]
It's ok, I also have a busy time now. Need to catch up with all the github notifications waiting for me :slightly_smiling_face:

**Comment by zaps166** [comment]
The same issue on my Caja, but I haven't looked into a code yet.

**Comment by raveit65** [comment]
weird, i can't reproduce it here with mate-1.19 on fedora 26.
If i do a right click on picture folder and choose open in new tab, panel task-list shows me my home folder. Or do i miss something?
