### ISSUE TITLE
[minor bug] delete old nautlus icons in /usr/share/icons/hicolor

### ISSUE THREAD

**Issue by pirate486743186** [mate-desktop/caja#722]
EDIT: These images
find /usr/share/icons/**/* | grep caja

/usr/share/icons/hicolor/16x16/apps/caja.png
/usr/share/icons/hicolor/22x22/apps/caja.png
/usr/share/icons/hicolor/24x24/apps/caja.png
/usr/share/icons/hicolor/32x32/apps/caja.png
/usr/share/icons/hicolor/scalable/apps/caja.svg

They are all the nautilus shell logo.

I think, they aren't actually used, i only saw system monitor use them. I'm assuming it's by it's own initiative. I renamed them, and nothing wrong seamed to happen. I don't think they need to be replaced, they are wrong any way, so they should be deleted.

**Comment by kn00tcn** [comment]
is it possible it has to do with the icon theme?

**Comment by lukefromdc** [comment]
The caja.png icons that go into /usr/share/icons/hicolor are the original snail shell Nautilus icons. A new icon for Caja could be created to replace them I suppose.

**Comment by pirate486743186** [comment]
bump. The images should be deleted.

**Comment by pirate486743186** [comment]
please some dev fix this already. -_-
It's a trivial fix. Just need to delete images that are not been used....

**Comment by kn00tcn** [comment]
confirming the caja package NOT the theme package(s) are installing the icons? (i havent checked)

**Comment by pirate486743186** [comment]
in ubuntu 18.04 MATE edition
these images are installed by package caja-common

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/caja/commit/040a897fe879e949f4e11be4b0d065486c677e97
