### ISSUE TITLE
mate pre-releases

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#733]
@monsta 
I stumbled about some pre-released packages on server a week ago.
I am still testing all of those and they work fine in the the short moments when i am using f25 or epel7.
Normal i am on f24 with 1.17.x.
I think you can release them.
But honestly without open an issue for it and asking ppl for testing, i would never aware of pre-released packages ;-)

Please close this report after reading...

**Comment by monsta** [comment]
Sure, you can move them to release server if you don't find any regressions. I told @flexiondotorg about these tarballs a few days ago, so I thought he would tell you about them on IRC.

I'll try to get back to 1.16 releases today or tomorrow, there are a few more needed to be made (applets, terminal...).
