### ISSUE TITLE
"Open With" dialog doesn't scale icons to the same size

### ISSUE THREAD

**Issue by monsta** [mate-desktop/caja#735]
Menta icons:
![open-with-menta](https://cloud.githubusercontent.com/assets/5138986/22691883/e0b53a54-ed55-11e6-8270-d968ac016448.png)

Mate-Faenza icons:
![open-with-mate-faenza](https://cloud.githubusercontent.com/assets/5138986/22691886/e6375d7c-ed55-11e6-9899-a57a418c96a7.png)

Looks like the icons aren't scaled to the same size. So if there's only a large icon available for an app, it's shown as is and that breaks the layout.

Tested with GTK+ 3.22.7 in Debian Testing.
##
While testing this, I also noticed that the dialog doesn't react to icon theme change. You need to close it and open it again to see the icons from the new icon theme there.

**Comment by lukefromdc** [comment]
Are you sure all the icons in question are resizable? Also, this sort of behavior when only a large image is available has been an issue with GTK3 for years.

**Comment by monsta** [comment]
I don't know if they're all resizable, but we should probably use some icon scaling here...
