### ISSUE TITLE
Feature request: Panel widget editor like XFCE

### ISSUE THREAD

**Issue by gaelanlloyd** [mate-desktop/caja#736]
First off, I'm a big fan of MATE!

As MATE matures and grows I think it could benefit from a panel editor like the one in XFCE.  The XFCE editor makes it really easy to add widgets, change their order, etc.  Sometimes it's really hard to grab items with really thin handles (especially the "Notification Area") and move them around.

Here's an example of the XFCE panel editor.  You can see that there are entries for each widget in the panel, and easy to use buttons to move items around, or add or remove items.  This is also really helpful for adding "Separator" elements and moving them exactly where you want them.

![xfce-panel-editor](https://cloud.githubusercontent.com/assets/1403649/22716306/457d9abe-ed4a-11e6-8c76-cf781d16bade.png)

**Comment by kn00tcn** [comment]
you meant to put this in https://github.com/mate-desktop/mate-panel/issues

**Comment by gaelanlloyd** [comment]
Whoops!  Didn't know about that.  Thanks, I'll post this over there.
