### ISSUE TITLE
Caja 1.17.2 & 3: no desktop icons for root

### ISSUE THREAD

**Issue by burdi01** [mate-desktop/caja#737]
Caja 1.17.2 & 3 on Slackware64 Current as provided by http://slackware.uk/msb/current/latest/x86_64/base/ and http://bear.alienbase.nl/mirrors/slackware-live/1.1.6/slackware64-live-mate-current.iso.

When logged-in as root I do not see the desktop icons, nor does rightclicking on the desktop have any discernable effect. When logged-in as a non-root user I see the desktop icons and right-clicking on the desktop pops-up a context menu.

**Comment by raveit65** [comment]
Sorry, we are not responsable for distros.
And login as root is strictly forbidden in most distros, ie. fedora.
...and why root session?
So nobody can reproduce this here.
I suggest to file out a report at your distro, maybe the maintainer there wants to help you with this very insecure user case.

**Comment by lukefromdc** [comment]
If you have a need for GUI administration as root, one way to get a desktop is to remove caja from root's desktop>session>required components and then from a terminal in that session run caja --force-desktop .
Just be sure to keep networking turned off in such a session!

**Comment by burdi01** [comment]
**@raveit65**: 

> And login as root is strictly forbidden in most distros, ie. fedora.

For me the quintessence of Open Source is that nothing is forbidden there.

I booted the Fedora-MATE_Compiz-Live-x86_64-25-1.3 ISO in VirtualBox, set as "liveuser" the root password via "sudo -i", logged out and logged in as root: no problems whatsoever.
Even the desktop icons are there, and rightclicking on the desktop pops up a context menu. This non-failure was as expected because this ISO contains Caja 1.16.1 and for as far as I know the symptoms at hand were introduced with Caja 1.17.x.

> this very insecure user case.

For a single-user workstation system type (as opposed to a multi-user server one) I respectfully disagree.

**@lukefromdc**: Thank you for responding. 

:D
