### ISSUE TITLE
Caja displays wrong properties info

### ISSUE THREAD

**Issue by lotar1954** [mate-desktop/caja#738]
Caja displays wrong properties info as you can see from the link below.

https://drive.google.com/open?id=0B3iAYb-9aeiHXzhwTzFIRzAwRVk

The folder is about 180GB but Caja only says that is 7.5GB. 
In addition, Caja wrongly reports the numbers of items and the free space.

Please let me know if you need any more info.

**Comment by lotar1954** [comment]
Could someone please tell me in which file Caja's properties code is located?
I would like to fix it myself without waiting no longer.

**Comment by fbarriga** [comment]
Is not counting hidden files.
If you check the number of files on your screenshots, they doesn't match: 18.160 v/s 26.714.

repro steps:
```
$ mkdir tmp
$ dd if=/dev/zero of=tmp/foo bs=1M count=1
$ dd if=/dev/zero of=tmp/.bar bs=1M count=1
```
now check the properties of the directory with caja, it will display `1 item, with size 1.0 MB`

**Comment by fbarriga** [comment]
duplicates #527

**Comment by fbarriga** [comment]
nautilus and nemo behavior:
- if option 'show hidden files' is enabled, it display 2 files and count the size of the 2 files
- if option 'show hidden files' is disabled, it display 1 file and display the size of the visible file

Maybe we could show the visible number of files ant their size, and also the real number of files and their size. 

Also in caja, if you copy a directory, it will copy always all the files (not only the visible ones). This behavior is not consistent but I think that is the proper one (nobody want to lose files...).
