### ISSUE TITLE
segmentation fault from caja 1.17.2 (ubuntu 16.10)

### ISSUE THREAD

**Issue by nitrofurano** [mate-desktop/caja#739]
Caja shows a segmentation fault error on terminal when we access other directory from the left shortcuts area after accessing the trash directory, causing caja window to close immediately - why does this happens?

**Comment by lukefromdc** [comment]
I am unable to duplicate this on Debian Unstable with caja from git master (now up to 1.17.4) at all.

**Comment by monsta** [comment]
Already reported at https://github.com/mate-desktop/caja/issues/649, already fixed in 1.17.3 and 1.16.2.
