### ISSUE TITLE
Icons are very finacky after using a touch screen

### ISSUE THREAD

**Issue by Lyude** [mate-desktop/caja#74]
No matter what, it seems I cannot double click any of the icons in Caja using my touch screen. I can do it just fine with my touch pad however. Attempting to double click just seems to select something, then deselect it. 
I am running MATE 1.4.1 on Gentoo Linux x86_64 on a Lenovo S10-3t
EDIT: I should have added this before, I have no idea why I didn't.
Steps to reproduce this problem:
1. Try to click various icons on the desktop or in a file manager window using the touch screen. You should see them be highlighted on the first click, then unselected on the second click.
3. Try to click the icons with another pointer device. You should notice that in addition to the touch screen not working correctly with the icons, that only one pointer device will work correctly with them.

**Comment by NiceandGently** [comment]
Is the problem still exists with caja-1.8.x ?

**Comment by NiceandGently** [comment]
@monsta 
please close, no answer from reporter
