### ISSUE TITLE
Rename broken in list view after keyboard navigation (GTK3)

### ISSUE THREAD

**Issue by cwendling** [mate-desktop/caja#741]
# Steps to reproduce

* open Caja built against GTK3 (here tested with GTK 3.20 and 3.22, and Caja 1.16.2 and master)
* make sure it is in List View
* move focus to a file or folder with the keyboard (just press <kbd>DownArrow</kbd> as many times as needed to go to the file you like)
* hit <kbd>F2</kbd>

# Expected result

Enter rename mode for the selected file

# Actual result

Nothing seems to happen (but the displayed focus line disappeared)

---

Alternatively to reproduce, you can also:

* open Caja in List View
* right click on a file *in another column than the Name one*
* hit <kbd>Escape</kbd> to quit rename mode
* hit <kbd>F2</kbd>

My wild guess is that the name column isn't properly focused initially, or something like that (but I could be totally wrong)

**Comment by lukefromdc** [comment]
I can confirm this

**Comment by raveit65** [comment]
Confirmed, issue exists in compact mode too.

**Comment by cwendling** [comment]
> Confirmed, issue exists in compact mode too.

You mean compact view?  I can't reproduce with compact view with current master, but still with list view.

**Comment by monsta** [comment]
@raveit65: in compact view we have this: https://github.com/mate-desktop/caja/issues/670
