### ISSUE TITLE
after search-by-typing (not via search bar), can't select/open file until move cursor after first click

### ISSUE THREAD

**Issue by ubbaeppae** [mate-desktop/caja#749]
this issue started recently. i'm on Fedora 24 with Caja 1.16.2

I'll try to illustrate with screen captures ...

Here's the search interface I'm talking about (search by typing, not using the search bar):
![search-by-typing](https://cloud.githubusercontent.com/assets/26627170/24251137/86440e48-0faf-11e7-9788-f53abe08e5a5.png)

everything to this point appears normal. notice search box at lower right, and that the "fstab" file is highlighted.

here's what happens after i click once on the "fstab" file:
![after-initial-click-on-file](https://cloud.githubusercontent.com/assets/26627170/24251247/e1929742-0faf-11e7-9107-05ef7aeade94.png)

notice in above image that the search box at the lower right has disappeared (normal), and that the "fstab" file is no longer highlighted (previously, the file would have remained highlighted; e.g. I'm comparing to Caja 1.14.1 in Fedora 24 in a virtual machine).

now, ***without moving the cursor at all***, if I continue clicking on the "fstab" file, it won't highlight. if I double-click, it won't highlight or open. clicking on the "fstab" file doesn't have any effect ***until I reposition the mouse***, at which point it behaves normally again (this as compared to Caja 1.14.1 in Fedora 24 VM).

It seems that an update between 2016-06-27 (when the VM I'm comparing against was last updated) and today has caused this regression. I've noticed the issue some time within the last few weeks, although it's conceivable that it's been an issue longer than that. please let me know if I can provide any further information to assist in identifying when and where this regression comes from.

**Comment by lukefromdc** [comment]
I don't understand how to click on an icon without moving the cursor to it unless the cursor is prepositioned over the icon to be selected. When doing that I was entirely unable to duplicate this bug.

**Comment by ubbaeppae** [comment]
in order to reproduce, you cannot move the cursor again ***after*** the first click of the icon that occurs in the second screen capture. so, immediately after performing a search, move your mouse over the highlighted icon, be careful to hold the mouse still, click once ... icon is no longer highlighted ... keep mouse in same position and continue to click ... nothing will happen for each subsequent click until the mouse is moved.

**Comment by raveit65** [comment]
F24 use mate-1.16 (gtk2) and will never updated to 1.18.
Please update to f25 or f26 what i use.
I don't see that issue with mate-1.18 (gtk3).

**Comment by ubbaeppae** [comment]
hmm, well this is confusing ... I'm not sure the versions are showing right in a fully updated F25 -- mate has clearly been switched to GTK3 even though the version of mate is listed as 1.16.1, the same as on my F24 system where mate uses GTK2. Caja, for example, is clearly GTK3, but shows as version 1.16.2, same as my F24 GTK2 caja.

Anyway, a fully updated F25 install does not exhibit the problem I have described in this bug, despite the versions of mate and caja being the same.

**Comment by raveit65** [comment]
In f24 some applications are switched to gtk3 and some use gtk2.
Caja use gtk2 here in f24 and i can confirm the issue.
After search is done and /etc/fstab is highlighted, moving the cursor to the file closes the search box and the file isn't highlighted anymore and you can't open it with a left click.
A second movement of the mouse is needed.
But at this point a right click is working and why not simple press **enter** to open the file, instead of using the mouse for it?
Well, it is a bug but we are a small team and current supported release is 1.18 with gtk3.
Sorry, we can't support gtk2 only bugs at this time.

**Comment by ubbaeppae** [comment]
> But at this point a right click is working

Actually, right-click doesn't work at this point -- the right-click context menu is for /etc rather than /etc/fstab

> why not simple press enter to open the file, instead of using the mouse for it?

Thank you for the suggestion -- but of course old habits die hard :-/

> current supported release is 1.18 with gtk3

it's frustrating that a 9 month old version of a major distribution is no longer supported :-/

i'm currently playing with Fedora 25 in a virtual machine, as I probably won't have time to upgrade within the next few days, at least. upgrading the whole OS once a new bug appears isn't my favorite suggestion i've heard....

by the way, i can see there are some major improvements to gtk3 theme support in F25 as compared to F24 -- very nice work! it's always appreciated :-)
