### ISSUE TITLE
GTK2: backgrounds in dirs are broken with 1.16.3

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#752]
@monsta @XRevan86 @lukefromdc 
Huston we have have a problem. After update to 1.16.3 backgrounds in large dirs are broken with gtk+-2.
![caja-gtk2](https://cloud.githubusercontent.com/assets/961604/24343875/ff0f588e-12c8-11e7-819e-410a8739891b.png)
This affects all themes. Also, the background does not change if you switch the theme, here a new caja window is needed to see the new theme bg color.
Tested with f24 and rhel7.
Please confirm

**Comment by raveit65** [comment]
https://github.com/mate-desktop/caja/commit/dedfcf46269792f1fa112d6236226f17d7d8050d
fixes the issue for me.
@monsta @flexiondotorg 
Please test to avoid releasing another broke tarball

**Comment by monsta** [comment]
@XRevan86: thanks! But interesting... I didn't know that auto-closing issues won't work in this branch:

> If the commit is in a non-default branch, the issue will remain open and the issue will be referenced with a tooltip.

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by monsta** [comment]
Building in my GTK+2 VM to confirm the fix...

**Comment by monsta** [comment]
Yes, that commit fixes it.

**Comment by lukefromdc** [comment]
I can confirm that MATE 1.16.4 background setting from the "backgrounds and emblems" window still works with GTK 3.22 as well, just in case that didn't get tested.
