### ISSUE TITLE
Feature request: hash values tab in file properties

### ISSUE THREAD

**Issue by ReaperX** [mate-desktop/caja#758]
It would nice if Caja could make verifying file hashes more convenient by integrating a functionality similar to the hashtab windows shell extension. See:

http://img.brothersoft.com/screenshots/softimage/h/hashtab_windows_shell_extension-26765-1.jpeg

There could be a similar tab in the properties for each file, called Hashes, that shows common hash function values (CRC32, MD5, SHA256, etc.) for the file. If there is a hash value in the clipboard, it would automatically be displayed in a box and compared to all the computed hashes. A checkmark would indicate a match.

**Comment by monsta** [comment]
GtkHash project has Caja extension: https://github.com/tristanheaven/gtkhash/commit/fadad946ad591632075e9de8a54cc0a0f5b210a8.
