### ISSUE TITLE
Building Caja without Mate

### ISSUE THREAD

**Issue by rdiez** [mate-desktop/caja#763]
I wanted to test the latest Caja version without having to switch to the MATE environment, but I hit the following bug upon initial configuration from Git:
  No package 'mate-desktop-2.0' found
I am running Xubunt 16.04.2, and there is no such a package.
Is this going to turn into dependency hell?
Alternatively, is there any other way to get a more up-to-date Caja on my Xubuntu 16.04? Any updated Caja PPA for Ubuntu?
Sorry to ask here, but the mailing list link referenced from http://wiki.mate-desktop.org/contribute does not work. I did not find any other communication channel. On IRC, nobody answered, but I am not used to IRC so maybe I did not operate the freenode web chat properly.
Thanks in advance.

**Comment by monsta** [comment]
`sudo apt-get build-dep caja`
