### ISSUE TITLE
Extra pane background colour

### ISSUE THREAD

**Issue by baem2** [mate-desktop/caja#767]
I was using MATE 1.8 on debian jessie and upgraded to debian stretch (MATE 1.16) now. I'm using the TraditionalOk theme, but the problem also seems to apply e.g. for the Menta theme.

With MATE 1.8, when pressing F3 in caja, there was an extra/2nd pane added. The inactive (= not reacting on keyoard input) pane then always was greyed out. With MATE 1.16, the inactive pane is no longer greyed out, at least not in "symbol" and "compact" view modes ("Symbolansicht"/"Kompakte Ansicht"). The greyish background only appears in "list" view mode ("Listenansicht").

Would it be possible to add the grey background for the inactive pane in symbol view mode also? Or even better, how can I change that myself? (As if you fix it for the next version, it is not going to be in debian anytime soon ...)

Could this be a solution?
http://forums.debian.net/viewtopic.php?f=6&t=132773&sid=7f9aeebaa39ce416d966309d89e3e8d7#p642231

I tried it, but I did not find fitting entries.

**Comment by raveit65** [comment]
I've no idea why debian always lacks of updating....
Please use latest MATE-1.16.x releases + https://github.com/mate-desktop/mate-themes/commit/6c01fc4449fd245d5c416de374668b5a035c2c9f
and all is fine.
I want to bet that debian stretch don't use caja-1.16.5.
In a full updated fedora-25 with caja-1.16.5 and mate-themes-3.22.10 traditional themes don't have this issue.

**Comment by baem2** [comment]
Thank you! You're right, debian stretch at the moment uses caja 1.16.2. I'll let them know, hopefully it's possible to update these packages.
