### ISSUE TITLE
[Feature Request]: Switch tabs with CTRL+ TAB [$20]

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/caja#768]
It'd be nice to be able to switch open tabs the same way we can for Firefox: CTRL+TAB. and CTRL+SHIFT+TAB for reverse switch.

**Comment by snaiperskaya96** [comment]
You can actually switch tab using CTRL + Page up and CTRL + Page down. 
Should we switch to a more standard CTRL + TAB & CTRL + SHIFT + TAB? Or maybe allow both?

**Comment by epgfm** [comment]
Yeah, as discussed here: https://github.com/mate-desktop/pluma/issues/211
Having both would be good.

**Comment by snaiperskaya96** [comment]
Please have a look at this PR https://github.com/mate-desktop/caja/pull/825 :)
