### ISSUE TITLE
[$150 bounty] Can't figure out how to install Caja without losing extensions [$150]

### ISSUE THREAD

**Issue by rubberbandaid** [mate-desktop/caja#769]
(BountySource link: https://www.bountysource.com/issues/44445027-150-bounty-can-t-figure-out-how-to-install-caja-without-losing-extensions )

Hey guys, new user here, but a monthly donor to the MATE project. Basically, all I'm trying to do is install Caja (with modified source code) without losing my extensions. I've spent so much time on this, and noticed there are bounties here so thought I'd try that out, since I'm not getting anywhere.

My goal is to install Caja 1.16.5 from source, plus this small bug fix: https://github.com/mate-desktop/caja/commits/1.16 , on Linux Mint MATE 18.1. I need to do this without losing the functionality of the extensions that come packaged with Mint, all of which can be installed separately from source, so rebuilding and reinstalling them is fine too if need be, as long as they work in the end.

My commands are, with Caja 1.16.5 downloaded and the patch in the bug applied: "./autogen.sh --prefix/usr && make && sudo make install". This works fine, and Caja 1.16.5 comes up with the changes, but no extensions are listed.

Note: I actually have to change one more thing to get 1.16.5 to compile, in configure.ac:
-m4_define(mate_desktop_minver,         1.16.2)
+m4_define(mate_desktop_minver,         1.16.1)

But, I looked over the sources and found no reason this shouldn't work, plus, I run into the same exact problems when building and installing Caja 1.16.2, which uses "mate_desktop_minver 1.16.1", which comes with Mint 18.1. So I am sure this configure.ac change isn't the source of my problem.

Anyway, when the new Caja 1.16.5 (or 1.16.2) comes up, no extensions are listed, and the "Network Browser" is never able to detect any of my LAN systems.

My progress so far, after building and installing my modified 1.16.5:
- If I build and install "caja-extensions"  1.16.0, the common extensions show up (gksu, wallpaper, open terminal, etc -- I don't need Xreader or Atril, BTW).
- To get the Engrampa extension working, I just build and install Engrampa after Caja.
- Then, if I build and install python-caja and folder-color-switcher (which lets you right click on a folder to change its color), which is the one python extension I need, they don't work, and nothing gets listed for this extension in the extensions listing. To install folder-color-swticher, I run "sudo python setup.py install". It doesn't take a --prefix. That package can be found here: https://github.com/linuxmint/folder-color-switcher

Additionally, the "Browse Network" option only shows "Windows Network", and not any of my LAN systems, but a stock Mint 18.1 install can't seem to detect my network shares inside of a VM anyway, so this might not be due to the modified Caja build. I do need this to work though.

I am guessing that it is possible to install my modified build of Caja without touching these extensions, and thus leaving them in place. This would be an ideal solution.

If one is to continue on the progress I have made so far, building a bunch of other packages, though, I think the problem is either with the python-caja install or the folder-color-swticher install. Placing a test python extension in ~/.local/share/caja/extensions doesn't work, so it might be with the python-caja install process.

Also, after installing my version of Caja, runing "apt install python-caja caja-folder-color-swticher" has no effect.

I imagine this probably will be a 1 minute answer for anyone who develops Caja, and that person deserves the bounty! :) I need this for my business, and time is money, and I've wasted a lot of time on this already!

If you want to know how to reproduce it, this is what I do:
1. Create a Mint MATE 18.1 x64 virtual machine in Virtualbox.
2. Download Caja 1.16.5 (probably easier to first try it with 1.16.2) from https://github.com/mate-desktop/caja/releases .
3. Run "./autogen.sh --prefix/usr && make && sudo make install", then run "caja -q && caja", or just reboot the VM.
4. In the new Caja build, go to Edit -> Preferences -> Extensions. At least these extensions must be present: Gksu, Engrampa, Python: caja-folder-color-swticher, Wallpaper, and Open Terminal. Nice to have: "Send To". These are all installed by default in Mint. "Browse Network" issue might not be an issue, but is explained above.

Thanks for taking a look! Also, thanks so much to the devs for making this GREAT desktop environment.

**Comment by lukefromdc** [comment]
You are installing Caja into /usr/local while Debian/Ubuntu/Mint installs to /usr and in addition installs associated libraries such as libcaja-extension to /usr/lib/x86_64-linux-gnu (multiarch support). Extensions normally install to /usr/lib/caja . Might be that Caja in /usr/local isn't seeing your extensions installed into /usr?

**Comment by rubberbandaid** [comment]
Hey Luke, thanks for the reply, I'm testing this right now. Will update within the next 30 mins probably.

**Comment by rubberbandaid** [comment]
Ok, Luke, I think this did it! :)

While I was building with the --prefix=/usr flag (to autogen.sh), the solution here was to do this after install (and will need to do this after adding any extensions in the future):

sudo cp -r /usr/lib/x86_64-linux-gnu/caja-sendto/ /usr/lib/
sudo cp -r /usr/lib/x86_64-linux-gnu/caja/extensions-2.0/ /usr/lib/caja/

Then, after restarting Caja, the extensions work! :)

Do you have a BountySource account? If so, want to mark it as "solved" there?
To discuss further, you might want to message me on IRC, I'm in the #mate channel but have to go to bed in about an hour. I'll be on tomorrow though around 9 EST worst case scenario.
Or, if Github has private messaging, you can PM me here.
Thank you!!!

**Comment by lukefromdc** [comment]
I don't have such an account, in fact I don't have any online financial accounts at all.

**Comment by rubberbandaid** [comment]
Hmmm, well, you saved me a LOT of time, I'd really like to follow through on my end of the bargain as promised. Unfortunately it doesn't seem like there is a way to "cancel" on BountySource, there is a 6 month expire time, but that's it. Since you don't do online payments, that means you don't have a Paypal, which is probably what BountySource pays with.

I'm a little stumped for ideas, any thoughts?

**Comment by lukefromdc** [comment]
I don't have Paypal or credit cards I control at all. I don't do any online shopping, and a lot of commercial websites don't work on my computers due to extensive blocking of ads, trackers, and verification (fingerprinting) code. The money would be nice, but I have electronic way to move it. We could move this to an email discussion, if you have a gpg public key or could use mine we could exchange emails without the spammers being able to read them

**Comment by rubberbandaid** [comment]
I don't know anything about gpg, but do understand the concepts of public/private key crypto.
As such, I'm guessing you'd give me your public key, I'd encrypt a message and post it here, and then you'd decrypt it with your private key and get my email from there.
If this is correct, if you can give me the command to run to generate the output on my email string, that will work.

**Comment by lukefromdc** [comment]
Bountysource can pay out in physical checks according to their website. I've always used a GPG GPU frontend to encrypt text, and only ever used webmail emailers so would not know the command in question.  My public key is here:

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.6 (GNU/Linux)

mQGiBElz9bERBADHbO/o4DHTv5tNDs0N/QCL2nXKbLDMwLJatti6QtEDOB98yNeW
1oKaJ4B9kWJQanMy4fZZLPBriYybxUudU5RCqKY64KK3Pnc9oAMuYk5PxVO+7hrx
8GIShwJtEFVBpS4K59Re3VTK6r6uBNgBfteST3jy/XvuvXQSWi9408lCswCgnnGK
KYYoOiI4G6k5WJaURzWn6vcD/2lW4sEUFnCfVSFuTdP0/CSJQq4XUJsys1thsm6W
320u7wt8VEvXUV8HfzmcqnYj9Tpi51XMCvqpi1vb2awxEE4PZ2AtKgWXkqfJHzl1
IyqtGHyf5JOQUQJGdkf571f61cJhtyWCmlTMu9TLd5NilwwPtxMTrQSzA+f1xlaH
+hneBAC1invLXDeypGmPr6buv1LYfaK3PMpwjAhxYvCKBsqjSk/KYiiliHyNIFnq
xZdhTBLS6BjVJ7lNUHbKHmICToDaxbuTQdIKbBjMCAzf3xLZCiRP3F3jPF66QDO/
iDTLzKkvjjNwIliI5xbUGhDQu3ym842NbmsrGBoE4b75S+5DzLQbTHVrZSA8bHVr
ZWt1aG5AaG90bWFpbC5jb20+iGAEExECACAFAklz9bECGyMGCwkIBwMCBBUCCAME
FgIDAQIeAQIXgAAKCRCrYZ03I1TDoo14AKCapTyOXADsXtR9oAjvSwAbF/zNIgCe
OQvVHgmQ266jsNq1alG38b4UHzu5AQ0ESXP1tBAEALhyO0p3hLYVywLkgUEImo1M
qthrNk6gIMdRKMULSHtyCQWz6trl8W/hqz8dLdlYAM7Mxv681PJHCC4PEo9bYIdk
K7QJT62A8mQCHOtmX7uvGgeZBH53mdUct0D7LUyDW/mOxUp/yVy49LUhqO4YcNiA
NdCk1/fzZq9Yc3XouZTTAAMFA/45PsuZ12ZZdZSCj0PH02ByN95qVzXYP7714eY2
IFcFImuFsGqf3vrkbKPAhmypHDdzFIBuAyP2VkMW3T/2JPNtY7VelD6B1mUEJGvd
rQCavsYox98QMAg34aD+UcqzDwwSPa+fDfy9JQIGQeUPhMGrzBc+ZGAvtq7xNMn9
6gqxnIhJBBgRAgAJBQJJc/W0AhsMAAoJEKthnTcjVMOiQBYAnjqEF54U0HUdJ3JE
oYo/l5t7j7RRAJ98TzjlIc1pGxlnWBE91IIUq4FzZA==
=mwCZ
-----END PGP PUBLIC KEY BLOCK-----

**Comment by rubberbandaid** [comment]
Any chance you can share the command I'd use to make use of that key with my ~25 byte email string? Never used gpg before, doing a bit of googling but no luck yet.

**Comment by lukefromdc** [comment]
That's just a key export, I cannot explain it and really don't know how to teach. I am sending an email to
support@bountysource.com  to ask what they advise.  Apparently they can do physical checks, but I don't have an account with them.

**Comment by rubberbandaid** [comment]
Just sent you an email.

**Comment by lukefromdc** [comment]
Not sure what address you sent it to,  I don't see it. I could post the address here, you could use it, and I could then delete the comment so spammers don't have access to it for long

**Comment by rubberbandaid** [comment]
Just edited my previous comment, I think we are set with that.

**Comment by lukefromdc** [comment]
File was corrupted, not a text file.

**Comment by lukefromdc** [comment]
email to lukefromdc@hushmail.com, I will take this comment down shortly due to spammers so let me know when you have copied it

**Comment by rubberbandaid** [comment]
I got it.

**Comment by rubberbandaid** [comment]
Emails exchanged, moving to email.

**Comment by lukefromdc** [comment]
In case it's needed by Bountysource or by anyone else having this problem, here are the build options I use to set the path:
` --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu  --sysconfdir=/etc`

**Comment by rubberbandaid** [comment]
Excellent, thanks Luke, using that will negate the need for me to run those cp commands.
