### ISSUE TITLE
Interference between caja file renaming and Mouse Preferences/Locate Pointer

### ISSUE THREAD

**Issue by Brownegmx** [mate-desktop/caja#770]
When the option "Locate Pointer" of "Mouse Preference" is selected it interferes with the renaming of files within caja. While editing the file name, pressing ctrl (useful for copy or paste) closes the rename editing window. It is therefore no longer possible to copy or paste text to rename of file.

**Comment by monsta** [comment]
The problem was in mate-settings-daemon.
Already reported at https://github.com/mate-desktop/mate-settings-daemon/issues/159, already fixed in versions 1.18.1 and 1.16.2.
