### ISSUE TITLE
The fdb_manager was not created

### ISSUE THREAD

**Issue by zuxunyang** [mate-desktop/caja#771]
I find the fdb_manager was not created by caja_freedesktop_dbus_new in the range caja-1.17.* and caja-1.18.*.
So the Firefox download-page can not use caja to open a folder.

**Comment by lukefromdc** [comment]
Testing today with caja 1.19 from git master 4-24-2017, firefox 53 (built by default with gtk3) can open and create folders just fine from the file save dialog. Firefox uses a lot of custom widgets but normally filechoosers and save dialogs are standard gtk items. These descended from Nautilus code but do not actually call Nautilus, Nemo, Caja et all-they are part of GTK 3.

**Comment by raveit65** [comment]
```
[rave@mother ~]$ cat /usr/share/dbus-1/services/org.freedesktop.FileManager1.service 
[D-BUS Service]
Name=org.freedesktop.FileManager1
Exec=/usr/bin/nautilus --gapplication-service
```

**Comment by raveit65** [comment]
Hmm, llooks like this is only a problem if nautilus is installed.
```
[root@mother rave]# dnf provides /usr/share/dbus-1/services/org.freedesktop.FileManager1.service
nautilus-3.24.0-1.fc26.x86_64 : File manager for GNOME
Quelle      : @System
```
I will test this.

**Comment by monsta** [comment]
Now it works for me: https://github.com/mate-desktop/caja/pull/778.

**Comment by monsta** [comment]
Ok, it's done now, and we'll release new 1.18.x version later.
