### ISSUE TITLE
Thumbnail view for image - "image/svg+xml"

### ISSUE THREAD

**Issue by office-work-account** [mate-desktop/caja#772]
Currently caja dont show "image/svg+xml" type. Version of caja - Caja 1.16.2

**Comment by monsta** [comment]
Works for me in various Debian/Ubuntu/Mint versions. Which distro do you have?

What would this command print?
`$ gdk-pixbuf-query-loaders | grep svg+xml`

**Comment by monsta** [comment]
Ok, yet another the-reporter-is-not-interested report
