### ISSUE TITLE
[1.18] opening download folder from Firefox "freezes" X

### ISSUE THREAD

**Issue by monsta** [mate-desktop/caja#777]
Steps to reproduce:
- download some file
- right-click on it in the downloads window
- select "open containing folder"

Then you can get X freeze, or just mouse freeze (keyboard still working), or something else that we already experienced in https://github.com/mate-desktop/mate-terminal/issues/171... Killing firefox process stops it.

This affects only Caja 1.18. As @clefebvre hinted it might be something with GtkApplication which indeed appeared only in 1.18. GTK+ version isn't important (happens with 3.14, 3.18, 3.22). FF version seems to be not important too (happens with 45 and 52).

Also, according to Clem, this doesn't affect Nemo.

Some reports from users:
https://ubuntu-mate.community/t/firefox-freezes-after-trying-to-open-downloads/12630/17

@lukefromdc: can you please take a look at this?

**Comment by lukefromdc** [comment]
Did not happen on my system, using Firefox 53 and and either caja 1.18.0 from my oldest build of it or current caja 1.19.0 from git master. Using gtk3.22.12, glib 2.52.1 over Debian Unstable. Had to uninstall Nautlius just to test this, as normally Nautilus poaches the "open containing folder" from Caja entirely.

**Comment by raveit65** [comment]
Confirmed with caja-1.18 (gtk3) and firefox (gtk2) in centos7/rhel7. (gtk+-3.14)
[rave@localhost ~]$ rpm -qa firefox
firefox-52.1.0-2.el7.centos.x86_64
[rave@localhost ~]$ rpm -qa caja
caja-1.18.2-1.el7.centos.x86_64
Looks like caja-1.18 causes the issue.
Sadly 'journalctl -f --no-tail' give me no hints.

**Comment by lukefromdc** [comment]
This looks like it relates to older GTK versions, possibly only to GTK 3.14 which I can no longer build and run against on my systems as too many other things have changed.

**Comment by raveit65** [comment]
I can reproduce this with fedora 26 too.
[rave@mother ~]$ rpm -qa firefox
firefox-53.0-2.fc26.x86_64
[rave@mother ~]$ rpm -qa gtk3
gtk3-3.22.12-2.fc26.x86_64

I tested it first on centos7 to be sure it isn't gtk+ related.

**Comment by monsta** [comment]
I can reproduce it with various GTK+ versions, including 3.22.11 in Debian Testing...

**Comment by lukefromdc** [comment]
OK, little more I can do on this one as I can't reproduce it. My firefox install though is rather unconventional, using the upstream "no-eme" binary dropped into /usr/local and some files associated with things I consider anti-features deleted. Also have a lot of extensions, some of which interact with the downloader. Won't name that one as I don't want to publish a potential attack vector.

**Comment by raveit65** [comment]
chromium or google-chrome does not have this problem and opens clean a caja browser window.
[rave@mother ~]$ rpm -qa chromium
chromium-57.0.2987.133-1.fc26.x86_64
[rave@mother ~]$ rpm -qa google-chrome*
google-chrome-stable-58.0.3029.96-1.x86_64

**Comment by lukefromdc** [comment]
Since my customized Firefox install also does not do this, it must be specific to some exact way firefox is calling Caja. Can someone with this issue find a way to get the exact character string passed by Firefox in invoking Caja so this can be tested independently of the browser? That would also make it much easier to fix.

**Comment by monsta** [comment]
Found some hints at https://bugs.mageia.org/show_bug.cgi?id=18648#c11...

**Comment by monsta** [comment]
Oh great, we lost DBus functionality on migration from libunique. :disappointed:

**Comment by monsta** [comment]
So in fact, we have a duplicate of https://github.com/mate-desktop/caja/issues/771 which I didn't recognize until I looked at the code.

**Comment by raveit65** [comment]
And using this workaround helps after a session restart.
But this is really ugly 
```
[rave@mother ~]$ cat /usr/share/dbus-1/services/org.freedesktop.FileManager1.service 
[D-BUS Service]
Name=org.freedesktop.FileManager1
Exec=/usr/bin/nautilus --gapplication-service
```
Why those heros hardcoding this to nautilus?
Btw. why firefox use this?

**Comment by monsta** [comment]
I have no idea why they do what they do, we just need to fix what was working with 1.16...

You probably look at Nautilus' own file. Our file is `org.mate.freedesktop.FileManager1.service`.

**Comment by raveit65** [comment]
Hmm, llooks like this is only a problem if nautilus is installed.
```
[root@mother rave]# dnf provides /usr/share/dbus-1/services/org.freedesktop.FileManager1.service
nautilus-3.24.0-1.fc26.x86_64 : File manager for GNOME
Quelle      : @System
```
I will test this.

**Comment by raveit65** [comment]
wtf, uninstalling nautilus with the dbus file doesn't help.
But i found out that it takes exactly 2mins to reach the dbus time out, than firefox is usable again and a caja window with the containing download location pops up.
