### ISSUE TITLE
Mouse wheel doesn't scroll location bar any longer

### ISSUE THREAD

**Issue by goober99** [mate-desktop/caja#779]
In previous versions of MATE, if the breadcrumbs in the location bar were wider than the window, I could hover over the location bar and scroll left to right with the mouse wheel. As of 1.18, this no longer works. The mouse wheel doesn't scroll the location bar. I'm using Ubuntu MATE 17.04.

**Comment by monsta** [comment]
Confirmed, another mouse scroll issue with GTK+3...

**Comment by raveit65** [comment]
locationbar entry or locationbar buttons?

**Comment by monsta** [comment]
Buttons. The scroll should do the same as the left/right buttons on the sides of the bar. It can be tested in GTK+2 build of 1.16.
