### ISSUE TITLE
Caja does not like unity-gtk-module or appmenu-gtk-module with GTK 3.22

### ISSUE THREAD

**Issue by rilian-la-te** [mate-desktop/caja#783]
Steps to reproduce:
1. Install one of these modules.
2. Relogin.

Bug:
![screenshot at 2017-05-10 17-49-38](https://cloud.githubusercontent.com/assets/1329638/25904846/1ac0a6b6-35a9-11e7-8ff5-20497904f061.png)
(Notice non-transparent icon)

I think, we need tigether think about it (I do not know, how Caja creates icon for drag desktop items around).

**Comment by rilian-la-te** [comment]
Nemo also have this issue, but PCManFM is not.

**Comment by rilian-la-te** [comment]
We can also see this bug when dragging something out of Caja window:
![screenshot at 2017-05-10 18-06-00](https://cloud.githubusercontent.com/assets/1329638/25905746/78f103e6-35ab-11e7-9175-344c9c9a6f6a.png)

**Comment by rilian-la-te** [comment]
Where Caja defines drag icons? Maybe I will found a source of bug...

**Comment by raveit65** [comment]
@XRevan86 
Can you help please?

**Comment by rilian-la-te** [comment]
I think workaround can be marking drag windows by some wmclass, I will blacklist it then.
But proper way is switching from GtkActions to GActions and using MenuModels (so, no third-party GtkModules).

**Comment by flexiondotorg** [comment]
Plank also exhibits the issue, so this is not Caja specific. 

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rilian-la-te** [comment]
I does not see issue with Plank now using OpenSuse tumbleweed and appmenu-gtk-module.

**Comment by rilian-la-te** [comment]
But it is not Caja specific, because Nautilus and Nemo both have this issue.

**Comment by rilian-la-te** [comment]
Fixed in https://github.com/rilian-la-te/vala-panel-appmenu/commit/78f3153306034f490886b7d7ac1f62d541ed8be6, AFAIK. Please test.

**Comment by flexiondotorg** [comment]
I will test this tomorrow. Thanks!

**Comment by rilian-la-te** [comment]
Fixed in both modules (for vala-panel-appmenu - in commit above), closing now.

**Comment by raveit65** [comment]
Can you do a PR at  upstream unity-gtk-module to fix it there?

**Comment by rilian-la-te** [comment]
already done by @flexiondotorg

**Comment by rilian-la-te** [comment]
I do not like upstream module, although:))) Because it requires patched GTK((((

**Comment by raveit65** [comment]
Link please?

> I do not like upstream module, although:))) Because it requires patched GTK((((

Ok, my hope died to use the already packed upstream modul in fedora.

@besser82
Any chance to patch unity-gtk-module for fedora?

**Comment by rilian-la-te** [comment]
You need rev 347 at least. Link to rev 345 and rev 347 changes:
1. http://bazaar.launchpad.net/~indicator-applet-developers/unity-gtk-module/trunk.15.04/revision/347
2. http://bazaar.launchpad.net/~indicator-applet-developers/unity-gtk-module/trunk.15.04/revision/345
