### ISSUE TITLE
Feature Request: Tab key to switch panels (instead of F6)

### ISSUE THREAD

**Issue by MarioMey** [mate-desktop/caja#785]
As I used to use with Norton Commander, fisical Tab key has faster access than F6 to switch between panels (when additional panel is added with F3).

Actually, Tab is used to (not-so-usefull) switch between all sectors:
Left Panel -> Right Places (every) Button -> Right Panel -> Main Tools buttons -> Side Panel Type -> Close Side Panel Button -> Side Panel -> Left Panel Places (every) Button.

**Comment by flexiondotorg** [comment]
Sadly your personal preference isn't going to be agreeable to everyone and changing a long standing default (we have learned) can upset people. So we will politely decline this request.

**Comment by MarioMey** [comment]
Ok, I understand. Thanks!
