### ISSUE TITLE
Use current path as custom script argument on no selection

### ISSUE THREAD

**Issue by mxmlnkn** [mate-desktop/caja#787]
Hello,

I just switched from nemo to caja, because of frequent crashes and bugs and currently I'm impressed by caja.
Now I want to write a script which sets thumbnails for folders. So if I select some files and then do RMB->Scripts->setIcons my script is called with the selection. Up until here everything as expected.

But now I also want the following behavior: When I right click inside a folder, but without selecting any file, i.e. click on empty space between icons, then I would want my script to be called with the currently opened folder/path, but instead the script will be called with no argument at all.

**Comment by monsta** [comment]
Not sure what you want us to do...

**Comment by mxmlnkn** [comment]
I want you to consider the feature request: "Call scripts with currently opened path if no files are selected (instead of calling it without any argument)"

**Comment by monsta** [comment]
I've looked at the code and found the `CAJA_SCRIPT_CURRENT_URI` environment variable that is set to the URI of current directory. For example, in my home folder it's set to `file:///home/monsta`. Maybe you could make use of it?

**Comment by mxmlnkn** [comment]
Ah, thank you! That works for me. Sorry I didn't find this on my own.

**Comment by monsta** [comment]
It's ok, I'm not sure if it's actually documented somewhere besides the code.
