### ISSUE TITLE
Caja zoom in list view is broken [$30]

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/caja#790]
Downstream bug report for Ubuntu MATE 17.04

https://bugs.launchpad.net/ubuntu/+source/caja/+bug/1680604

I've reproduced on Caja 1.18.2 and 1.18.3

**Comment by lukefromdc** [comment]
Confirmed here, little response to attempts to zoom in list view-except for unwanted DELAYED changes coming up on subsequent openings. Have to screw with zoom values, switching to icon view and back, and closing and reopening the window just to get back to standard zoom. Only the folder experimented with was affected.

**Comment by lukefromdc** [comment]
Ubuntu 17.04 is using GTK 3.22.7, I'm using GTK 3.22.15 and caja 1.19 from git master, same results

**Comment by monsta** [comment]
Confirmed with git master, and there's a Debian bug report about 1.16.2 at https://bugs.debian.org/863752. So this issue was around for some time...

**Comment by monsta** [comment]
For the record, it's also reproducible with GTK+ 3.14 and 3.18.

**Comment by snaiperskaya96** [comment]
Hi, it's me again, i made a PR to fix this https://github.com/mate-desktop/caja/pull/835

**Comment by raveit65** [comment]
weird, i only need to click on the GtkComboBox for views to apply the new zoom size.

**Comment by snaiperskaya96** [comment]
I guess this can be closed as the linked PR has been merged 😃
