### ISSUE TITLE
very slow when change directory

### ISSUE THREAD

**Issue by crzsparrow** [mate-desktop/caja#794]
#### Expected behaviour
Less than 0.01 sec

#### Actual behaviour
0.4-1.2sec

#### Steps to reproduce the behaviour
1. open home folder 
2.choose list view
3.single click to focus a folder
4.use up and down key on the keyboard to move the focus to another folder.

#### Package version
Caja 1.16.1

#### Linux Distribution
Linux Mint 18.1 MATE edtion

**Comment by tychosoft** [comment]
@crzsparrow what you describe "very slow" this seems very fast to me, or I wish it were just that slow.  With Caja 1.18 (first version of Mate I ever tried, and on a brand new system install, on Fedora 26, too), sometimes it would take 10 seconds or more changing directories!  The whole time the window is unresponsive.  Even hitting the close button always lags for a second or 2. Actually unusable.  I thought about substituting nemo for caja, but I switched to xfce4 for now as  right panel clicks and the mate menu is also a bit slow pulling up submenus, though not that slow, thankfully....

**Comment by nfrozi** [comment]
I am agree with @crzsparrow It's slower than (ex.) Nemo when changing the directory.

**Package Version**
Caja 1.18.5

**Linux Distribution**
Linux Mint MATE 18.3 (upgraded from 18.1), on Core i3 with 8 GB of RAM

**Comment by flexiondotorg** [comment]
The issues with slow operation of the file manager were tracked to GVFS. Ubuntu 16.04 has SRUd fixed GVFS to incorporate the upstream performance fixes. @monsta does Linux Mint ship its own GVFS packages?

**Comment by monsta** [comment]
Nope, they're from Xenial repos here.

**Comment by flexiondotorg** [comment]
Does the default Linux Mint update policy prevent these updates from being installed?

**Comment by monsta** [comment]
I don't know, it's better to ask @clefebvre about that.

**Comment by scjeti** [comment]
I agree with @**crzsparrow** 
I'm now on Mint 19.1, and Ubuntu Mate 18.04, and Caja is still slow to open folders, even with folders that have only a couple files in them.
 I do not have any of these slow-to-open-folders issues on Dolphin(Kubuntu 18.04), or Thunar, or even PCManFM.
Is it a gvfs/gtk3 issue, or a weird cacheing issue, ...,  I dunno?, but this has been going on for YEARS now.
Can we please speed things up with Caja ?
TY.

**Comment by nfrozi** [comment]
My problem was resolved after upgrading to Linux Mint 19.1 :)

**Comment by switzel** [comment]
I'm using Ubuntu Mate 20.04 and I have this same problem.

**Comment by nddipiazza** [comment]
Same here.
