### ISSUE TITLE
Make Caja calculate folder size in same units as file size

### ISSUE THREAD

**Issue by jbn-github** [mate-desktop/caja#796]
Caja would be more helpful to me if it could calculate the size of folders in terms of occupied space on the storage volume (KB, MB, GB, TB, etc.) and list that as the folder's size just as a file's size is listed in list view.

I understand this will generate a lot of disk/network access and that's okay. I'd like to do this because I'd like to have an always-updated view of which folders occupy a lot of space. I'd like to get this information without another program (such as K4DirState) or running `du --summarize --human-readable * |sort -hr |less` on the command line to get a list of items in the current working directory sorted by their size (largest -> smallest).

I suggest this be a togglable feature set to off by default, much as it is in MacOS's Finder. I'd like it if one could turn this on in Caja, wait while Caja computes the size of folders in the opened Caja windows, and lets users sort by size in a more meaningful way (no more using radically different units for folders than files).

**Comment by raveit65** [comment]
We don't accept reports without using the template!
```
#### Expected behaviour


#### Actual behaviour


#### Steps to reproduce the behaviour


#### MATE general version


#### Package version


#### Linux Distribution

```
Try again!
