### ISSUE TITLE
caja problem with shortcut

### ISSUE THREAD

**Issue by linuxjca** [mate-desktop/caja#80]
Hello,
I have a problem with a shortcut to run caja under Debian Wheezy and Linux Mint Debian Edition.
I have tried this ( found in properties of a button on the task bar that works ) : 
/usr/bin/caja --no-desktop -browser %U but in a shortcut i receive an error message can't found %U ...
This work : /usr/bin/caja --no-desktop -browser / or /usr/bin/caja --no-desktop -browser /home
Nautilus works fine without any parameters et go directly to the /home/userxyz folder !

Thanks.
Best regards,

Juan Carlos

**Comment by skaranja** [comment]
Thanks for the workaround.
