### ISSUE TITLE
Little changes to make Caja more uniform

### ISSUE THREAD

**Issue by jEsuSdA** [mate-desktop/caja#805]
#### Expected behaviour

Caja should looks like other filemanagers with the same GTK theme.

#### Actual behaviour

The left panel has strange borders.

#### Steps to reproduce the behaviour

Here all the information, screenshots and info:
https://github.com/shimmerproject/Greybird/issues/195

#### Linux Distribution
Debian Testing.

**Comment by raveit65** [comment]
Caja needs a theming for the sidebar, as we provide different views for it. See our BlueMenta theme as esample.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/mate-applications.css#L126
This needs to be done by greybird theme.

**Comment by jEsuSdA** [comment]
Thanks for the info! ;)
