### ISSUE TITLE
problem with scrolling back in compact view mode

### ISSUE THREAD

**Issue by peneus** [mate-desktop/caja#806]
#### Expected behaviour
scrolling back should work as well as scrolling forward on any folder.

#### Actual behaviour
When Caja is on compact view mode, scrolling forward works fine, but scrolling back does not if there are lots of files.

#### Steps to reproduce the behaviour
open Caja, go to a folder with lots of files, choose "compact view" mode, scroll back and forth. Scroll back does not work properly. This doesn't seem to happen in list view or icon view modes.

#### MATE general version
1.18

#### Package version
1.18.3

#### Linux Distribution
Linux Mint 18.3 Mate edition

**Comment by monsta** [comment]
Which device do you use for scrolling - mouse, touchpad, ...?

**Comment by galik** [comment]
This sounds somewhat similar to issue #801. Are you able to test with the current development version? There is a fix that may solve this issue (PR #804)

**Comment by peneus** [comment]
I have this problem with both touchpad and mouse but not on all the computers I have.
I don't know how to apply the development version. So I am able to test the development version.

**Comment by monsta** [comment]
Right, it's the same as https://github.com/mate-desktop/caja/issues/801. Fixed in 1.18.4.
