### ISSUE TITLE
[1.18]  "Browse media when inserted" option is broken

### ISSUE THREAD

**Issue by monsta** [mate-desktop/caja#807]
#### Expected behaviour

When "Browse media when inserted" option (in Media tab in settings dialog) is enabled, inserted USB drives should be auto-opened in a new directory window.

#### Actual behaviour

The mentioned option does nothing. USB drives are only auto-mounted, but never auto-opened.

#### Steps to reproduce the behaviour

Well, insert some USB drive...

#### MATE general version

1.18

#### Package version

1.18.3

#### Linux Distribution

Linux Mint 18.2

@lukefromdc: can you please have a look at this? I traced it down to 9e5ea15d104720cfee752c193b77f8b03558c6b9.

Building from its parent commit (24bb72b321c044479728fd1d43c941afc0309f18) makes the feature work. I had to install libunique to build it of course... Building from 9e5ea15d104720cfee752c193b77f8b03558c6b9 breaks the feature, no matter if I use `--disable-libunique` option or not. I assume the libunique build is the default there (I don't remember that now, but the commit message hints about that). Looks like the feature is broken for both GtkApplication and libunique.

**Comment by lukefromdc** [comment]
Libunique support was removed before 1.18 was released, as of that commit the default was to build with libunique. The code for libunique builds should not have changed, that may be a clue.

**Comment by monsta** [comment]
Well, it seems like something was changed after all, as building from that commit with libunique already shows the problem.

**Comment by lukefromdc** [comment]
If I can find that difference it should find the problem

**Comment by lukefromdc** [comment]
I will also check the function of this in Nemo, as we now only use GtkApplication. My guess is that whatever watches for this is not getting started.

**Comment by lukefromdc** [comment]
I just found this not working in GNOME and not working in Nemo either at the moment

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/808 is a one-liner and I didn't find it in Nemo, so GNOME might have moved the handling for this to somewhere else somewhere around their origjnal Libunique/GtkApplication transition. Now broken there too it seems.

**Comment by monsta** [comment]
Yeah, they removed it early in 3.0 development phase. I searched for "autorun" in Nautilus commits and there are some hints there. Autorun seems to be moved to g-s-d instead, and media handling settings to g-c-c.

**Comment by lukefromdc** [comment]
GNOME 3 included a major refactoring between Nautilus and the rest of GNOME, as the GNOME devs are really big on the whole "no icons on the desktop" idea for some reason. I think they wanted to ensure that media handling and such would work if Nautilus as a whole was not running.

**Comment by monsta** [comment]
Another hint is https://github.com/linuxmint/nemo/issues/681#issuecomment-56168789 - apparently c-s-d inherited the feature from g-s-d, so I suppose it should work in Cinnamon where c-s-d is running.
