### ISSUE TITLE
caja doesn't use the the right font color in iconview with dark themes

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#81]
If i use use a dark desktop theme caja-1.5.x doesn't displayed the expected white font color for folder names if i used 'iconview' when caja starts.
I see the folder names with black color on dark background.
I can toogle to 'listview' with crtl+2 and the font color is white, than toogle back to 'iconview' with crtl+1 and the fontcolor has the expecected value 'white'.
All sreenshots with gnomishdark
- after caja starts with iconview
https://dl.dropbox.com/u/49862637/Mate-desktop/Bugs/caja-1.png
- switch to listview
https://dl.dropbox.com/u/49862637/Mate-desktop/Bugs/caja-2.png
- back to iconview
https://dl.dropbox.com/u/49862637/Mate-desktop/Bugs/caja-3.png

Also i  notice, if i switch back to a white theme and a caja window is open, the font color stays on white color with a white caja background in iconview.

This issue happes with all dark themes which i know, (gnomishdark, delorean-dark, anewstartblood, drackfire dreamblack) so i don't think it's a theme issue.
All tested themes working well with caja-1.4.x.
@jasmineaura
Does #72 fix this perhaps?

**Comment by sunweaver** [comment]
This has also been reported as  debbug#770760.

**Comment by axalix** [comment]
I still have this problem. Caja 1.8.2. Linux Mint 17

**Comment by dcharlespyle** [comment]
Still happening in mate-desktop 1.8.2, in Fedora 21.  As a workaround I used the eyedropper to set the background to the same color as the dark theme (BlackMATE) I am using.

**Comment by Ralnoc** [comment]
This is still seen in Fedora 22 running xfce4 with Caja 1.10.2. 

A easy workaround is to apply a color background that doesn't conflict with the font coloring through 'Backgrounds and Emblems -> Colors'. You drag a non-conflicting color to the file list and this will address it. 

However we should not have to implement a workaround. Caja should honor the correct theme colors provided by the WM.

**Comment by luispabon** [comment]
Still an issue on Ubuntu 15.10 + Mate 1.8 (Caja 1.10.4).

**Comment by gamax92** [comment]
Still an issue, font color is black and after changing theme and back, it goes to proper text color. Then after a while I notice it's back to the wrong color.

**Comment by raveit65** [comment]
fixed for gtk3

**Comment by raveit65** [comment]
@sunweaver 
I've cherry-picked that commit to 1.12 too.
It should be easy too backport to older releases if you need it

**Comment by raveit65** [comment]
Well there's a regression after all... When using custom background color (you can set it via Emblems & Background dialog), font color isn't changed. E.g. if I select dark bg color and font of my GTK+ theme is black, it will remain black (and thus unreadable).

Tested in GTK+2 build.

**Comment by monsta** [comment]
Fixed for GTK+2 as well with https://github.com/mate-desktop/caja/pull/526.
