### ISSUE TITLE
Details tab on Caja (Metadata)

### ISSUE THREAD

**Issue by binarydepth** [mate-desktop/caja#810]
#### Expected behaviour
When right clicking on a file and choosing properties it would be useful to have the details tab too. In the Basic tab, there's info about the format but I know that from the file extension. Example, being able to see the resolution in images and videos. Another case would be metadata on music files.

#### Actual behaviour
Caja doesn't display metadata, only the basic information of size, dates and type

#### Steps to reproduce the behaviour
Right click on a video file and choose properties

#### MATE general version
MATE 1.12.1

#### Package version
MATE caja 1.12.7

#### Linux Distribution
Ubuntu MATE

**Comment by politas** [comment]
This is a really good feature to add. Nautilus does it through totem integration, I believe?.

**Comment by linux-man** [comment]
I implemented a Media Info tab using https://mediaarea.net/pt/MediaInfo.
It's on https://github.com/linux-man/caja-mediainfo-tab.
