### ISSUE TITLE
Borders in main window are inconsistent

### ISSUE THREAD

**Issue by TomaszGasior** [mate-desktop/caja#811]
#### Expected behaviour
- Remove "frame" CSS class from sidebar widgets (CajaPlacesSidebar, FMTreeView, CajaHistorySIdebar, CajaNotesSidebar) and add "frame" class to GtkNotebook that contains these widgets. 
OR
Add "frame" CSS class to sidebar widgets without it (box inside CajaInformationPanel, CajaEmblemSidebar).
 
- Remove "frame" class from FMIconView and add it to CajaNotebook.

See screenshot:
![screenshot](https://user-images.githubusercontent.com/1395027/28240421-f7f4676e-6981-11e7-8f4b-6976448b7643.png)

#### Actual behaviour
(as in title)

#### Package version
Caja 1.18.3

**Comment by raveit65** [comment]
I like to set up borders in sidebar with a theme, you need to edit your theme, which isn't a MATE theme.

**Comment by raveit65** [comment]
Sigh, I have no idea what 'The newest in Arch Linux.' is.....
and i don't google for it ;-)

**Comment by TomaszGasior** [comment]
It seems to me that version of Caja is not important because each current version of Caja has this problem. I updated my post.

**Comment by TomaszGasior** [comment]
raveit65 wrote „I like to set up borders in sidebar with a theme, you need to edit your theme, which isn't a MATE theme.”

I do not agree with you. Problem exists in Caja, not in theme. Some places sidebar widgets have frame, other have not. It is inconsitent.
