### ISSUE TITLE
History-back with mouse button when pointer hovering file or directory

### ISSUE THREAD

**Issue by scytho** [mate-desktop/caja#827]
#### Expected behaviour
When viewing the content of a directory with Caja in compact view (Ctrl+3) and pressing the back button on the mouse (a thumb button) while the mouse pointer is hovering an entry in the viewed directory, Caja should go one step back in history, i.e. go to the previously viewed directory.

#### Actual behaviour
It doesn’t, nothing happens. You have to move the pointer away from the entry.

#### Steps to reproduce the behaviour
See above.

#### MATE general version
1.18.0

#### Linux Distribution
Linux Mint

**Comment by lukefromdc** [comment]
Remember that you have to restart Caja, mate-panel etc to get a new version into actual use and test the features
