### ISSUE TITLE
"Open With" dialog "Open" button's text misaligned

### ISSUE THREAD

**Issue by iffocca** [mate-desktop/caja#828]
#### MATE general version
1.18

#### Package version
1.18.3-3

#### Linux Distribution
Fedora 26

The "Open" button's text is oddly left-aligned:
![open-with](https://user-images.githubusercontent.com/31083290/29390091-1fa4562c-82bc-11e7-9089-12567e965e72.png)

I believe this issue started with the switch to GTK3.

**Comment by lukefromdc** [comment]
Looks like the same code must be used for the buttons with the icons and the "Open" button. The labels for the other two are left aligned to fit next to the icon, but the 3ed buttoon does not have an icon and obviously uses the same code to align the label.

This affects all themes but is worst in BlackMATE.

**Comment by raveit65** [comment]
Using GTK_ALIGN_CENTER on the parent of the GtkLabel, which is a GtkBox, will fix the issue.
![caja-open-with](https://user-images.githubusercontent.com/961604/29421678-1d2a7272-8376-11e7-8eee-34a6ce4e3f8e.png)

The default GTK_ALIGN_FILL act like GTK_ALIGN_START for some reasons.
