### ISSUE TITLE
click top menu crash when using mutiny panel layout 

### ISSUE THREAD

**Issue by fastfading** [mate-desktop/caja#833]
Expected behaviour

click menu , menu pop out

Actual behaviour

crash

Steps to reproduce the behaviour

set ubuntu mate -> mate tweak-> panel->panels->set to mutiny
open caja
click menu on the top
crash

MATE general version

ubuntu mate 17.04

Package version

1.18.1

Linux Distribution

ubuntu mate

**Comment by monsta** [comment]
I can't reproduce it in 17.10, and both Mutiny layout and the global menu applet are specific to Ubuntu MATE anyway. If it still happens, please report to [ubuntu-mate bug tracker](https://bugs.launchpad.net/ubuntu-mate) on Launchpad.

**Comment by fastfading** [comment]
it should be on a virtualbox machine.
Real machine would not have this issue.
my environment
mac pro  , virtualbox 5.1.8
ubuntu 17.10

2017-10-22 3:33 GMT+08:00 monsta <notifications@github.com>:
