### ISSUE TITLE
black wallpaper with 2 monitors

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/caja#836]
#### Expected behaviour
exactly the same wallpaper on all monitors

#### Actual behaviour
Wallpaper is black on one monitor

#### Steps to reproduce the behaviour
Install caja-1.19.1

#### MATE general version
1.19.x

#### Package version
master

#### Linux Distribution
fedora 26

#### Link to downstream report of your Distribution
not applicable,  as 1.19.1 isn't in downststream repos.

![caja-desktop-2-monotors](https://user-images.githubusercontent.com/961604/29749496-a5cd6ab2-8b2d-11e7-9a26-338f17db0d32.png)

Issue is caused by https://github.com/mate-desktop/caja/commit/ac12e6d16f4a51b3327d013781e72cfec17f3624
Removing that fix brings back the wallpaper for the second monitor.

Btw. icons are working on that monitor, so only drawing the background failed.

**Comment by raveit65** [comment]
@lukefromdc 
Can you please confirm that?
@sc0w 
Please take a look at it.

**Comment by lukefromdc** [comment]
This is CONFIRMED, and a further effect is that when changing the background it is initially displayed OK, then turns black after a second or so. Any files or folders  you put on the desktop in the second monitor are still rendered.

**Comment by lukefromdc** [comment]
My suspicion is that the use of   gdk_display_get_primary_monitor is causing this by excluding other monitors. When it was root window if handled both monitors but had an issue with redrawing when the resolution was changed. This may have to be done monitor by monitor-or else several deprecation fixes will have to be reverted.
