### ISSUE TITLE
Columns are no longer resizeable

### ISSUE THREAD

**Issue by wolverine9827** [mate-desktop/caja#840]
#### Expected behaviour
Mouse hover over column separator and icon changes to resizer to allow adjustments to size of column.  This functioned as expected in caja 1.18.3

#### Actual behaviour
Nothing happens on mouse hover over column separator - removing the ability to resize columns

#### Steps to reproduce the behaviour
Hover mouse over any column separator

#### MATE general version
mate-desktop-1.18.0-5.fc26.x86_64

#### Package version
caja-1.18.4-1.fc26.x86_64

#### Linux Distribution
Fedora 26 x64

**Comment by lukefromdc** [comment]
PR https://github.com/mate-desktop/caja/pull/838 fixes this, it is a regression that came in with https://github.com/mate-desktop/caja/pull/835, which makes zoom work again in list views

**Comment by raveit65** [comment]
Feel free to test already fixed build and leave karma.
https://bodhi.fedoraproject.org/updates/FEDORA-2017-a84ccb5228

**Comment by wolverine9827** [comment]
FIXED :)

Now running:
caja-share-1.18.1-1.fc26.x86_64
caja-extension-xreader-1.4.4-1.fc26.x86_64
**caja-extensions-1.18.4-2.fc26.x86_64**
caja-wallpaper-1.18.1-1.fc26.x86_64
caja-xattr-tags-1.18.1-1.fc26.x86_64
caja-actions-1.8.3-1.fc26.x86_64
caja-image-converter-1.18.1-1.fc26.x86_64
caja-actions-doc-1.8.3-1.fc26.noarch
caja-beesu-1.18.1-1.fc26.x86_64
**caja-1.18.4-2.fc26.x86_64**
caja-open-terminal-1.18.1-1.fc26.x86_64
caja-sendto-1.18.1-1.fc26.x86_64
caja-dropbox-1.18.0-1.fc26.x86_64
**caja-schemas-1.18.4-2.fc26.x86_64**
caja-extensions-common-1.18.1-1.fc26.noarch

Thanks!
