### ISSUE TITLE
can not change file permissions for external devices

### ISSUE THREAD

**Issue by caltrop-3** [mate-desktop/caja#852]
#### Expected behaviour
change file permissions for external devices

#### Actual behaviour
can not change file permissions on external drives
USB Hard Disk
USB Flash Drive
nothing external

#### Steps to reproduce the behaviour
use caja

#### MATE general version
MATE 1.18.0

#### Package version
unknown

#### Linux Distribution
Linux Mint 18.2 Sonya
Kernal Linux 4.10.0-33-generic x86_64

#### Link to downstream report of your Distribution
none

**Comment by monsta** [comment]
FAT32 limitations
