### ISSUE TITLE
wrong behaviour with mouse wheel over scroll bar in compact view

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/caja#855]
into the folder it works fine, this wrong behavior happens only with the mouse "into" the scroll bar

with images, it works fine here:

![good](https://user-images.githubusercontent.com/7734191/30993035-34e662f6-a4ad-11e7-889d-3afc308d6374.png)

and it doesn't work here:

![bad](https://user-images.githubusercontent.com/7734191/30993049-400dfa40-a4ad-11e7-95d3-73bcded75e77.png)

#### Expected behaviour

wheel up/left: go to the left

wheel down/right: go to the right

#### Actual behaviour

the inverse:

wheel up/left: go to the right

wheel down/right: go to the left

#### caja version

It happens here with caja 1.18.4 and latest git master

**Comment by sc0w** [comment]
the problem is here:

https://github.com/mate-desktop/caja/blob/master/src/file-manager/fm-icon-view.c#L2486

`(icon_view->details->compact)` is false if the mouse is over the scrollbar

**Comment by lukefromdc** [comment]
I got a different behavior: fast scrolling with the mouse out of the scrollbar, and slow (fine-tune) scrolling with the mouse within the scrollbar. This is with caja (and pluma) from git master (1.19 as of now) and overlay scrolling off. I tested with my UbuntuStudio_Legacy theme and with BlueMenta, no difference. I wanted to see if how themes render scrollbars had any effect on this, apparently it does not.

**Comment by monsta** [comment]
Confirmed, it's inverse scrolling, affects only compact view.

**Comment by lukefromdc** [comment]
Confirm here too now that I know compact view and only compact view are affected

**Comment by sc0w** [comment]
the same happens with gedit 3.22.1

seems this is a gtk issue

**Comment by monsta** [comment]
I don't know, I can reproduce it here in Mint 18.2, based on Ubuntu 16.04 with GTK+ 3.18.

**Comment by lukefromdc** [comment]
If this is a GTK 3.22 issue we could invert the mouse scroll behavior, then put it behind a GTK 3.22 only build time selector. Downside is if GNOME fixes GTK we have to come back to it. Interestingly, Pluma does NOT have this problem, at least not on my machine.

**Comment by monsta** [comment]
I meant the inverse scrolling is reproducible with 3.18, so it's not just 3.22 issue.

Some additional testing showed it doesn't happen with 3.14 though. Don't know about 3.16 as I don't have that version anywhere.

**Comment by sc0w** [comment]
@monsta 

> Don't know about 3.16 as I don't have that version anywhere.

In an old VM I can't reproduce the issue with caja 1.10 and gtk 3.16.6

@lukefromdc 

> we could invert the mouse scroll behavior

I think it is not possible, I have tested and the function `fm_icon_view_scroll_event` never is called if the mouse is over the scrollbar on `fm-icon-view.c` ( https://github.com/mate-desktop/caja/issues/855#issuecomment-333052750 )

**Comment by sc0w** [comment]
the same problem with engrampa (git master) and file-roller (3.26.0)

I will close this, caja is not the problem

**Comment by monsta** [comment]
Does the problem happen only with horizontal scrollbars in these apps?

**Comment by sc0w** [comment]
@monsta yes, only with horizontal scrollbars

**Comment by monsta** [comment]
Ok... I also see it in `mate-sensors-applet` in the prefs dialog, so maybe it's just a GTK+ "feature".

![mate-sensors-applet](https://user-images.githubusercontent.com/5138986/31430938-fd13ea60-ae7a-11e7-93ab-7f7d5c7d8bfd.png)

**Comment by sc0w** [comment]
@monsta yes, confirmed

I reported it to gtk+

https://bugzilla.gnome.org/show_bug.cgi?id=788824

**Comment by monsta** [comment]
Thanks, let's see if they call it a bug or a feature...

**Comment by lukefromdc** [comment]
https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=91064360037fed243af588807e49e10ab6683dcb

in GTK 3.22 addresses this very issue, I am about to test it.

**Comment by lukefromdc** [comment]
The commit above to GTK 3.22 does indeed fix this, even though it is to GtkRange.  Turns out 
`#include "gtkrangeprivate.h" `
appears within  gtkscrollbar.c , so that's probably why this fixes our horizontal scrollbars

**Comment by monsta** [comment]
Oh, so it was already reported... there's a link in the commit message:

https://bugzilla.gnome.org/show_bug.cgi?id=788905

**Comment by sc0w** [comment]
yes, my report was earlier xD

https://bugzilla.gnome.org/show_bug.cgi?id=788824

and, one day later:

https://bugzilla.gnome.org/show_bug.cgi?id=788905
