### ISSUE TITLE
Three separate buttons for icon view/folder view/compact view

### ISSUE THREAD

**Issue by alexanderdd** [mate-desktop/caja#856]
#### Expected behaviour
For one-click switching between icon view/folder view/compact view, there are three separate buttons.

#### Actual behaviour
To switch views, one needs two clicks: one on dropdown menu, one to select view.

#### Steps to reproduce the behaviour
Click on dropdown menu to switch views

#### MATE general version
1.14 and later

I was expecting to find an already existing feature request for this topic... did I miss it?
For me this is actually quite annoying cause I switch views a lot, and since the filemanager is so central to a distro, it keeps me away from MATE at the moment. For file managers, at the moment only nemo and dolphin are satisfactory (I know I can use those in MATE.. at the moment I am using nemo in XFCE and it only creates trouble).

**Comment by meequz** [comment]
Why don't you use keyboard shortcuts for this? Ctrl+1, Ctrl+2 and Ctrl+3

**Comment by alexanderdd** [comment]
Because it is faster to click on a single button than to use the shortcut ctrl+1. There is nothing faster than a one-click action. 
Also, some power-users might like the keyboard shortcuts, but I wanna keep in mind the average user, and design user-friendly UI.

I don't understand why devs chose to go with drop-down menu, maybe someone can explain? Or were the devs trying to be different from other file managers (no other filemanager that I know uses this method)?

**Comment by flexiondotorg** [comment]
Personally I don't think adding more buttons makes the UI simpler, the user now has to interpret 3 glyphs rather then one drop down. If speed of switching is your concern then keybindings are available.

Changing a well established UI for one user doesn't seem sensible to me and what you're suggesting I isn't compatible with the HIG that MATE adheres to.

**Comment by raveit65** [comment]
@flexiondotorg 
i agree with you.

**Comment by monsta** [comment]
Hmm... so it's about optimizing two clicks into one?

**Comment by lukefromdc** [comment]
I also agree with keeping the existing dropdown menu, as this is consistant with the original GNOME 2 Nautilus that Caja was forked from and is used the same way. Also the fact that text is in the combobox button explaining "icon view" "text view" or "compact view" makes it immediately  clear what this is without the user having to rely on a tooltip or the help to find out. Three icon buttons would fit in the same space, but not three text buttons. Without the text new users might never find the other view options.

**Comment by meequz** [comment]
I just realized that you actually can use one click with the existing scheme. Here's how: click on dropdown and don't release the mouse button. The dropdown will open. Then move the cursor to the wanted item and release the button. The item will be activated.
