### ISSUE TITLE
is this AC_SUBST(GAIL_REQUIRED, [gail_minver]) still necessary?

### ISSUE THREAD

**Issue by oz123** [mate-desktop/caja#862]
I saw the following line
```
AC_SUBST(GAIL_REQUIRED, [gail_minver])
```
in `configure.ac` and asked my self what it does. Since caja is only gtk3 now, is it really necessary?

> As you may be aware, GTK 2 accessibility is implemented in a couple of modules, gail, and atk-bridge. The atk-bridge is provided by at-spi, both v1 and v2. The gail module is provided by gtk itself. Later on in GTK 3's development, the gail module code was refactored, and moved directly into GTK itself

Source https://github.com/mate-desktop/caja/issues/590#issuecomment-248270985

**Comment by monsta** [comment]
Source code of libgail might be in GTK+ code, but when it's built and distributed, it's a separate library.

**Comment by oz123** [comment]
Not sure that this is always true. Maybe on Debian it is the case, not in gentoo and maybe even arch Linux.

**Comment by monsta** [comment]
Library name is `libgailutil-3.so.*`
