### ISSUE TITLE
'Save' button appears in other application launched instance, but action is to open highlighted directory

### ISSUE THREAD

**Issue by ywum7fhv0skqh07h** [mate-desktop/caja#866]
I'm a bit confused by this bug - not sure if it's caja, MATE, Ubuntu MATE, Thunderbird, or even upstream Nautilus.

System: up to date (internode AU mirror, 0600 UTC) Ubuntu MATE 17.10 AMD64.

On an email in Thunderbird, right click -> save image launches a limited instance of caja. In that instance, when the focus is on either pane that displays directories (anything other than the file name), but no directory is specifically in focus (highlighted, but not in focus), the bottom right 'open' button changes to 'save', but pressing 'save' actually opens the directory.

In this instance, it appears the only way to actually save the file is to focus on the file name, yet the UI is wrong in other panes of focus.

On a completely different system & distro & DE, I have noticed Nautilus does some funny things with focus, although it may be a feature.

**Comment by monsta** [comment]
> I'm a bit confused by this bug - not sure if it's caja, MATE, Ubuntu MATE, Thunderbird, or even upstream Nautilus.

Very good reason to create a thread in [Ubuntu MATE community](https://ubuntu-mate.community/) first. With screenshots of course.
