### ISSUE TITLE
Search Performance Slow

### ISSUE THREAD

**Issue by oscardssmith** [mate-desktop/caja#867]
#### Expected behaviour
When I search for python from the root of a file system it should take almost no time

#### Actual behaviour
It takes ~45 seconds and uses 100% cpu (only 1 core)

#### Steps to reproduce the behaviour
search for something from root

#### MATE general version
1.18.0

#### Package version
1.18.4

#### Linux Distribution
Ubuntu Mate 17.10

**Comment by jhasse** [comment]
Would it make sense to use something as https://github.com/sharkdp/fd#benchmark as a backend?
