### ISSUE TITLE
Desktop icons aren't shown under a root session

### ISSUE THREAD

**Issue by giogziro95** [mate-desktop/caja#871]
#### Expected behaviour

When using MATE under a root session, the file manager is available on the desktop like it's the case of ordinary users.

#### Actual behaviour

When using MATE under a root session, the file manager isn't loaded on the desktop, thus no icons are shown. I can't use the mouse cursor to select anything on the desktop. The only thing that's there is the wallpaper.

#### Steps to reproduce the behaviour

Log in as root.

#### MATE general version

1.18.0

#### Package version

1.18.0+1

#### Linux Distribution

Kali Linux (rolling release, latest packages)

#### Link to downstream report of your Distribution

N/A

**Comment by lukefromdc** [comment]
A workaround for this is to invoke Caja (1.18 or later only) with --force-desktop. The root session is usually not used with the GUI and when it is, it should only be used to fix problems and especially not for web surfing.

**Comment by giogziro95** [comment]
> The root session is usually not used with the GUI and when it is, it should only be used to fix problems and especially not for web surfing.

Normally, yes, but as I mentioned in the issue, it's Kali Linux.

**Comment by giogziro95** [comment]
So, I modified the appropriate launcher in _/usr/share/applications_ by appending command with _--force-desktop_ and after restarting the session, the folder is loaded on the desktop normally.

Since the issue is specific to the distribution's wants and needs, I guess I should report it downstream to its developers.

**Comment by giogziro95** [comment]
Okay, after doing that, _System_ → _Log Out root..._ and _System_ → _Shut Down..._ menu items (from the top panel) misbehave. You need to click them repeatedly to get the dialogs.

**Comment by monsta** [comment]
This is intentional restriction when you run Caja as root or in other desktop environments (https://github.com/mate-desktop/caja/pull/439, https://github.com/mate-desktop/caja/pull/489, https://github.com/mate-desktop/caja/pull/654).

**Comment by giogziro95** [comment]
Makes sense. Thanks for your suggestion.

On 13 Mar 2018 12:18 am, "yveslec" <notifications@github.com> wrote:

Yes to avoid mate-session misbehaviour for ordinary users,
DO NOT MODIFY system file:
/usr/share/applications/caja.desktop
BUT JUST MANAGE ROOT Mate session envirenment
Once logged as root, in a mate-session
go
System -> Preferences -> Personnal -> Startup Application:
and just add a new command
name: Caja manage root desktop
command: caja -force-desktop
So just only root, will be affected by this change!
Doing so, you will not have misbehaviour,neither in ordinary user
environment, nor in root environment!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mate-desktop/caja/issues/871#issuecomment-372448675>,
or mute the thread

**Comment by jcvdam1990** [comment]
> Yes to avoid mate-session misbehaviour for ordinary users,
> DO NOT MODIFY system file:
> /usr/share/applications/caja.desktop
> BUT JUST MANAGE ROOT Mate session environment
> Once logged as root, in a mate-session
> go
> System -> Preferences -> Personnal -> Startup Application:
> and just add a new command
> name: Caja manage root desktop
> command: caja --force-desktop
> So just only root, will be affected by this change!
> Doing so, you will not have misbehaviour,neither in ordinary user environment, nor in root environment!

can you please break this down? For the life of me I still cant get control over my desktop in kali 2018.2 rolling 64bit Gnome Version 3.30.0. In file manager i can see desktop and folder that are there i just cant physically see the icons on the actual desktop...  Any help would be appreciated.

**Comment by lukefromdc** [comment]
First things first: in a MATE session as root, open a terminal window and run caja --force-desktop and see what happens. Make sure you actually have at least one item in the Desktop folder or there will be nothing to display of course. If it does not work, cut and paste any error messages from the terminal into a reply message here.

GNOME versions should have nothing to do with this. Nautilus does not support desktop icons AT ALL anymore, though a gnome-shell extension to bring them back is (I think) at an alpha status at this point. In MATE we will never go down that route. The only reason we don't run root icons on the desktop by default is because otherwise a root instance of Caja run from terminal in a normal session can take over the desktop under some circumstances. That was an old and aggravating Nautilus bug in the GNOME 2 days.

**Comment by jcvdam1990** [comment]
Hey thanks for your response. Yeah I didnt know that desktop icons were no longer supported.. Im total noob lol.

**Comment by secwatch** [comment]
Just goto software in Kali settings, Software >  Add-ons > Categories > Desktop Icons and install it. Edit the settings later for small icons. You'll be ok, for now.

**Comment by giogziro95** [comment]
@lukefromdc
> The only reason we don't run root icons on the desktop by default is because otherwise a root instance of Caja run from terminal in a normal session can take over the desktop under some circumstances.

Why not separate the desktop icons from the Caja process and draw them via the shell (like Plasma and LXQt do) or something else? Wouldn't that be a better way? Just curious.

**Comment by lukefromdc** [comment]
We don't have a "shell" in the sense that GNOME et all do. The closest thing to that would be splitting out the desktop window to another application as Nautilus used to do and Nemo does now. No real reason to do that at this point, and its a lot of work. We have other things to deal with right now.

**Comment by jcvdam1990** [comment]
thank you.

**Comment by sujitvasanth** [comment]
Thanks so much! I tried reinstalling my enire mate desktop on a recent android build of ubuntu and kali as I like the mate interface. no dice until this wonderful tip!
But i did find that caja sometimes crashes once I drill down a few directories when run in this mode...dont know why..

**Comment by tomchadar** [comment]
Thank you very much! This has solved my freenx problems on root sessions on Ubuntu 18.04 and later.
