### ISSUE TITLE
[Feature request] Format option missing for USB devices

### ISSUE THREAD

**Issue by Philippe734** [mate-desktop/caja#873]
#### Expected behaviour
On the devices side, right click on the USB device plugged, then select "Format..."
The "Format" option is already in Nautilus, see capture attached.

**This option is useful for beginner users, in particular for old people.**

![nautilus format usb](https://user-images.githubusercontent.com/24923693/33186337-062e5d08-d089-11e7-8557-b1a1f225df98.png)

#### Actual behaviour
On the devices side, right click on the USB device plugged, the "Format..." option is missing, see capture attached.
![mate format missing](https://user-images.githubusercontent.com/24923693/33186462-1f1d7cc6-d08a-11e7-96e8-21233164285a.png)

#### Steps to reproduce the behaviour
Plug an USB device, as a stick. Open Caja. Right click on the USB plugged.

#### Linux Distribution
Format option missing in Ubuntu Mate 14.04, 16.04 and 17.10

**Comment by danboid** [comment]
I've thought this is the main missing feature from MATE / caja for years but never got round to reporting it.

Formatting disks is a very common task and neither using mkfs.* from the terminal, using gparted nor installing nautilus/GNOME are good options for a beginner user or anyone who prefers easy-to-use GUIs and the MATE desktop.
