### ISSUE TITLE
Caja's file selection box does not show space correctly

### ISSUE THREAD

**Issue by yanderemoe** [mate-desktop/caja#884]
#### Expected behaviour
Show all files/folders in correct space

#### Actual behaviour
Seems has different space between different files/folders (As picture shown below)
![bugs](https://user-images.githubusercontent.com/25140626/34062405-6bf95eb6-e1ba-11e7-8e1c-aca6fa8f4a97.png)

#### Steps to reproduce the behaviour
Open any application then open file/folder selection box.

#### MATE general version
MATE Desktop Environment 1.18.0

#### Package version
Caja 1.18.5

#### Linux Distribution
ArchLinux

#### Link to downstream report of your Distribution
https://bugs.archlinux.org/index.php?project=5&do=index&switch=1

**Comment by monsta** [comment]
> Open any application then open file/folder selection box.

[GtkFileChooserDialog](https://developer.gnome.org/gtk3/stable/GtkFileChooserDialog.html) is a part of GTK+3 and is not related to Caja.
