### ISSUE TITLE
Maybe some README files should be removed or updated

### ISSUE THREAD

**Issue by TomaszGasior** [mate-desktop/caja#890]
Such as this.

https://github.com/mate-desktop/caja/blob/2ac7f3788d2bf9f4688da834856d53174f8f5124/cut-n-paste-code/README#L21

**Comment by sc0w** [comment]
Fixed in https://github.com/mate-desktop/caja/commit/38a5478e62c84c373d1acf8fb1d278003a3a2d53

**Comment by monsta** [comment]
Fixed more radically in https://github.com/mate-desktop/caja/commit/6c162ba243f9e62651a13ce2cb4ca2ec9d422509

**Comment by TomaszGasior** [comment]
I have an idea. Libegg parts are also used in other MATE apps: Atril, Engrampa, EOM. It would be good to move all used parts of libegg to `mate-desktop` libraries and make its as hard dependency for these apps, replacing redundant copying and pasting code. I am right?

**Comment by monsta** [comment]
Historically, [libegg](https://git.gnome.org/browse/libegg/) was an "Incubator for GTK+ enhancements" (it still has that description). It wasn't meant to be a shared library, instead developers were picking its parts into their projects. When MATE was forked, it inherited all these parts all over the place. We might consider moving them to a separate shared library, but not now. We're near MATE 1.20 release (end of January), so we better not start reorganizing code now.

**Comment by raveit65** [comment]
In result all this packages depends on mate-desktop libs and it is harder to use them as single application for other destops.
I don't see any benefit in this action, only work.....

**Comment by TomaszGasior** [comment]
@raveit65 — you are right, but `mate-desktop` is very small and currently it is needed by Caja, Pluma, EOM and I don't see any problems to have `mate-desktop` package installed in my XFCE. ;-) But it is nice to hear that you are interested in situaction of other DE's users, not only yours DE, thanks!

@monsta — understand. Code shouldn't be reorganized near before stable release, you are right too I think. But it seems to me its ugly and redundant to have copied the same (or similar) code in 4 different repos instead of keeping it in one shared library, one place. It's good idea to move it to `mate-desktop`, but in the future.

**Comment by lukefromdc** [comment]
According to GNOME, libegg is still gettting new commits. We have very old cut and pasted code that no longer relates to what was upstream. Thus the old cut-and-paste-code rules no longer apply, but a common name for this throughout all MATE apps that use it still makes sense
