### ISSUE TITLE
why the search_dispose about search directory don't run?

### ISSUE THREAD

**Issue by chendonghai01** [mate-desktop/caja#895]
#### Expected behaviour
when search behavior finished, the search_dispose, search_finalize, caja_directory_finalize should be called to run. 
#### Actual behaviour
all finalize functions about search directory don't  be call to run.

#### Steps to reproduce the behaviour
1. add log info in search_dispose, search_finalize, caja_directory_finalize
2. make & make install
3. open caja file manager
4. search 
5. close caja file manager
6. view log information

#### Package version
caja-1.18.3

**Comment by lukefromdc** [comment]
This is fallout from the GtkApplication work, as that is the origin of the code in question. Turns out Nautilus got a lot of bugfixes well after the fact for this file. I will take a look at them

**Comment by lukefromdc** [comment]
I do not know how to add the log info you mention, BTW. Running Caja as root in gdb I didn't get any references to these functions

**Comment by lukefromdc** [comment]
In GDB, I get three threads starting when a search is started, and three threads exiting cleanly when a search is stopped

**Comment by lukefromdc** [comment]
On further examination, I found that this did NOT come from the GtkApplication work, though some of the gobject code resembles that used in GtkApplication. That was why I thought this came from that porting effort.

libcaja-private/caja-search-directory.c has not been changed in 5 years it turns out.

**Comment by sc0w** [comment]
If the search works, for me there is no issue

@chendonghai01 if the code can be improved in your opinion, feel free to open new PR with your suggested changes

**Comment by chendonghai01** [comment]
i had work it for two weeks, but don't find the root cause.  i add the log info in these functions of caja as below :
syslog(LOG_ERR, "============= %s", __func__) 
when search finished, these finalize function didn't be called to run.   but these search finalize functions are always be called to run  when the search finished in nautilus.  

i print the gobject reference count after g_oject_unref in both caja_directory_unref and nautilus_directory_unref.  the reference count is 1 after  the both function be called at the last time.  
so i don't know why ?

**Comment by chendonghai01** [comment]
i had work it for two weeks, but don't find the root cause. i add the log info in these functions of caja as below :
syslog(LOG_ERR, "============= %s", __func__);
when search finished, these finalize function didn't be called to run. but these search finalize functions are always be called to run when the search finished in nautilus.

i print the gobject reference count after g_oject_unref in both caja_directory_unref and nautilus_directory_unref. the reference count is 1 after the both function be called at the last time.
so why these finalize functions will be run in nautilus  and not be run in caja ?

**Comment by chendonghai01** [comment]
i had worked about it for two weeks, but don't find the root cause. i add the log info in these functions of caja as below :
syslog(LOG_ERR, "============= %s", __func__);
when search finished, these finalize function didn't be called to run. but these search finalize functions are always be called to run when the search finished in nautilus.

i print the gobject reference count after g_oject_unref in both caja_directory_unref and nautilus_directory_unref. the reference count is 1 after the both function be called at the last time.
so why these finalize functions will be run in nautilus and not be run in caja ?

**Comment by chendonghai01** [comment]
i had worked about it for two weeks, but don't find the root cause. i add the log info in these functions of caja as below :
syslog(LOG_ERR, "============= %s", __func__);
when search finished, these finalize function didn't be called to run. but these search finalize functions are always be called to run when the search finished in nautilus.

i print the gobject reference count after g_oject_unref in both caja_directory_unref and nautilus_directory_unref. the reference count is 1 after the both function be called at the last time.
so why these finalize functions will be run in nautilus and not be run in caja ?

**Comment by lukefromdc** [comment]
I get 
bash: syntax error near unexpected token `LOG_ERR,'
 if I try to apply either
syslog(LOG_ERR, "============= %s", func);

or syslog(LOG_ERR, "search_dispose %s", func);

This sort of thing with the logs is not something I have ever done before

**Comment by chendonghai01** [comment]
please add #include <syslog.h>  in caja_directory.c

**Comment by monsta** [comment]
I usually just add some `g_warning` as a debug message, of course it spams my `~/.xsession-errors`, but I get the info I need 🙂
