### ISSUE TITLE
cannot select all the search keywords with Ctrl+a

### ISSUE THREAD

**Issue by zhangwen2** [mate-desktop/caja#918]
#### Expected behaviour
When the search entry gets focus, the keywords in the search entry can be selected with Ctrl+a.

#### Actual behaviour
When the search entry gets focus, the keywords in the search entry can not be selected with Ctrl+a, but all the files in the slot will be selected.

#### Steps to reproduce the behaviour
1.Click the search entry, and enter the search keywords, such as "hello";
2.Press the shortcut "Ctrl+a", the keywords "hello" will not be selected.

#### MATE general version
1.18.5

#### Linux Distribution
Fedora-Mate 25

**Comment by sc0w** [comment]
Fixed in https://github.com/mate-desktop/caja/pull/919 with https://github.com/mate-desktop/caja/commit/012d9f86e046cfbffd4d2d4e55633d250ec90dd7
