### ISSUE TITLE
Please make caja cross-compile safe

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/caja#923]
This patch we use in the Debian package...
https://anonscm.debian.org/cgit/pkg-mate/caja.git/tree/debian/patches/1001_use-correct-macros-to-cross-build.patch?id=541398f4c85193a924b4b3876227f4d399deec57

**Comment by monsta** [comment]
This is fixed since 1.22.0 as https://github.com/mate-desktop/caja/pull/1108 is merged.
