### ISSUE TITLE
[HiDPI] Icons could be created beyond screen boundaries

### ISSUE THREAD

**Issue by MingcongBai** [mate-desktop/caja#933]
#### Expected behaviour

When creating icons on the desktop, icons should be wrapped to a second column if the first is exhausted in its vertical space.

#### Actual behaviour

With `window-scaling-factor=2`, the vertical space is not properly scaled, that icons could be put in the same column until it reaches approximately twice the vertical space.

#### Steps to reproduce the behaviour

Set `window-scaling-factor=2`, then open a terminal emulator on the desktop, run the following command...

```
mkdir 1
mkdir 2
mkdir 3
...
```

Until issue is prevalent.

#### MATE general version

MATE 1.20.0.

#### Package version

mate-* 1.20.0.

#### Linux Distribution

AOSC OS, package tree: https://github.com/AOSC-Dev/aosc-os-abbs/tree/staging/extra-mate/.

#### Link to downstream report of your Distribution

N/A

**Comment by flexiondotorg** [comment]
Fixed via #962
