### ISSUE TITLE
Feature request: Sort by extension

### ISSUE THREAD

**Issue by Smirftsch** [mate-desktop/caja#952]
I know this is a VERY old story and somewhat hated? topic, but please let me explain before it goes unread into trash.
I had a look myself in adding it, but got quickly lost inside the dependency libs and use of their functions.

Reasoning: I have to interact often with windows files and I have a cross OS project Linux/Windows. In this case neither type nor mime-type sort does work out if I want to copy just some specific files.

Examples:  
Sort by "Type" does mix up localization files like .int, .itt, .frt and even worse, it does mix in also .ini files here. Mime type again does sort them all as text/plain.
By "Type" mixes up .bsc, .mhr, .u and some more development files. 
In the Linux case it also does mix up the symlinks .so and the libs .xx.xx - this does make sense, no doubt, but is also not needed or wanted if one wants f.e. to copy only plain .so files. 

Please don't argue this is something which has to be fixed by mime recognition, that's no solution, it's comparing apples and oranges. Mime type never will be able to recognize and differentiate properly everything especially when it comes to localization files like the above mentioned. 

Sorting by extension does make sense if one has to work with multiple OS files especially from the Windows side and seen technically it should be very simple to add it for one familiar with all the libs involved in caja development. I really don't get it why such a thing is discussed that often, is always denied and that in literally all desktop environments- as if the community is afraid of being to much "Windows alike" or something. It's really just about workflow and functionality here.
Please consider adding this functionality.

**Comment by muesli4** [comment]
> I had a look myself in adding it, but got quickly lost inside the dependency libs and use of their functions.

The actual functionality is in *libcaja-private* folder.

> In this case neither type nor mime-type sort does work out if I want to copy just some specific files.

I think it is a reasonable request.

> Please don't argue this is something which has to be fixed by mime recognition, that's no solution, it's comparing apples and oranges.

Is there a problem with mime recognition?

> Please consider adding this functionality.

Maybe, I will look into this. But I'm not sure how one should handle filenames with multiple dots in it.

* How would I identify the proper extension? First dot? It's probably irrelevant.
* Does it have an extension at all or just dots in the name? Not our problem then?
* Should we compare basename based on dot segments in reverse order? It looks to me that this would work properly.

**Comment by muesli4** [comment]
The trickiest part was to figure out how everything connects. It really looks like caja needs a clean rewrite. Anyway, this is how it looks now:
![sort_by_extension](https://user-images.githubusercontent.com/2077630/38022991-62167614-3281-11e8-8224-e3aa9fd5e621.png)
I hope that is to your liking.

**Comment by Smirftsch** [comment]
damn, you just made my day. Sorry, I had some very busy days and just noticed the response here. The example looks absolutely perfect!
I never checked in detail, but Windows does only sort by the last dot segment to so do. 

Thank you so much!

**Comment by muesli4** [comment]
> damn, you just made my day. Sorry, I had some very busy days and just noticed the response here. The example looks absolutely perfect!

In the example it's perfect. Some files that have dots in their names may be sorted a bit different. But they still appear in the same group (i.e. by their last extension segment, for example, `pdf`).

Things that could be changed:

* Stop sorting after the n-th segment.
* Ignore segments with over-length (e.g., more than 3).
* Add exceptions for file types with more than one extension.

Personally, I don't mind.

> I never checked in detail, but Windows does only sort by the last dot segment to so do.

In Linux compound extensions are common. In Archlinux `pkg.tar.gz` is a package type and it makes sense to group these together.

> Thank you so much!

You're welcome. :)

**Comment by muesli4** [comment]
Files with several dots in it will always be displayed as if the segments between these dots resemble a part of the extension. So you can either life with it or use some heuristic to filter these cases out. I'm afraid there is no solution that will catch all cases.

> I am not sure what this means to be honest.

E.g., when we encounter `tar.gz` it is recognized as an extension, but the numbers in `2.0.0.1.pkg.tar.gz` are probably not part of the extension.

> I take it that it is only implemented in icon / compact view so far?

I pushed another commit that adds *Extension* as a caja column type (just uses the string after the first dot). Not sure how useful it is.

**Comment by Smirftsch** [comment]
> Files with several dots in it will always be displayed as if the segments between these dots resemble a part of the extension. So you can either live with it or use some heuristic to filter these cases out. I'm afraid there is no solution that will catch all cases.

> 
Sounds reasonable to me.

> I pushed another commit that adds Extension as a caja column type (just uses the string after the first dot). Not sure how useful it is.

> 

Great! Will test some with all this to see if there is even any need for changes, but for now everything looks just fine :)

**Comment by muesli4** [comment]
This should be closed as it has been implemented with: https://github.com/mate-desktop/caja/commit/0585258dc117b50cf8e8f6b5361fd815cc292cca
