### ISSUE TITLE
Bringing features aiming to better efficiency

### ISSUE THREAD

**Issue by Ricky-Tigg** [mate-desktop/caja#982]
#### [Link](https://bugzilla.redhat.com/) to downstream report of your Distribution

Hi _mate-desktop/caja_.

Needed in section _Help_ | _About_:
– Along with the release version, a mention of the **release date**; as model _v. 1.20.2 – 2018-02-07_. 
– Not to **link** any more to '_http://mate-desktop.org_/' which is currently an insecure protocol. In a close future most of the modern web browsers aimed to secure browsing, will have to refuse connections to web servers that serve contents relying on insecure protocol. Same approach can be applied also to information communicated in relation with packages from **@ystem** repository related to Mate (e.g. in terminal on Fedora:  `'dnf info <package-name>'`).

Need for additional entries in the side pane respectively associated to:
– **Star-targets** (targets to which user applied stars). Such entry assumes the addition of a function to apply a star to common and hidden files.
– **Recently opened documents**; Currently such entry is located at MATE desktop panel, under _Places_ | _Recent documents_. Once in Caja, that property is needed.

In general:
– A **graphical indicator** regarding the future arrangement in _Places_ view of a selected target while creating **bookmark**, be it by _Crtl+D_ or by _Drag-and-drop_ operation. Such indicator could be illustrated by two parallel horizontal lines in between the link would be added.
– When _Extra pane_ (**F3**) is active, the presence on each opened pane of an **icon dedicated for closing** the pane by clicking would be efficient.
– Allow **extended capabilities** applying to **arrangement items**; The ability to combine arrangements at least up to five criteria. Currently arrangement is allowed upon one criteria at a time.

- At last a technically highly challenging implementation:  the ability to display in a dedicated line for each processed operation its **equivalent command line** in terminal according to the Shell interpreter in use.  For example –assumed active _Shell_ is _Bash_– while location is _Home_ folder, applying function '_Rename..._' to test.txt into double-test.txt would have for equivalent in command line `'mv -i test.txt double-test.txt'.`

**Comment by flexiondotorg** [comment]
@Ricky-Tigg https://mate-desktop.org/

**Comment by Ricky-Tigg** [comment]
That 's indeed the URL every links should had point to.

**Comment by allanlaal** [comment]
Ricky-Tigg /admins: please edit title to be specific, not generic ;)
