### ISSUE TITLE
Clicking a location button does not activate the corresponding panel

### ISSUE THREAD

**Issue by gabdub** [mate-desktop/caja#988]
#### Expected behaviour
In a two-panel view (use F3 to split the view), if you click on a location button in the non-active panel, that panel is activated and the location is changed accordingly.

#### Actual behaviour
In a two-panel view, if you click on a location button in the non-active panel, the other panel is not activated and the current one changes its location to something else. See the picture:

![extra-pane bug](https://user-images.githubusercontent.com/11639609/39656344-81452dde-4fd5-11e8-8508-572980e81c6f.png)

#### Steps to reproduce the behaviour
Press F3, navigate to some folder, click a button in the other panel.

#### MATE general version
1.20.1

#### Package version
1.20.2

#### Linux Distribution
Ubuntu Mate 18.04 64bits

**Comment by zhangn1985** [comment]
no one going to fix this?

**Comment by cpcbegin** [comment]
This is a big bug.

**Comment by raveit65** [comment]
It is fixed, so your comment is complete useless. Better read the whole report
To avoid more smart comments like yours in my mail box i will lock report.
